### ISSUE TITLE
Add an Example for NonlinearRegression Constructor (Int32, RegressionFunction, RegressionGradientFunction)

### ISSUE THREAD

**Issue by qingypharm** [accord-net/framework#1007]
Please add an example for NonlinearRegression Constructor (Int32, RegressionFunction, RegressionGradientFunction).

TODO (optional): Describe a specific scenario you would like to see addressed. How does it do sigmoidal fit?

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Models_Regression_NonlinearRegression__ctor_1.htm

**Comment by cesarsouza** [comment]
Hi @qingypharm,

Thanks for opening the issue! However, there are examples already available at the [main documentation page for the NonlinearRegression class](http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Regression_NonlinearRegression.htm). If you need an example for a more specific scenario, please re-open the issue.

Regards,
Cesar
