### ISSUE TITLE
Recurrent Neural Net

### ISSUE THREAD

**Issue by georgecampanis** [accord-net/framework#1008]
Hi,

Would it be possible to add support for RNNs: https://en.wikipedia.org/wiki/Recurrent_neural_network?

Help Topic: http://accord-framework.net/docs/html/N_Accord_Neuro_Networks.htm

Awesome library by the way!

George.

**Comment by cesarsouza** [comment]
Hi @georgecampanis,

Thanks a lot for opening the issue! Support for RNNs will be added through [Keras#](https://github.com/cesarsouza/keras-sharp), and then integrated into the project. If you would like, please open a new issue in the Keras# project to track the development of this feature!

Regards,
Cesar
