### ISSUE TITLE
Add an Example for BoundedBroydenFletcherGoldfarbShanno Class

### ISSUE THREAD

**Issue by amiraliiam** [accord-net/framework#1011]
Please add an example for BoundedBroydenFletcherGoldfarbShanno Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Math_Optimization_BoundedBroydenFletcherGoldfarbShanno.htm

**Comment by cesarsouza** [comment]
Hi @amiraliiam,

Thanks for opening the issue. There is already an example at the bottom of the page you've linked. If you need a more specific example, please re-open the issue.

Regards,
Cesar
