### ISSUE TITLE
Site isn't working?

### ISSUE THREAD

**Issue by Residentik** [accord-net/framework#1012]
Hello. I'm visited examples page on your site:
http://accord-framework.net/samples.html
and nothing can download.

**Comment by blaisexen** [comment]
https://onedrive.live.com/?authkey=%21ABBpXNIhGLK7gXQ&id=808347681CC09388%21530797&cid=808347681CC09388

hi,
that link still on saved,

good luck :dancer:

**Comment by cesarsouza** [comment]
Hi,

I've just tested from a different computer and the links still seem to be working. They are OneDrive links. It might take a few seconds to get redirected to the site where the download will finally start from.

Regards,
Cesar

**Comment by michel-carbone** [comment]
yes links are working even when not connected with a Microsoft account

Michel

**Comment by cesarsouza** [comment]
Thanks, I will be closing this issue for now as the download links seem to be working. If you have trouble downloading a particular application, please re-open this issue with more details!
