### ISSUE TITLE
quadratic linear  SVM Error -  The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by shoshtarian** [accord-net/framework#1014]
I am using the Quadratic Linear SVM method as mentioned in your sample.(https://github.com/accord-net/framework/wiki/Linear-Support-Vector-Machines) as follows:
 double[][] expansion = matrixInput.Apply(quadratic.Transform);
but I get the error "  The call is ambiguous between the following methods or properties" 
I know that its an programming issue but what is the correct form.
 Regards

**Comment by cesarsouza** [comment]
Hi @shoshtarian,

Thanks for opening the issue! I haven't realized this page of the wiki was still outdated, thanks a lot for raising it to my attention. I've just updated it to demonstrate how to use the latest versions of the library, which hopefully should not have the issue you've raised.

Again, thanks a lot. Please let me know if you run into any other issues.

Regards,
Cesar
