### ISSUE TITLE
Question regarding the audio buffer using Accord.Video.FFPMEG.VideoFileReader.ReadVideoFrame

### ISSUE THREAD

**Issue by courgeon** [accord-net/framework#1023]
Hello,

I'm trying to use Accord.Video.FFPMEG.VideoFileReader.ReadVideoFrame to retrieve both image frame and audio, using :

public void ReadVideoFrame(BitmapData output, IList<byte> audio);

The image works well, but I don't understand the audio buffer. I get a list of byte every 0.5sec, but how are they aligned ?
I'm trying the stream that in OpenAL, but a mostly get a sort of white noise.

The video i'm using has 44100 stereo audio.
Each audio chunk is 86016 bytes long (i was expecting 88200), I'm quessing it's a 16bit per channel, but I didn't find any documentation: Little Big / Endian ? what about L and R channel, are they interleaved ? 

Any help would be appriciated.
Thanks

**Comment by courgeon** [comment]
Well, if i can help anyone, apparently, converting the video using an MP3 encoding instead of AAC, the output audio byte[] can be send directly to OpenAL and works fine.

Do AAC format need to be decoded externaly ?

**Comment by cesarsouza** [comment]
Hi @courgeon,

Thanks for opening the issue! In the current pre-release version, the ReadVideoFrame is taking the audio frames decoded by FFmpeg and storing them directly in the provided list of bytes. This means that the format in which those frames should be interpreted currently depends on the codec being used in FFmpeg.

What my intuition tells me is that the AAC decoder is outputting frames using a particular format (e.g. 32-bit float_ whereas MP3 is outputting using another (e.g. 16-bit PCM). And it might happen that OpenAL is expecting the same format being output by the MP3 by default too, and thus it works.

In a next version it should become possible to indicate which output format you would like to receive the samples - or at least, the output will be returned in a Signal class which should include information about the audio sample format being used.

Regards,
Cesar

**Comment by courgeon** [comment]
You're right ! In fact, I can tell OpenAL how to read the buffer.
using ALFormat.StereoFloat32Ext, the AAC plays normaly.
AAC does output 32bit float values.
As the AudioCodec property is available in the VideoFrameReader, I can make a simple test to switch to the correct format depending on the codec.
Works for me.
Thanks !
