### ISSUE TITLE
Using strings in decision tree algorithm

### ISSUE THREAD

**Issue by krashby** [accord-net/framework#1027]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

I want to use the Multiclass Decision Tree algorithm to categorise my data, which is text in the form of strings. Is it possible to do with Accord?

I've got a DataTable of all my data, which I have made into two arrays,  inputs and outputs.

**Comment by cesarsouza** [comment]
Hi @krashby,

Thanks for opening the issue! Yes, this is perfectly possible, but the way to do it depends on what kind of data you have. 

If each training instance in your dataset is a vector of strings with fixed length (i.e. your data table has a fixed number of columns where each of them has the data type string), then you can take a look at the second example at the [bottom of the DecisionTree documentation page](http://accord-framework.net/docs/html/T_Accord_MachineLearning_DecisionTrees_DecisionTree.htm) to see how to convert your data to a matrix of integer values using the Codification class.

However, if each of your training samples is an entire text, with a variable number of words on it, then you might need to first convert your training samples to a fixed form representation using either the [BagOfWords](http://accord-framework.net/docs/html/T_Accord_MachineLearning_BagOfWords.htm) or [TF-IDF classes](http://accord-framework.net/docs/html/T_Accord_MachineLearning_TFIDF.htm). There are examples in those pages I've linked that hopefully should get you started. 

Hope it helps,
Cesar

**Comment by krashby** [comment]
Hi Cesar,

I've followed the 2nd example through with my dataset (which is a table with multiple columns which all contain strings) however I get the error `"System.ArgumentException: 'Attribute 0 is a constant.'"` when trying to `Learn()` the inputs and outputs. 

Could this be because some of my fields are empty? It is important that my dataset include empty fields as I want my final algorithm to be able to handle this.

When I define my attributes I use the line 
`DecisionVariable[] attributes = DecisionVariable.FromCodebook(codebook, inputHeadings);`
with all input headings.

Also, how do I make the decision tree multiclass or does this happen automatically by passing in multiple outputs?

Thanks in advance!

**Comment by krashby** [comment]
Actually I've just solved my issue - `DecisionVariable.FromCodebook(codebook, inputHeadings)` returns a set of discrete attributes which my data most certainly isn't. I've made a loop to add them all continuously - here it is in case this is useful to anyone!

`List<DecisionVariable> attributes = new List<DecisionVariable>();`

            foreach (string columnName in inputColumnNames)
            {
                 attributes.Add(new DecisionVariable(columnName, DecisionVariableKind.Continuous));
            }

            C45Learning teacher = new C45Learning(attributes.ToArray());


My last question still stands, is this a multiclass algorithm?

Another question, too - what does the error represent in the line ` double error = new ZeroOneLoss(outputsAsCode[0].ToDouble()).Loss(predictedNameAsCode);` - I get 0.92 with my algorithm

**Comment by cesarsouza** [comment]
Hi @krashby,

If all you have in your dataset are strings (and words within strings), then what you have is indeed a dataset of discrete symbols. Discrete symbols are used when there is no notion of order between elements in your dataset (i.e. you cannot say if "cat" is greater than "dog" or giraffe is smaller than "pineapple" - well, unless you have some metric defined for them but the decision tree cannot handle this case at the moment). So in this case, using DecisionVariableKind.Discrete would be the correct choice (albeit maybe the property is a bit ill-named, a better name would be ```DecisionVariableKind.Symbol``` instead of ```Discrete```).

The error about attribute 0 being a constant means that all values in your current dataset, in that particular column, are the same. In this case, there is nothing to be learned from this column, so you may want to remove it from your dataset before attempting to learn a tree (or any other machine learning model) for it.

However, since you mentioned about having missing values in your dataset, I think you can find a better example in the [documentation for the C4.5 class, since this algorithm can handle missing values natively](http://accord-framework.net/docs/html/T_Accord_MachineLearning_DecisionTrees_Learning_C45Learning.htm). For example, please take a look at the third example there, it specifically mentions how to create a codebook from a DataTable of strings with missing fields and then learn a DecisionTree with C4.5 using it.

Hope it helps!
Cesar

**Comment by cesarsouza** [comment]
Sorry, forgot to answer the other two questions!

Regarding multi-class: Yes, ID3Learning and C45Learning are multi-class algorithms by default - just feed multiple class labels to them and they should work. 

Regarding the error rate, I am not completely sure what is being fed to them (what are outputAsCode[0] and predictedNameAsCode? Are they your entire dataset or just an example?) but normally it should tell you the classification error of the model in your dataset. A value of 0.92 would mean that the model only got a right answer in 0.08 of the cases (which may be an indicative something is not right).

If you have a multi-class problem, you can also use the easier to interpret [GeneralConfusionMatrix class](http://accord-framework.net/docs/html/T_Accord_Statistics_Analysis_GeneralConfusionMatrix.htm). You can pass your model, the input data, and the output data it was supposed to predict to the  [GeneralConfusionMatrix.Estimate(model, inputs, outputs) method](http://accord-framework.net/docs/html/M_Accord_Statistics_Analysis_GeneralConfusionMatrix_Estimate__1_1.htm) and it will return an object with many performance measures already calculated for you in its properties.

Regards,
Cesar

**Comment by krashby** [comment]
Ah ok, I understand what you are saying, and that may explain why the error is so high if they are in fact discrete and I'm using continuous. `outputAsCode[0]` was simply the actual output (I have 2 sets of outputs) whereas `predictedNameAsCode` was predicted values - I should have tidied that up, apologies.

The issue with missing values is that part of my criteria is that I must pass entire empty columns to the algorithm. What about if I define the attribute manually, telling it that it has 1 option instead of 0, should that work?

I'll also have a look at the GeneralConfusionMatrix class.

Thanks for all the info on the other questions!

**Comment by cesarsouza** [comment]
Hi @krashby,

I haven't tested, but probably setting ```tree.Attributes[index_of_attribute_you_need].Range``` directly should make it work, even though I am not sure this would make much sense - the classifier would never be able to learn anything about this column, since it is always empty.

Hope it helps,
Cesar

**Comment by krashby** [comment]
Hi Cesar, 
I've played around with it all and got it working, to a point - however not working how I want it, but I fear that is due to the actual algorithm itself. 

Essentially, I want to feed it several different fields of data per entry, and for it to choose the most appropriate field out of the data - which in my case is a person's name. So in essence, my output is one of my inputs. To complicate things, name could be found in one of several fields. 

Then, for unseen data (and unseen names) I want it to be able to predict what the name is.

Is that possible with this algorithm, or any ML algorithm on Accord?

**Comment by cesarsouza** [comment]
Hi @krashby,

I am afraid I couldn't understand exactly the mapping you are trying to do, but I think you may have to find a suitable representation for your problem that would allow you to express it as a problem of mapping a _fixed set_ of inputs to a fixed set of outputs. Once you can find one, then all classification algorithms in Accord would be applicable to the problem.

Sometimes it is hard to find one, but it is often possible. For instance, for a first try, you could augment your dataset with samples containing all possible inputs that would lead to a same known output (if that's applicable). 

Or if this may be useful, you can also split your problem into two, i.e. first you learn a classifier to find the best field, then learn another (or a set of others, possibly one per possible field) to predict it.

Regards,
Cesar
