### ISSUE TITLE
Add an Example for BlobCounter Class

### ISSUE THREAD

**Issue by futomaki115** [accord-net/framework#1028]
Please add an example for BlobCounter Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Imaging_BlobCounter.htm

**Comment by cesarsouza** [comment]
Hi @futomaki115,

Thanks for opening the issue! For a complete example, please take a look at the [Blob detection sample application](https://github.com/accord-net/framework/wiki/Sample-applications#blobs-detection).

Regards,
Cesar
