### ISSUE TITLE
The same field name is serialized multiple times in the class or its parent class. This is not supported

### ISSUE THREAD

**Issue by LuisAverhoff** [accord-net/framework#1032]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

So after solving my last issue, the error I'm getting now is this `The same field name is serialized multiple times in the class or its parent class. This is not supported:  -> Base(Classifier) kNNClassifier(KNearestNeighbors) outputs`. It seems that unity does not support serializing multiple fields with the same name even though in my class I have outputs as a local variable and not as an instance variable. Looking through the source code, I found multiple instances of the same variable(outputs) but with different types(one as an `integer` in the `transform base class` and the other one as an `int []` in `BaseKNearestNeighbours class`). I'm guessing this is probably why this error is occurring but I'm not sure. What I can do to fix this issue?

``` C#
using System.Collections.Generic;
using Accord.MachineLearning;
using UnityEngine;
using Accord.Math.Distances;
using Accord.IO;
using System.IO;

public class Classifier : MonoBehaviour
{
    [SerializeField]
    private DataService dataService;

    [SerializeField]
    private int neighbours;

    public readonly static string modelPath = @"Assets/StreamingAssets/Models/GestureModel.bin";

    private KNearestNeighbors kNNClassifier;

    private Dictionary<string, int> gestures;

    private void Start()
    {
        List<FeatureVector> featureVectors = dataService.getAllFeatureVectors();

        createGestureDictionary(featureVectors);

        if (File.Exists(modelPath))
        {
            kNNClassifier = loadModel();
        }
        else
        {
            train(featureVectors);
            saveModel();
        }
    }

    private void createGestureDictionary(List<FeatureVector> featureVectors)
    {
        gestures = new Dictionary<string, int>();

        int gestureLabel = 0;

        foreach (FeatureVector featureVector in featureVectors)
        {
            if(!gestures.ContainsKey(featureVector.Gesture))
            {
                gestures.Add(featureVector.Gesture, gestureLabel);
                gestureLabel++;
            }
        }
    }

    private void train(List<FeatureVector> featureVectors)
    {
        kNNClassifier = new KNearestNeighbors(k: neighbours, distance: new Euclidean());

        double [][] inputs = new double[featureVectors.Count][];
        int [] outputs = new int[featureVectors.Count];

        createInputsAndOutputs(inputs, outputs, featureVectors);

        kNNClassifier.Learn(inputs, outputs);
    }

    private void createInputsAndOutputs(double [][] inputs, int [] outputs, List<FeatureVector> featureVectors)
    {
        for (int i = 0; i < featureVectors.Count; i++)
        {
            inputs[i] = featureVectors[i].createDistanceVector();
            outputs[i] = gestures[featureVectors[i].Gesture];
        }
    }

    public string classifyGesture(double [] distanceVector)
    {
        int gesureIndex = kNNClassifier.Decide(distanceVector);

        foreach (KeyValuePair<string, int> pair in gestures)
            if (gesureIndex.Equals(pair.Value)) return pair.Key;

        return "Unknown Gesture";
    }

    public void saveModel()
    {
       kNNClassifier.Save(modelPath);
    }

    public KNearestNeighbors loadModel()
    {
        return Serializer.Load<KNearestNeighbors>(modelPath);
    }
}
```

**Comment by ibrahimpenekli** [comment]
It's a silly bug. I've found a solution that worked for me: Rename `kNNClassifier` to `kNNClassifier2` and get back to the Editor and wait for compile. Then rename to `kNNClassifier` again.

**Comment by cesarsouza** [comment]
Hi @ibrahimpenekli,

I am glad you got it solved - it has been some weeks now since I last touched Unity but I remember well how sometimes we can run into silly issues like this. 

May I ask if this fixed the issue permanently? Or do you have to keep re-applying it from time to time?

Regards,
Cesar

**Comment by LAOMUSIC** [comment]
I just got this error in version 2018.37!
Compiling with MonoDeveloper game thos .NET warning:
`    <GetReferenceAssemblyPaths`
