### ISSUE TITLE
Add an Example for PerceptronLearning Class

### ISSUE THREAD

**Issue by javierhc92** [accord-net/framework#1038]
Please add an example for PerceptronLearning Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Neuro_Learning_PerceptronLearning.htm

**Comment by cesarsouza** [comment]
Hi @javierhc92,

Thanks for opening the issue! In the mean time while the example is written, you may would like to take a look at the [Perceptron Learning sample application](https://github.com/accord-net/framework/wiki/Sample-applications#perceptron).

Regards,
Cesar
