### ISSUE TITLE
Can the Accrod.IO package depend on the .net Standard  SharpZibLib version?

### ISSUE THREAD

**Issue by sconan32** [accord-net/framework#1039]
- [x ] question
  - [ ] bug report
  - [ ] feature request

**Issue description**
The Nuget Package Accord.IO depends on the SharpZibLib package which is not adaptable for .net Core or .net Standard . And the SharpZibLib has publish a .net Standard Package. Is it possible to using the .net Standard version SharpZibLib package?

**Comment by cesarsouza** [comment]
Hi @sconan32,

Thanks for opening the issue! However, Accord.IO already depends on the .NET Standard package of SharpZipLib if you install it through NuGet to a .NET Core application or .NET Standard library. 

There are multiple versions of Accord.IO, one for each framework you are targeting. If you install Accord.IO to a .NET 4.6 project through NuGet, NuGet should install the version that depends on non-.NET Standard SharpZipLib. If you install it to a .NET Core or .NET Standard project, NuGet will install the version that depends on .NET Standard.

Maybe you have converted the project type after you have installed the packages? In this case, removing all NuGet packages and reinstalling them should hopefully fix the issue you are experiencing.

Hope it helps,
Cesar
