### ISSUE TITLE
Add an Example for ExcelReader Constructor (String)

### ISSUE THREAD

**Issue by Himmelsadler** [accord-net/framework#1041]
Please add an example for ExcelReader Constructor (String).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_IO_ExcelReader__ctor_3.htm

**Comment by vonboettichert** [comment]
Hi,

Here is an example:

`var file = new OpenFileDialog();
            if (file.ShowDialog() == DialogResult.OK)
            {
                ExcelReader excelReader = new ExcelReader(file.FileName);
                string[] sheets = excelReader.GetWorksheetList();
                DataTable dataTable = excelReader.GetWorksheet(sheets.FirstOrDefault());
            }`

Does that help?

Regards,
Thorsten

**Comment by cesarsouza** [comment]
Hi @Himmelsadler,

Thanks for opening the issue! The main examples are in the [main documentation page for the ExcelReader class](http://accord-framework.net/docs/html/T_Accord_IO_ExcelReader.htm), whereas a more particular example has been given by @vonboettichert above (thanks!). If you need further examples, please re-open this issue with more details.

Regards,
Cesar
