### ISSUE TITLE
Add an Example for Drawing.Rectangle Method (BitmapData, Rectangle, Color)

### ISSUE THREAD

**Issue by majidhajizae** [accord-net/framework#1048]
Please add an example for Drawing.Rectangle Method (BitmapData, Rectangle, Color).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Imaging_Drawing_Rectangle_1.htm

**Comment by blaisexen** [comment]
hi their,
I hope it helps, you may closed this issue if it's good for you.

        RectanglesMarker marker;
        private void videoSourcePlayer_NewFrame(object sender, ref Bitmap image)
        {
            UnmanagedImage im = UnmanagedImage.FromManagedImage(image);
Rectangle window = //YOUR CODE HERE....
                    marker = new RectanglesMarker(window);
                    marker.MarkerColor = Color.DeepSkyBlue; //CHANGE COLOR OF THE RECTANGLE
                    marker.ApplyInPlace(im);
                    image = im.ToManagedImage();
}
