### ISSUE TITLE
Add an Example for TestImages Class

### ISSUE THREAD

**Issue by iamsky13** [accord-net/framework#1054]
Please add an example for TestImages Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_DataSets_TestImages.htm

**Comment by cesarsouza** [comment]
Hi @iamsky13,

Thanks for opening the issue! However, there is already an example at the bottom of the page you've linked. If you would like a more specific example, please re-open the issue.

Regards,
Cesar
