### ISSUE TITLE
Add an Example for NaiveBayesLearning Class

### ISSUE THREAD

**Issue by mkeshavarzi** [accord-net/framework#1055]
Please add an example for NaiveBayesLearning Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_Bayes_NaiveBayesLearning.htm

**Comment by vonboettichert** [comment]
Hi @mkeshavarzi 

I just stumbled upon your question; there is already an example at the bottom of the page you linked?

**Comment by cesarsouza** [comment]
Hi @mkeshavarzi,

Thanks for opening the issue! However as @vonboettichert stated, there are already examples at the bottom of the page you have linked. If you would like an example for a more specific scenario that you would like to see addressed, please reopen the issue.

@vonboettichert Thanks!

Regards,
Cesar
