### ISSUE TITLE
Unsafe code is unsafe

### ISSUE THREAD

**Issue by nomnomdom** [accord-net/framework#106]
It looks like all the assemblies are marked as unsafe, which means the library can't be used in any .Net application, framework, or platform that requires safe code.  Is there any plan to fix this?

For example in Matrix we have:

        public unsafe static double[,] ToDouble(this float[,] matrix)

It looks like this is used in several hundred places in Accord.Math alone.  Was this done for any particular reason?  Unsafe code gives trivial, if any, performance boosts as the compiler is pretty good at optimizing bounds checking.  It is also just ridiculously dangerous.

**Comment by cesarsouza** [comment]
Hi there,

Unfortunately, the compiler doesn't optimize bounds checks for multidimensional (i.e. [,]) matrices. Other code sections have been adapted from Fortran or C/C++ public domain algorithms that are not trivial to be rewritten without using pointers.

It should be possible, however, to exclude certain parts from the generated assemblies using compiler directives, but this would mean removing some functionality from the framework, or at least moving them to a different assembly. However, it wouldnt make sense in all the cases. For example, one part that absolutely needs pointers is the Imaging assembly. Image and video processing using .NET's System.Drawing cannot be done efficiently without using pointers. 

I will switch off the unsafe for Accord.Math and see how much effort would be necessary to replace the unsafe sections with safe counterparts and extra compiler directives. Thanks for registering the issue!

**Comment by anders9ustafsson** [comment]
@nomnomdom Which applications/frameworks/platforms are you referring to, could you give an example? As long as the public API is "safe", I do not think that it matters to the consuming app/lib/platform that *Accord.NET* uses `unsafe` code internally. 

From a platform limitation perspective, both the "modern" *Windows 8.1* (tablet + desktop) and *Windows Phone 8.1* platforms support `unsafe`. I have ported *Accord.NET* to these platforms via *portable class libraries*, see [here](https://github.com/cureos/accord). 

OK, *Silverlight* does not support `unsafe`, and the *Silverlight*-based *Windows Phone 8*  platform does not officially support it (but it is possible to circumvent this limitation). But these legacy platforms are increasingly abandoned for the modern platforms, so it is hardly a practical limitation that these platforms do not (officially) support `unsafe`.

**Comment by anders9ustafsson** [comment]
@nomnomdom Looking more closely into the code you refer to, I realize that the public API is indeed `unsafe`. 

It is a good thing that you bring this up, because I don't think the API needs to be `unsafe` in this case. @cesarsouza In the [Matrix.Conversions](https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Matrix/Matrix.Conversions.cs) file, would it not be better to exclude `unsafe` from the method signatures, and instead put the "unsafe" code in an `unsafe` block inside the respective method?

**Comment by anders9ustafsson** [comment]
@cesarsouza I am currently preparing a PR where `unsafe` is removed from the public API to the largest possible extent. Please stay tuned :-)

**Comment by anders9ustafsson** [comment]
@cesarsouza I have now made a pull request to reduce the number of `unsafe` occurrences in the public API as much as possible. @nomnomdom Many thanks for bringing up this issue.

**Comment by cesarsouza** [comment]
Thanks Anders! That's magnificent! I will integrate the pull request as soon as possible.

**Comment by nomnomdom** [comment]
Wow... Thank you so much. :)  Allowing some of the libraries to run as safe and non-external is just staggeringly useful. :)

I am doing a using Accord.MachineLearning to do some basic classification in a compiled SQL CLR stored procedure running on SQL Server 2012.  It seems to be working really, really well.

Thanks for the quick response, and _huge_ thanks for creating such an absolutely amazing project!

Rob

**Comment by cesarsouza** [comment]
The pull request #107 has been integrated into the codebase; as such, I am closing this issue. Thank you all for the contributions!
