### ISSUE TITLE
Write Text inside the video frame in particular line XY

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#1061]
**What would you like to submit?** (put an 'x' inside the bracket that applies)
  - [x] question

Hi @cesarsouza 

I would like to know, How can we write Text inside the video frame?

for example I would like to write text "Unknown or Match" from the Rectangle above.

**Comment by blaisexen** [comment]
Ops, I hope this is enabled on the newest version!

**Comment by blaisexen** [comment]
I got the answer now,
```
                    RectangleF rectf = new RectangleF(objects[i].X, objects[i].Y, 200, 50);
                    Graphics g = Graphics.FromImage(myBitmapImage);
                    g.DrawString("TEST TEXT", new Font("Tahoma", 26), Brushes.Black, rectf);
                    g.Flush();
```
I hope this function will be updated to the next version.

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Exactly, you can write text to a frame using System.Drawing's Graphic class. The [VideoPlayer sample application actually shows how it can be done](https://www.centerspace.net/doc/NMath/user/general-sparse-matrix-88276.htm#Xgeneral-sparse-matrix-88276) (it writes the time and date to the frame when you are playing a MJPEG stream).

Regards,
Cesar

**Comment by blaisexen** [comment]
```
        private void writetoframeimage(string aliasname, Bitmap image, int linex, int liney)
        {
            Graphics g = Graphics.FromImage(image);
            g.DrawString(aliasname, this.Font, Brushes.Black, new PointF(linex, liney));
            g.Flush();
        }

```
yes, thank you!
writetoframeimage(aliasname, image, faces[i].X - 4, faces[i].Y - 14);
