### ISSUE TITLE
Add an Example for MultivariateKernelRegression(TKernel) Class

### ISSUE THREAD

**Issue by gx1144** [accord-net/framework#1063]
Please add an example for MultivariateKernelRegression(TKernel) Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: ms-its:D:\Accord.NET-3.8.0-archive\Docs\Accord.NET.chm::/html/T_Accord_Statistics_Models_Regression_MultivariateKernelRegression_1.htm

**Comment by vonboettichert** [comment]
Bump

**Comment by cesarsouza** [comment]
Hi @gx1144,

I've just committed some examples on how to use MultivariateKernelRegression. However, in case you are interested in performing [Support Vector Regression](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_FanChenLinSupportVectorRegression_1.htm) (which is different from multivariate Kernel regression), you can also take a look at the examples in [FanChenLin's Support Vector Regression class](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_FanChenLinSupportVectorRegression_1.htm).

Regards,
Cesar
