### ISSUE TITLE
Add an Example for QLearning Class

### ISSUE THREAD

**Issue by krflol** [accord-net/framework#1064]
I'm struggling to refactor the code for use on real time data.
In my example I have a classifier that returns a number from 0-256, a reward, and two possible actions.
Please point me in the right direction. Thank you.

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_QLearning.htm

**Comment by cesarsouza** [comment]
Hi @krflol,

Thanks for opening the issue! However, there is already an example at the bottom of the page you've linked. If you would like to see a more particular example for a more specific scenario you would have in mind, please re-open this issue.

Regards,
Cesar

**Comment by krflol** [comment]
Thank you for your quick reply, but as mentioned in the request, I am having a hard to using QLearn on real time data

> In my example I have a classifier that returns a number from 0-256, a reward, and two possible actions.
Please point me in the right direction. Thank you.
