### ISSUE TITLE
Add an Example for DistanceNetwork Class (Save and Load)

### ISSUE THREAD

**Issue by krflol** [accord-net/framework#1068]
I get multiple errors when trying to load a saved distancenetwork

I have tried
`(DistanceNetwork)DistanceNetwork.Load(fileName)` 
`(DistanceNetwork)Network.Load(fileName`
and the Accord.IO.Serializer method
All give me errors

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Neuro_DistanceNetwork.htm

**Comment by cesarsouza** [comment]
Hi @krflol,

Thanks for opening the issue! However, I couldn't reproduce the reported errors when saving or loading a network. I am posting below a passing unit test that I am about to commit to the framework, which hopefully you may be able to use as an example:

```csharp
Accord.Math.Tools.SetupGenerator(0);

int numberOfInputs = 3;
int hiddenNeurons = 25;

// Create some example inputs
double[][] input = 
{
    new double[] { -1, -1, -1 }, 
    new double[] { -1,  1, -1 }, 
    new double[] {  1, -1, -1 }, 
    new double[] {  1,  1, -1 }, 
    new double[] { -1, -1,  1 }, 
    new double[] { -1,  1,  1 }, 
    new double[] {  1, -1,  1 }, 
    new double[] {  1,  1,  1 }, 
};

// Create a new network
var network = new DistanceNetwork(numberOfInputs, hiddenNeurons);

// Create a teaching algorithm
var teacher = new SOMLearning(network);

// Use the teacher to learn the network 
double error = Double.PositiveInfinity;
for (int i = 0; i < 10; i++)
    error = teacher.RunEpoch(input);

// Save the network to a stream (could have been a file stream, or a file location)
MemoryStream stream = new MemoryStream();
Accord.IO.Serializer.Save(network, stream);

// Rewind the stream so we can load it back
stream.Seek(0, SeekOrigin.Begin);

// Load the network back from the stream
DistanceNetwork target = Accord.IO.Serializer.Load<DistanceNetwork>(stream);

// Make sure the network we loaded is exactly the same
Assert.AreEqual(network.InputsCount, target.InputsCount);
for (int i = 0; i < network.Layers.Length; i++)
{
    Assert.AreEqual(network.Layers[i].InputsCount, target.Layers[i].InputsCount);
    for (int j = 0; j < network.Layers[i].Neurons.Length; j++)
    {
        Assert.AreEqual(network.Layers[i].Neurons[j].InputsCount, target.Layers[i].Neurons[j].InputsCount);
        Assert.AreEqual(network.Layers[i].Neurons[j].Weights, target.Layers[i].Neurons[j].Weights);
    }
}
```

Regards,
Cesar

**Comment by krflol** [comment]
Im still struggling with this one. I am able to load the network, but when I try to adapt the network my error values start much higher than expected. I think it is something to do with  having to initiate a new SOMLearning class in order to continue training, but SOMLearning is not serializable. Perhaps it is an issue with my code, but that is my guess.
