### ISSUE TITLE
Any Idea, How do I use HaarObjectDetector on a Thread or Task?

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#1069]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question

This error happens when I try to run in a new thread or task,
.
this is when I tried to load many images files from a folder to detect face(s), starts from first file.
> Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

or

this is when I tried to load a single image file to detect face(s)
> Object is currently in use elsewhere.

.
.
This is the line error pointed,
> Rectangle[] objects = XHaarObjectDetector.ProcessFrame(ximage);

any idea @cesarsouza 

if not how about this one:
https://github.com/accord-net/framework/issues/1061

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Yes, in fact you may be stepping in a bug in GDI+. How are you loading your images from disk? Try to load them using [Accord.Imaging.Image.FromFile](http://accord-framework.net/docs/html/M_Accord_Imaging_Image_FromFile.htm) instead of Bitmap.FromFile if that's how you are loading them.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Also, if you are using the [HaarObjectDetector](http://accord-framework.net/docs/html/T_Accord_Vision_Detection_HaarObjectDetector.htm) in multiple tasks, please make sure that you are creating one detector for each of the tasks, and not creating just one HaarObjectDetector before you start the tasks and then reusing the same instance across different tasks. The HaarObjectDetector class is not thread-safe.

**Comment by blaisexen** [comment]
It's Ok now, thank you
