### ISSUE TITLE
Is it possible using Accord.Net to track objects like banana,apple or any fruits or any object like bottle.

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#1081]
For example,
in my web cam or video, if apple is seen in the video then it will make rectangle of the object OR if banana and beer bottle seen in the video then both objects will be rectangle.

@cesarsouza 
is that possible in the near version?

**Comment by blaisexen** [comment]
But,
Changing 
from
ResizeNearestNeighbor resize = new ResizeNearestNeighbor(320, 200);
to
ResizeNearestNeighbor resize = new ResizeNearestNeighbor(640, 400);
then
Changing
from
detector = new HaarObjectDetector(new FaceHaarCascade(), 32, ObjectDetectorSearchMode.Average, 1.5f, ObjectDetectorScalingMode.GreaterToSmaller);
            detector.UseParallelProcessing = true;
to
            detector = new HaarObjectDetector(new FaceHaarCascade(), 32, ObjectDetectorSearchMode.Average, 2.6f, ObjectDetectorScalingMode.GreaterToSmaller);
BUT
if you set ScaleFactor back to 1.5f 
THEN
it slows down so much

I'm sorry if I'm confusing, but I'm also confused!

But anyway I'll closed this issue soon as I get answers

**Comment by cesarsouza** [comment]
Hi @blaisexen,

No, we cannot do multiple object tracking at the moment, unfortunately. Maybe will be possible with Keras#.

Regards,
Cesar

**Comment by blaisexen** [comment]
thank you for the reply
