### ISSUE TITLE
Add an Example for BaseFilter.Apply Method (Signal)

### ISSUE THREAD

**Issue by OMRBYRM** [accord-net/framework#1087]
Please add an example for BaseFilter.Apply Method (Signal).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Audio_Filters_BaseFilter_Apply.htm

**Comment by cesarsouza** [comment]
Hi @OMRBYRM,

Thanks for opening the issue! However, is there any filter in particular that you would like to see an example for?

Regards,
Cesar

**Comment by OMRBYRM** [comment]
Thank you for replying. I'd like to see high pass and low pass filter
example. I have a double array. I want to filter that array.

**Comment by xxl-cc** [comment]
I have the same needs
