### ISSUE TITLE
Add an Example for KDTree(T) Class

### ISSUE THREAD

**Issue by vulkanzhou** [accord-net/framework#1088]
Please add an example for KDTree(T) Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Collections_KDTree_1.htm

**Comment by cesarsouza** [comment]
Hi @vulkanzhou,

Thanks for opening the issue! However, there is already an example available in the page you've linked. If you would like a more specific example, please re-open the issue.

Regards,
Cesar
