### ISSUE TITLE
Scatterplot marquee in the wrong place

### ISSUE THREAD

**Issue by nomnomdom** [accord-net/framework#111]
Whenever I create a scatterplot control, press the mouse down button on the control, and drag the mouse the zoom marquee is shown.  However, the marquee is drawn in the wrong location. 

Attached is a rough screen shot of the issue:

![plot](https://cloud.githubusercontent.com/assets/4212248/8025961/eab797de-0d34-11e5-85a9-0c60bcb4a8f1.png)

The issue seems to occur however I create the control.  I can reproduce it by creating a new windows form application, and replacing the form1.cs code with the following;

using System.Windows.Forms;
using Accord.Controls;

namespace Test01
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            ScatterplotBox.Show(new double[] { 1, 2 });
            InitializeComponent();
        }
    }
}

**Comment by cesarsouza** [comment]
Are you using a high-DPI display (i.e. a Surface Pro)? If that's the case, I think you will have to enable support for high-DPI in Windows Forms by calling the Windows function "SetProcessDPIAware" in your Program.cs you create your Application and its first Form.

Here is an example of how it can be done:

  - https://github.com/accord-net/framework/blob/development/Samples/MachineLearning/Decision%20Trees/Program.cs

I am not sure it will fix the issue, though. In any case, I will investigate the issue as soon as possible!

**Comment by cesarsouza** [comment]
Fixed in release 3.2.
