### ISSUE TITLE
Learning an HCRF<double[]>

### ISSUE THREAD

**Issue by ejulio** [accord-net/framework#112]
Is it possibile to learn an HCRF<double[]> without learning a HiddenMarkovClassifier first?
The available potential functions require a HiddenMarkovClassifier or they can only model a potential function of int.

**Comment by cesarsouza** [comment]
It should be possible, but you are right that right now there is no example on how to do it. For the time being, create a new HiddenMarkovModelClassifier without teaching it, and pass this untrained model to one of the the potential functions. This will be equivalent to creating a HCRF without learning the Markov classifier first. Only the structure (i.e. topology) will be carried over to the HCRF model, which would be somewhat desirable.

Hope it helps!

**Comment by ejulio** [comment]
With this setup I should be able to learn an HCRF though HiddenResilientGradientLearning, right?

**Comment by ejulio** [comment]
Hi César.
I was working on learnin the HCRF<double[]> and I noticed that when I'm using HiddenResilientGradientLearning I can't have negative observations. Is it ok?

my setup:
```C#
var s1 = new[]
{
	new double[] { -1.0, 0.0, 1.0 },
	new double[] { 0.0, 1.0, 2.0 },
	new double[] { 1.0, 2.0, 3.0 },
};

var s2 = new[]
{
	new double[] { -1.0, -2.0, -3.0 },
	new double[] { -2.0, -3.0, -4.0 },
	new double[] { -3.0, -4.0, -5.0 },
};

var s3 = new[]
{
	new double[] { -1.0, 1.0, -3.0 },
	new double[] { 3.0, 5.0, -4.0 },
	new double[] { -3.0, 7.0, -5.0 },
};

var observations = new[] {s1, s2, s3};
var classes = new[] {0, 1, 2};

var hmm = new HiddenMarkovClassifier(3, new Forward(5), new MultivariateNormalDistribution(3));
var f = new MarkovMultivariateFunction(hmm);
var hcrf = new HiddenConditionalRandomField<double[]>(f);
var hrgl = new HiddenResilientGradientLearning(hcrf);

hrgl.Run(observations, classes); // throws an ArgumentOutOfRangeException at MultivariateFirstMomentFeature.cs: line 126
```

**Comment by cesarsouza** [comment]
Yes, this is expected. You can make your observations always positive by transforming them to the exp domain using the Math.Exp function. In this way, observations that were initially negative will be between 0 and 1, and observations that were positive will be between 1 and positive infinity. 

I agree that the framework could have done this automatically, but in case your data was already positive this could lead to unnecessary computations during the learning phase.

Hope it helps!

Best regards,
Cesar

**Comment by cesarsouza** [comment]
Hi Julio!

Did you manage to solve the problem? Did the HCRF learning work for you? I will leave this ticket open so I can remember to update the documentation. Thanks!

Regards,
Cesar

**Comment by ejulio** [comment]
Yes, it worked. But I at the end I worked with HMMs instead of HCRFs.

**Comment by cesarsouza** [comment]
Hi Julio! 

Thanks for answering! But then, may I ask if there was any particular reason for working with the HMMs instead of HCRFs? Were they too hard to train? Did you find issues with your particular application?

I am looking into ways to make HCRF usage easier, so please let me know if you could share more details about what you tried, how did it work, etc. 

Regards,
Cesar

**Comment by ejulio** [comment]
I was working with HCRFs through HMMs. But I tried to work directly with HCRFs and the training time jumped from ~5s (HMMs or HMMs + HCRFs) to ~30s (HCRFs). I think that it was a mistake using the framework and at the moment I'd not much time to figure out what could the problem. But in the next weeks I'm thinking try HCRFs again.
