### ISSUE TITLE
Add an Example for Histogram.Cumulative Property

### ISSUE THREAD

**Issue by bemoregt** [accord-net/framework#1126]
Hi, @aggieben @bradphelan @dsblank @dreikin @haf.
 
Please add an example for Histogram.Cumulative Property.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/P_Accord_Statistics_Visualizations_Histogram_Cumulative.htm

**Comment by aggieben** [comment]
@bemoregt please don't @-notify specific people with your requests unless there is some prior context.
