### ISSUE TITLE
Add an Example for FourierTransform2.FFT Method (Complex[], FourierTransform.Direction)

### ISSUE THREAD

**Issue by bemoregt** [accord-net/framework#1128]
Hi, @aggieben @bradphelan @dsblank @dreikin @fdncred ,

Please add an example for FourierTransform2.FFT Method (Complex[], FourierTransform.Direction).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Math_Transforms_FourierTransform2_FFT_1.htm

**Comment by fdncred** [comment]
#672 Does that help?
