### ISSUE TITLE
In GeneralizedBetaDistribution.cs Generate calls Random with the parameters in the wrong order so sampling is incorrect

### ISSUE THREAD

**Issue by MichaelIRIS** [accord-net/framework#114]
The output of generate is in GeneralizedBetaDistribution.Pert is giving just the value 3 for symmetrical PERT and the reason, I believe, is below:
In GeneralizedBetaDistribution.cs Generate calls Random in the order (min, max, alpha, beta) Random  on the other hand accepts the parameters in the order (alpha, beta, min, max) as such parameters from Generate are being mapped in the following order
min->alpha
max->beta
alpha->min
beta->max

In a symmetrical distribution as the underlying distribution is B(3,3) so the random variable is being generated as Beta(min,max) and then scaled to just the number 3. 

double[] Generate(int samples) has the same problem with the parameter ordering.

**Comment by cesarsouza** [comment]
Many thanks for reporting this issue! I am correcting it right now.

**Comment by cesarsouza** [comment]
Will be available in the next release.
