### ISSUE TITLE
Blob Rectangles are wrong

### ISSUE THREAD

**Issue by fdncred** [accord-net/framework#1147]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [x] bug report
  - [ ] feature request

**Issue description**

@cesarsouza ,
After quite a bit of testing I believe the blob rectangles are being calculated wrong.

In this [file](https://github.com/accord-net/framework/blob/development/Sources/Accord.Imaging/Blob%20Processing/BlobCounterBase.cs#L1304)
What it is currently
```csharp
Blob blob = new Blob(j, new Rectangle(x1[j], y1[j], x2[j] - x1[j] + 1, y2[j] - y1[j] + 1));
```
What I think it should be
```csharp
Blob blob = new Blob(j, new Rectangle(x1[j], y1[j], x2[j] - x1[j], y2[j] - y1[j]));
```
It appears that the width and height are being added to for some reason that I don't understand.

Thanks,
Darren

**Comment by fdncred** [comment]
Updated Rectangle in 792015d

**Comment by honeyext** [comment]
@fdncred but now blob rectangles may have zero size. In case of x1=x2 or y1=y2 (one pixel blob)

Aliaksei

**Comment by fdncred** [comment]
We evaluate and accept a PR for this.
