### ISSUE TITLE
Add documentation about how to work with sparse data.

### ISSUE THREAD

**Issue by hodzanassredin** [accord-net/framework#115]
I can't find any docs which describe how to represent sparse data for example for text processing. More details in my [SO question](http://stackoverflow.com/questions/30842663/how-to-do-text-classification-with-accord-net)

**Comment by cesarsouza** [comment]
Thanks very much for creating this issue! I am adding a new example in the documentation for sparse support vector machines.

**Comment by cesarsouza** [comment]
An [example on how to learn sparse machines can be found at the bottom of the SupportVectorMachine documentation page](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_SupportVectorMachine_2.htm).
