### ISSUE TITLE
Random Forest Implementation

### ISSUE THREAD

**Issue by Bella31** [accord-net/framework#116]
Is there a Random Forest implementation in the Accord framework?

**Comment by Jaffray** [comment]
"Currently only supports binary classification."
https://github.com/accord-net/framework/pull/179

**Comment by cesarsouza** [comment]
Random Forests have been added in release 3.2.

**Comment by khiladiusman** [comment]
please let me know if i want to give weight to attributes, So is there Any way to do this in Random Forest.
If Yes tell how to do this..?
