### ISSUE TITLE
Still Alive? @cesarsouza 

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#1170]
- [x] question
@cesarsouza 

are you still alive and kicken? it's been 2 months since I haven't heard from you,

I hope you are fine and good.

Do you intend to continue this framework?

I advice to make this stable and do not add any other class requested from new users.
The important is this framework is stable on the current classes made closed.

no offend!
But unless you have tried the Accord_FaceRecognizer that uses lbph,svm,hmm,dnn,etc.,...(don't bother to include fisher and eigen)
then you can stop, lol, because I think there are lot of developers who really waited time on great face recognition. lol then you will have a lot of donation.

I think that is very true. :1234:

**Comment by fdncred** [comment]
Ya @cesarsouza, where are you? We miss you!

**Comment by blaisexen** [comment]
I think he was so tired with the face recognition algorithms, or he was hired by someone else.

**Comment by fdncred** [comment]
I figured he was just taking and extended vacation. He's put in a ton of work on this framework. I'd hate to see it be unsupported. I have a PR I'm working on now but I'm not going to submit it until he returns. I'm not sure how he can have time for this and another job.

**Comment by blaisexen** [comment]
if only I understand what was going on from this framework,, I will help.  My problem is I can't even make my own simpleeeeeeeeeeeeee basic framework structure. lol,

I can only understand a few of lines for the usage, but overall knowledge of how to make this framework or how it would be used is the most complicated in my mind.

I hope he's fine and ready for a good news.

**Comment by blaisexen** [comment]
@fdncred 
hi,
in your opinion and experienced, what is the best way to compare images 1 to 1?

for example I arrived to a solution(Rprop) that recognized face as false, the train face image was front then the compare image is 15 degrees facing?

I hope you don't mind asking you that, since I noticed your also active here.

**Comment by fdncred** [comment]
@blaisexen, No problem asking. 

I have some experience comparing grocery items. My path with that was to use OpenCv to resize source and destination image to equal sizes then use Kaze features to compare images. I wrote [this](https://github.com/shimat/opencvsharp_samples/blob/ed0f5ee7974e31cb7cfe5a8b56223cc1aa365231/SamplesCS/Samples/KAZESample2.cs) a year or so ago that does something similar to what I'm referring to.

This [site](http://chatzichristofis.info/?page_id=213) also has some excellent source code and tutorials about image comparison/similarity.

Good luck!

**Comment by blaisexen** [comment]
oh,
thanks, now I think about Keras.

**Comment by blaisexen** [comment]
or this one is good too:
https://sorenbouma.github.io/blog/oneshot/

**Comment by csalperwyck** [comment]
It would be better if César himself close this ticket ;-)

**Comment by blaisexen** [comment]
@csalperwyck 

I know @cesarsouza is bored now,
he was expecting something that is not accountable.

and as my comment rate from sourceforge accord.net is very true, I hope this guy still in good condition even he don't show himself.

**Comment by blaisexen** [comment]
@fdncred and @csalperwyck 

Do you know that compiled dlls from netStandard2.0 can be used in Android development like Xamarin.Android, Xamarin.IOS?

Do you have information how to port from 3.8.0 Accord.Net c# dev to android dev?

**Comment by csalperwyck** [comment]
No idea at all... I come from Java world :-)

**Comment by fdncred** [comment]
@blaisexen I'd start with #1096 and go from there. Yes, Xamarin supports .Net Standard.

**Comment by blaisexen** [comment]
@csalperwyck ,
I've been programming for almost 28 years, my comment to Java, very slow and until now, the only reason why I'm gonna continue trying Java because it never dies, slowly but surely.

@fdncred 
thanks for the links

my ques, @cesarsouza  wont be back again... this framework consumes hes time without proper income, less donations.  But I'm waiting for the time that I can used the framework with compensation, so I'll have my donation soon, lets say I have  $1000, then I will donate $50-$100 dollars, for a start.

Good Luck to you guys, thank you for the replies.


@cesarsouza ,
your the best mathematician programmer of all times.

**Comment by csalperwyck** [comment]
@blaisexen I don't comment on Java speed, it is ages that Java produced compiled code so it performance is similar to .NET.

**Comment by blaisexen** [comment]
@csalperwyck 
that's right, correct!
because now a days cpu runs faster, so it's carried away, 
but it the cpus don't get upgrades then Java has the worst speed of all during compilation time.
but Java is a survivor, that make's this language win.

**Comment by blaisexen** [comment]
@cesarsouza is Alive, so I'm going to closed this issue, lol, it's not, were just happy that you came.
