### ISSUE TITLE
Add an Example for CanvasCrop Constructor (Rectangle)

### ISSUE THREAD

**Issue by 4minds** [accord-net/framework#1197]
Please add an example for CanvasCrop Constructor (Rectangle).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Imaging_Filters_CanvasCrop__ctor.htm

**Comment by blaisexen** [comment]
hi,
try this lines of code,
```
Bitmap ximage = _YourImage_;
Rectangle[] objects = _YourObject_.ProcessFrame(ximage);

objects[0].X = 100;
objects[0].Width = 100;
objects[0].Y = 100;
objects[0].Height = 100;

var zimage = new Crop(objects[0]).Apply(ximage); //zimage is now a cropped Bitmap
```
