### ISSUE TITLE
Reset() of MulticlassSupportVectorMachine 

### ISSUE THREAD

**Issue by chefsache** [accord-net/framework#120]
http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_MulticlassSupportVectorMachine.htm

Hi there,
I have got a strange issue at the Accord Library to report.
I load a saved model from the filesystem and use the compute() Method then. 
I got a nullreferenceexception at a ...creatorreset() method.
I solved it by using the MulticlassSupportVectorMachine.reset() method, but now I dont know why I had to do that and which other effect do I get by that? My friend did not have to call that method before the compute(). I coded in VB, he in C#. I also added some classes and encapsulation. 
Also with his machine model, I had to call the reset method. Can you explain it or say if it a bug?

**Comment by cesarsouza** [comment]
Hi there!

Sorry for not replying earlier, I was in the middle of a trip with limited access to internet... apologies for that. Could you please upload a copy of the SVM model that was causing the exception so I could take a look at the issue?

Best regards,
Cesar

**Comment by chefsache** [comment]
sure, when I am at work (takes some days)

**Comment by cesarsouza** [comment]
Hi there,

Please, did you manage to generate a copy of the SVM model that causes the issue?

Thanks!

Best regards,
Cesar

**Comment by chefsache** [comment]
not yet. have to code sth and check some things. I will report back.
