### ISSUE TITLE
This is why Accord.Net Freezed -> Sad to Say that Ceasar is Gone! -> No Support.No Donation -> Programmer needs to EAT -> LIVE

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#1207]
https://www.bountysource.com/teams/accord-net/issues

thousands of users, millions maybe, but look at it.

not all developers are just users,

users of the framework,

users of the knowledge,

users for business!

maybe not all are GREED!

**Comment by blaisexen** [comment]
and Sad to say many software business industry closed because of open source code development! Open source code is a Mistake? Find out in the future shallow minds!

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Thanks for the support, but that is not true. The project does not need donations right now, and business are more than welcome to keep using the project to make as much money as they want, even without donations.

I understand your good intentions, but I will be closing this issue for now.

Regards,
Cesar
