### ISSUE TITLE
Future of Accord.NET?

### ISSUE THREAD

**Issue by FireDragonGameStudio** [accord-net/framework#1229]
Hy @cesarsouza, I think it's time to talk about the future of Accord.NET! Many users are working with it and it seems that this framework could be exceptionally useful for future projects (e.g. using it in Unity3D). As there are continuous issues posted and users offering their help to solve them by contributing PRs, why not making Accord.NET a full open source project? How about adding more main collaborateurs to Accord.NET and revive/reinforce contribution? It would be a shame if Accord.NET will be abandoned, after you put so much effort into creating, documenting and supporting it. 😿 

I'm not quite sure what your main intention was for starting this project, but afaik there was never some kind of big request for donations or something else (Please feel free to correct me if I'm wrong). A short clarification in terms of "What is the goal?", "How will the support be guaranteed?", "Please support Accord.NET also on a financial base, to improve it." would also encourage users to donate. Please protect Accord.NET from beeing a graveyard like AForge.NET!!!

Please just be honest and give us a short and snappy explanation about the current state and the future. Nobody will be mad at you, whatever the reasons are! ❤️ 

All the best and hoping to hear from you soon @cesarsouza 
Max aka FireDragonGameStudio

PS: Please also feel free to ask for help! There are many talented developers out there who are happy to help develop and improve Accord.NET 😃

**Comment by Rager71** [comment]
This is nicely written and a very valid request.

**Comment by blaisexen** [comment]
Yeah nice written, But did someone really donated to Accord.Net or @cesarsouza ?

I think there are so few.

and I ques it did not even reach $100 per month.

We don't live to code only, we hope and feed families.

No offense!

**Comment by FireDragonGameStudio** [comment]
@blaisexen None taken 😃 

I know what you mean and you've got a point, but there are also a lot open-source projects out there, where developers work on in their free time without earning money (just saying). Also a "call for support" would have been a possibility to encourage users to donate. 

But as long as we don't know the true reasons why @cesarsouza isn't responding, it's all just guessing.

**Comment by blaisexen** [comment]
Well that open source project you mean is a mistake.....didn't they know that  the users used there project for commercial purposes. and earn  much much money than  the original source they have....with not thankful gratitude.

They ears much, what about the?

lol

Open source code is a mistake... you don't see clearly right now.
Open source code personality have a shallow mind.

**Comment by FireDragonGameStudio** [comment]
@blaisexen I think there is a big misunderstanding here. Open-source (as far as my understanding is) does not literally mean, that nodody earns money. If there is a clear statement like: "Ok guys, we need xx dollars to keep the project up and running" I'd be happy to support (as I'm currently doing with other projects). The only thing I want to know beforehand is that the support is really needed, as there are a lot of projects, that I can use without donating, see popular examples like GIMP, VLC, Handbrake or Firefox.

So I would say your statement "Open-source is a mistake" is neither true nor false. It depends on the project, goals and also on the target audience. I would also say I'm an open source code personality and the shallow mind thing... I'm a developer for about 15 years now, so I would say I know a thing or two 😉 

AND to make it clear beforehand: no offense taken! I respect your opinion @blaisexen and just write this as my answer could possibly be misinterpreted by other readers.

**Comment by FireDragonGameStudio** [comment]
In addition to the commercial purpose, because I'm 100% with you @blaisexen when it comes to commercial use: I don't see any advantage for free commercial use.

**Comment by blaisexen** [comment]
I understand, 
thank you for your thoughts.

**Comment by cesarsouza** [comment]
@everyone

I just wanted to say I am still alive. I can totally add more collaborators to the Accord.NET project, and I have total interest to do so. I have big plans for this project and I still plan to continue contributing to it in the foreseeable future. 

Now, the main reason for the lack of updates was simply that I got overwhelmed. I am about to submit my PhD thesis in less than a month, have moved temporarily to another country, am just starting to prepare for the defense, and soon I will be switching to a new job. 

I really do apologize for the lack of updates. And I am deeply grateful for the number of messages I have received in the last weeks wondering whether everything is fine. 

Regarding commercial use, I absolutely do not have anything against it. People are free to use the project to earn as much money as they want, and although the project offers links for donations in the front page, no one is actually obliged to do so. 

Regards,
Cesar

**Comment by cesarsouza** [comment]
I forgot to precise: I will be resuming normal development as soon as I am back, which should happen around May. Also, if you would like to become a member of the project and apply to have commit access to the code, or know someone else who might be willing to, please let me know. All work done by you in the framework will be properly credited and advertised.

**Comment by xieliaing** [comment]
@Cesar I am glad you are back. PhD defense is a milestone in life, best luck!

**Comment by FireDragonGameStudio** [comment]
Hy @cesarsouza,
thank you for your reply 👍 All the best (from all of us) for your PhD thesis + defense and a great start with relocation and your new job. Really looking forward working with you on Accord.NET :)

Best regards,
Max

**Comment by csalperwyck** [comment]
All the best for your PhD - yep, it takes really a lot of time at the end - but Open Source contributions are a big plus in the academic environment. Please feel free to post the invitation for your defense :-)

I agree that few committers might help the project.
