### ISSUE TITLE
Bug in the Euclidean on Accord.Math.Distance

### ISSUE THREAD

**Issue by hzawary** [accord-net/framework#123]
Dear Dr,

First of all, thanks for create great Accord framework. I was be angry cause my program doesn't work correctly without any algorithmic or exception problems! I found a silly bug in parameter references that exchange it!
_________________________________________________________________
public static double Euclidean(double x1, double y1, double x2, double y2)
        {
            return System.Math.Sqrt(SquareEuclidean(x1, y1, x2, y2));
        }

public static double SquareEuclidean(double x1, double x2, double y1, double y2)
        {
            double dx = x1 - x2;
            double dy = y1 - y2;
            return dx * dx + dy * dy; ;
        }
_________________________________________________________________
It is bit issue, but it is a shadowy nightmare issue :)

Best regards,
Hashem.

**Comment by DiegoCatalano** [comment]
Hello hzawary,

I fixed in this moment, It's in the pull request #122. Thank you.

Best regards,
Diego Catalano

**Comment by cesarsouza** [comment]
Hi Hashem,

Sorry for the inconvenience, I've just accepted Diego's pull request fixing the issue!

Diego, thank you very much as always!

Best regards,
Cesar
