### ISSUE TITLE
Add an Example for HiddenMarkovModel Class

### ISSUE THREAD

**Issue by isaactarume** [accord-net/framework#1230]
Hi

Does  Accord. have a HHMM implementation in C# just curious since some highly structured problem need more structure other than  a flat HMM. Fine and Singer (1998) have a mathematical formulation of the implementation, Or are there any suggestion of how to capture multi-level structures in modeling natural hierarchical problems?

**Comment by isaactarume** [comment]
So representing an HHMM as a HMM whose states are the production states of the HHMM with a fully connected structure means that the resulting HMM lacks the multilevel structure because there is non-zero probability of transition from any state to any other state.

Now to solve this issue one might introduce constraints which will bring back the multilevel structure.

Apply restriction to the model to allow for estimation and inference to be feasible.
The transition matrix will have zero probabilities to represent nodes with no connections

**Comment by blaisexen** [comment]
hi,
as far as I know HMM is a Sequence classification, for example: handwriting(signature) recognition

for image or object or face recognition then I think HMM is not the answer.

**Comment by isaactarume** [comment]
hi, thanks for your comment and yes l agree but,
in this incident l have used HMM for anomaly detection successfully, l just needed to see if l used HHMM whether that will improve the results as by FineSinger1998, l however have not come across a C# implementation of HHMM, thats what am looking for.

**Comment by blaisexen** [comment]
I understand, here's the sample link,
http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Markov_HiddenMarkovModel.htm

and at the end of the page,
https://github.com/accord-net/framework/wiki/Classification

Good Luck
