### ISSUE TITLE
Add an Example for FanChenLinSupportVectorRegression(TKernel) Class

### ISSUE THREAD

**Issue by mauricepillet** [accord-net/framework#1237]
Please add an example for FanChenLinSupportVectorRegression(TKernel) Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_FanChenLinSupportVectorRegression_1.htm

**Comment by blaisexen** [comment]
```
// Create a LibSVM-based support vector regression algorithm
var teacher = new FanChenLinSupportVectorRegression<Gaussian>()
{
    Tolerance = 1e-5,
    // UseKernelEstimation = true, 
    // UseComplexityHeuristic = true
    Complexity = 10000,
    Kernel = new Gaussian(0.1)
};

// Use the algorithm to learn the machine
var svm = teacher.Learn(inputs, outputs);

// Get machine's predictions for inputs
double[] prediction = svm.Score(inputs);

// Compute the error in the prediction (should be 0.0)
double error = new SquareLoss(outputs).Loss(prediction);
```

**Comment by wup11111** [comment]
@blaisexen
Hi,Dear!

If I did not input  `Kernel = new Gaussian(σ)`,
how σ is assigned

**Comment by blaisexen** [comment]
if you want to remove <Gaussian> then your referring a linear kernel.

                    double[][] xinputs = new double[imagecount][];
                    double[] xoutputs = new double[imagecount];
                    for (int i = 0; i < imagecount; i++)
                    {
                        xinputs[i] = inputvalues[i];
                        xoutputs[i] = inputnums[i];
                    }

                    SupportVectorMachine gsvm; //make Gloval Variable.... for gsvm.Decide.....
                    var fteacher = new FanChenLinSupportVectorRegression()
                    {
                        UseKernelEstimation = true, 
                        UseComplexityHeuristic = true
                    };
                    gsvm = fteacher.Learn(xinputs, xoutputs);


Good Luck!
