### ISSUE TITLE
How to rotate the camera view?

### ISSUE THREAD

**Issue by sliontc** [accord-net/framework#1252]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

I have finished the face tracking solution. And now I want to rotate the camera view which I didn't find related resources in wiki.

**Comment by blaisexen** [comment]
hi, do you mean the camera view rotate up side down when using Accord.Net?

How about using another Web Camera application, does it rotate also?

or do you really want to rotate the camera even it's in the proper place?

**Comment by sliontc** [comment]
Yes, I need to rotate the camera view. Generally the camera is horizontal and the resolution ratio is like 640 * 480 which is horizontal rectangle. If I rotate the camera(not view), the face tracking doesn't work. So I want to rotate the view by code.

**Comment by blaisexen** [comment]
I think that can be done by this, use the new image for the video.
http://accord-framework.net/docs/html/T_Accord_Imaging_Filters_RotateNearestNeighbor.htm

or if you want to use the camera properties, here:

```
internal IVideoSource videoSource = null;
internal FilterInfoCollection videoDevices;
internal string ldevice;

        private void uselocalcamera(int camnum)
        {
            try
            {
                videoDevices = new FilterInfoCollection(FilterCategory.VideoInputDevice);
                if (videoDevices.Count == 0) return;
                ldevice = videoDevices[camnum].MonikerString;
                selectlocalvideodevice(ldevice);
            }
            catch
            {
            }
        }

        private void selectlocalvideodevice(string dev)
        {
            // create video source
            VideoCaptureDevice videoSource = new VideoCaptureDevice(dev);
            // set frame size
            videoSource.VideoResolution = selectResolution(videoSource);
            // open it
            OpenVideoSource(videoSource);
        }

        private void button_Click(object sender, EventArgs e)
        {

uselocalcamera(0); //first camera

            if ((videoSource != null) && (videoSource is VideoCaptureDevice))
            {
                try
                {
                    ((VideoCaptureDevice)videoSource).DisplayPropertyPage(this.Handle);
                }
                catch (NotSupportedException)
                {
                    MessageBox.Show("The video source does not support configuration property page.", "Error",
                        MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
```

**Comment by sliontc** [comment]
Thanks for your tips. I use the code you provided and got the camera properties. Here is screenshot attached. From the image, you could see the Roll configuration is disabled. Does that mean the camera don't support rotation?
Btw, how can I use the image filter to the video?
![tim 20180314091552](https://user-images.githubusercontent.com/6959147/37378052-87a81618-2768-11e8-906f-ba64d3548ec3.jpg)

**Comment by blaisexen** [comment]
:1st_place_medal: 
https://sourceforge.net/projects/accord-net-rotate-video-camera/

**Comment by blaisexen** [comment]
@sliontc 
please closed this issue or question rotating the camera.

**Comment by sliontc** [comment]
Great thanks.
