### ISSUE TITLE
Fast KMeans (Request)

### ISSUE THREAD

**Issue by DiegoCatalano** [accord-net/framework#127]
Hello César,

It would be interesting writing a fast kmeans.

**Comment by cesarsouza** [comment]
Hi Diego,

Do you mean the one described in this paper? http://www.eecs.tufts.edu/~dsculley/papers/fastkmeans.pdf

Regards,
Cesar

**Comment by DiegoCatalano** [comment]
Hello César,

That is exactly what the framework (and I) need. It is also necessary to have a version of fast kmeans.

Best regards,
Diego

**Comment by cesarsouza** [comment]
Added in #817

**Comment by cesarsouza** [comment]
Added in 3.8.0.
