### ISSUE TITLE
Multi class support vector machine doesn't work with SparseGaussian kernel

### ISSUE THREAD

**Issue by Telavian** [accord-net/framework#130]
I was trying to test a Multi class support vector machine with a few different kernels to see what worked best. My test data was very large so I was limited to the sparse kernels.

Upon testing I found that SparseGaussian fails in the method SparseLinear.SquaredEuclidean.

It seems that method fails in the other sparse kernels that use it.

**Comment by cesarsouza** [comment]
Thanks for reporting the issue! This issue was resolved as part of a much larger refactoring and redesign that unfortunately took several months to complete. The documentation on how to use sparse kernels will be updated soon.

**Comment by cesarsouza** [comment]
Fixed on release 3.3.0.
