### ISSUE TITLE
Add an Example for VideoFileWriter.WriteAudioFrame Method

### ISSUE THREAD

**Issue by Qaiserpk** [accord-net/framework#1303]
Please add an example for VideoFileWriter.WriteAudioFrame Method with WriteVideoFrame(Bitmap, TimeSpan)
.
Target is a video where you have one image per audio file. All images and audio clips are combined to produce single video file.
Help Topic: http://accord-framework.net/docs/html/M_Accord_Video_FFMPEG_VideoFileWriter_WriteAudioFrame.htm

**Comment by enginates** [comment]
is there any update on this ?
