### ISSUE TITLE
Add an Example for HaarCascade car Class

### ISSUE THREAD

**Issue by mccabe-d14** [accord-net/framework#1361]
Please add an example for HaarCascade Class.

Hi could you add an example on how to implement HaarCascade Car detection class in C# please. I have not been able to achieve this.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Vision_Detection_HaarCascade.htm

**Comment by mbithy** [comment]
Please refer to this example with an explanation using accord.net and code from  [CodeProject](https://www.codeproject.com/Articles/441226/Haar-feature-Object-Detection-in-Csharp)
