### ISSUE TITLE
Separate the Linear regression model from the learning algorithm

### ISSUE THREAD

**Issue by cesarsouza** [accord-net/framework#138]
Separate the LinearRegression model from the learning algorithms, also adding support for resilient propagation and other gradient optimization methods.

**Comment by cesarsouza** [comment]
The OrdinaryLeastSquares class can now be used to learn LinearRegression models.

**Comment by pantojasc** [comment]
Hi.
I like the split.

There seems to be a mismatch between OrdinaryLeastSquares.Learn(x,y) and SimpleLinearRegression.Regress(x,y). Replacing SimpleLinearRegression.Regress with OrdinaryLeastSquared.Learn in the RANSAC sample application, the result differs. The Intercept/Slope of the SimpleLinearRegression object output of OrdinaryLeastSquares.Learn(x,y) is switched relative to the behavior of SimpleLinearRegression .Regress(x,y).

Example:
var regression = new OrdinaryLeastSquares().Learn(new double[]{0,1,2,3}, new double[]{4,3,2,1});
results in
Slope = 4
Intercept: -1
but should be
Slope = -1
Intercept = 4

**Comment by cesarsouza** [comment]
Hi there,

Thanks for reporting the issue! I had also noticed this problem, and I have uploaded another pre-release package for the framework to the NuGet servers. Please, can you try updating to the newest pre-release version and see if the issue still persists?

You can get pre-release packages by clicking the "Include prerelease" checkbox in the NuGet package browser in Visual Studio.

Hope it helps!

Regards,
Cesar

**Comment by pantojasc** [comment]
Works like a charm! Thank you.

**Comment by cesarsouza** [comment]
Fixed on release 3.3.0.
