### ISSUE TITLE
AForge version included in Accord.Net

### ISSUE THREAD

**Issue by ytn3rd** [accord-net/framework#140]
Hey,
Quick question. Is the AForge potions (AForge.Video) that is included Accord.Net untouched, or has there been updates to it? I notice in NuGet it says its version is 3.0.2 whereas AForge is 2.2.5.

**Comment by cesarsouza** [comment]
Hi there,

As far as I can remember, AForge.Video hasn't received any significant changes yet. However, the current goal right now is to perfectly unify the two frameworks under the Accord.NET name, and as such, one of the first steps I had to do was to put the version numbers of both projects in sync.
