### ISSUE TITLE
MeanShift Distortion method

### ISSUE THREAD

**Issue by LeonIPierre** [accord-net/framework#1404]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [x] bug report
  - [ ] feature request

**Issue description**
There seems to be a conflict with the [Distortion](https://github.com/accord-net/framework/blob/f78181b82eb6ee6cc7fd10d2a7a55334982c40df/Sources/Accord.MachineLearning/Clustering/MeanShift/MeanShiftCluster.cs) method in the algorithm. The first line will throw an unsupported exception if the labels are not null but at the same time the parallel loop uses that variable in a lock thus throwing "value cannot be null exception" rendering the method unusable. I'm new to the code base and I'm not sure which should be changed. Can anyone point me in the right direction?

**Comment by crtmneric** [comment]
ping @LeonIPierre

**Comment by LeonIPierre** [comment]
Should this be closed or should I wait until its merged?

**Comment by LeonIPierre** [comment]
@crtmneric did you get the bounty? If not send me the link I can't seem to find it.
