### ISSUE TITLE
Compiling Error on Xamarin

### ISSUE THREAD

**Issue by CabbyM** [accord-net/framework#143]
I've installed Accord through nuget but came across an error while compiling. Im using the latest xamarin on osx. I've restarted xamarin and reinstalled this package but im getting the same results. Anyone having the same problem ? 

The package Accord and Accord.Video compiles with no errors. But i've noticed that it gives me errors when adding the package Accord.Video.FFMPEG to the project. 

Error: Target 'CopyFilesToOutputDirectory', a dependency of target 'CopyNativeBinaries', not found.

**Comment by cesarsouza** [comment]
Hi there,

I am sorry for your experienced difficulties; unfortunately I don't have Xamarin or a MacOS so I can't actually reproduce this issue right now. However, please let me know which packages are you installing through NuGet so I can investigate better.

Best regards,
Cesar

**Comment by CabbyM** [comment]
Hi Cesar,

I’ve tried to reinstall Xamarin on mac osx an started e new project and then add the accoord.video.ffmpeg to the project but i still get this compiling error.
Error: Target 'CopyFilesToOutputDirectory', a dependency of target 'CopyNativeBinaries', not found. 
After reading your response on github i thought maybe i should try it on a windows os to see if i get the same error. So i installed xamarin on a windows machine and repeat the same steps and it compiled there with no errors. So i dont know if it has something to do with Xamarin on osx because it also compiles in VS2012. 

Regards,


Carven

**Comment by cesarsouza** [comment]
The project has now a specific build target called "Mono". If the framework is compiled using this configuration it should work on any platform/distribution supporting the latest versions (2.8+) of Mono.
