### ISSUE TITLE
Add an Example for ByteRange Constructor

### ISSUE THREAD

**Issue by wangzhian2017** [accord-net/framework#1439]
Please add an example for ByteRange Constructor.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://localhost:22631/docs/html/M_Accord_ByteRange__ctor.htm

**Comment by justingruenberg** [comment]
There is an example on [the class](http://accord-framework.net/docs/html/T_Accord_ByteRange.htm). Not sure what functionality you would like to see that's specific to the constructor.
