### ISSUE TITLE
User Level Discussions

### ISSUE THREAD

**Issue by Bluejay47** [accord-net/framework#144]
Is there a forum where user level discussions about this framework should take place? I apologize for posting this here, but I have looked and can't seem to find the link.

Thanks,

**Comment by OmarMAmin** [comment]
Thanks @Bluejay47  for this question, I do have the same question, where should we ask or discuss about this framework.

Thanks

**Comment by cesarsouza** [comment]
Hi there,

At the current time there is no forum for carrying user level discussions about the framework. There used to be, but unfortunately people would mistake it as a place to post issues or bugs. For questions on how to use the framework, the recommended place is Stackoverflow (questions posted there are tracked). 

However, I am open to suggestions; if anyone has a suggestion for a great place for creating/maintaining a discussion group (except Google Groups), please let me know!

Best regards,
Cesar

**Comment by cesarsouza** [comment]
Also please don't be afraid of posting in the issue tracker; I also just realized that there is a 'question' label that can be leveraged to tag questions or discussions here in the tracker itself. Perhaps it could be used to keep user level discussions here too. What do you think?

Regards,
Cesar

**Comment by anders9ustafsson** [comment]
@cesarsouza Have you considered the [Gitter](https://gitter.im) chat forum? I think it works fairly well for quick discussions on a specific project, and it is very well integrated with Github. Registering *accord-net/framework* on *Gitter* should be a matter of seconds :-)

**Comment by Bluejay47** [comment]
If the devs are ok with us posting questions here I obviously have no problem with it. I just didn't want to be junking up their dev discussions unless they were ok with it :)

**Comment by cesarsouza** [comment]
I am not a big fan of having a separate site for discussions because what happens is that users would ask questions there that wouldn't become easily searchable or seen by others that are facing similar issues. But this might have been just because of a bad experience with Google Groups: So I have just followed Anders' advice and I created a room on Gitter:

https://gitter.im/accord-net/framework

@anders9ustafsson Thanks for the suggestion!! Let's see how it works!

Regards,
Cesar

**Comment by anders9ustafsson** [comment]
@cesarsouza I hope I haven't tricked you into anything :-)

From a history searchability point of view *Gitter* might not be the optimal tool either. From that perspective, I think your idea of using the **question** label here on *Github Issues* is a better choice. Personally I have primarily found *Gitter* useful for day-to-day discussions and announcements. I hope it will work out fine for *Accord.NET* as well.

**Comment by cesarsouza** [comment]
Indeed, using the question label here in GitHub is a much better choice. I do not mind cluttering the GitHub issues pages as we have filters/labels for this reason. I would actually avoid the gitter channel as it is actually quite hard to find time to stay there and listen to user requests.
