### ISSUE TITLE
MovingNormalStatistics

### ISSUE THREAD

**Issue by Bluejay47** [accord-net/framework#145]
I was attempting to modify the values of a matrix to be a n-period moving average per column and ran across this class, but I couldn't find any details on how to use it. Even after looking at the source code for the class I am at a bit of a loss. Any details available?

**Comment by cesarsouza** [comment]
Hi there,

Moving Normal Statistics its a class that you can feed one value at a time, and it keeps track of the mean and variance of your samples without registering the samples themselves. It is useful for feeding (x,y) trajectories of a movement tracker, for example, and filter the results (i.e. show the average point on the past 10 frames) and monitor the quality of the tracking (i.e. if the variance becomes too high, tracking might have been lost).

Values are registered using the "Push" method.

I agree that the documentation for that class is nearly absent. I will have to fix that.

Regarding your particular problem, can you show me an example of your input and what would be the best way for you to retrieve back the outputs that you want? If it cannot be done with the framework right now in an easy way, we can add a way to do so.

Regards,
Cesar

**Comment by cesarsouza** [comment]
There is also the RunningNormalStatistics, which is basically the same, but doesn't consider a time window. It simply goes building the mean and the variance as samples become available.

I also accept suggestions on how to organize those classes better, if you have any!

**Comment by Bluejay47** [comment]
Seems straight forward enough. I was definitely over thinking it.

Are you open to having help with the documentation?

As soon as I use this in one of my projects I can try to clean up and simplify my code add it to the documentation as an example with some text based on your description if that would be helpful?

**Comment by cesarsouza** [comment]
Yes, it would definitely be helpful! I will leave this issue/question open so we can track it in the future!

Huge thanks!

**Comment by Bluejay47** [comment]
Hows this:

>Provides statistics derived from successive segments of constant, overlapping size ('windowSize') of a >series of values. Values are added one at a time to a MovingNormalStatistics instance by the Push() >method and are not maintained by the instance.

```c#
Random rnd = new Random();
int windowSize = 5;

Accord.Statistics.Moving.MovingNormalStatistics ms = new Accord.Statistics.Moving.MovingNormalStatistics(windowSize);

for (int i = 0; i < 50; i++) {

    ms.Push(rnd.Next(1, 10));

}

Debug.Print ("Sum: " + ms.Sum);
Debug.Print ("Mean: " + ms.Mean);
Debug.Print ("Standard Deviation: " + ms.StandardDeviation);
```

**Comment by cesarsouza** [comment]
An example has been added to the [MovingNormalStatistics documentation page](http://accord-framework.net/docs/html/T_Accord_Statistics_Moving_MovingNormalStatistics.htm) in release 3.8.0.
