### ISSUE TITLE
Assistance with Neural Network Implementation

### ISSUE THREAD

**Issue by Bluejay47** [accord-net/framework#146]

**Comment by cesarsouza** [comment]
Did it work? :smile: The problem is that you have to normalize your outputs to the interval of the output of the activation function (i.e. [-1,1] for BipolarSigmoid, [0,1] for Sigmoid). This was a common issue with AForge that I plan to mitigate once I add support for having multiple activation functions in the same network.

Thanks for sharing the issue though, I would have loved to have it here as an example for further people facing the same problem!

Regards,
Cesar

**Comment by Bluejay47** [comment]
Yes, I figured out through trial and error that the inputs had to be scaled between 0 and 1. That threw me for a bit as other libraries I have used and when I have written my own forward and back propagation code the inputs only had to be close to the -1:1 range. Thanks for following up though.

**Comment by Bluejay47** [comment]
Yes, I figured out through trial and error that the inputs had to be scaled between 0 and 1. That threw me for a bit as other libraries I have used and when I have written my own forward and back propagation code the inputs only had to be close to the -1:1 range. Thanks for following up though. 


     On Wednesday, September 30, 2015 3:50 AM, César Souza <notifications@github.com> wrote:
   

 Did it work?  The problem is that you have to normalize your outputs to the interval of the output of the activation function (i.e. [-1,1] for BipolarSigmoid, [0,1] for Sigmoid). This was a common issue with AForge that I plan to mitigate once I add support for having multiple activation functions in the same network.Thanks for sharing the issue though, I would have loved to have it here as an example for further people facing the same problem!Regards,
Cesar—

**Comment by Abulala** [comment]
> Did it work? 😄 The problem is that you have to normalize your outputs to the interval of the output of the activation function (i.e. [-1,1] for BipolarSigmoid, [0,1] for Sigmoid). This was a common issue with AForge that I plan to mitigate once I add support for having multiple activation functions in the same network.
> 
> Thanks for sharing the issue though, I would have loved to have it here as an example for further people facing the same problem!
> 
> Regards,
> Cesar

Were you able to implement multiple activation functions in the same network? If yes can you give an example? If no, do you know any workarounds?
