### ISSUE TITLE
Pearson VII Universal Kernel Fix

### ISSUE THREAD

**Issue by rozgura** [accord-net/framework#148]
The constructor for Pearson kernel is missing the call to set the "constant" variable, so it is always 0, producing incorrect training.  All we need is this line in the main constructor:

this.constant = 2 * Math.Sqrt(Math.Pow(2, (1 / omega)) - 1) / sigma;

Sorry if this needs to be put somewhere else, I couldn't find a bug report thing here and I'm inexperienced on github.

**Comment by DiegoCatalano** [comment]
Hello rozgura,
I forget to set the constant, I'll fix it.
