### ISSUE TITLE
Baum-Welch learning iterations

### ISSUE THREAD

**Issue by Flori1989** [accord-net/framework#154]
I have discovered the following problem with the iteration counting in the BaseBaumWelchLearning class.

When I call the "run" method the CurrentIteration value is 0. But then in line 259 the NewValue property of the convergence object is initialized, which sets CurrentIteration to 1. When the first value is assigned to NewValue in line 309, CurrentIteration is set to 2. This leads to the problem that the parameter re-estimation is only done when MaxIterations is at least 3.

**Comment by cesarsouza** [comment]
Fixed in release 3.6.0.
