### ISSUE TITLE
Issue in Survival analysis using VB.net

### ISSUE THREAD

**Issue by Dolphin72** [accord-net/framework#157]
Hi,

I am trying to implement survival analysis with VB.net. I kind of follow the given example  in C# and use

Dim cox As New Accord.Statistics.Analysis.ProportionalHazardsAnalysis(DataCox_Variable,        DataCox_Time, DataCox_Event)

cox.Compute()  

But cox.compute() is not accepted, and its seems it expect a regression model (Accord.Statistics.Models.Regression.ProportionalHazard). It's not in the example in C# I try to follow, and I am wondering what I do wrong. Can someone help?

**Comment by cesarsouza** [comment]
Examples in VB.NET have been added to the [ProportionalHazardAnalysis documentation page](http://accord-framework.net/docs/html/T_Accord_Statistics_Analysis_ProportionalHazardsAnalysis.htm) in 3.8.0.
