### ISSUE TITLE
LeptonicaSharp

### ISSUE THREAD

**Issue by Phreak87** [accord-net/framework#1585]
- [ ] question
  - [ ] bug report
  - [X] feature request

**Issue description**

Maybe you like to add my Leptonica Wrapper with over 2000 image manipulation
functions to the imaging class. Leptonica is used in great projects like Tesseract too.

You can find the wrapper here:
https://github.com/Phreak87/LeptonicaSharp

**Comment by fdncred** [comment]
LOL. I'm familiar with your wrapper, Markus. :)

**Comment by fdncred** [comment]
Feel free to send a PR for review.
