### ISSUE TITLE
Random Forest method

### ISSUE THREAD

**Issue by SkyQuant** [accord-net/framework#161]
What the class within this framework which is expose Random Forest method?

**Comment by cesarsouza** [comment]
At the time this question was asked unfortunately there was no RandomForest implementation in the framework. However, as of now it is provided by the [Accord.MachineLearning.DecisionTrees.RandomForest](http://accord-framework.net/docs/html/T_Accord_MachineLearning_DecisionTrees_RandomForest.htm) class.
