### ISSUE TITLE
HoughLineTransformation corrupts image size

### ISSUE THREAD

**Issue by haf** [accord-net/framework#164]
I got code like this:

``` fsharp

  printfn "apply canny"
  let cannied =  canny.Apply eight
  cannied.Save (sprintf "cannied-%s" args.[0])

  let lineTransform = new HoughLineTransformation()
  printfn "apply hough"
  lineTransform.ProcessImage cannied

  let houghLineImage = lineTransform.ToBitmap()
  houghLineImage.Save args.[1]
```

After apply canny:

![cannied-img_2112](https://cloud.githubusercontent.com/assets/193115/10768135/de3e1cce-7cdf-11e5-9901-513cc05d3d19.png)

After apply hough:

![test-hough](https://cloud.githubusercontent.com/assets/193115/10768156/efa5f2a2-7cdf-11e5-9d50-4f1f9713fa48.png)

It seems the hough transformation somehow distorts the image... I noticed it's the only one that goes through unmanaged memory, perhaps that's the reason?

**Comment by cesarsouza** [comment]
Well...

Please accept my deep apologies for not having been able to answer this question earlier. In fact, the output of the Hough Transform is correct. It is not that it is corrupting the image, it's just that the set of lines shown at the bottom are really the output of the Hough Transform, e.g. [check this image from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Hough-example-result-en.png/800px-Hough-example-result-en.png):

![Hough Transform](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Hough-example-result-en.png/800px-Hough-example-result-en.png)

If you would like to draw the lines that can be found by the Hough Transform into the original image, please [take a look at the Hough Transform sample application](https://github.com/accord-net/framework/wiki/Sample-applications#hough-transform). It should give an example on how it can be done.

Regards (and sorry again),
Cesar

**Comment by haf** [comment]
Better late than never, right?
