### ISSUE TITLE
OutOfMemory exception at Matrix.Multiply

### ISSUE THREAD

**Issue by lolaparra** [accord-net/framework#165]
Hello: I have some troubles when I run this code on a PC with Intel i7, 4GB RAM.
 My code is: (n_table.Length is about 21 integer and isize depends, sometimes is 280 and others is 1024)
for(int i=0; i<n_table.Length;i++)
            {
                int n = n_table[i]; 
                int m = Math.Abs(m_table[i]); 
                int m_sign = m_table[i]; 
                double[] zer = new double[isize * isize];

                for (int k = 0; k <= (n - m) / 2; ++k)
                {
                    double[] vp = ((double[])matrices[0]).ElementwisePower(n - 2 * k);
                    double v = (Math.Pow(-1, k) * UtilM.fact(n - k)) / ((UtilM.fact(k)) * UtilM.fact((n + m) / 2 - k) * UtilM.fact((n - m) / 2 - k));
                    vp = v.Multiply(vp);
                    zer = Matrix.Add(zer, vp);
                }

                double[] thM = ((double[])matrices[1]).Multiply(m);

                
                if (m != 0)
                {
                    if (m_sign > 0)
                        zer = (zer.Multiply(Math.Sqrt(2))).ElementwiseMultiply(thM.Apply(Math.Cos));
                    else
                        zer = (zer.Multiply(Math.Sqrt(2))).ElementwiseMultiply(thM.Apply(Math.Sin));
                }

                
                zer = zer.Multiply(Math.Sqrt(n + 1));
                this.stack[i] = zer;
            }
  

When I call this code sometimes appears a "OutofMemory exception" in lines with Multiply.
How can I fix this? Release memory? or something? 

Thank you

**Comment by danthecomputerguy** [comment]
I was having the same issue with a Classification (SVMs), but when I made all of the suggested changes in post #133, the OutofMemory exception was fixed.

**Comment by lolaparra** [comment]
The suggested changes include that change the compilation to x64 bits but I need it at x86 because my windows is for 32bits. Which release have you using?

**Comment by danthecomputerguy** [comment]
Windows 8.1 64 bit.  I think either way we will need to use 64 bit, just simply because some of the things that accord does takes a lot of memory, and 32 bit is limited when it comes to memory.  That is just a guess though.

**Comment by cesarsouza** [comment]
Hello there,

The latest release of the framework now provides a more memory-efficient API for manipulating native C# matrices. In the particular code originally posted as an example, one of the best approaches for reducing memory usage is to reuse memory, rather than generate multiple copies of the data at every time. 

As such, parts of the code could now be rewritten like this:

```
// Allocate all needed memory outside of the loop
double[]][ zer = Jagged.Zeros(isize, isize);
double[] vp = ...

for (int i=0; i < n_table.Length; i++)
{
    int n = n_table[i]; 
    int m = Math.Abs(m_table[i]); 
    int m_sign = m_table[i]; 
    double[] zer = new double[isize * isize];
    for (int k = 0; k <= (n - m) / 2; ++k)
    {
        // almost all matrix methods now offer a 'result' parameter that 
        // can be used to reduce memory usage by reusing existing matrices/arrays
        matrices[0]).Pow(n - 2 * k, result: vp); 

        double v = (Math.Pow(-1, k) * UtilM.fact(n - k)) / ((UtilM.fact(k)) * UtilM.fact((n + m) / 2 - k) * UtilM.fact((n - m) / 2 - k));
                v.Dot(vp, result: vp);
                zer.Add(vp, result: zer);
            }

            matrices[1].Dot(m, result: thM);

            if (m != 0)
            {
                zer.Multiply(Math.Sqrt(2), result: zer);
                if (m_sign > 0)
                {
                    thM.Apply(Math.Cos, result: thM);   
                }
                else
                {
                    thM.Apply(Math.Sin, result: thM);
                 }
                 zer.Dot(thM, result: zer);
            }
            zer.Multiply(Math.Sqrt(n + 1), result: zer);
            this.stack[i] = zer.Copy(); // (if you need to force a copy)
        }
```

Regards,
Cesar
