### ISSUE TITLE
HiddenMarkovModel< TDistribution> . Posterior Method (Int32[] ,Int32[] ) 

### ISSUE THREAD

**Issue by yanpanlau** [accord-net/framework#167]
Dear Cesar,

          In HiddenMarkovModel< TDistribution>. I am trying to get the sequences of states using posterior decoding method. Given the observation are double[] array, I think the first argument should be double[] instead of int[]. Would you please take a look?

Proposed method: 
public double[][] Posterior( DOUBLE[] observations, out int[] path)

http://accordframework.net/docs/html/M_Accord_Statistics_Models_Markov_HiddenMarkovModel_1_Posterior_1.htm

Thanks,

Ben

**Comment by cesarsouza** [comment]
Thanks for reporting the issue! I have just committed a fix.

**Comment by cesarsouza** [comment]
Fixed in release 3.2.
