### ISSUE TITLE
Add an Example for UnmanagedImage.FromManagedImage Method (Bitmap)

### ISSUE THREAD

**Issue by ArthuurGomes** [accord-net/framework#1672]
Please add an example for UnmanagedImage.FromManagedImage Method (Bitmap).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Imaging_UnmanagedImage_FromManagedImage.htm

**Comment by justingruenberg** [comment]
Is there anything you're trying to accomplish?  This just creates a new UnmanagedImage from an existing System.Drawing.Bitmap.
