### ISSUE TITLE
Add an Example for HarrisCornersDetector Constructor

### ISSUE THREAD

**Issue by yakunindmitry** [accord-net/framework#1692]
Please add an example for HarrisCornersDetector Constructor.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Imaging_HarrisCornersDetector__ctor.htm

**Comment by justingruenberg** [comment]
There is an example of how to use it on the [class overview page](http://accord-framework.net/docs/html/T_Accord_Imaging_HarrisCornersDetector.htm).
