### ISSUE TITLE
Add Random Forest Implementation

### ISSUE THREAD

**Issue by functionsoft** [accord-net/framework#172]
Please add Random Forest to the Accord Framework, built upon the existing Decision Trees implementation as an Ensemble method.

Many thanks

**Comment by mthmn20** [comment]
@functionsoft, @cesarsouza, @DiegoCatalano : I actually wrote a Random Forest implementation on top of Accord. Should I just submit a pull request? I've never contributed to an open source project before so I'm not sure if there's anything else I need to do.

**Comment by DiegoCatalano** [comment]
Hello mthmn20,

Yes, you can submit a pull request. Does your implementation handles the decision variable (Continuous or Discrete data) ?

**Comment by mthmn20** [comment]
@DiegoCatalano: So far, my implementation can only handle binary classification.

**Comment by DiegoCatalano** [comment]
I got a [random forest](https://github.com/DiegoCatalano/Catalano-Framework/blob/master/Catalano.MachineLearning/src/Catalano/MachineLearning/Classification/DecisionTrees/Learning/RandomForest.java) implementation for java, I need some time to port to accord.

**Comment by mthmn20** [comment]
Cool, how about I submit a pull request on Monday and you extend it as you
see fit

**Comment by mthmn20** [comment]
@DiegoCatalano @cesarsouza @functionsoft 
Pull request submitted!

**Comment by Betwulf** [comment]
Would love to see this in accord! Thanks

**Comment by cesarsouza** [comment]
Thank you all for the inputs and suggestions! An initial random forest implementation has been added on release 3.2, though it may still benefit from some tests and optimizations.

**Comment by mmehrle** [comment]
Hello Cesar et al... Quick question: is there a good example demonstrating the new _random forest_ implementation? I'd like to throw a dataset at it but am unsure as to how to use it and I'm not sure as to how it accepts input There appears to be no pertinent documentation. Thanks in advance!!

**Comment by MoritzGoeckel** [comment]
I would appreciate an example or some kind of documentation aswell. Cant wait to try out the random forest implementation!

**Comment by mmehrle** [comment]
Hey, thanks for working on that. Looking forward to the next release.

**Comment by mmehrle** [comment]
Question: Is there a random forest example that separates between a train and test set? The current example I found in the ML test project uses the same data for training and testing.

**Comment by mmehrle** [comment]
I posted the same question in [stackoverflow](http://stackoverflow.com/questions/40157702/how-to-sync-train-and-test-codebooks-in-accord-net), so feel free to answer it there.

**Comment by mmehrle** [comment]
Anyone? Bueller?

**Comment by cesarsouza** [comment]
Documentation has been added in release 3.6.0.

**Comment by ibuse2012** [comment]
First of all, wanted to say thank you to everyone that contributed to this awesome project!  
Are there any plans to add functionality for Regression Trees (i.e. M5 Prime) or Regression Forest ?
