### ISSUE TITLE
Add an Example for Crop Class

### ISSUE THREAD

**Issue by GMstrikerz** [accord-net/framework#1722]
Please add an example for Crop Class.

i need help for crop class for When Want to crop a video from rectangle box for face recognition.
using BsourceImage and getframe.

Bitmap(getframe) ---detect to face with motion -----rectangle Box appear--- Want to be crop ---put to another Picturebox.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Imaging_Filters_Crop.htm

**Comment by blaisexen** [comment]
This is your answer,
https://github.com/accord-net/framework/issues/1717
