### ISSUE TITLE
Add an Example for FaceHaarCascade Constructor

### ISSUE THREAD

**Issue by Hmssallom** [accord-net/framework#1727]
Please add an example for FaceHaarCascade Constructor.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Vision_Detection_Cascades_FaceHaarCascade__ctor.htm

**Comment by blaisexen** [comment]
hi,
are you looking like this?
https://github.com/accord-net/framework/issues/1717
