### ISSUE TITLE
Can this library be used to find variances?

### ISSUE THREAD

**Issue by mika76** [accord-net/framework#174]
I'm sorry for posting this here but there is no forum or community link I could use.

Could you point me in the direction of using this library for finding variances in a list of numbers or movements? I found this library through researching K Nearest Neighbour but do not see how to use it (I am not a mathematician so am just figuring it out as I go along).

**Comment by cesarsouza** [comment]
Well... It is obviously too late for the original poster, but one can compute the variance of a list of numbers using the [Measures class](http://accord-framework.net/docs/html/Methods_T_Accord_Statistics_Measures.htm):
```
double[] list = { 1, 2, 3 };
double variance = Accord.Measures.Variance(list);
```
Hope it helps future users,
Cesar

**Comment by mika76** [comment]
Brilliant thanks @cesarsouza - I still might actually give it a go 😄

**Comment by cesarsouza** [comment]
Woah, I was not expecting a response at this point in time! I am really sorry for the (almost 2 years) late response. I kind of missed it in the middle of all others at the time, and I didn't have the opportunity to come back this far in the issue list for a while.

**Comment by mika76** [comment]
Not a problem. I was really looking at options to fixing some weird problems I have and trying to find variances was one way I was looking at solving it. We still have some problems though so anything that comes up I'm happy to check out when I get a chance 😄
