### ISSUE TITLE
Probably dumb question, but is this 64bit? Can't find it.

### ISSUE THREAD

**Issue by tcdoe** [accord-net/framework#175]
Hello,
I downloaded and installed latest Accord.NET but can only seem to find 32bit library. Of course, for large images (and compatibility) I absolutely need 64bit.

Am I just missing something obvious here?
Thanks.

**Comment by tcdoe** [comment]
Wow, no comments or response at all after 2 days...

I'll try and download source and build 64bit dlls myself. If successful I'll post an update here.

**Comment by steinard** [comment]
What is there to say? Just change the target of the framework to 64 bit and compile. That is what I do.

 

Cheers,

Steinar.

**Comment by tcdoe** [comment]
Thanks, Of course i tried to compile, but gave me a bunch of errors in 64bit target... I must be doing something whrong.

**Comment by steinard** [comment]
I tried the same just now, and it is not enough to just change the target platform. You are not doing anything wrong, it’s just a bunch of errors you have to remove.

 

The first one is to remove a doc error in KMeans.cs

 

/// <summary>

        ///   Divides the input data into K clusters. 

        /// </summary>

        /// 

        /// <param name="data">The data where to compute the algorithm.</param>

        /// <param name="threshold">The relative convergence threshold

        ///   for the algorithm. Default is 1e-5.</param>

        ///   This is used in weighted K-Means</param>

        /// <param name="computeInformation">Pass <c>true</c> to compute additional information

        ///   when the algorithm finishes, such as cluster variances and proportions; false

        ///   otherwise. Default is true.</param>

        ///   

        [Obsolete("Please set the 'Tolerance' and 'ComputeInformation' properties instead of using this overload.")]

        public int[] Compute(double[][] data, double threshold, bool computeInformation)

        {

            double[] dataWeights = createDefaultWeights(data);

            return Compute(data, dataWeights, threshold, computeInformation);

        }

 

The end of param outlined in yellow prevented the MachineLearning project to compile in 64 mode on my machine. 

 

When that one was fixed then the only projects not compiling are the cpp projects. Here you need to change so they compile to 64, I tried to do it, but I could not get it to work within the few minutes I have dedicated to your problem.

 

The solution for me is to not use the Accord.Net solution file, but rather the Accord.NET.LGPL. I cannot use the GPL stuff anyway, so I never use the  main solution file. In Accord.NET.LGPL it is much easier to get the solution to compile to 64 bit architecture. So you need to check if the LGPL solution contains what you need or if you really need to use the main solution.

 

1.       Remove the Accord.Tests.Match.Cpp project, which is not used in the LGPL solution, it was probably forgotten when the LGPL solution was made. It is the CPP projects which is the main hindrance.

2.       Change target platform to 64 bit, compile and wola, you are home free.

 

 

Steinar.

**Comment by tcdoe** [comment]
Thank very much for this helpful information!

**Comment by cesarsouza** [comment]
Hello,

First and foremost, sorry for the long delay in replying. In case it is still worth, the project is actually both 32-bits and 64-bits. The target is set to Any CPU, which should work on both. 

However, please note that VS has an option that might be forcing your application to run on 32-bit mode, even if have also configured your project to target AnyCPU. In this case, please make sure that [the option "prefer 32-bit" is disabled in your project preferences](http://4.bp.blogspot.com/-K1V1NmSwacA/Uh9TFmBwIcI/AAAAAAAAGSE/OdAn38qUHGQ/s1000/Prefer32Bit.png).

Hope it helps anyone else facing the same issue!

Regards,
Cesar
