### ISSUE TITLE
DecisionTreeWriter uses local CultureInfo when writing values

### ISSUE THREAD

**Issue by pantojasc** [accord-net/framework#178]
DecisionTreeWriter uses localized CultureInfo when writing C# class for DecisionTree, causing comparison values to be written with comma in some localizations, where commas are used as decimal point.

Suggested solution: CultureInfo.InvariantCulture should be used in DecisionTreeWriter.

**Comment by cesarsouza** [comment]
Fixed on release 3.3.0.
