### ISSUE TITLE
Pad Function for Jagged Arrays

### ISSUE THREAD

**Issue by mercem** [accord-net/framework#1794]
- [ ] question
  - [ ] bug report
  - [X] feature request

Hi,

It would be good if padding function can take jagged arrays as well.

Since rectangular arrays are weak in performance wise, I'm using jagged arrays and I cannot use pad function. I know there may be problem with jagged arrays since their dimension can be different.

Thank you!

**Comment by fdncred** [comment]
Will accept a PR for this.
