### ISSUE TITLE
Samples don't compile on Windows 10 x64 + Visual Studio 2015.1

### ISSUE THREAD

**Issue by sidshetye** [accord-net/framework#180]
Haven't tried other permutations of VS and OS, but if you clone the repo and try loading the sample solution(s), they don't even compile. This is on the tip of the dev branch i.e. commit 7989706b828f4aab93439e3395f405988a971177

Tried loading two different sln files
1. `framework\Samples\Samples.sln`
   Issue: NuGet references to Accord.\* are missing (they don't exist in packages.config either). Note that if you manually add those references, the build still borks on other errors...
2. `framework\Samples\Neuro\Deep Learning\Deep Learning.sln`
   Issue: All local as well as NuGet references are broken
   Build error: This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. **The missing file is `framework\Samples\Neuro\Deep Learning\\.nuget\NuGet.targets`** (this file is missing in the repo)

**Comment by sidshetye** [comment]
In case 2, you can recreate the `.nuget\NuGet.targets` file by copying it from `..\..\.nuget\`. With the above you reduce both case 1 and case 2 to a common one, so then the fix is to manually add the NuGet references back so that your packages.config file contains 

```
﻿  <package id="Accord" version="3.0.2" targetFramework="net40-client" />
  <package id="Accord.Controls" version="3.0.2" targetFramework="net40-client" />
  <package id="Accord.Imaging" version="3.0.2" targetFramework="net40-client" />
  <package id="Accord.MachineLearning" version="3.0.2" targetFramework="net40-client" />
  <package id="Accord.Math" version="3.0.2" targetFramework="net40-client" />
  <package id="Accord.Neuro" version="3.0.2" targetFramework="net40-client" />
  <package id="Accord.Statistics" version="3.0.2" targetFramework="net40-client" />
  <package id="ZedGraph" version="5.1.6" targetFramework="net40-client" />
```
Then you can run 
```
Update-Package -reinstall -ProjectName <projectName>
```
NOW, when you try to compile, you'll get this error

```
NotifyPropertyWeaver: Failed to extract target assembly path from the BuildEngine. 
Please raise a bug with the below exception text.
The temporary work-around is to change the weaving task as follows 
<WeavingTask ... TargetPath="PathToYourAssembly" />
Exception details: System.Exception: Could not extract targetBuilderCallback from Microsoft.Build.BackEnd.TaskHost
   at BuildEnginePropertyExtractor.GetProjectInstance()
   at BuildEnginePropertyExtractor.GetEnvironmentVariable(String key, Boolean throwIfNotFound)
   at TargetPathFinder.Execute()	Deep Learning			
```

**Comment by cesarsouza** [comment]
Hi there,

Thanks for the time in investigating all those issues! Indeed, the development branch of the framework is a bit unstable as it is undergoing many changes due the recent merge with AForge.NET. The master branch, however, remains stable and compilable.

There were also some issues when updating to VS2015, which have not yet been totally solved. They will probably be solved after the next release is finished. Thanks for letting me know about that missing file! 

Regards,
Cesar

**Comment by CBrauer** [comment]
Hi Cesar,

Is there a workaround for this issue (until you get the VS 2015 issues resolved)?

Charles

**Comment by cesarsouza** [comment]
All sample applications now compile using VS2017.
