### ISSUE TITLE
Missing Namespaces for Sample projects

### ISSUE THREAD

**Issue by jakelly** [accord-net/framework#181]
Not sure what I'm missing here.  I pulled down the source code from GitHub, opened the Samples Solution File in VS2013 and updated the references to Accord namespaces and I'm still receiving errors missing namespaces.  Any ideas what I'm overlooking? 

Your documentation for building these samples may need some attention as there is no reference to the Samples from within the core solution file Accord.Net.sln.

![image](https://cloud.githubusercontent.com/assets/2788655/12057485/94bccb92-af0f-11e5-85ae-a0483634c8a7.png)

![image](https://cloud.githubusercontent.com/assets/2788655/12057493/aadd138c-af0f-11e5-9b73-cdaabe1203f2.png)

**Comment by sjihttam** [comment]
Had the same problem and seems it is a project configuration issue.

I rebuild the Accord.Net solution with configuration NET45 and switched the 'Classification (SVM) project also to 4.5 framework this solved it for me.

Also check: http://stackoverflow.com/questions/4764978/the-type-or-namespace-name-could-not-be-found

**Comment by cesarsouza** [comment]
Some samples projects might be linked against .NET4.0 instead of 4.5. They will be gradually replaced with NuGet references as soon as release 3.1 gets out. The project is a bit unstable right now (specially the development branch) due to the merge with AForge, so I apologize for the inconvenience.

**Comment by cesarsouza** [comment]
All sample applications have been updated to use packages from NuGet instead. Should be fixed on the next release.

**Comment by cesarsouza** [comment]
Fixed on release 3.3.0.
