### ISSUE TITLE
Recherche et ajout des fichiers sur SharePoint avec l'API Microsoft Graph

### ISSUE THREAD

**Issue by didabel** [accord-net/framework#1815]

**Comment by didabel** [comment]
Bonjour à tous, 

J'utilise l'api microsoft graph pour ajouter, dans un premier temps, un fichier à SharePoint, mais je ne trouve pas un exemple à suivre en C# y'a il des personnes qui ont déjà utilisé cette api ?

Merci d'avance.

**Comment by justingruenberg** [comment]
Cette question ne semble pas être liée au Accord Framework.

**Comment by didabel** [comment]
Non pas du tout c'était une erreur de ma part.  Désolée .
