### ISSUE TITLE
Could you give me a graylevel coocurrences matrices sample?

### ISSUE THREAD

**Issue by vnorukawa** [accord-net/framework#184]
I'm quite newbie using this library. Could you give me a sample to use graylevel coocurrences matrices? Thanks.

**Comment by cesarsouza** [comment]
Examples have been added to the [Gray-level Co-occurrence matrix class documentation page](http://accord-framework.net/docs/html/T_Accord_Imaging_GrayLevelCooccurrenceMatrix.htm) in release 3.8.0.
