### ISSUE TITLE
ProbabilisticOutputCalibration Class Example Incorrect Object Name

### ISSUE THREAD

**Issue by jakemdrew** [accord-net/framework#188]
Example code appears to be incorrect here:

http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_ProbabilisticOutputCalibration.htm

The object in the following line should be ProbabilisticOutputCalibration?

// Instantiate the probabilistic learning calibration
ProbabilisticOutputLearning calibration = new ProbabilisticOutputLearning(svm, inputs, labels);

**Comment by cesarsouza** [comment]
That's correct. Thanks!

**Comment by jakemdrew** [comment]
Then perhaps the namespace is incorrect in the documentation?

Accord.MachineLearning.VectorMachines.Learning

When I try to use the example code, it says the object code does not exist or I am missing a reference?

I have the following with no errors in my using statements:

using Accord.MachineLearning.VectorMachines;
using Accord.MachineLearning.VectorMachines.Learning;
using Accord.Statistics.Kernels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

**Comment by jakemdrew** [comment]
![image](https://cloud.githubusercontent.com/assets/2107763/12526645/2e27325e-c135-11e5-9266-a1e5fa58c261.png)


![image](https://cloud.githubusercontent.com/assets/2107763/12526654/46675092-c135-11e5-91c9-6221e10b630b.png)
