### ISSUE TITLE
SparseReader creates dense arrays

### ISSUE THREAD

**Issue by Telavian** [accord-net/framework#190]
I am trying to build a document classifier with 3 millions instances and about 10000 features. This is too large to fit in memory by itself. In order to work with this I changed it to be in the LibSvm format and modified the Naive Bayes algorithm. This works okay however I want to try building SVM models.

I see that there is a working path for LibSVM formatted input data described here. https://github.com/accord-net/framework/wiki/Sample-applications#liblinear-linear-svms

However what is the point really if the SparseReader class just creates dense arrays? Are not the point of the LibSVM arrays to be more compact? Does any SVM algorithm support LibSVM formatted data and not require it all in memory at once?

**Comment by Telavian** [comment]
After some research I found that I could use a SparseLinear kernel for this purpose.

https://github.com/accord-net/framework/blob/aebb29a5be68c927f4f15a09af84585a1305d105/Sources/Accord.Statistics/Kernels/Sparse/SparseLinear.cs

**Comment by cesarsouza** [comment]
Hi there,

Sorry for the delay in answering. As you could see, it is possible to use Sparse kernels with the SMO algorithm for training kernel machines. However, unfortunately it is still not possible to use specialized linear methods with the sparse linear kernels. This might be added in a future release.

Please let me know if you managed to apply the existing methods to your problem. If not, I will enqueue the implementation of a more appropriate method in the issue tracker.

Thanks!

Regards,
Cesar

**Comment by Telavian** [comment]
I am not sure what you mean. Is it currently possible to build a linear svm
using the SparseKernel without all data in memory at some time?

I will try and get this working however I just wanted to check.
