### ISSUE TITLE
Different accuracy by specifying KernelSupportVectorMachine input length

### ISSUE THREAD

**Issue by Telavian** [accord-net/framework#191]
I noticed that the following SVMs produce different accuracy values based on whether the input length is set. This is for the same inputs and outputs in both cases.

            var machine1 = new KernelSupportVectorMachine(new Linear(), inputs[0].Length);
            var teacher1 = new LinearDualCoordinateDescent(machine1, inputs, outputs);
            var error1 = teacher1.Run(true);

            var machine2 = new KernelSupportVectorMachine(new Linear(), 0);            
            var teacher2 = new LinearDualCoordinateDescent(machine2, inputs, outputs);            
            var error2 = teacher2.Run(true);

**Comment by cesarsouza** [comment]
Hi Telavian,

An input length of zero is an indication that the machine should expect input vectors of varying length. However, this only makes sense for Kernel machines, as the support for varying length inputs is actually provided by certain kernel functions (i.e. DynamicTimeWarp). 

The problem in this case is that the LinearDualCoordinateDescent is not checking this inconsistency. I can fix this issue by adding some checks and throwing an exception in case a linear algorithm receives a variable-length SVM as an input.

Hope it helps!

Regards,
Cesar
