### ISSUE TITLE
Recurrent Neuron Network (Request)

### ISSUE THREAD

**Issue by sudoantang** [accord-net/framework#198]
Hello César,

As far as I am concerned, your great framework does not include any classes for this type of deep learning network (i.e. Elman RNN, Jordan RNN (these are basics), Long Short Term Memory RNN (said to be more developed) ...). Furthermore, a lot of researchers in computer vision and pattern recognition have studied this for a quite.

In the past, the author of AForge as I see on the cache of google code, he promised to write about this but he forget it. Hope you have time to keep an eye on this soon to get this more easy to apply in practice.

Regards,

**Comment by cesarsouza** [comment]
Related to #612

**Comment by cesarsouza** [comment]
Further development of the Accord.Neuro classes will happen in https://github.com/cesarsouza/keras-sharp.
