### ISSUE TITLE
infinite loading for dataset in deep learning sample

### ISSUE THREAD

**Issue by alifakhari** [accord-net/framework#204]
Hi
I have a problem with the prepared sample for deep learning.
I downloaded the sample application and when i run "DeepLearning.exe" file, the attached screen goes forever!
Should i do something? for example introducing the dataset e.g. optdigits-tra.txt file to application in some way?
![untitled](https://cloud.githubusercontent.com/assets/16303979/13405764/4b4548da-df35-11e5-9b30-eb096de75dc9.jpg)
Thanks

**Comment by JustasB** [comment]
Same here

**Comment by cesarsouza** [comment]
Hi there,

This might happen in case the application runs from a compressed folder. For those who might find this issue in the future, please uncompress the sample application .zip or .rar into a separate folder before attempting to run it. 

Regards,
Cesar
