### ISSUE TITLE
How can i compose The inverse of the covariance matrix of given 2 vectors

### ISSUE THREAD

**Issue by MonsterMMORPG** [accord-net/framework#205]
For example i have these below double vectors and i have to calculate their The inverse of the covariance matrix

Here my example vectors

[0.3, 2, 0, 4]

[1.2, 0, 6, 1.1]

How can i calculate The inverse of the covariance matrix of these 2 given vectors?

the result should be double [,]

ty

I want to calculate Mahalanobis distance of these 2 given vectors for clustering task ty

**Comment by cesarsouza** [comment]
Hi there,

I am afraid it is not really interesting (or even possible) to compute a covariance matrix given only two samples. You might need to provide an estimate of the covariance matrix of the entire population from where those two vectors come from. Then, once you have it, you can use the Mahalanobis distance method from the framework to compute it.

**Comment by cesarsouza** [comment]
Hi there, 

Have you found a solution to the problem you were trying to solve?

Regards,
Cesar
