### ISSUE TITLE
Seems like Chessboard distance is incorrect

### ISSUE THREAD

**Issue by MonsterMMORPG** [accord-net/framework#206]
According to the wikipedia

Chebyshev and Chessboard distance are the same thing

But when i test both, i get different results

How come?

https://en.wikipedia.org/wiki/Chebyshev_distance

http://accord-framework.net/docs/html/M_Accord_Math_Distance_Chessboard.htm

http://accord-framework.net/docs/html/M_Accord_Math_Distance_Chebyshev.htm

**Comment by cesarsouza** [comment]
@DiegoCatalano do you know why those two implementations are different in the framework? I think one of them came from one of your contributions, and the other already existed in the framework. If its the case, we have to remove one of them!

**Comment by DiegoCatalano** [comment]
Yes, I had implemented wrong. @MonsterMMORPG has reason, Chebyshev and Chessboard are the same. In this [line] in the cheeboard(https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Distances/Chessboard.cs#L102) I forget to calculate the absolute number, while the [chebyshev](https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Distances/Chebyshev.cs#L66) is correct. However, just delete the chessboard.

**Comment by cesarsouza** [comment]
Fixed in release 3.2.
