### ISSUE TITLE
ResizeBilinear filter can be supported by more pixel format

### ISSUE THREAD

**Issue by hzawary** [accord-net/framework#207]
Hi authors,

I found some shallow bugs in ResizeBicubic and ResizeBilinear AForge.NET 2.5.5 filters (maybe exist on the other filters too), where ResizeNearestNeighbor filter can be support almost pixel formats such as:
PixelFormat.Format8bppIndexed;
PixelFormat.Format24bppRgb;
PixelFormat.Format32bppRgb;
PixelFormat.Format32bppArgb;
PixelFormat.Format16bppGrayScale;
PixelFormat.Format48bppRgb;
PixelFormat.Format64bppArgb;
but I think that miss some supported pixel formats like PixelFormat.Format16bppGrayScale to ResizeBilinear filter, cause do test resizing an 16bpp image by pass and succes it.

Best regards,
HZ:)

**Comment by cesarsouza** [comment]
Hi Zawary,

First and foremost, sorry for the delay in answering all those issues. Yes, you are right: I have also seen other cases of AForge.NET filters saying they don't support a particular pixel format when actually they do. I will eventually look into them, thanks for reporting!

**Comment by cesarsouza** [comment]
Fixed in release 3.6.0.
