### ISSUE TITLE
Gap on calculating Length member of IntRange Structure in AForge core

### ISSUE THREAD

**Issue by hzawary** [accord-net/framework#208]
Hi friends,

In AForge core to calculating length in IntRange is deffirence between maximum and minimum values, but if we have range [-3 .. 3] for example, length will be 7 instead 6. In other word, deffirence betwwen max limit and min limit plus 1!

Best regards,
HZ:)

**Comment by cesarsouza** [comment]
Hi Zawary!

It depends on whether the IntRange should have its upper limit interpreted as inclusive or exclusive. In the current implementation, the upper limit of IntRange is treated as an exclusive value, as in the DoubleRange case. 

Regards,
Cesar
