### ISSUE TITLE
Any samples on how to use Boosted Decision Trees?

### ISSUE THREAD

**Issue by functionsoft** [accord-net/framework#211]
Hi,

Any samples out there using the boosted decision trees?

Many thanks,

Mike

**Comment by cesarsouza** [comment]
An example for [Boosted Decision Trees using AdaBoost<DecisionTree> has been added to the AdaBoost documentation page](http://accord-framework.net/docs/html/T_Accord_MachineLearning_Boosting_AdaBoost_1.htm) in release 3.8.0.
