### ISSUE TITLE
MJPEG Stream with Password and Username

### ISSUE THREAD

**Issue by pthoelken** [accord-net/framework#2113]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

Is there a way to open a HTTP MJPEG Stream with username and password? Like tihs? 

```
Dim objStream = New MJPEGStream("http://192.16.16.30/control/faststream.jpg?stream=full")
VideoSourcePlayer4.VideoSource = objStream
VideoSourcePlayer4.Password="Password1"
VideoSourcePlayer4.Username="User2"
VideoSourcePlayer4.Start()
```

**Comment by justingruenberg** [comment]
I haven't tested this, but these are options in the MJPEGStream object.  You'd want to do something like:

```vb
Dim objStream = New MJPEGStream("http://192.16.16.30/control/faststream.jpg?stream=full")
objStream.Password="Password1"
objStream.Login="User2"
VideoSourcePlayer4.VideoSource = objStream
VideoSourcePlayer4.Start()
```

**Comment by pthoelken** [comment]
Merci! :-) This works perfectly.
