### ISSUE TITLE
Bug found in ReplaceChannel filter

### ISSUE THREAD

**Issue by hzawary** [accord-net/framework#214]
Hi there,

Exists a bug in when used an UnmanagedImage as input channel in AForge.Imaging.Filters.ReplaceChannel filter.

Incorrect in line 277: int offsetCh = chData.Stride - rect.Width;
Correct it: int offset Ch = ch Stride - rect.Width;

Sincerely,
HZ

**Comment by cesarsouza** [comment]
Thanks! I've just committed a fix.

**Comment by hzawary** [comment]
Oh! Doctor I'm glad you came back from a long times finally:) I waiting for your viewpoints on my issues:

https://github.com/accord-net/framework/issues/207
https://github.com/accord-net/framework/issues/208
https://github.com/accord-net/framework/issues/207

Thanks to response on this.

**Comment by cesarsouza** [comment]
Fixed in release 3.2.
