### ISSUE TITLE
SequentialMinimalOptimizationRegression<> not founded 

### ISSUE THREAD

**Issue by mikesneider** [accord-net/framework#2151]
I am trying to use `SequentialMinimalOptimizationRegression<Polynomial>() `as the example in [here ]( http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_SequentialMinimalOptimizationRegression.htm)
nevertheless, _SequentialMinimalOptimizationRegression_ is not founded in _MachineLearning.VectorMachines.Learning_ library.

Accord.NET version 3.8
![image](https://user-images.githubusercontent.com/12171113/87251394-fcfaf180-c430-11ea-905a-d2a84a352a68.png)

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_SequentialMinimalOptimizationRegression.htm

**Comment by cesarsouza** [comment]
Hi there,

If I recall correctly, I believe the SMOr algorithm is in the .GPL part of the library. You might need to add a package reference to https://www.nuget.org/packages/Accord.MachineLearning.GPL/ as well.
