### ISSUE TITLE
DeepLearning GaussianFunction

### ISSUE THREAD

**Issue by Mazecreator** [accord-net/framework#223]
The " GaussianFunction : IStochasticFunction" appears to be a linear function not a gaussian.  This is for the DeepLearning ActivationFunction.  the "Function()" is as follows:
`
        public double Function(double x)
        {
            double y = alpha \* x;

```
        if (y > range.Max)
            return range.Max;
        else if (y < range.Min)
            return range.Min;
        return y;
    }`
```

I would have expected something like this:
`
        public double Function(double x)
        {
            double y =  Math.Exp(-alpha\* x*X);

```
        if (y > range.Max)
            return range.Max;
        else if (y < range.Min)
            return range.Min;
        return y;
    }`
```

The derivative is incorrect as well.  i used the following reference for the GaussianActivation function:
https://en.wikipedia.org/wiki/Activation_function

**Comment by Mazecreator** [comment]
I have made my best guess at creating the Gaussian, but I am missing something as the Deep Belief network doesn't seem to converge with this function.  Hopefully it gets you close to a solution.  I might not fully understand the activation function.


[GaussianFunction2.TXT](https://github.com/accord-net/framework/files/215349/GaussianFunction2.TXT)

**Comment by cesarsouza** [comment]
Hi there,

Thank you very much for identifying the problem and attempting to provide a solution. However, if I remember correctly, the Gaussian activation function used in the Contrastive Divergence algorithm has a slightly different definition than what a true Gaussian activation function would mean. In its context, this activation function was meant to be similar to a linear function with added Gaussian noise.

Gaussian units are shown in page 13 of https://www.cs.toronto.edu/~hinton/absps/guideTR.pdf .

I agree that the name current location of this functionality (implemented as an ActivationFunction) was unfortunately not ideal.

**Comment by zgrkpnr** [comment]
@Mazecreator following expression holds always true.
```
            return -2*Math.Sqrt(-Math.Log(y))*y;
```
I see what you mean. The last equation is ln(y) = -x^2; What you don't consider is that value `y` is always 0<y<1 and that mean ln(y) is always negative. Thus negating ln(y) will always be positive.
