### ISSUE TITLE
Independent Component Analysis not converging

### ISSUE THREAD

**Issue by armwal** [accord-net/framework#225]
I did a comparison of the FastICA implementations in Accord.NET (V 3.0.2), Hyvärinen's Matlab toolbox (http://research.ics.aalto.fi/ica/fastica/code/dlcode.shtml) and the Python implementation in scikit-learn (https://github.com/scikit-learn/scikit-learn) on some real-world data ([data.zip](https://github.com/accord-net/framework/files/230175/data.zip), 24 channels, 20001 samples).

I used the parallel/symmetric approach (not deflation) and the kurtosis as contrast function. I found that the Matlab and Python implementations converged within less than 100 steps for this data, while the Accord.NET implementation did not converge within 1000 steps.

I looked a bit more into this and the main culprit seems to be the convergence check (getMaximumAbsoluteChange function in IndependentComponentAnalysis.cs) which differs from the Matlab and Python implementations. In Accord.NET it takes the entry in the demixing matrix W with the maximum absolute difference to the demixing matrix W0 of the last step, calls this difference `delta` and does this comparison: `delta < tolerance * lastChange` where `tolerance` is 0.001 by default and `lastChange` is the `delta` found in the last step. Does this work as intended? In essence, the maximum absolute difference would need to change by a factor of 1000 from one step to the next which does not really make sense to me...

The Matlab and Python implementations instead do this comparison (here in Matlab-ish pseudo-code): 
`1 - min(abs(diag(W * W0'))) < tolerance` 
If I modify the IndependentComponentAnalysis to check for convergence in the same way, it converges fine on my test data. 

It would be nice to get a fix for this convergence check, or maybe just better default parameters? The Accord.NET framework looks great otherwise, but this convergence issue prohibits me from using it.

**Comment by cesarsouza** [comment]
Hi there,

First of all, thank you very much for reporting the issue, which will be fixed as soon as possible. Please, if you have some time (and I would completely understand if you don't), would you mind providing a unit test (or simply a snippet of code) that would reproduce the issue given the dataset you provided? 

I couldn't determine which format your dataset is stored in.

Best regards,
Cesar

**Comment by armwal** [comment]
Hi Cesar,

thanks for the quick response! Here is a bit of code which loads the data (expecting the data.dat file in the same folder) and runs the ICA on it: 
[ICATest.zip](https://github.com/accord-net/framework/files/234440/ICATest.zip)

On my PC it takes around 1 minute to run the ICA. Using the modified convergence check I mentioned above, it takes about 2.5 seconds.

For unit testing I suppose it would be best to add something like a "HasConverged" flag to the IndependentComponentAnalysis class. This might be nice to have in general.

Kind regards
Armin

**Comment by cesarsouza** [comment]
Fixed on release 3.2.
