### ISSUE TITLE
Fresh release on nuget

### ISSUE THREAD

**Issue by zabulus** [accord-net/framework#227]
Do you plan to publish new version of the library to nuget? Last release dated in Aug 2015.

**Comment by cesarsouza** [comment]
Definitely yes; many parts of the framework have been under active work in the past months. Now that the framework has merged with AForge.NET, lots of work have been dedicated to the unification of the AForge.NET APIs with existing code in the framework, as well as performance improvements.

However, it is quite tricky to provide those new APIs and data formats without breaking existing code and making sure that models stored using previous versions of the framework still load correctly in the new release. This is one of the reasons on why making a new public release has taken this long.

**Comment by cesarsouza** [comment]
I have uploaded preview packages for release 3.1 on NuGet. However, there might be some breaking changes with existing projects. If you experience issues, please let me know!

**Comment by cesarsouza** [comment]
Accord.NET 3.2. has finally been released.
