### ISSUE TITLE
GeneralDiscreteDistribution 

### ISSUE THREAD

**Issue by MarcinZiabek** [accord-net/framework#228]
I found a bug described earlier but not corrected. Here is the explanetion based on somebody else's post:

Hi,
I'm trying to sample multiple observations from a GeneralDiscreteDistribution as following, but always get 0 as the elements of output array:
              
            ...
            double[] transProbRow = emoStateTransMatrix.GetRow(currentEmoState);
            GeneralDiscreteDistribution gdd = new GeneralDiscreteDistribution(transProbRow);
            int[] emoParticles = gdd.Generate(100); // This gives me an all zero vector
            ...

But if I sample in the following way everything works fine

            ...
            double[] transProbRow = emoStateTransMatrix.GetRow(currentEmoState);
            GeneralDiscreteDistribution gdd = new GeneralDiscreteDistribution(transProbRow);
            int[] emoParticles = new int[100];  
            for(int i=0; i<100; i++)
               emoParticles[i] = gdd.Generate();
            ...

Am I using the Generate function wrong in the first case or is this a some kind of bug?

**Comment by cesarsouza** [comment]
Hi there,

Sorry for the delay in answering your message. This has been fixed on development branch but has still not been released.

**Comment by cesarsouza** [comment]
Hi there,

Sorry; actually I thought this had been fixed as part of a large update on the Generate methods for probability distributions, but the GeneralDiscreteDistribution still seems to have this issue. Thanks for reporting! It will be fixed in the next release.

**Comment by cesarsouza** [comment]
Fixed on release 3.2.
