### ISSUE TITLE
Can't build cloned repository

### ISSUE THREAD

**Issue by robinchesterman** [accord-net/framework#229]
It doesn't seem to be possible to clone the framework repository and have anything build.

I can't get the samples or most of the sources to build either. Do things need to be built in order?

The references to Accord in the samples projects all have warnings next to them, but no nuget packages or anything.

**Comment by robinchesterman** [comment]
The samples don't build when I use the installer either.

**Comment by cesarsouza** [comment]
The issue eventually got fixed and the current development and master branches are currently building on VS2013, but not yet on VS2015.

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
