### ISSUE TITLE
Accord Framework code not working

### ISSUE THREAD

**Issue by mhammadpk** [accord-net/framework#233]
Hi all,

I am trying to run the source code of Classification (SVMs), but it is not building correctly. Here are the following steps which I have used to run the source code:

1. Download the whole source code by using https://github.com/accord-net/framework
2. Open "Samples.sln" solution file in Visual Studio 2013, on Windows 8 having 64 bit environment.
3. Install accord.machine, accord.Controls, and accord.IO, accord.Imaging by using NutGet.
4. Now all missing references is resolved.
5. But once I tried to build the code of Classification (SVMs), it is giving me errors as under:

Error	5	'Accord.Math.Vector' is inaccessible due to its protection level
	....\MainForm.cs	178	17	Classification (SVMs)

Error	7	'System.Array' does not contain a definition for 'GetRange' and no extension method 'GetRange' accepting a first argument of type 'System.Array' could be found (are you missing a using directive or an assembly reference?)	....\MainForm.cs	174	42	Classification (SVMs)

..........

..........
![error](https://cloud.githubusercontent.com/assets/734469/15474747/edec5c52-210e-11e6-9828-32f6d40b49e6.png)

**Same issue comes with other projects like "Clustering (K-Means, MeanShift)".** 

Please reply me how can I build all the projects successfully.

**Comment by zgrkpnr** [comment]
I have the same problem with Deep Belief Learning example. Cartesian is not accessible as well as Vector.

**Comment by mhammadpk** [comment]
Please let me the solution as soon as possible.

**Comment by cesarsouza** [comment]
Hi there,

I just committed a fix for the sample applications. Some of them were indeed not building. However, in order to build the samples correctly, you first have to compile the framework using the "NET40" configuration on Visual Studio (you can select at the top, on the left of "Any CPU", on the right of the green arrow for compiling).

Please let me know if this solves the issue. I am also preparing a new release in a few days.

**Comment by ThorPets** [comment]
I have the same issues when trying to compile and I am using .NET framwork 4,
The problems arise in the createSurfaace method - accord.Math.MAtrix does not contain a definition for Cartesian........
It all compiles and runs, if i comment out the body of this method.  Does the new relese solve this issue?
Thor P

**Comment by cesarsouza** [comment]
Fixed on release 3.3.0.
