### ISSUE TITLE
Accord.Math.Distance.Correlation is no where to be found

### ISSUE THREAD

**Issue by MonsterMMORPG** [accord-net/framework#239]
I can not locate this function

Can you point me?

**Comment by cesarsouza** [comment]
@DiegoCatalano I think the Correlation distance came from the set of distances you implemented a while ago. Do you have a reference for it? I think I removed it because it was similar to another distance that already existed.

**Comment by MonsterMMORPG** [comment]
Well i have experimented and Correlation  produces exactly same as pearson
Correlation  distance

**Comment by DiegoCatalano** [comment]
@cesarsouza Here is the [reference](https://reference.wolfram.com/language/ref/CorrelationDistance.html).
