### ISSUE TITLE
Organize unit tests dependencies

### ISSUE THREAD

**Issue by cesarsouza** [accord-net/framework#24]
In the main project, certain projects don't reference each other for obvious reasons. For example, Accord.Math cannot reference Accord.MachineLearning, but actually it is Accord.MachineLearning that should reference Accord.Math. 

However, the same cannot be said for the unit tests. In the current version, the unit tests have references among themselves, which might be a bit confusing, specially if you are trying to disentangle them from the main project. 

As such, uncommon dependencies must be removed, and the resulting broken tests and references should be fixed.

**Comment by cesarsouza** [comment]
This shouldn't be an issue anymore.

**Comment by cesarsouza** [comment]
Reopening this issue to track the following changes:

- Each unit test project should depend only on the assembly being tested and its dependencies
- Unit tests that are testing GPL code must be moved to separate unit tests projects.
- There should be a separate project containing any GPL'd assemblies.

**Comment by cesarsouza** [comment]
- Now each unit test project should depend only on the assembly being tested and its dependencies.
- Unit tests for MachineLearning.GPL have been moved to a separate unit test project (Accord.Tests.MachineLearning.GPL), and unit tests for Math.Noncommercial have been moved to Accord.Tests.Math.Noncommercial
- A separate solution file (named Accord.NET (LGPL-only) has been created to hold only strictly LGPL projects).

**Comment by AlexJCross** [comment]
Is branch GH-24 active? Propose delete?

**Comment by cesarsouza** [comment]
No, it is not active, it can be deleted!
