### ISSUE TITLE
Re() and Im() function of ComplexMatrix generates a OutOfRangeException.

### ISSUE THREAD

**Issue by conaonda** [accord-net/framework#240]
The exception is occured from next block.

public static double[,] ToArray(this Complex[] c)
{
...
            for (int i = 0; i < rows; i++)
                for (int j = 0; i < cols; j++)
                    re[i, j] = c[i, j].Real;
...
}

Second loop is using invalid condition. It must use "j", not "i".

**Comment by cesarsouza** [comment]
Thanks! It will be available on the next release.
