### ISSUE TITLE
(AForge) Backpropagation Algorithm assumes every layer uses the same Activation function.

### ISSUE THREAD

**Issue by zgrkpnr** [accord-net/framework#241]
``````
/```
/ assume, that all neurons of the network have the same activation function
            IActivationFunction function = (network.Layers[0].Neurons[0] as ActivationNeuron).ActivationFunction;
``````

Line 227 in BackPropagationLearning.cs where the code above is present, the algorithm assumes all the layers use the same activation function which is not always the case. 

```
```

**Comment by cesarsouza** [comment]
Thanks for reporting the issue. Yes, this is a known problem that dates back from the AForge.NET code. Ideally, I would like to re-write the Neuro module using DiffSharp (http://diffsharp.github.io/DiffSharp/). It would be way more useful and solve many problems with the current implementation.

**Comment by zgrkpnr** [comment]
Glad to hear that you have plans for the Neuro module. Looking forward to it.

**Comment by cesarsouza** [comment]
The Accord.Neuro namespace will be replaced by https://github.com/cesarsouza/keras-sharp. This issue might not be relevant once this happens, so I am closing it for now.
