### ISSUE TITLE
Incorrect method usage in Distance.GetDistance?

### ISSUE THREAD

**Issue by anders9ustafsson** [accord-net/framework#245]
Looking at the variable names and the general workflow of the `Distance.GetDistance<T>` method in the *Accord.Math* library, I suspect that [this](https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Distance.cs#L141) line:

    var methods = typeof(Distance).GetMembers(BindingFlags.Public | BindingFlags.Static);

should be replaced with this line?

    var methods = typeof(Distance).GetMethods(BindingFlags.Public | BindingFlags.Static);

**Comment by cesarsouza** [comment]
Thanks! Both methods work, but of course GetMethods suits the needed functionality better!
