### ISSUE TITLE
Hidden Markov Model porbailities and transitions

### ISSUE THREAD

**Issue by fafazai** [accord-net/framework#254]
I have a question can I get  the porbailities and transitions matrix without log of fitted model directly?

**Comment by cesarsouza** [comment]
Hello,

If you need to convert HMMs log matrices into normal probabilities, you can call the .Exp() extension method on them. For example:

```
// Create a HMM with 2 states and 4 symbols
var hmm = new HiddenMarkovModel(2, 4);

// Obtain HMM parameter matrices
double[][] A = hmm.LogTransitions.Exp();
double[][] B = hmm.LogEmissions.Exp();
double[] pi = hmm.LogInitial.Exp();
```

Regards,
Cesar
