### ISSUE TITLE
Handwriting sample crashed

### ISSUE THREAD

**Issue by 80LevelElf** [accord-net/framework#256]
If you try to open file in Handwrinig sample I get an error:

> An unhandled exception of type 'System.IndexOutOfRangeException' occurred in Handwriting (SVMs).exe
> Additional information: Index was outside the bounds of the array.

Also I've try to run it from compile sources and got the same error here:
`if (lines[i][j] == '0')` in the `public static Bitmap Extract(string text)` function.

**Comment by 80LevelElf** [comment]
It's because of you assume that resource text file lines are splitted by the '\r\n', but they splitted by the '\n'
So you need to change buffer size and spliiter.

But maybe I'm alone here with such problem and it depends on something?

**Comment by rpmSportsAnalytics** [comment]
I have experienced the same error with v3.3.0

**Comment by cesarsouza** [comment]
Hi there,

Thanks a lot for reporting the current status of this issue.

Right now, the latest version on the development branch assumes the text files are in UNIX format, and the files are also indeed in this format. What could be [happening is that git could be converting the line endings for you automatically](https://help.github.com/articles/dealing-with-line-endings/). However, I have specifically set up the repository .gitattributes to avoid this kind of situation, so I am not sure what could be causing it at this stage.

Please, may I ask from where you are downloading the sample application? Is it from git, from the downloadable installer, from the website, or is it from some other source?

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
