### ISSUE TITLE
Why output - desiredOutput on Rprop?

### ISSUE THREAD

**Issue by sukasenyumm** [accord-net/framework#258]
Hello,
Im new on Neural Nets, but i need an explanation about, 
Why `double e = output - desiredOutput[i];` on ParallelResilientBackPropagationLearning.cs isn't like `e = desiredOutput[i] - output;` on AForge.Neuro/Learning/BackPropagationLearning.cs ? 

i try to change the `double e = output - desiredOutput[i];` to  `double e = desiredOutput[i]-output;` on ParallelResilientBackPropagationLearning.cs but i have the squared error increased.

**Comment by zgrkpnr** [comment]
If you look at `UpdateNetwork` one does `weight -= (weight update)` other does `weight += weightUpdate`. Thus, they are basically doing the same thing. 

Conventionally `(y - targetValue)` is used for error and `(weight -= weightUpdate)` for weight updates.

**Comment by cesarsouza** [comment]
Exactly, thanks @zgrkpnr for the explanation!
