### ISSUE TITLE
ProbablisticOutputCalibration name error in documentation example code

### ISSUE THREAD

**Issue by trankmichael** [accord-net/framework#265]
Same issue as #188.  The change from ProbablisticOutputLearning to ProbablisticOutputCalibration was included in release v2.13, but was not updated on the project webpage. 

https://github.com/accord-net/framework/releases/tag/v2.13.1

**Comment by cesarsouza** [comment]
Thanks! I have rebuilt the documentation and now the class names should have been corrected.
