### ISSUE TITLE
Documentation for Linear kernel is contradictory.

### ISSUE THREAD

**Issue by kdbanman** [accord-net/framework#268]
Looking at the published docs page for the [Linear IKernel](http://accord-framework.net/docs/html/T_Accord_Statistics_Kernels_Linear.htm), I noticed different values are reported for the default intercept.

The [Linear.Constant](http://accord-framework.net/docs/html/P_Accord_Statistics_Kernels_Linear_Constant.htm) property says

> Gets or sets the kernel's intercept term. **Default is 0.**

But the [Linear(Double)](http://accord-framework.net/docs/html/M_Accord_Statistics_Kernels_Linear__ctor_1.htm) constructor says

> Parameters
> *constant*
>     Type: System.Double
>     A constant intercept term. **Default is 1.**

This [appears to be fixed](https://github.com/accord-net/framework/blob/57ef2debd3d31702eeab3818e0a8957456345331/Sources/Accord.Statistics/Kernels/Linear.cs#L44) in the most recent commit, though I'm not sure when the correction was actually made.  When will that change make it to the public docs?

**Comment by cesarsouza** [comment]
Thanks for reporting the issue! The online documentation has already been updated to reflect the latest release.
