### ISSUE TITLE
VideoFileWriter not working

### ISSUE THREAD

**Issue by cyberwoki** [accord-net/framework#273]
Hello,

I would like to use this VideoFileWirter.
A.t.m. it is not working in my VS2015 C# Project.
An exeption is thrown immediatelly :
"_An unhandled exception of type 'System.BadImageFormatException' occurred in mscorlib.dll_"

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AForge.Video.FFMPEG;

namespace AccordVideoTest1
{
    class Program
    {
        static void Main(string[] args)
        {
            VideoFileWriter vfw = new VideoFileWriter();
        }
    }
}
`
please give me a hint!

Regards,
Wolfgang

[AccordVideoTest1.zip](https://github.com/accord-net/framework/files/387779/AccordVideoTest1.zip)
![exception](https://cloud.githubusercontent.com/assets/20696703/17203031/4647a30e-549d-11e6-9726-153fc2b75ef6.JPG)

**Comment by cyberwoki** [comment]
I changed to framework 3.5 and x86 ... but still not working

**Comment by kdbanman** [comment]
I get the same behavior.  It does it for accord versions 3.0.2 and 3.1.0 alpha, both downloaded from NuGet.

**Comment by cyberwoki** [comment]
first success with screen capture !
but with Video Converter for .NET

**Comment by cesarsouza** [comment]
Fixed on release 3.3.0.

**Comment by SaddamBInSyed** [comment]
copy the  dlls from C:\afoge..\externals\bin\ *dlls - to your app exe / ffmpeg dll path . then add the useruntimelegacy = true in your app.cfg file. now it should work fine.
