### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by mechenghn** [accord-net/framework#279]
Does Accord. Net support GPU computation for training DBN models?

**Comment by vsuhax** [comment]
I wonder the same
Nobody answers?

**Comment by cesarsouza** [comment]
Hello there,

At this current time, the framework does not support computations on the GPU. Planned GPU support is being discussed in #92

**Comment by cesarsouza** [comment]
GPU support will be implemented through [Keras Sharp](https://github.com/cesarsouza/keras-sharp)
