### ISSUE TITLE
possible bug in GammaDistribution

### ISSUE THREAD

**Issue by ahsimb** [accord-net/framework#281]
Generate method doesn't work (returns junk) if the shape (k) < 1

**Comment by cesarsouza** [comment]
Hi there,

Thanks for reporting the issue! However, I cannot replicate it in the latest release (3.2, released yesterday). Can you please confirm if you are still experiencing the issue, and if you are, do you think you could provide a little example so I could reproduce it?

Thanks!

Regards,
Cesar

**Comment by ahsimb** [comment]
Hi Cesar,

 

Sorry, I was off on business and missed your email. 

 

I’ve got version 3.0.2.

 

Here is a code example

 

            foreach (var k in new double[] { 1.1, 0.9 })

            {

                GammaDistribution gd = new GammaDistribution(1.5, k);

                Console.WriteLine("k = {0}", k);

                foreach (var val in gd.Generate(5))

                    Console.WriteLine(val);

            }

 

The output I get is similar to the following:

 

k = 1.1

2.04949627582387

0.413265395865197

0.89342877781768

2.17366630737244

0.238713434099315

k = 0.9

6115472497.0252

7757201199.45204

17733330790.6179

18794327455.778

11646060839.1819

 

Kind Regards,

Mikhail

**Comment by cesarsouza** [comment]
Hi Mikhail,

Thanks for replying! Indeed the issue should have already been fixed in the latest release. The abnormally high values are not produced anymore when k < 1. 

Regards,
Cesar

**Comment by ahsimb** [comment]
Hi Cesar,

 

That’s a great news. Many thanks for looking at this.

 

Kind Regards

Mikhail
