### ISSUE TITLE
BUG: Matrix.TransposeAndDotWithDiagonal(this T1[][] a, T2[] diagonal)

### ISSUE THREAD

**Issue by kindermannhubert** [accord-net/framework#289]
I believe there is a bug in implementation of Matrix.TransposeAndDotWithDiagonal for jagged arrays because there is an expression 'a.GetLength(1)' which works only when the input 'a' is multidimensional array and it throws an 'out of range' exception.

There should be 'a[0].Length' instead (if we suppose all members of array are the same length).

Same problem is in methods Matrix.TransposeAndDotWithDiagonal(this T1[][] a, T2[] diagonal, T3[][] result).

**Comment by cesarsouza** [comment]
Hi there, many thanks for catching this bug! I have updated the code to use the safer .Columns() or Rows()() methods from the framework itself.

**Comment by cesarsouza** [comment]
Fixed on release 3.3.0.
