### ISSUE TITLE
PERF: Allocations of empty arrays

### ISSUE THREAD

**Issue by kindermannhubert** [accord-net/framework#290]
I saw an unnecessary allocation of empty array in methods Matrix.TransposeAndDotWithDiagonal but there are probably more places where emty array is allocated like this.

At these situations there should be used an [Array.Empty&lt;T&gt;()](https://msdn.microsoft.com/en-us/library/dn906179%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) method.

**Comment by cesarsouza** [comment]
Many thanks! I saw the ticket but couldn't reply it on time. Basically, to add those corrections it would first be needed to finally port the framework to the latest .NET framework version, as well as VS2015. This will be looked upon once GH-299 is solved.

**Comment by cesarsouza** [comment]
Even thouguh GH-299 has now been solved, I doubt if those changes would make any noticeable difference whatsoever. I guess that the either C# or the JIT compilers could easily detect that the code is doing a useless allocation of an empty array and output optimized code in either case - but well, I might be wrong. 

If anybody has evidence of a concrete performance bottleneck due the allocation of empty arrays, please re-open this issue.

Regards,
Cesar
