### ISSUE TITLE
Accord.Imaging nuget dependencies 

### ISSUE THREAD

**Issue by Viper2k4** [accord-net/framework#291]
Hi,

https://www.nuget.org/packages/Accord.Imaging/

Dependencies are:
- Accord (>= 3.2.0)
- Accord.Math (>= 3.2.0)
- Accord.MachineLearning (>= 3.2.0)
- Accord.Statistics (>= 3.2.0)

is this really needed? Because AForge.Imaging only needs AForge it self and Math.

https://www.nuget.org/packages/AForge.Imaging/

Greetings

**Comment by cesarsouza** [comment]
Hi there,

Thanks for reporting the issue! 

Indeed, there seems to be an issue with current dependencies of Accord.Imaging. There shouldn't have been a dependency on Accord.MachineLearning, as imaging methods that need machine learning methods are actually computer vision methods and would be more suited to belong to the Accord.Vision project.

I will perform this change in after the next release, in order to avoid breaking too much code at once. If you have more observations about other assemblies, please let me know!

Regards,
Cesar

**Comment by Viper2k4** [comment]
Would be fine. After the change i could finally switch to accord.net :)

i think Accord.Statistics is also not needed. I search in all cs Files and don't find any reference.

Grettings

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.

**Comment by Viper2k4** [comment]
Yes its gone :)

But Accord.Statistics is still a dependencie. Is this needed, i dont find a used reference.

**Comment by cesarsouza** [comment]
Hi there,

Thanks for the reply!

Yes, there are dependencies between Imaging and Statistics. For example, the [AdditiveNoise filter](http://accord-framework.net/docs/html/T_Accord_Imaging_Filters_AdditiveNoise.htm) depends on the statistics distributions, and [ImageStatistics](http://accord-framework.net/docs/html/T_Accord_Imaging_ImageStatistics.htm) on [histograms](http://accord-framework.net/docs/html/T_Accord_Statistics_Visualizations_Histogram.htm).

Also, I might be wrong, but I think in your project you had been using AForge.NET and are considering switching to Accord, is that right? Then in this case it is natural to wonder why there is this extra Accord.Statistics project when before there was only an AForge.Math. 

The truth is that before, many Statistics methods [were contained inside AForge.Math, mostly in the form of a static class](http://www.aforgenet.com/aforge/framework/docs/html/ced1137a-589b-3a7f-d22d-deaff9eb233b.htm). What I have done was to separate what was related to Statistics on a second assembly, including some things that were in AForge.Math before. So please think of Accord.Math and Accord.Statistics as the current replacement for the previous AForge.Math (and also, please keep in mind that if you never use the other statistics methods contained in .Statistics in your application, they will never be compiled by the JIT anyways).

Hope it helps!

Best regards,
Cesar
