### ISSUE TITLE
Accord.Video.FFMPEG.VideoFileWriter ignores bitrate

### ISSUE THREAD

**Issue by T-o-m-a-s-z** [accord-net/framework#295]
Overloaded method VideoFileWriter::Open with bitRate parameter ignores it in a call to another version of this method. Instead of parameter value a hardcoded value of 400000 is passed (which is fine when bitRate parameter doesn't exist but not here).

Line 137:
`Open(fileName, width, height, frameRate, codec, 400000, AudioCodec::None, 0, 0, 0);`
should be chaged to:
`Open(fileName, width, height, frameRate, codec, bitRate, AudioCodec::None, 0, 0, 0);`

**Comment by cesarsouza** [comment]
Many thanks!

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.

**Comment by TharosTheDragon** [comment]
Has that already been released? I downloaded Accord.NET last week and it was 3.3.0.
