### ISSUE TITLE
SVM regression where inputs and outputs have only one dimension

### ISSUE THREAD

**Issue by lguy2000** [accord-net/framework#298]
This code will not compile because apparently it works only with two dimensional inputs (inputs[][]). Is that true?  If so, how does one set up an SVM regression where inputs and outputs are one dimensional (like a simple y = f(x))

double[] inputs = new double[obs];
            double[] outputs = new double[obs];
            Random random = new Random();
            for (int i = 0; i < obs; ++i)
            {
                inputs[i] = ((double)obs - (double)i) / (double)obs;
                outputs[i] = Math.Cos(inputs[i]) + (random.NextDouble() - 0.5);
            }

            var machine = new KernelSupportVectorMachine(new Polynomial(2), inputs: 1);

            // Create the sequential minimal optimization teacher
            var learn = new SequentialMinimalOptimizationRegression(machine, inputs, outputs);

**Comment by cesarsouza** [comment]
Hi there,

As you correctly noticed, the standard SVMs expect the data to be given as an array of double[]. As such, they expect to be not two dimensional, but rather n-dimensional: each training vector can have as many dimensions as you need.

If you would like to use a SVM with scalar values, you can convert your samples from double to double[] by using `Jagged.ColumnVector(your_samples)`. This is the most simple and recommended approach.

However, if you would like to avoid converting your scalars to unidimensional vectors for any reason, you can actually create a new class implementing the IKernel<double> interface. In this way, you will be able to create SVMs that operate directly on scalar double values. However, this solution might be too complicated and unnecessary if all you are looking for is a simple solution for this problem.

Hope it helps!

Regards,
Cesar

**Comment by lguy2000** [comment]
Thanks!  that was super helpful!  Larry
