### ISSUE TITLE
Regression (SVMs) : NullReferenceException on clicking 'Create Machine'

### ISSUE THREAD

**Issue by ashokbugude** [accord-net/framework#302]
Attaching the screenshot of the error which occurs in Line 111 "svm=svm.Learn(inputs,outputs)" in MainForm.cs of Regression (SVMs) on clicking 'Create Machine' in 'Machine Creation' tab

![capture](https://cloud.githubusercontent.com/assets/10016848/18776764/19c196d2-8189-11e6-9628-879970c88865.PNG)

**Comment by cesarsouza** [comment]
Thank you for reporting the issue! A fix will be committed soon.

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
