### ISSUE TITLE
Camera Property Control

### ISSUE THREAD

**Issue by tpitman** [accord-net/framework#303]
I am using Accord.Video and Accord.DirectShow and Accord.FFMPEG.

It is working great to capture, display and save to a file from a USB Capture box.

I am creating a VideoCaptureDevice. This class has a great method called DisplayPropertyPage. This shows the capture box's property page and lets me pick all kinds of great settings.

The down side is that this property page is ugly and has way more properties than I want to expose to my users.

There are a couple other methods that have to do with settings and properties, but none of those are the properties I want to expose to the user to change.

Specifically there is a property to select the input type. This capture box has HDMI, VGA, DVI and SVideo inputs on it. It remembers the last one chosen and does not auto detect which input is connected. Therefore I either have to show this ugly property dialog to let the user change it or I have to find another way to do so.

Is there some facility in the Accord tool box that would allow me to do this?

**Comment by cesarsouza** [comment]
Hi there,

It should be possible to do this from C#, but I might need to extend the framework a little to add support for this.

Can you please share as much details as you can about the device you have? The property pages are very device-dependent. It [might be the case that we will need to specify an interface like this one](https://github.com/accord-net/framework/blob/development/Sources/Accord.Video.DirectShow/Internals/IAMCameraControl.cs), but for the device you have.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Additionally, do you get extra video inputs listed on [videoCaptureDevice.AvailableCrossbarVideoInputs](http://accord-framework.net/docs/html/P_Accord_Video_DirectShow_VideoCaptureDevice_AvailableCrossbarVideoInputs.htm) property? If yes, you might be able to select the video input by setting [videoCaptureDevice.CrossbarVideoInput](http://accord-framework.net/docs/html/P_Accord_Video_DirectShow_VideoCaptureDevice_CrossbarVideoInput.htm) to the appropriate input.

**Comment by tpitman** [comment]
What do you need from me to make an interface or interact with this device? Here is a link to the device:

https://www.startech.com/AV/Converters/Video/usb-3-0-video-capture-device-hdmi-dvi-vga~USB3HDCAP

I already emailed their tech support asking if they had an API for the device. They replied that they do not.

Would it help for me to buy one and send it to you? The software they use is called StreamCatcher. You can download it here. I started going through the DLL files in the software folder, but when I found that I could show the property dialog I stopped. You can download StreamCatcher and drivers on the right hand side of the Support tab on that page.

As far as the crossbar inputs, it is an empty array. I looked for any other settings and nothing is populated that seems like it would help.

Let me know how we can move forward on this.

**Comment by cesarsouza** [comment]
Hi tpitman,

Thank you a lot for the details. I have taken a look on what they provide, their drivers, etc, and it seems they are using a really custom property page. In order to alter the properties of the device from using COM we would need to know exactly the interface definition that they are using in order to implement it in C#, but I am afraid it will not be possible without an API.

It is bad that the crossbar options are not populated. I suspect this would have been the standard way of solving this issue through standard DirectShow, but it seems their driver does not support it.

However, if you are really, really interested in making this work without the property pages, _maybe_ it should be possible to hack the other way around - instead of altering programmatically what is being shown in the interface, try to alter the interface programmatically. This might be possible in Windows by getting the window handle of the property page and trying to locate and [tamper with the controls inside it](http://stackoverflow.com/questions/10355286/programmatically-mouse-click-in-another-window). You could hide the properties window so it not visible during this trick.

Well I know this isn't the best solution to the original problem, but I hope it may help.

Regards,
Cesar

**Comment by quantumdot** [comment]
Sorry to reopen a closed issue, but I am looking for similar functionality and it looks like this wasn't really resolved. Is it possible to expose the items under the "Video Proc Amp" tab through the existing interface of GetCameraProperty/SetCameraProperty/GetCameraPropertyRange? It looks like this is how the "camera control" properties are handled in this way.

**Comment by quantumdot** [comment]
Let me back up a second. My application needs to save acquisition settings and later re-apply them to devices for reproducible capture sessions. So I really need a way to programmatically set the various camera and post-processing properties.

Yes, I'm aware of the `DisplayPropertyPage()` method, but this doesn't really help with the above end goal. I see the methods `GetCameraProperty` / `SetCameraProperty` / `GetCameraPropertyRange`, but these only accept `CameraControlProperty` values (zoom, focus, exposure, etc). I need to be able to set other properties, specifically those that show up under the "Video Proc Amp" tab of the dialog created by `DisplayPropertyPage()` (e.x. brightness, contrast, hue, saturation, ..., gain, etc), but there seems to be no way to do it programmatically. These properties seem to be defined by the DirectShow subsystem via structs like `KSPROPERTY_VIDEOPROCAMP_BACKLIGHT_COMPENSATION`.

**Comment by blaisexen** [comment]
I think it's not applied in this framework,
I have tried it but only this I got,
        private void selectlocalvideodevice(string dev)
        {
            VideoCaptureDevice videoSource = new VideoCaptureDevice(dev);
            videoSource.VideoResolution = selectResolution(videoSource);
           
            //SET Exposure
            videoSource.SetCameraProperty(CameraControlProperty.Exposure, -1, CameraControlFlags.Manual);

            OpenVideoSource(videoSource);
        }

 brightness, contrast, hue, saturation, ..., gain, ? I can't figure out.

**Comment by blaisexen** [comment]
Yes I understand now,
I search then I get ideas from here:
https://gist.github.com/MZachmann/557bf6663ce4806dfa85f1cd348027b4

Implementation is the issue now

**Comment by blaisexen** [comment]
Got new ideas, here:
but I don't know to make it work,
        private void button3_Click(object sender, EventArgs e)
        {
            SharpDX.MediaFoundation.DirectX.ProcAmpValues asdf;
            asdf.Brightness.Value = -10;
            asdf.Contrast.Value = 0;
        }

**Comment by quantumdot** [comment]
It looks like this could be mostly copy/pasted from the Accord implementation of the camera control properties, with minor modifications. The gist you linked to looks like a good place to start (https://gist.github.com/MZachmann/557bf6663ce4806dfa85f1cd348027b4) with a lot of these items. 

1. Add implementation of `IAMVideoProcAmp` to the namespace `Accord.Video.DirectShow.Internals`.
2. Add implementation of new enum `VideoProcAmpProperty` to the namespace `Accord.Video.DirectShow`. The gist implementation above seems incomplete, missing some enum values. See the enum definition from the win sdk here (lines 4991-5017): https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/shared/ksmedia.h. Specifically, the gist is missing `GAIN`, `DIGITAL_MULTIPLIER`, `DIGITAL_MULTIPLIER_LIMIT`, `WHITEBALANCE_COMPONENT`, and `POWERLINE_FREQUENCY`.
3. Add implementation of new enum `VideoProcAmpFlags` to the namespace `Accord.Video.DirectShow`. 
4. Expose the following methods on `Accord.Video.DirectShow.VideoCaptureDevice`:
    
    - `GetVideoProcAmpProperty(VideoProcAmpProperty property, out int value, out VideoProcAmpFlags controlFlags)`
    - `SetVideoProcAmpProperty(
	VideoProcAmpProperty property,
	int value,
	VideoProcAmpFlags controlFlags)`
    - `GetVideoProcAmpRange(VideoProcAmpProperty property,
	out int minValue,
	out int maxValue,
	out int stepSize,
	out int defaultValue,
	out VideoProcAmpFlags controlFlags)`

**Comment by quantumdot** [comment]
I put together an implementation based on my comment above. This basically works the same way as the CameraProperties, but for the video signal post-processing properties. 

I initially attempted to put the changes on the development branch, but was getting unrelated errors. However, applying the proposed implementation on master works: https://github.com/quantumdot/framework/commit/bcab96c397881ec960034777bebc8edff8776bb7

Could we get this added to Accord?

Resources:
MS specification for the `VideoProcAmpProperty` enum 
https://docs.microsoft.com/en-us/windows-hardware/drivers/stream/propsetid-vidcap-videoprocamp

Reference implementation of `IAMVideoProcAmp`
https://gist.github.com/MZachmann/557bf6663ce4806dfa85f1cd348027b4

**Comment by blaisexen** [comment]
private void button3_Click(object sender, EventArgs e)
{

//select or use or point the device source here...
//then I guess it will be alright lighting it up....

SharpDX.MediaFoundation.DirectX.ProcAmpValues asdf;
asdf.Brightness.Value = -10;
asdf.Contrast.Value = 0;
}

**Comment by quantumdot** [comment]
What's the advantage of doing it this way rather than baking these methods into the `VideoCaptureDevice`? Also, it looks like SharpDX only supports a subset of the ProcAmpValues available according to the MS docs (see the SharpDX enum here: https://github.com/sharpdx/SharpDX/blob/5222284613ecd876e4efac8aee8f878b8d673a59/Source/SharpDX.MediaFoundation/DirectX/Hand.Generated/Enumerations.cs#L2078)
