### ISSUE TITLE
L-M neural network hyperbolic tangent activation function

### ISSUE THREAD

**Issue by lguy2000** [accord-net/framework#305]
Is there a way to have the activation function of an L-M neural network by the hyperbolic tangent (TanH: -1,+1) instead of Sigmoid?  Thank you.

**Comment by cesarsouza** [comment]
Hi there,

The preferred way to get (-1;+1) outputs is by using [BipolarSigmoidFunction](http://accord-framework.net/docs/html/T_Accord_Neuro_BipolarSigmoidFunction.htm). It is actually equivalent to the TanH function but with a slightly more general parametrization.

(By the way, as a note to myself, I will leave this issue open until I can fix the image in the documentation, which is currently not displaying).
