### ISSUE TITLE
L-M Neural Network input standardization

### ISSUE THREAD

**Issue by lguy2000** [accord-net/framework#306]
Is it desirable to standardize inputs (subtract mean and divide by std for example) or does L-M Neural Network handle differences in scaling automatically?

**Comment by cesarsouza** [comment]
Yes, it is necessary to standardize inputs, as well as outputs (if you are using a sigmoid, the outputs must be between 0 and 1, for example). The network cannot do this automatically currently.

**Comment by lguy2000** [comment]
Thanks, Cesar.  What about my question about using TanH as the neuron activation function?

Merci!

Laurent
