### ISSUE TITLE
Compile error with release 3.2.2

### ISSUE THREAD

**Issue by edgar005** [accord-net/framework#309]
In project: Deep Learning

Error   108 The tag 'PropertyGrid' does not exist in XML namespace 'http://schemas.xceed.com/wpf/xaml/toolkit'. Line 45 Position 10.    A:\Archiv\3D\Accord\framework-3.3.0\Samples\Neuro\Deep Learning\PerfWindow.xaml 45  10

**Comment by cesarsouza** [comment]
Thanks for reporting the issue! The problem was that the NuGet references were outdated for the deep learning sample application. I will update the downloadable packages soon.

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
