### ISSUE TITLE
L1-regularized (Logistic) regression

### ISSUE THREAD

**Issue by mikhail-barg** [accord-net/framework#310]
I've been looking on having L1 regularization to LogisticRegression. It has a nice property — it's said to be useful for feature selection (see for example [this](https://web.stanford.edu/~boyd/papers/pdf/l1_logistic_reg_aaai.pdf)).

As far as I understand, the `IterativeReweightedLeastSquares.Regularization` parameter is only for L2 regularization, and there's no L1 currently supported. Is this correct? 

It would be nice to have it added (for example like [this](https://www.cs.ubc.ca/~schmidtm/Documents/2005_Notes_Lasso.pdf)). And maybe even being able to specify both L1 and L2 at the same time.

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue! It is currently possible to train L1-regularized Logistic Regression through [ProbabilisticCoordinateDescent](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_ProbabilisticCoordinateDescent.htm). Albeit being a method originally intended for learning L1-regularized linear support vector machines, it so happens that linear probabilistic SVMs are exactly the same model as logistic regression.

After you learn a L1-regularized SVM using this method, one possible way to convert it to a LogisticRegression was to use SVM's [ToWeights()](http://accord-framework.net/docs/html/M_Accord_MachineLearning_VectorMachines_SupportVectorMachine_1_ToWeights.htm) method and pass it to LogisticRegression's [FromWeights()](http://accord-framework.net/docs/html/M_Accord_Statistics_Models_Regression_LogisticRegression_FromWeights.htm) method. I will update the documentation with a concrete example on how this can be done.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
