### ISSUE TITLE
V3.3.0 Cannot set input and output names in LogisticRegressionAnalysis

### ISSUE THREAD

**Issue by rpmSportsAnalytics** [accord-net/framework#314]
Neither the LogisticRegressionAnalysis Constructor nor the Learn method support input and output names as parameters and the Inputs and Outputs properties do not have setters (are read-only).

**Comment by cesarsouza** [comment]
Thanks for reporting the issue, and sorry for the inconvenience! As a workaround, please note that you can just replace the values in the string arrays, e.g.
```
analysis.Inputs[0] = "name";
```

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
