### ISSUE TITLE
Accord.Video.FFMPEG.3.3.0 does not support vp9 encoding webm files

### ISSUE THREAD

**Issue by Thenabadu** [accord-net/framework#321]
Hi cesarsouza,

I used accord 3.3.0 (Accord.Video.FFMPEG.3.3.0). i try to decord, vp9 encoding webm file. but it is not success. (vp8 webm files we can) also cannot decode rtsp vp8 stream.( http vp8 stream can decord)

is there a way to do those things using ACCORD .net?

thanks.
Gayan Thenabadu

**Comment by cesarsouza** [comment]
Hi there,

The current FFMPEG version used in Accord.Video.FFMPEG does not support VP9 (but as you correctly noticed, it works with VP8). Unfortunately, the reason for this is the same discussed in GH-224. It would be necessary to re-write Accord.Video.FFMPEG to work with the newest versions of FFMPEG (which is doable, but would take a bit of effort and experience with the most recent version of the FFMPEG API).

**Comment by Thenabadu** [comment]
Hi cesarsouza,

Thank you for reply me. 
Vp8 "rtsp" stream decording also not working. But when we use h264 stream, both http and rtsp, decord fine. Is this a issue or you are not giving vp8 rtsp stream decord facility. I also try with aforge last release, it also not support for that.

Thank you.
Gayan Thenabadu

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
