### ISSUE TITLE
NegativeBinomialDistribution Cum Dist func not returning expected value

### ISSUE THREAD

**Issue by jonbarkerlondon** [accord-net/framework#327]
Forgive me if I am misusing the library, but I can't seem to get out the expected result.

For the NBD, with a **number-of-successes of 71**, and a **probability of success of 0.9712** and a value of **1**, I would expect the '**DistributionFunction**' method to return approx **0.382...**. 

However with your library, doing the following:

```
var distribution = new NegativeBinomialDistribution(71, 0.9712);
var X = distribution.DistributionFunction(1);
```

**The result of X is 1.1102230246251565E-16**

Wolfram alpha indicates the result should be 0.382...:
http://www.wolframalpha.com/input/?x=6&y=3&i=negative+binomial+distribution+n%3D71+p%3D0.9712

I also get this result from the Math.NET libraries by doing the following code:

```
var distribution = new MathNet.Numerics.Distributions.NegativeBinomial(71, 0.9712);
var X = distribution.CumulativeDistribution(1);
```

**The result of X is 0.382**

(See https://dotnetfiddle.net/BfeMuz for sample of MathNet)

Can you confirm that I am using the library as expected, and this is a bug? Or alternatively explain how to get the correct result.

Best,
Jon

**Comment by jonbarkerlondon** [comment]
Update: Looking at the source code and comparing MathNet and Accord

mathnet does this on the CDF:
1.0 - Accord.Math.Beta.Incomplete(k + 1, 71, **1 -** 0.9712))

accord does this on the CDF
1.0 - Accord.Math.Beta.Incomplete(k + 1, 71, 0.9712))

So math.net takes 1 away from the success probability. My understanding is that you should also be doing 1-successprobability in the DistributionFunction method.

**Comment by cesarsouza** [comment]
Hi Jon,

First of all, I apologize for such a bug in the library. It is beyond me how such simple issue had been undercover for so long. And thank you so much for reporting the issue and for the investigative work in determining its cause. I will be committing a fix to the development branch in the following minutes.

Regards,
Cesar

**Comment by jonbarkerlondon** [comment]
@cesarsouza No need to apologize! It's an awesome library and has saved me a huge amount of development time. Thankyou for contributing your time and energy into creating it.

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
