### ISSUE TITLE
Regression (Kernel SVM) error

### ISSUE THREAD

**Issue by rahimism** [accord-net/framework#328]
Hi
I tried to use the "Regression (Kernel SVM)" but it shows an error. I see the error both when I use the app or I compile it myself.

Rahimi

![error](https://cloud.githubusercontent.com/assets/17049672/19495927/56581296-9553-11e6-831e-28e17e78427c.jpg)

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue! However, I couldn't reproduce it on the latest development version. Can you please let me know which version of the framework are you using, and possibly from where you downloaded the sample application? (it might be the case that the download link is outdated)

Thanks!

Regards,
Cesar

**Comment by rahimism** [comment]
Hi,
I downloaded through the link provided in website:
http://dl.dropbox.com/u/32601472/accord/samples/accord-machinelearning-regression-(svms).rar

you can download and see the error.

**Comment by cesarsouza** [comment]
Thanks Rahimi, indeed the link was outdated. I have updated the samples with the ones from the latest version.

Regards,
Cesar
