### ISSUE TITLE
ExccelReader Class Not found

### ISSUE THREAD

**Issue by yasin-buet** [accord-net/framework#329]
Hello!
I installed Accord .NET and saw some videos.
Found it pretty cool :)
On How to use I found a guide to Excel file data. It is as follows
[https://github.com/accord-net/framework/wiki/How-to-use](url) 
`Tables

Excel and Excel compatible files (such as .csv)

To import a table from Excel or .CSV files, you can use the ExcelReader class class. To load the contents of "Sheet1" located in "worksheet.xlsx", use:

DataTable table = new ExcelReader("worksheet.xlsx").GetWorksheet("Sheet1");`
i also saw`http://accord-framework.net/docs/html/T_Accord_IO_ExcelReader.htm` for a double check

But in visual studio i got 
`Error  CS0246  The type or namespace name 'ExcelReader' could not be found (are you missing a using directive or an assembly reference?)`
![accord](https://cloud.githubusercontent.com/assets/15029067/19548217/023776b2-96bf-11e6-91d6-98bf3fdff362.PNG)

When i try Accord.IO.  i get no class which has a name ExcelReader.
Is there any problem 
or am i missing something?
Thanks in advance!

**Comment by erdomke** [comment]
Please make sure that you have installed the `Accord.IO` NuGet package and that you have `using Accord.IO;` at the top of your file.  That is what I discovered was required to get it to work.

**Comment by yasin-buet** [comment]
Thanks !! i works 💃

**Comment by bradh** [comment]
Suggest closing this.
