### ISSUE TITLE
capture video with audio

### ISSUE THREAD

**Issue by DenisTsapelnikov** [accord-net/framework#333]
Hi. the libraries are great. i saw the example wit capturing both video and audio. I would like to know is there a opportunity to capture in and out audio (microphone and speakers ) within the video?

**Comment by cesarsouza** [comment]
Please take a look at the [Screencast Capture Lite sample application](https://github.com/cesarsouza/screencast-capture). It should be able to capture video (from the desktop, but should work with any source) and audio from the microphone at the same time and store them into the video file.
