### ISSUE TITLE
Using Accord on Linux

### ISSUE THREAD

**Issue by rodrigohagen** [accord-net/framework#336]
Hi,

I have been working on a project that uses the accord library to run videos. The original project was made on windows and using .net 4.0. When I tried to port the whole project to linux I've been getting the following error message but I can't seem to find a solution for it:

Method '<Module>:_getFiberPtrId ()' in assembly '/home/rodrigo/Documents/LendaUnified/LendaUnified/bin/Debug/Accord.Video.FFMPEG.dll' contains native code that cannot be executed by Mono on this platform. The assembly was probably created using C++/CLI.

I know it seems the library file I am using can't be used by the same way I was referencing in my monodevelop project. However, I have no idea how to fix this. Does anyone have a clue of how to fix it?

Thank you

**Comment by cesarsouza** [comment]
Hi there,

Unfortunately the Accord.Video.FFMPEG project cannot be run on Linux at this time. It is a mixed-mode assembly containing both native and managed code and is thus not currently supported by Mono under Linux. However, there are some chances that the project can work using [Mono for Windows running on Linux through Wine](http://www.mono-project.com/docs/about-mono/languages/cplusplus/). 

In any case, for other users that eventually find this issue, this doesn't mean that the rest of the project will not run on Mono. In fact, the instructions on how to [build the Accord.NET framework to run on Linux using mono are available at the repository readme (the first page)](https://github.com/accord-net/framework#with-mono-linuxxbuild), but as it can be seen, not all project libraries will be available in this build.

Regards,
Cesar
