### ISSUE TITLE
ExpectationMaximization max Iterations can't be changed

### ISSUE THREAD

**Issue by franktore** [accord-net/framework#337]
Hi,
When learning a GaussianMixtureModel it should be possible to pass MaxIterations to the EM algorithm. As it is now the Iterations parameter is passed to EM instead of MaxIterations.
Since Iterations are private set and never changed in code it will always be 0. This leads to infinite loops when a problem does not converge.

I also notice a missing else statement in MultivariateNormalDistribution.Fit().
When computing unweighted covariance it will always default to full matrix even when options.Diagonal is set:

```
// Compute covariance matrix
if (options != null && options.Diagonal)
    cov = Matrix.Diagonal(Measures.Variance(observations, means));
cov = Measures.Covariance(observations, means).ToMatrix();
```

Best regards,
Frank

**Comment by cesarsouza** [comment]
Hi Frank,

Many thanks for reporting the issue. This was, in fact, a bug that had been introduced when the new learning interfaces were implemented. I am committing a fix in the next minutes, and I am sorry for updating it this late after your initial report.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
