### ISSUE TITLE
Low Pass Filter alpha

### ISSUE THREAD

**Issue by brody7u7** [accord-net/framework#339]
Hello, can someone please tell me which is the range of alpha or if measured in Hz?
Thank's.

**Comment by cesarsouza** [comment]
Hi there,

The low-pass filter is computer according to the formula 

```
for (int t = 0; i &lt; length; t++)
    y = y[t-1] + Alpha * (x[t] - y[t-1]);
```

As such, the alpha value for a given sampling rate and cut-off frequency could be found by using a method like this:

```
        public static float GetAlpha(double frequency, double sampleRate)
        {
            double rc = 1 / (2 * Math.PI * frequency);
            double dt = 1 / sampleRate;
            return (float)(dt / (dt + rc));
        }
```

I am adding such method and other facilities to determine the appropriate alpha directly in the low and high filter classes. Sorry for not including it earlier!

Regards,
Cesar

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.

**Comment by brody7u7** [comment]
Thanks! It helped me a lot.
