### ISSUE TITLE
PoissonDistribution InverseDistributionFunction not returning expected value

### ISSUE THREAD

**Issue by nwiman** [accord-net/framework#340]
I can't seem to get out the expected result.

For the Poisson with a lambda of 2 and k set to 7 i get 0.99890328103214132 from the 'DistributionFunction'. However when i call the 'InverseDistributionFunction' with that same number i get 9.

var dist = new PoissonDistribution(lambda: 2.0);
double cdf3 = dist.DistributionFunction(k: 7); // 0.998903281032141
int icdf3 = dist.InverseDistributionFunction(p: cdf3); // Expects 7
The result of icdf3 = 9
https://dotnetfiddle.net/cGufGD

This only seems to be in the upper >98%.
Tried to test this in Math.Net but it doesn't implement an InverseCDF.

Can you confirm that I am doing this right and this is a bug? 
Or explain how to get the correct result?

Cheers
Wiman

**Comment by nwiman** [comment]
Possible fix for this;
  
      public override int InverseDistributionFunction(double p)
        {
            if (p < 0.0 || p > 1.0) throw new ArgumentOutOfRangeException(nameof(p));

            // expand interval until we bracket P
            int ka = 0;
            int kb = (int)Math.Ceiling(lambda);
            while (p > DistributionFunction(kb))
            {
                ka = kb;
                kb = 2 * kb;
            }

            // reduce interval until we have isolated P            
            while (ka != kb)
            {
                int k = (ka + kb) / 2;
                if (p > DistributionFunction(k))
                {
                    ka = k + 1;
                }
                else
                {
                    kb = k;
                }
            }
            return ka;
        }`

**Comment by cesarsouza** [comment]
Hi Wiman,

Many thanks for reporting the issue and a possible fix. Indeed, the previous version of the code was using the inverse Gamma function to compute the inverse CDF, which was quite problematic. The fastest solution is to remove the InverseDistributionFunction from the PoissonDistribution class altogether, as the base class implementation will perform a binary search in a way similar to what you proposed.

Thanks a lot again for bringing this into attention, and sorry for the delay in answering. A fix will be available soon!

Regards,
Cesar

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.
