### ISSUE TITLE
"Index out of Bounds" when setting symbols value over 19

### ISSUE THREAD

**Issue by HiGravity** [accord-net/framework#342]
Is there a constraint on the number of symbols in a HMM? I was trying to run unit tests to figure out optimal number of states to use against some data as I try and learn HMM and I receive an index outside of bounds error when BaumWelchLearning.Learn() is executed. I have six (6) int[25] for training sequences then I'm using new observations of a single (1) int[25] and created unit tests that are very similar to the code [HERE](http://www.codeproject.com/Articles/541428/Sequence-Classifiers-in-Csharp-Part-I-Hidden-Marko). I even use the same inputs for my first set of tests and they provide the same output, but when I start expanding it out to use a larger data set with my data I get this error. I have a method that checks the saved data and the new data and calculates the distinct symbols in the data set. In this case its 29 which represent keys to screens a user may click on. It happens whether I set it for 1 state or 29. Is there some reason this is too many symbols or am I misunderstanding the API? 

![capture](https://cloud.githubusercontent.com/assets/8883525/20032885/bfa0670a-a361-11e6-899e-ff2527a4f44f.PNG)

**Comment by HiGravity** [comment]
The issue seems to be at Accord.Statistics\Distributions\Univariate\Discrete\GeneralDiscreteDistribution.cs

`p[observations[i] - start] += weights[i] * observations.Length;`

...weights and observations is length 150 while p is length 29.

**Comment by cesarsouza** [comment]
Hi there,

First and foremost, sorry for the delay in answering. Answering the original question, no, there are no limits on the number of inputs a HMM can take. Thanks for the initial investigation regarding the GeneralDiscreteDistribution, I am in the process of writing a few more unit tests in order to isolate and finally fix the issue.

Regards,
Cesar

**Comment by cesarsouza** [comment]
This should have been fixed in release 3.6.0.
