### ISSUE TITLE
Build error: When building PCA example

### ISSUE THREAD

**Issue by frankfugang** [accord-net/framework#343]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'Complex' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

I use Visual studio 2015, When I build PCA example, I get this error.

**Comment by Lyubna** [comment]
You should add a reference to "System.Numerics" in your project like that: 
1. Right click on your project in the solution explorer and click on "Add reference"
![1](https://cloud.githubusercontent.com/assets/18594914/22498898/deb7102a-e863-11e6-8ed9-360b1c496004.png)

2. From the .Net tab search for "System.Numeric" then add it and click ok 

![2](https://cloud.githubusercontent.com/assets/18594914/22498902/e8d2f4c0-e863-11e6-9eeb-4c8b6c0fced3.png)


Good luck

**Comment by cesarsouza** [comment]
@Lyubna, 

Many thanks for the help in answering this issue!  And @frankfugang I hope these very detailed instructions have helped, even though I recognize I am a bit late in the reply (sorry for not answering it before...). 

A reference to System.Numerics is needed in many sample applications, but I am still not quite sure why I am not getting those errors when compiling in my development machines. 

Regards,
Cesar

**Comment by frankfugang** [comment]
Thank you very much for your response. That's really helpful.

Best regards,

Gang

**Comment by cesarsouza** [comment]
All sample applications have been upgraded to use NuGet, so hopefully this error will not happen anymore (I was never been able to reproduce it, though).
