### ISSUE TITLE
Cannot install an older version of the framework without NuGet

### ISSUE THREAD

**Issue by theonelugnut** [accord-net/framework#346]
Cannot install an older version of the framework (eg (3.2.3-alpha)) without NuGet.  The user does not have install permissions on the workstation (ie cannot install NuGet). The framework is to installed on a second workstation where the user has install privileges but no Inernet access

**Comment by cesarsouza** [comment]
Hi there,

Sorry for the late reply. Unfortunately, the pre-release packages (those tagged with -alpha) are only available through NuGet. If you need to use a pre-release package in a machine that doesn't have internet access, you can always download the NuGet packages in a workstation that has, and then copy the .dlls from the project directory into the other machine. 

Alternatively, perhaps an easier way would also be to commit the project .dll files into your source code repository directly.

On the other hand, if you need the .dlls for supported releases, they can also be found in the [project's release page](https://github.com/accord-net/framework/releases).

Regards,
Cesar
