### ISSUE TITLE
Critical bug in two LineSegment intersection

### ISSUE THREAD

**Issue by yusufumac** [accord-net/framework#350]
These two line segments does not intersects in reality. 

(32.0951, 36.0828) -> (32.0863, 36.1038)
(32.0861, 36.2358) -> (32.0859, 36.0889)

But, GetIntersectionPoint method of LineSegment class outputs 32.0859, 36.1035 as the intersection point.

**Comment by cesarsouza** [comment]
Hmm... Did you actually mean ```GetIntersectionWith``` rather than ```GetIntersectionPoint```? If that is the case, then I couldn't reproduce the issue:
```
LineSegment segA = new LineSegment(new Point(32.0951f, 36.0828f), new Point(32.0863f, 36.1038f));
LineSegment segB = new LineSegment(new Point(32.0861f, 36.2358f), new Point(32.0859f, 36.0889f));

Point? result = segA.GetIntersectionWith(segB); // correctly returns null in this case
````
