### ISSUE TITLE
Take so much time create a SequentialMinimalOptimizationRegression in Accord.NET

### ISSUE THREAD

**Issue by mikesneider** [accord-net/framework#352]
I'm creating a SMOR (

> SequentialMinimalOptimizationRegression

) with Accord.NET

This is my code:

smo = new SequentialMinimalOptimizationRegression(machine, InPut, OuPut);
My input is a `double[1119][9] //x1,x2,...,x9`
My output i a `double[1119][1] //y1`

but creating the SMOR takes around **29 minutes,** someone knows why this takes a so much time?

**Comment by cesarsouza** [comment]
A new optimization algorithm, which should be faster, will be available for learning SVR in the next release.

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
