### ISSUE TITLE
MultivariteNormalDistribution generate function with specific seed

### ISSUE THREAD

**Issue by nwiman** [accord-net/framework#353]
Is there some way of passing the seed to the NormalDistribution.Random function?
And then expose this functionalty to the MultivariateNormalDistribution generate function?
Now it always creates new a NormalDistribution random with stocastic seed for each sample... am i missing somehing why it can't be the same seed and then just continue to generate random numbers for every sample...

Best regards
Wiman

**Comment by nwiman** [comment]
Resolved.

**Comment by cesarsouza** [comment]
Hi there,

I am glad you could solve the issue. For further reference, it is possible to fix the seed for any method in the framework by setting ```Accord.Math.Random.Generator.Seed``` to any random number, e.g.

```
Accord.Math.Random.Generator.Seed = 42;
```

Some values (0 or negative) can have special meaning affecting the way the seed is propagated to other threads. More details are available in the [documentation page of Accord.Math.Random.Generator](http://accord-framework.net/docs/html/T_Accord_Math_Random_Generator.htm)..

Regards,
Cesar

**Comment by nwiman** [comment]
Hello and thank u for all help with the Poisson inverse.

I figured the seed thing out eventually... :)

I been developing a model which uses alot of inverse cdfs and one thing that is still missing is to setup a NegativeBinomialDiatribution and pass failures as a double (instead of integer).
I've solved it in another way now but this seems pretty common.

Thx for a great lib!

Cheers
Wiman
