### ISSUE TITLE
Can HOG to work with BoW'2 with SVM or OSVM

### ISSUE THREAD

**Issue by gkomix88** [accord-net/framework#365]
Hi Ceasar and All,

Thanks for the great work in Accord.NET! It make everything sound possible :)

I m currently trying to apply object recognition using HOG with Bag of Visual Words and classifier by SVM or OSVM. However, it seem the HOG could not work with the BoW'2 class. For instance,

var kmodes = new KModes<double>(numberOfWords, new Hamming());
var detector = new HistogramsOfOrientedGradients(9, 3, 6);
var hogBow = new BagOfVisualWords<FeatureDescriptor, double[]>(detector, kmodes);
hogBow.Compute(TrainImages.Values.ToArray());

Could anyone assist on this case? Thanks in advance.

**Comment by cesarsouza** [comment]
Hi there,

I will soon commit some changes that will facilitate the use of HOG and other feature extractors in the BoW framework. Sorry for the delay in answering though.

Regards,
Cesar

**Comment by cesarsouza** [comment]
https://github.com/accord-net/framework/commit/e185da97cbbd0a0960727b351eb64b453d01469d

**Comment by gkomix88** [comment]
Thanks! Cesar. Will try it now.

**Comment by hzawary** [comment]
Hi everybody :)

Is also there way to use the other descriptors such Haar in BoW?!

Best,
H.Zavvari

**Comment by cesarsouza** [comment]
Hi Zawari,

Yes, it should have been possible to use any descriptor or clustering algorithms in BoW. However, some algorithms like SOM still haven't been updated to use the more recent clustering/classifier interfaces, and as such will not work yet.

Haralick should work though, but I am not sure if I have written a test to confirm yet.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
