### ISSUE TITLE
Samples/Imaging/Classification (BoW) is obsolete.

### ISSUE THREAD

**Issue by ghost** [accord-net/framework#366]

**Comment by NickTriada** [comment]
I very need same example but for shape recognizing and training for different shapes. Can anybody share with code example, doesn't matter is it now obsolete or not, just working and comment example solution that I can use it for my tasks. 
HIGHLY APPRECIATED!

**Comment by Owinger** [comment]
@NickTriada Check [this](https://github.com/accord-net/framework/tree/development/Samples/Imaging/Detection%20(Shape)) out.

**Comment by cesarsouza** [comment]
An updated sample application will be committed soon. I am sorry for the late reply, the update took a bit longer than I had planned for.

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
