### ISSUE TITLE
Accord.IO.Serializer.Load Extension Method

### ISSUE THREAD

**Issue by Chevy1977** [accord-net/framework#369]
Accord.IO.Serializer.Load Extension Method does not exist.
The documentation has the copy/paste text of the Save Method and the Save Extension Method exists.
Version 4.0.30319

**Comment by cesarsouza** [comment]
Hi there,

The Load is not an extension method, but rather a static class method of the Serializer class. Could you please let me know which documentation page are you referring to, so I can take a look and fix it?

Many thanks!

Best regards,
Cesar

**Comment by Chevy1977** [comment]
Hi,
this old api is telling me that it is an extension:
http://accord-framework.net/docs/html/M_Accord_MachineLearning_VectorMachines_MulticlassSupportVectorMachine_Load_1.htm

**Comment by cesarsouza** [comment]
Fixed in release 3.4.0.
