### ISSUE TITLE
Algorithm Question

### ISSUE THREAD

**Issue by Chevy1977** [accord-net/framework#370]
I updated Accord via nuget and needed to name a kernel. Now I am wondering if it is exactly the same Algorithm what I use (in comments is the old code):

`      'Dim teacher = New MulticlassSupportVectorLearning(Machine, svm_problem_matrix, svm_labels_dc) With
      '              {.Algorithm = Function(svm, classInputs, classOutputs, i, y)
      '                               Return New LinearDualCoordinateDescent(svm, classInputs, classOutputs) With
      '                                                                           {.Loss = Loss.L2,
      '                                                                            .Complexity = 1000,
      '                                                                            .Tolerance = 0.00001}
      '                            End Function
      '              }
      'Dim errorCode As Double = teacher.Run()`

      ' Januar 2017
      Dim teacherY As New MulticlassSupportVectorLearning(Of **Linear**) With {
         .Learner = Function(p) New LinearDualCoordinateDescent() With {
                                                                        .Loss = Loss.L2,
                                                                        .Complexity = 1000,
                                                                        .Tolerance = 0.00001
                                                                       }
                       }

**Comment by cesarsouza** [comment]
Hi there,

Yes, it should be. Afterwards you can learn the svm using
```
Machine = teacherY.Learn(svm_problem_matrix, svm_labels_dc)
```
and you should also be able to recompute the error using
```
Dim error = New ZeroOneLoss(svm_labels_dc).Loss(Machine.Decide(svm_problem_matrix))
```

Hope it helps!

Regards,
Cesar
