### ISSUE TITLE
FrameRate as double in Accord.Video.FFMPEG

### ISSUE THREAD

**Issue by cesarsouza** [accord-net/framework#373]
The VideoFileWriter should accept a double instead of an int.

From https://github.com/andrewkirillov/AForge.NET/issues/6

**Comment by vincss** [comment]
I up-vote this one ! I need it to generate a 29.97 video. :-)

**Comment by cesarsouza** [comment]
There you go :-) will be available in the next release!

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
