### ISSUE TITLE
Add an Example for LevenbergMarquardt Class

### ISSUE THREAD

**Issue by kotval** [accord-net/framework#377]
Please add an example for LevenbergMarquardt Class.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Math_Optimization_LevenbergMarquardt.htm

**Comment by cesarsouza** [comment]
Hi @kotval,

First of all, sorry for the delay in answering. I am also finally about to add an example to the LevenbergMarquardt class, and only now I realized you have added some examples in your branch. 

Would you like to submit them to the project as a pull request?

Regards,
Cesar

**Comment by kotval** [comment]
@cesarsouza I have not added any examples that would be appropriate for general use. Most of my work has been on trying to use your LevenbergMarquardt implementation to solve problems with inequality constraints using Lagrangian relaxation. My version of of LevenbergMarquardt, which has this as an option, is probably not tell tested enough to be included in a pull request.

**Comment by blaisexen** [comment]
hi,
samples can be found at sample folder from this framework,

here is the folder you want using "LevenbergMarquardt" implementation
https://github.com/accord-net/framework/tree/development/Samples/Neuro/Classification%20(ANN)

**Comment by blaisexen** [comment]
@cesarsouza ,

hi,
since I also Forked from this framework, can I add my own samples as "Samples2" in my Forked framework?

just asking...

I know I don't own the framework but is it Ok to put the samples2 in my Forked folders?

**Comment by cesarsouza** [comment]
Hi @blaisexen,

He is referring to a the Levenberg-Marquardt class for general optimization. It has a different interface from the Levenberg-Marquardt for neural network training, and it didn't have any examples in the documentation.

This should be fixed soon.

Regards,
Cesar

**Comment by blaisexen** [comment]
I'm sorry I think I don't understand this all.

**Comment by cesarsouza** [comment]
Added in 3.8.0.
