### ISSUE TITLE
net46 version from nuget is actually built against .NET 4.6.1

### ISSUE THREAD

**Issue by PawelTroka** [accord-net/framework#379]
I have updated Accord.Math library from nuget from version 3.3.0 to version 3.4.0 and my project stopped compiling. It seems like "binary packages\Accord.3.4.0\lib\net46\Accord.dll" is actually built against .NET 4.6.1 not 4.6.

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The primary reference "Accord.Math, Version=3.4.0.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7, processorArchitecture=MSIL" could not be resolved because it has an indirect dependency on the assembly "Accord, Version=3.4.0.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7" which was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6".	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1820

**Comment by cesarsouza** [comment]
Ouch, sorry about that. Would it be possible to upgrade your project to 4.6.1 in the meantime?

**Comment by PawelTroka** [comment]
I need to stay on NET46 because it is the last version Windows Vista supports. For now I just reverted back to using Accord 3.3.0 so there is no problem from my side - I just wanted to help by reporting what I have spotted.

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
