### ISSUE TITLE
LibBFGSCComparisonTest failures

### ISSUE THREAD

**Issue by anders9ustafsson** [accord-net/framework#39]
For a while now, 4 of the 7 unit tests in the `LibBFGSCComparisonTest` class,

* `ParameterBatchTest`
* `ParameterBatchTest2`
* `ParameterRangeTest`
* `ParameterTest1`

are failing with the following failure message:

> Assert.AreEqual failed. Expected: &lt;LBFGS_CONVERGENCE&gt;. Actual:&lt;LBFGS_SUCCESS&gt;.

For all but one failing tests the stack trace starts with the following line:

>    at Accord.Tests.Math.LibBFGSComparisonTest.compute(List`1 problems, LBFGSComparer cmp) in LibBFGSComparisonTest.cs: line 301

For the remaining failing unit test (`ParameterRangeTest`) this stack trace is displayed:

>    at Accord.Tests.Math.LibBFGSComparisonTest.ParameterRangeTest() in LibBFGSComparisonTest.cs: line 272

**NOTE!** These failures have been observed when running unit tests for the PCL version of *Accord.NET Framework* (I am currently having a few issues when trying to run main repository unit tests). Nevertheless, the code masses should be equivalent and I expect that the failures would show up even for the main repository.

Regards,
Anders @ Cureos

**Comment by cesarsouza** [comment]
Hi there,

I have been able to reproduce the issue after I upgraded to VS2013 and .NET 4.5, and I plan to solve it shortly. Thanks!
