### ISSUE TITLE
Add an Example for GrayLevelCooccurrenceMatrix Constructor

### ISSUE THREAD

**Issue by jalil92** [accord-net/framework#392]
Please add an example for GrayLevelCooccurrenceMatrix Constructor.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Imaging_GrayLevelCooccurrenceMatrix__ctor.htm

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
