### ISSUE TITLE
Add an Example for OneclassSupportVectorLearning(TModel, TKernel, TInput) Class

### ISSUE THREAD

**Issue by RichardLeeK** [accord-net/framework#397]
Please add an example for OneclassSupportVectorLearning(TModel, TKernel, TInput) Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_OneclassSupportVectorLearning_3.htm

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
