### ISSUE TITLE
PrincipalComponentAnalysis serialization error in v3.4.0

### ISSUE THREAD

**Issue by AndreiArdelean1** [accord-net/framework#398]
When trying to serialize a member of class PrincipalComponentAnalysis in Accord.Statistics version 3.4.0, I revive the error:

> Type 'System.Threading.CancellationToken' in Assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.

The error is not present in version 3.3.0

`Accord.IO.Serializer.Save(new Accord.Statistics.Analysis.PrincipalComponentAnalysis(), System.IO.Path.GetFullPath("a.txt"));`

**Comment by cesarsouza** [comment]
Many thanks for reporting the issue! I will commit a fix in the following minutes.

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
