### ISSUE TITLE
Unable to build 2.13.1

### ISSUE THREAD

**Issue by sekinan** [accord-net/framework#40]
Just downloaded latest version 2.13.1 and attempted to build using Visual Studio 2013. After conversion by VS to 2013 solution, fails to build successfully with 35 errors including:

	C#: Several methods are applicable to '(double[][])': 'Accord.Math.Matrix.ToMatrix<T>(T[])' and 'Accord.Math.Matrix.ToMatrix<T>(T[], bool)' and 'Accord.Math.Matrix.ToMatrix<T>(T[][])'	MatrixFormatter.cs	Accord.Math	334	35	C#	E:\Development\DevCsharp\Common\Accord.NET 2.13.1\Framework\Sources\Accord.Math\Formats\Base\MatrixFormatter.cs
There are multiple instances of the above error.

	C#: Unexpected end of expression	Tools.cs	Accord.Math	555	30	C#	E:\Development\DevCsharp\Common\Accord.NET 2.13.1\Framework\Sources\Accord.Math\Tools.cs
 Source:           Int32 i = *(Int32*)&f;

Also same error occurs in
Accord.Neuro.LevenbergMarquardtLearning.cs;
Accord.Neuro.ParallelResilientBackPropagationLearning.cs
in the Parallel.For construction

Any thoughts gratefully received.

**Comment by cesarsouza** [comment]
The project now supports VS2013 by default.
