### ISSUE TITLE
Can't load (.NET 3.5) SVM serialized using .SAVE in .NET4.5  

### ISSUE THREAD

**Issue by Houyi-88** [accord-net/framework#400]
Using VS2015, saved multiclass svm <wavelet> to file using .NET 4.5. 

Can't load from the same file into MONO .NET 3.5

Got very cryptic error messages (I recall something like...)
NullExeception, Parameter type, can't be null...
Exception thrown...binding error

This class uses a binding mechanism to automatically convert files saved using older versions of the framework to the new format. If a deserialization doesn't work, please fill in a bug report at https://github.com/accord-net/framework/issues 

I think my issue is the reverse. NEW version saved and read by OLDER version didn't work.

**Comment by Houyi-88** [comment]
VS2015 has a 'Unity .NET35' target. I rebuilt VS .NET45 with that .NET35 target selected. I stored a blank svm, wavelet object to file and was able to load it using MONO .NET35 without the previous error messages appearing.

I should try this with a full svm object before closing this issue and will try that soon.

**Comment by Houyi-88** [comment]
Was able to load 'full' svm object that contained data and was saved as described above.

**Comment by cesarsouza** [comment]
Hi Houyi,

Thank you very much for reporting the issue, investigating and finding a fix. Before the issue is closed, do you think I could ask more details in order to understand better what happened and how we could instruct new users in the future?

Can you please let me know why you were using it on Mono 3.5? In particular, were you trying to run it on Unity?

In order to load the object, have you called Serializer.Load from Mono to load an object that was created using Visual Studio/Microsoft .NET, and did it just work? Have you found any other problems loading objects to/from different framework versions?

Best regards,
Cesar

**Comment by Houyi-88** [comment]
Hello,

Yes, using it on Unity v5.4 (not sure what version of Mono). The problem is
trying to keep track  of all the various versions of accord.net dll's and
compatibility with Visual Studio, Mono, and Unity. The accord.net s/w is
changing rather rapidly,so it's a bit difficult to keep up with changes.

I created, saved svm object in visual studio 2015 and I believe that I was
using accord.net .net45 dlls (ver 3.3.0 i think). I used
Accord.IO.Serializer.Save<MulticlassSupportVectorMachine<Wavelet>>(svm,
path);

In unity, I used
Accord.IO.Serializer.load<MulticlassSupportVectorMachine<Wavelet>>(path);
This didn't work. I think because of dll mismatches. I switched to
...(stream) and still didn't work.

I aligned dll's using visual studio 'target' = unity .net35 full library. I
re-ran above load on an empty svm and it worked without error messages. I
re-ran load statement on an 'full' svm and was also able to load without
errors. So, it's working.

This is great software! Thanks. I think that I will be giving a
presentation soon about the accord.net framework to a big data Ai group.
Now that I have the SVM's working in VS2015, MONO and Unity, I definitely
will talk about that.

I'm trying to make a donation using paypal. I don't want to 'join' paypal
but if that's the only way, then I will do so. Keep up the good work!

Thanks,

Kevin

**Comment by Houyi-88** [comment]
Hello,

Got another issue with svm's using double[][] inputs, runs out of memory at
40k inputs (each double[9]). I tried to change to int[][] but get syntax,
compile errors :

        // 2-5-17, Kevin : try to make it use int[][] instead of double[][]
        // runs out of memory for larger data sets
        MulticlassSupportVectorMachine<Wavelet>
ksvm;                         // works up to 4k inputs
        // doesn't work
        //MulticlassSupportVectorMachine<Wavelet, int[][]>
ksvm;             //syntax errors

I'm also using the MSVM Learner<Wavelet>,
SequentialMinimalOptimization<Wavelet>() and would need those to be int[][]
compatible as well.

Where can I post this to get some help?

Thanks,

Kevin

**Comment by cesarsouza** [comment]
Hi Kevin,

Sorry for the delay in answering! Have you tried to set the [CacheSize property](http://accord-framework.net/docs/html/P_Accord_MachineLearning_VectorMachines_Learning_BaseSequentialMinimalOptimization_3_CacheSize.htm) of the SequentialMinimalOptimization class to a lower value, such as 2000? The cache size can be used to control the tradeoff between memory and speed when learning a support vector machine.

Regards,
Cesar

**Comment by Houyi-88** [comment]
Hello,

I reduced record size from 40k to 20k 'records' (actually double[20k][9]
and it ran : trained on 80%, tested on 20% with ZERO error! Saved and
loaded SVM into Mono/Unity (as .net35 target).

It would be great to try int[20k][9] as my input data is really in that
form and doesn't need the precision of double[][]. I would like to get to
int[100k][9] and maybe even int[350k][9] on my local desktop which only has
4gb of memory.

The multiclass svm constructor works with a generic <kernel> but doesn't
like <kernel, tinput> which is where I'm guessing that I could change from
the default input of  double[][] to int[][]. The SMO and Learner have a
similar constructor to change to int[][] but I'm having
similar syntax/compiler complaints.

 I will try your SMO suggestion as well.

Thanks,

Kevin

**Comment by cesarsouza** [comment]
Hi Kevin,

No worries, the problem is actually that the Wavelet class implements only the ```IKernel<double[]>``` interface but not the ```IKernel<int[]>```. I will commit a fix in the following minutes, as well as some unit tests to make sure your use case works.

In any case, to make sure the code will work in any computer with any amount of ram, it would be really necessary to control the CacheSize property according to the characteristics of the target computer. At worst, you can set it to -1 in order to disable the cache and use as few memory as possible (at the expense of longer training times).

Out of curiosity, may I ask what's your motivation behind using the Wavelet kernel? Did it work better for your particular problem? I haven't found many use cases where the Wavelet kernel would perform best, so I would be eager to know more about yours.

Regards,
Cesar

**Comment by Houyi-88** [comment]
That's funny about the wavelet kernel! I tried about 6 or 8 kernels prior
to it. All had very disappointing results. For my application specific
training data, previous kernels had correct predictions of only about 12%
using gaussian, polynomial, timewarp, chi squared (  i think 83% correct)
and a few more.

The wavelet kernel started at about 88% correct prediction. With input data
tweaks, got it to 96% then 98% and now 100% on training and test data when
split 80%/20% on up to 20k input records. I'm also making progress on HMM,
HCRF and KNN. As a word of caution, my methodology relies heavily on trial
and error. My data inputs may not be theoretically pure but they work in my
practical application.

I want to try an accord.net neural net next. There's some exciting
developments here in silicon valley by a new startup that's putting a
neural net 'engine' on a chip. I want to run an accord.net neural net
application on it hopefully within a few months. They only have a
networked, server based platform at the moment. Don't have a lot details
other than that their neural net engine can run user applications written
in c++.

Thanks again for the accord framework and your attention to this issue,

Kevin

**Comment by Houyi-88** [comment]
>Out of curiosity, may I ask what's your motivation behind using the
Wavelet kernel? Did it work better for your particular problem? I haven't
found >many use cases where the Wavelet kernel would perform best, so I
would be eager to know more about yours.

Hit a roadblock with <wavelet> kernel. It run time errors at 20k+ inputs.
On closer inspection, it may not be appropriate for my specifice
application. I think the error is due to the fact that it was producing 29K
support vectors for just 20K inputs. Also, I assumed that the
wavelet.translation and wavelet.dialation was part of the machine learning
and SMO process but I think that is not correct. Those parameters are
fixed. I tried adjusting them but that didn't help. So, it's seems to work
more like just a dumb filter. The user would need to make it smart with
manual/programmatic translation, dialations.

This process made me think about my data and input vectors. I changed them
and went back to the basics using a <linear> kernel. I get 85-100% correct
on training and similar for the test data on a small dataset. Hopefully,
I'm on the right track now to a usable svm for my application.

A big help would be easily graphing the data with all the required info to
make informed adjustments (like dumping a kernel). For example, I don't
know how to plot the support vector. Is there a way to do that or something
helpful like that? More graphing example code would be greatly appreciated.

Thanks,

Kevin

**Comment by Houyi-88** [comment]
So many variables, so little time.

Anyway, <linear>, <polynomial> and <wavelet> all work with new input data
format. <wavelet> seems to work best. I changed CacheSize to 1000 and that
really helped. Created svm<wavelet> for 20k records (with cachesize =
1000). Saved, loaded into Unity and it seems to make sense in that
application.

Regards,

Kevin
