### ISSUE TITLE
Face Detection issue!

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#413]
Hi, do you have a face detection with web camera?
I found a sample in the accord.net folder but the face detection is not good.

I run the sample with my sister, face the web camera then detects only 1 face, if I move then the rectangle transfer to the other face, randomized and not clear face detection on live camera.

do you have a very good face detection? that cuts the rectangle face and make it gray-scale in the new image bitmap?

I'm planning to port from EMGU to Accord.NET if this functions are available.
1. Real good simple sample of face detection that cuts face to gray-scale into another image bitmap.
2. Add Face Recognizer, like EMGU has eiginefaceRecognizer, fisherfaceRecognizer, lbphfaceRecognizer.

as of Now, I used EMGU for face detection and recognition, and for Audio Visual I used Accord.Net

thank you for this wonderful .net framework.

**Comment by cesarsouza** [comment]
Hi there!

Thanks for opening the issue! The framework uses the Viola-Jones method for recognizing faces. This is the same method available in OpenCV (and thus the same in EMGU.NET). 

Please, may I ask if the problem you experienced was when detecting the face, or was it when tracking the face across different frames? I am not quite sure I understood the sample case you described.

The Face tracking sample application focus on only one face. If you would like to detect multiple faces, then please take a look at the [Face detection](https://github.com/accord-net/framework/tree/master/Samples/Vision/Face%20detection%20(Viola-Jones)) sample application. It should be able to detect multiple frames at the same time.

Regards,
Cesar

**Comment by blaisexen** [comment]
The Face tracking sample application focus on only one face, sorry I was expecting a multiple faces from the sample.
so I used, Viola-Jones, the problem is when I set size to 640x480 it was so slow, even 320x240

`using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Drawing.Imaging;
using System.Threading;

using Accord.Imaging.Filters;
using Accord.Vision.Detection;
using Accord.Vision.Detection.Cascades;
using Accord.Vision.Tracking;
using Accord.Imaging;
using Accord.Math.Geometry;
using Accord.Video;
using Accord.Video.DirectShow;


namespace voiceemotiondetection
{
    public partial class Form1 : Form
    {
        
        // window marker
        RectanglesMarker marker;

        FilterInfoCollection videoDevices;
        private string ldevice;

        // opened video source
        private IVideoSource videoSource = null;

        // object detector
        HaarObjectDetector detector;

        public Form1()
        {
            InitializeComponent();
            videoSourcePlayer.NewFrame += new Accord.Controls.VideoSourcePlayer.NewFrameHandler(this.videoSourcePlayer_NewFrame);

            HaarCascade cascade = new FaceHaarCascade();
            detector = new HaarObjectDetector(cascade,25, ObjectDetectorSearchMode.NoOverlap, 1.1f, ObjectDetectorScalingMode.SmallerToGreater);
            detector.UseParallelProcessing = true;
            detector.Suppression = 2;
            
            /*
            detector.SearchMode = ObjectDetectorSearchMode.NoOverlap;
            detector.ScalingMode = ObjectDetectorScalingMode.SmallerToGreater;
            detector.ScalingFactor = 1.5f;
            */

            //if selected at startup
            uselocalcamera(0);
        }

        private void uselocalcamera(int camnum)
        {
            try
            {
                videoDevices = new FilterInfoCollection(FilterCategory.VideoInputDevice);
                if (videoDevices.Count == 0)
                    throw new ApplicationException();
                ldevice = videoDevices[camnum].MonikerString;
                selectlocalvideodevice(ldevice);
            }
            catch (ApplicationException)
            {
            }
        }


        private void selectlocalvideodevice(string dev)
        {
            // create video source
            VideoCaptureDevice videoSource = new VideoCaptureDevice(dev);
            // set frame size
            videoSource.VideoResolution = selectResolution(videoSource);
            // open it
            OpenVideoSource(videoSource);
        }


        // Close current video source
        private void CloseVideoSource()
        {
            // stop current video source
            videoSourcePlayer.SignalToStop();

            // wait 2 seconds until camera stops
            for (int i = 0; (i < 50) && (videoSourcePlayer.IsRunning); i++)
            {
                Thread.Sleep(100);
            }

            if (videoSourcePlayer.IsRunning)
                videoSourcePlayer.Stop();
        }


        // Open video source
        private void OpenVideoSource(IVideoSource source)
        {
            // close previous video source
            CloseVideoSource();

            // start new video source
            videoSourcePlayer.VideoSource = source;
            videoSourcePlayer.Start();

            videoSource = source;

        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            CloseVideoSource();
        }

        private static VideoCapabilities selectResolution(VideoCaptureDevice device)
        {
            foreach (var cap in device.VideoCapabilities)
            {
                if (cap.FrameSize.Height == 480)
                    return cap;
                if (cap.FrameSize.Width == 640)
                    return cap;
            }
            return device.VideoCapabilities.Last();
        }

        // New frame received by the player
        private void videoSourcePlayer_NewFrame(object sender, ref Bitmap image)
        {
                    UnmanagedImage im = UnmanagedImage.FromManagedImage(image);
                    ResizeNearestNeighbor resize = new ResizeNearestNeighbor(640, 480);
                    UnmanagedImage downsample = resize.Apply(im);

                    Rectangle[] regions = detector.ProcessFrame(downsample);

                    if (regions.Length > 0)
                    {
                        marker = new RectanglesMarker(regions, Color.Fuchsia);
                        marker.ApplyInPlace(im);
                        image = im.ToManagedImage();
                    }
        }



    }
}
`

and Yes the Voila-Jones detects multiple faces even with web camera, but too slow.


Ok,
please if you can help us, 

Can you provide a simplest sample windows form code that uses the fastest method to get multiple faces from camera and then crop the faces, please send a link to download that sample.

Is it possible that you can Add Face Recognizer, like EMGU has eiginefaceRecognizer, fisherfaceRecognizer, lbphfaceRecognizer?
were using Emgu.Net because of Face Recognizer also.

One other thing so I may not open another issue post, I would like to ask this.
We are making or detecting sound signals or events like dog-bark,gun-shot,motor-crossing,train-crossing from Mic as Input.
We used ComplexSignal.
        private List<ComplexSignal> sample; //we used variables like power,channel,freq
then compare it to the Mic-Input power,channel,freq

`        
//USING MIC-INPUT
private void source_NewFrame(object sender, NewFrameEventArgs eventArgs)
        {
            Signal sourceSignal = eventArgs.Signal;
            sourceSignal.CopyTo(current);
            if (recording) encoder.Encode(sourceSignal);
            updateWaveform(sourceSignal.ToFloat(), sourceSignal.Length);

            //Create Hamming window so that signal will fit into power of 2:           
            RaisedCosineWindow window = RaisedCosineWindow.Hamming(1024);

            // Splits the source signal by walking each 512 samples, then creating 
            // a 1024 sample window. Note that this will result in overlapped windows.
            Signal[] windows = sourceSignal.Split(window, 512);

            // You might need to import Accord.Math in order to call this:
            ComplexSignal[] complex = windows.Apply(ComplexSignal.FromSignal);

            // Forward to the Fourier domain
            //complex.ForwardFourierTransform(); //Complete!        


            // We can start by converting the audio frame to a complex signal
            ComplexSignal csignal = complex[0];// ComplexSignal.FromSignal(sourceSignal);

            // If its needed,
            if (window != null)
            {
                // Apply the chosen audio window
                csignal = window.Apply(csignal, 0);
            }

            // Transform to the complex domain
            //csignal.ForwardFourierTransform();
            csignal.ForwardHilbertTransform();

            // Now we can get the power spectrum output and its
            // related frequency vector to plot our spectrometer.

            //MAYBE USING THIS VARIABLES TO HMM
            Complex[] channel = csignal.GetChannel(0);
            double[] power = Accord.Audio.Tools.GetPowerSpectrum(channel);
            double[] freqv = Accord.Audio.Tools.GetFrequencyVector(csignal.Length, csignal.SampleRate);

            power[0] = 0; // zero DC
            float[] g = new float[power.Length];
            for (int i = 0; i < power.Length; i++)
                g[i] = (float)power[i];

            // Adjust the zoom according to the horizontal and vertical scrollbars.
            chart1.RangeX = new DoubleRange(freqv[0], freqv[freqv.Length - 1] / 3);
            chart1.RangeY = new DoubleRange(0f, Math.Pow(10, -9));
            chart1.UpdateWaveform("fft", g);
        }

//
//THEN A FUNCTION TO COMPARE MULTIPLE WAVE-FILE FROM MIC-INPUT
//
`
Are we doing right or wrong?
Can you suggest us what is really the methods of this using Accord.Net?
