### ISSUE TITLE
XCeed reference in Accord.NET distribution - proprietry (product)!

### ISSUE THREAD

**Issue by jonmelvin** [accord-net/framework#414]
Accord.NET sample DeepLearning uses proprietary XCeeed library.  Not a public domain project?

**Comment by cesarsouza** [comment]
Hello Jon,

Many thanks for the question! The deep learning sample application uses the PropertyGrid from the [Extended WPF Toolkit](http://wpftoolkit.codeplex.com/) which is open source and [available on NuGet](https://www.nuget.org/packages/Extended.Wpf.Toolkit/)). 

Regards,
Cesar

**Comment by jonmelvin** [comment]
Thank you!
Jon
