### ISSUE TITLE
Add an Example for VideoFileWriter.WriteAudioFrame Method

### ISSUE THREAD

**Issue by farrukh54** [accord-net/framework#418]
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Accord.Audio.Windows;
using Microsoft.Xna.Framework.Audio;
using AForge.Video.DirectShow;
using AForge.Video;
using Accord.Video.FFMPEG;
//using Accord.Controls.Audio;
using System.IO;
using System.IO.IsolatedStorage;
using System.Threading;
using System.Runtime.InteropServices;
using System.Media;

namespace AForgenetScreenRecorder
{
    public partial class Form1 : Form
    {
        ScreenCaptureStream stream;
        Rectangle screenArea;
        VideoFileWriter writer;
      //  Mp3SoundCapture c = new Mp3SoundCapture();
        Bitmap bitmap;
        Accord.Audio.AudioSourceMixer audio;
        byte[] bffr;
        private const string FILE_NAME = "xna.ibo";
        [DllImport("winmm.dll", EntryPoint = "mciSendStringA", CharSet = CharSet.Ansi, SetLastError = true, ExactSpelling = true)]
        private static extern int mciSendString(string lpstrCommand, string lpstrReturnString, int uReturnLength, int hwndCallback);

        public void audioFunction()
        {
            mciSendString("open new Type waveaudio Alias recsound", "", 0, 0);
            mciSendString("record recsound", "", 0, 0);
        }
        public Form1()
        {
            InitializeComponent();
            writer = new VideoFileWriter();
            writer.Open("Mp4Video2.mp4", re.Width, re.Height, 100, VideoCodec.MPEG4, 50000000);
           
            audio = new Accord.Audio.AudioSourceMixer();
           MessageBox.Show( audio.Source.ToString());
          // Microphone mic = new Microphone();
        }
        Rectangle re = Screen.PrimaryScreen.Bounds;
        private void streamFunction()
        {
            screenArea = Rectangle.Empty;
            foreach (System.Windows.Forms.Screen screen in
                      System.Windows.Forms.Screen.AllScreens)
            {
                screenArea = Rectangle.Union(screenArea, screen.Bounds);
            }
            // create screen capture video source
            stream = new ScreenCaptureStream(screenArea);
            stream.NewFrame += new NewFrameEventHandler(video_NewFrame);
          }
        byte[] sound = new byte[30];
        private void button1_Click(object sender, EventArgs e)
        {
            MessageBox.Show("One time Working");
            streamFunction();

            // set NewFrame event handler
            audioFunction();
            
            stream.Start();
            
           // audio.Start();
            // ...
            // signal to stop
        
            // ...
        }
        private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
        {
            try {
                // get new frame
                bitmap = (Bitmap)eventArgs.Frame.Clone();
                /// bffr = (byte)eventArgs.Frame.Clone();
                mciSendString("save recsound D:\\result.wav", "", 0, 0);
                mciSendString("close recsound ", "", 0, 0);
                // aud

                //  mciSendString("save recsound D:\\result.wav", "", 0, 0);
                bffr = File.ReadAllBytes("D:\\result.wav");
              
                for (int i = 1; i < 30; i++)
                {
                    writer.WriteVideoFrame(bitmap);
                    writer.WriteAudioFrame(bffr);
                }

                pictureBox1.Image = bitmap; }
            catch(Exception ex) { MessageBox.Show(ex.Message); }
            // process the frame
        }
       
     
        private void button2_Click(object sender, EventArgs e)
        {
            audio.Stop();
            mciSendString("save recsound D:\\result.wav", "", 0, 0);
            mciSendString("close recsound ", "", 0, 0);

            //bffr = File.ReadAllBytes("D:\\123.mp3");
            //for (int j = 1; j <= 100; j++)
            //{
                writer.WriteAudioFrame(bffr);
            //}
            MessageBox.Show("Stream Stops");
            stream.SignalToStop();
        }
        private void Form1_FormClosed(object sender, FormClosedEventArgs e)
        {

            Application.Exit();
        }
        int abc = 0;
        private void timer1_Tick(object sender, EventArgs e)
        {
            abc++;
        }
    }

}
i use that piece of code.Video has been saved efficiently but the audio has been not store.
If you have any solution then share it or either give me another way so that i can complete my work ASAP.

**Comment by enginates** [comment]
@cesarsouza you added pending-release label but where is the documentation? i search but could not find single example of usage of mp3 or wav file read and write to video.

You guys made huge work but without doc it is hard to use it.
