### ISSUE TITLE
Add an Example for Combinatorics.Subsets(T) Method (ISet(T), Int32, Boolean)

### ISSUE THREAD

**Issue by gfroza** [accord-net/framework#419]
Please add an example for Combinatorics.Subsets(T) Method (ISet(T), Int32, Boolean).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Math_Combinatorics_Subsets__1_1.htm

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
