### ISSUE TITLE
Add an Example for DecisionStump.Learn Method

### ISSUE THREAD

**Issue by ashiknc** [accord-net/framework#422]
Please add an example for DecisionStump.Learn Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_Boosting_Learners_DecisionStump_Learn.htm

**Comment by cesarsouza** [comment]
Examples have been added to the [main documentation page for the DecisionStump class](http://accord-framework.net/docs/html/T_Accord_MachineLearning_Boosting_Learners_DecisionStump.htm) in release 3.8.0..
