### ISSUE TITLE
Add an Example for AdaBoost(TModel) Class

### ISSUE THREAD

**Issue by Yandychang1** [accord-net/framework#424]
Please add an example for AdaBoost(TModel) Class.

Is it possible to have a sample code on using boost, adaboost with random forrests, trees, and  KNNs?

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_Boosting_AdaBoost_1.htm

**Comment by cesarsouza** [comment]
Duplicate of #415
