### ISSUE TITLE
Create LocalBinaryPatternDetector for BagsOfVisualWord > Because Errors in Array

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#425]
var kmodes = new KModes<double>(numberOfWords, new Hamming());
var detector = new LocalBinaryPattern(); //NOT A DETECTOR
// Create bag-of-words (BoW) with the given algorithm
 var freakBow = new BagOfVisualWords<FeatureDescriptor>(detector, kmodes);

// Compute the BoW codebook using training images only
freakBow.Compute(originalTrainImages.Values.ToArray()); //ARRAY ERROR HERE

and Maybe the Detector can be used not only in pattern_detection but includes face_recognition that recognized the name or id of the face.

**Comment by fsteveb** [comment]
BaseBagOfVisualWords<BagOfVisualWords<FastRetinaKeypoint, byte[]>, FastRetinaKeypoint, byte[], IClusteringAlgorithm<byte[]>, IFeatureDetector<FastRetinaKeypoint, byte[]>>.Compute(Bitmap[])' is obsolete: 'Please use the Learn() method instead.

**Comment by blaisexen** [comment]
hi,
I don't understand what your talking about,  .Compute() is Different from .Learn(),

.Learn() is applied when the object is already cast or assigned.
.Compute() is used when you assigned an array of objects.

and why don't you show your code solution using localbinarypattern_detector with bagsofvisualwords.

thank you for the comment.

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Just to give a quick answer before I arrive home, if I remember correctly this issue has been fixed in the development branch but has not yet been included in a release. 

I will recheck if this is the case and reply. And many thanks for opening the issue!

**Comment by blaisexen** [comment]
Hello Cesar,

Ok, can you just put the answer here? maybe a line of code to correct the issue? or it's a huge work?
anyway I'll wait, please.

and really thank you for this framework, I have donated to Emgu because I had done projects with them, and I will also donate soon if my current project will be done after.

I also donated to openCv, and I will always donate after a project has been done from there framework or api.

**Comment by blaisexen** [comment]
I will donate after this project end as I always do to emgu.net and opencv.

because I'm really planning to port all my projects from emgu.net to accord.net

**Comment by blaisexen** [comment]
I've used the Accord.Net 3.4.0 LocalBinaryPattern.cs BUT error in  "public object Clone()" so I recompile it, then test to return null, but errors on BagOfVisualWords "public TModel Learn(Bitmap[] x, double[] weights = null)"

I don't know what next to do

**Comment by blaisexen** [comment]
I guess that was just Ok!

**Comment by cesarsouza** [comment]
Hi, sorry for the delay in answering! In the end I didn't manage to answer in the previous days, sorry about that. I have just committed a fix for using LBP with BoW together with the fix for Clone().

**Comment by blaisexen** [comment]
hi,
it's Ok, I only used or test localbinarypattern.

but I hope your last message will be on the other post I ask about speech expressions if possible.
thank you,
