### ISSUE TITLE
Adjust Face Detection not properly align, Other Configuration is Where?

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#426]
I used this code: 
BUT the alignment of the rectangle in the face is sometimes correct and sometimes not.
The rectangle is not doing constant alignment over the face.

I have also use old emgu.net 2.4.X But the rectangle face alignment is good, 
I used "lbpcascade_frontalface.xml", its only 51,856 bytes, so it's fast.

> What else configuration for face alignment to look for using accord.net?

`
       public MainForm()
        {
            InitializeComponent();
            videoSourcePlayer.NewFrame += new Accord.Controls.VideoSourcePlayer.NewFrameHandler(this.videoSourcePlayer_NewFrame);

            HaarCascade cascade = new FaceHaarCascade();
            
            detector = new HaarObjectDetector(cascade,32, ObjectDetectorSearchMode.Average, 1.5f, ObjectDetectorScalingMode.GreaterToSmaller);
            detector.UseParallelProcessing = false;
            detector.Suppression = 0;
            detector.Channel = 0;
            detector.MinSize = new Size(32, 32);
            detector.MaxSize = new Size(200,200);
            

            //if selected at startup
            uselocalcamera(0);

        }

        // New frame received by the player
        private void videoSourcePlayer_NewFrame(object sender, ref Bitmap image)
        {
            UnmanagedImage im = UnmanagedImage.FromManagedImage(image);

            float xscale = image.Width / 160;
            float yscale = image.Height / 100;

            ResizeNearestNeighbor resize = new ResizeNearestNeighbor(160, 100);
            UnmanagedImage downsample = resize.Apply(im);

            Rectangle[] regions = detector.ProcessFrame(downsample);
                if (regions.Length > 0)
                {
                    Rectangle window = new Rectangle((int)((regions.X + regions.Width / 2f) * xscale), (int)((regions.Y + regions.Height / 2f) * yscale), 1, 1);
                    window.Inflate((int)(0.4f * regions.Width * xscale), (int)(0.4f * regions.Height * yscale));

                    //DRAW FACE RECTANGLE TO VIDEO SOURCE
                    marker = new RectanglesMarker(window);
                    marker.MarkerColor = Color.DeepSkyBlue;                    
                    marker.ApplyInPlace(im);
                    image = im.ToManagedImage(); //RETURN THIS IMAGE WITH MARKER
                }
        }
`

**Comment by cesarsouza** [comment]
Hi there,

Have you tried using SmallerToGreater instead of GreaterToSmaller?

Also, since it seems you are processing a video, you could try averaging the rectangles in consecutive frames. It might also be interesting to inspect emgu/opencv source code to see what they are doing differently and see if we could also implement it here.

Regards,
Cesar

**Comment by blaisexen** [comment]
Ok,

It's much better when you see how I described it.
I will send a link download file of emgu.opencv.net and accord.net, 
so you can deeply understand the possible solution for accord.net,

thank you

**Comment by blaisexen** [comment]
The SmallerToGreater produces false random small rectangle marks, but much smoother moment than GreaterToSmaller.

GreaterToSmaller keeps false rectangle silent but moves fast.

So, I think I'll just play this for a while,

thank you for the comment.
