### ISSUE TITLE
Add an Example for GeneralConfusionMatrix Constructor (Int32, Int32[], Int32[])

### ISSUE THREAD

**Issue by bogdan4ce** [accord-net/framework#430]
Please add an example for GeneralConfusionMatrix Constructor (Int32, Int32[], Int32[]).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Analysis_GeneralConfusionMatrix__ctor_1.htm

**Comment by cesarsouza** [comment]
Examples have been added to the [main documentation page for the GeneralConfusionMatrix class](http://accord-framework.net/docs/html/T_Accord_Statistics_Analysis_GeneralConfusionMatrix.htm) in release 3.8.0.
