### ISSUE TITLE
How to change video resolution of local video capture device in MotionDetection sample

### ISSUE THREAD

**Issue by przemo1983** [accord-net/framework#435]
Hi.

I tried to change video resolution of  local video capture device in my PC to 1920x1080 but I cannot.
At an attmept to change this:

    videoSource.VideoResolution.FrameSize.Height = 1080;

I got the error about readonly field. I see the same info in documentation.

Is there any way to change input device resolution before starting capturing data?

**Comment by blaisexen** [comment]
The answer:
```
            foreach (var cap in device.VideoCapabilities)
            {
                if (cap.FrameSize.Height == 1080)
                    return cap;
                if (cap.FrameSize.Width == 1920)
                    return cap;
            }
```
Good Luck!

**Comment by przemo1983** [comment]
Thank you very much.

It works now. :)
