### ISSUE TITLE
Add an Example for VideoCaptureDevice.DesiredFrameSize Property

### ISSUE THREAD

**Issue by murtipan** [accord-net/framework#439]
Please add an example for VideoCaptureDevice.DesiredFrameSize Property.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/P_Accord_Video_DirectShow_VideoCaptureDevice_DesiredFrameSize.htm

**Comment by blaisexen** [comment]
I think you can find the answer here:
[(https://github.com/accord-net/framework/issues/435#issuecomment-280925919)]

because DesiredFrameSize is obsolete, then use VideoCapabilities to set the Resolution.

close this issue if you think its the answer of your question,
Good Luck
