### ISSUE TITLE
BagOfWords for audio signals

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#440]
//ERROR, BYPASS TO ANOTHER CODE....
..
IBagOfWords<Signal> bow;
...
double[] featureVector = (bow as ITransform<Signal, double[]>).Transform(emots.emotsignal);

or we are doing bad?

**Comment by blaisexen** [comment]
//
BinarySplit binarySplit = new BinarySplit(1); //ERRORS IF MORE THAN 1, I HAVE ONLY 30 SAMPLES
KMeansClusterCollection clustering = binarySplit.Learn(emotdouble.ToArray());
//ERROR HERE, CODE JUMPS OUT IN THIS LINE....
double[] xfeatureVector = (clustering as ITransform<double[], double[]>).Transform(emotdouble[0]);
//

Well I don't know if it's an Issue or Not, so I'll guess just I'm waiting for a comment, BUT so sad there are only few who uses Accord.Net to Know it!

**Comment by cesarsouza** [comment]
Hi there,

Are you trying to create a Bag-of-Words model for audio signals (as you have specified the Signal class as the generic parameter of the ITransform)? If yes, then unfortunately the project doesn't offer support for this (at least not yet). 

It should be possible to create an implementation for this by taking inspiration from the [BagOfVisualWords](https://github.com/accord-net/framework/blob/master/Sources/Accord.Vision/Accord.Imaging/BaseBagOfVisualWords%605.cs) class (that works for images) and try to adapt it for audio signals. It would also be necessary to come with some architecture for specifying audio feature extractors (such as the [IFeatureDetector](https://github.com/accord-net/framework/blob/master/Sources/Accord.Imaging/Interest%20Points/Base/IFeatureDetector.cs) interfaces).

Regards,
Cesar

**Comment by blaisexen** [comment]
yes, I am.

Ok, I understand.

You mean the bagofwords is only for bagofvisualwords that works for images ONLY?

so, I can't use bagofwords for Signal processing?

I hope I understand what you meant. let me read it back again...

or can't you write a short pseudo code, or small lines of sample?

**Comment by cesarsouza** [comment]
Not necessarily by converting signals to Bitmap, but a feasible start would be to copy and paste the BagOfVisualWords code into a, let's say, BagOfAudioWords and replace every occurrence of "Bitmap" with "Signal", and adapt the code as needed.

However, if you are not very familiar with the BagOfVisualWords class, it may be easier for you to just code the bag of words pipeline (extract features -> cluster -> transform signals into histograms using the clusters) directly, without trying to adapt any of the BagOfVisualWords classes.

May I ask what audio features are you extracting? Have you implemented a audio feature extractor such as MFCC?

Regards,
Cesar

**Comment by blaisexen** [comment]
> or I think to make an implementation BagOfVisualWords(that works for Signal)
that's right,

Ok,
I'm extracting like the facial emotions expression, sadhappyangrysurprised,disgust,etc...

?

**Comment by cesarsouza** [comment]
I am not sure I understand. The Signal class is for dealing with audio files, so I am not very sure how they could be used to represent facial emotions. Can you please describe a bit more what you are trying to achieve so I can try to tell you what to use?

**Comment by blaisexen** [comment]
> BagOfAudioWords and replace every occurrence of "Bitmap" with "Signal", and adapt the code as needed.

I think I'm gonna try this, thank you for that info... even I'm not familiar....

**Comment by blaisexen** [comment]
i meant to identify sad-happy-angry... etc... for speech?

**Comment by blaisexen** [comment]
I don't meant facial, I said I'm extracting LIKE facial emotion expression, for speech only.

**Comment by cesarsouza** [comment]
Thanks for the clarification! So I was going to mention that before you can apply bag-of-words, or even cluster your audio signals, you need first to extract fixed-length audio features from them. One type of those fixed-length features are called MFCCs. 

I am mentioning this because the BagOfVisualWords classes rely on the IFeatureDetector interface, which may as well need to be adapted for audio (and it will depend on which method for audio feature extractor you are currently using).

Regards,
Cesar

**Comment by blaisexen** [comment]
I doubt this can be done with ImpulseGenerator also? because it says "Impulse Train Signal Generator"

**Comment by blaisexen** [comment]
I think the audio feature extractor one of them is the wave decoder you meant.

I will try to implement your thoughts,

thank you

**Comment by cesarsouza** [comment]
A Bag-of-Audio-Words implementation will be included in the next release.

**Comment by cesarsouza** [comment]
An [example for audio classification using a Bag-of-Audio-Words approach and the MFCC class](http://accord-framework.net/docs/html/T_Accord_Audition_BagOfAudioWords.htm) has been added in the 3.8.0 release.

**Comment by blaisexen** [comment]
What a surprised!
thank you so much...

be using this soon, :dancer:
