### ISSUE TITLE
Add an Example for MultinomialLogisticRegression.Compute Method (Double[][])

### ISSUE THREAD

**Issue by innea55** [accord-net/framework#443]
Please add an example for MultinomialLogisticRegression.Compute Method (Double[][]).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Models_Regression_MultinomialLogisticRegression_Compute_1.htm

**Comment by cesarsouza** [comment]
This method is obsolete. Please use the .Probabilities() method of the MLR instead.
