### ISSUE TITLE
Is there any planned/scheduled date for the next release? Or any other future release...

### ISSUE THREAD

**Issue by jagbarcelo** [accord-net/framework#447]
Just that. I think that having a statement somewhere telling your users/followers when the next release will be (or at least is expected) would be of much help.

Thanks.

**Comment by cesarsouza** [comment]
Hi @jagbarcelo 

A new pre-release package is about to be released in a few days. I agree that there could have a place with a schedule for the next releases, but it really depends on the priority of each fixes/improvements they will contain.

I will update it here as soon as the new pre-release is uploaded to NuGet.

Regards,
Cesar

**Comment by cesarsouza** [comment]
A new pre-release package has just been made available (v.3.4.2-alpha).
