### ISSUE TITLE
Add an Example for SimpleShapeChecker Class

### ISSUE THREAD

**Issue by HNeukermans** [accord-net/framework#449]
Please add an example for SimpleShapeChecker Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Math_Geometry_SimpleShapeChecker.htm

**Comment by cesarsouza** [comment]
Hi @HNeukermans,

Sorry for the long delay in finally reaching to this issue. The SimpleShapeChecker class already has an example in its documentation page. If you would like to see an example for a particular scenario, please re-open the issue with more details.

Thanks!

Regards,
Cesar
