### ISSUE TITLE
lbp blocksize and cellsize issue

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#452]
//IT OK
var surfBow = new BagOfVisualWords<FeatureDescriptor>(new LocalBinaryPattern(10, 10, false), new BinarySplit(10));

//NOT OK
var surfBow = new BagOfVisualWords<FeatureDescriptor>(new LocalBinaryPattern(12, 12, false), new BinarySplit(10));

I really doubt there is really something wrong with this lbp, too slow, lbp supposed to be so fast.

as I tested all the detector, lbp is the very slowest among them.

so I open again this issue, I guess there's really something to fix inside lbp class.

**Comment by blaisexen** [comment]
i guess i have to much question!

**Comment by cesarsouza** [comment]
Hi @blaisexen,

First of all, thanks for opening the issue! Please don't close the issues before I've got the chance to review them. You are right, there must be something wrong with the current LBP implementation and it has to be looked up. Unfortunately, I don't have enough time to review it right now, but a review by someone external to the framework (e.g. you 😛, or anyone else that would like to join this discussion) would be more than welcome!

Regards,
Cesar

**Comment by blaisexen** [comment]
Hi @cesarsouza 

I will closed this issue but stay open in connection from this post 
https://github.com/accord-net/framework/issues/458

thank you for your positive mind, you understand everyone here, surely this framework will long live useful to everyone with your name.

I have not donated yet!, I will soon and more in every usage from this framework ;)
