### ISSUE TITLE
NumOfWords Issue

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#453]
How to Calculate NumOfWords?

Because I noticed NumOfWords depends on the size of the image, errors if not around the range, and NumOfWords also depends on number of images.

Do we have a formula to Set NumOfWords, so in-case hundreds of image inputted OR size of images differ  OR images at same size.

Really needed to know it.

thank you

**Comment by cesarsouza** [comment]
Hi @blaisexen,

The number of words is simply the number of clusters in the clustering algorithm that will be applied to your data. It really depends on the application, but for large image recognition tasks this number can range from 1000 to 8000.

**Comment by blaisexen** [comment]
Glad to see you,

I understand,

thank you
