### ISSUE TITLE
KMeansClusterCollection  and Svm does not give result, am I doing wrong, result not changing

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#457]
//TRAIN
KMeansClusterCollection clustering;//Gloval Variable

//KMeans kmeans = new KMeans(10);
BinarySplit binarySplit = new BinarySplit(10);
clustering = binarySplit.Learn(emotvalues2.ToArray()); //Learn All Needed

foreach (var emots in listmyemotsignal)
{
double[] featureVector = (clustering as ITransform<double[], double[]>).Transform(emots.emotsignaltodouble);
emotvalues.Add(featureVector);
emotclassnums.Add(emots.emotknum);
}
ksvm = svmteacher.Learn(emotvalues.ToArray(), emotclassnums.ToArray());//Learn Transformed

//DECIDE
double[] input = (clustering as ITransform<double[], double[]>).Transform(power);
double kprob = ksvm.Probability(input);
int kactual = ksvm.Decide(input);
**Label1.Text = kprob .ToString();**

KMeansClusterCollection  and Svm does not give result, am I doing wrong, result not changing,
always stay 0.041249870

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Your SVM has a single input, that is the integer label attributed by the clustering algorithm. Most definitely this is not what you may want to do. 

Instead, you should extract patches from your test image, cluster those patches and accumulate the class labels for those patches into a histogram. Then, you can present this histogram to be classified by the SVM. This is how Bag-of-Words works.

I hope it helps!

**Comment by blaisexen** [comment]
//DECIDE
double[] input = (clustering as ITransform<double[], double[]>).Transform(power);

hi,
the Transform(power) is from here:
double[] power = Accord.Audio.Tools.GetPowerSpectrum(channel);

the code above I'm doing is for audio emotion feature,

I have tried many of your SVM samples and succeed on many test,
But I can't get through comparing audio signals from mic.

clustering = binarySplit.Learn(emotvalues2.ToArray());
I used that because the emotvalues2.ToArray() is must in .Learn parameter, because I don't know to use .Learn(ComplexSignalX.ToArray()) 

because I have 2 to 4 seconds .WAV file(emot features) to compare using SVM from my Microphone.

I still have to figure it out what class or interface to used to develop .Learn(.....

**Comment by blaisexen** [comment]
thank you, closing issue
