### ISSUE TITLE
Add an Example for TwoWayAnova Constructor (Double[][][], TwoWayAnovaModel)

### ISSUE THREAD

**Issue by chandan123sahoo** [accord-net/framework#476]
Please add an example for TwoWayAnova Constructor (Double[][][], TwoWayAnovaModel).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Testing_TwoWayAnova__ctor_1.htm

**Comment by cesarsouza** [comment]
Examples for [Two-Way ANOVA have been added to the main documentation page for the TwoWayAnova class](http://accord-framework.net/docs/html/T_Accord_Statistics_Testing_TwoWayAnova.htm).
