### ISSUE TITLE
Really something weird about BOW and others(SMO) or SVM itself(not sure)

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#480]
I test all the samples specially the bow with svm using classification methods,

images are pick randomized per run,

i test many times, some images stay for train or test,

but, it randomized failure and success, even that image was success previously or failed previously,

there is really something wrong with the framework.

in other words, the classification is not stable, even images are same, etc...

**Comment by blaisexen** [comment]
i think I'm not only the one who recognized this problem,
https://github.com/accord-net/framework/issues/487

**Comment by cesarsouza** [comment]
Coming back to this issue after almost an year of development, I have to say that the SVMs are indeed fine. There were however some issues with the computation of BoW using multi-threaded that had been fixed some months ago (#549, #769, and unreferenced updates in releases 3.5.0, 3.6.0).

**Comment by blaisexen** [comment]
thanks for answering :dancer:
