### ISSUE TITLE
Add an Example for LibSvmModel.Save Method (String)

### ISSUE THREAD

**Issue by 864258496** [accord-net/framework#486]
Please add an example for LibSvmModel.Save Method (String).

            foreach (double m in newksvm.Weights)
            {
                Console.WriteLine("newksvm.Weights = " + m);
            }
            newksvm.Save("D:\\SVMs\\test00");               
            
            var load = LibSvmModel.Load("D:\\SVMs\\test00");
            foreach (double m in load.Weights)
            {
                Console.WriteLine("load.Weights = " + m);
            }

save() and load() values are not equal 

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_IO_LibSvmModel_Save_1.htm

**Comment by cesarsouza** [comment]
Fixed in 3.8.0. Examples on [how to save a machine in LibSVM format have been added to the main documentation page for the LibSvmModel class](http://accord-framework.net/docs/html/T_Accord_IO_LibSvmModel.htm).
