### ISSUE TITLE
Add an Example for DifferenceOfGaussians Constructor

### ISSUE THREAD

**Issue by sp14-bse-005** [accord-net/framework#494]
Please add an example for DifferenceOfGaussians Constructor.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Imaging_Filters_DifferenceOfGaussians__ctor.htm

**Comment by cesarsouza** [comment]
Please refer to the [example at the bottom of the main documentation page for DifferenceOfGaussians](http://accord-framework.net/docs/html/T_Accord_Imaging_Filters_DifferenceOfGaussians.htm).
