### ISSUE TITLE
Add an Example for QLearning Class

### ISSUE THREAD

**Issue by NelsonAndara** [accord-net/framework#498]
Please add an example for QLearning Class.

TODO (optional): I am trying to use QLearning to predict a financial security's price based on observations of Order Flow Imbalances, Book Ratios, and price trends with different levels of volatility.

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_QLearning.htm

**Comment by cesarsouza** [comment]
An example for the QLearning class has been added in 3.8.0.
