### ISSUE TITLE
Add an Example for KMeans Constructor (Int32)

### ISSUE THREAD

**Issue by khiladiusman** [accord-net/framework#499]
Please add an example for KMeans Constructor (Int32).
hi, Actully i have a problem in which 4 variables are categorical which can have upto hunderades of distinct values and 3 are continuous values. here i need to apply the k_means algo so please give some example relating to this. Or give me some needfull info .
Thanks 

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_KMeans__ctor.htm

**Comment by cesarsouza** [comment]
An example for mixed inputs has just been added to the [K-Means documentation page](http://accord-framework.net/docs/html/T_Accord_MachineLearning_KMeans.htm).
