### ISSUE TITLE
Add an Example for ConfusionMatrix Constructor (Int32[], Int32[], Int32, Int32)

### ISSUE THREAD

**Issue by lkdegroot** [accord-net/framework#505]
Please add an example for ConfusionMatrix Constructor (Int32[], Int32[], Int32, Int32).

TODO (optional): And use the results of the matrix in a wpf xaml file to display in an application.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Analysis_ConfusionMatrix__ctor_4.htm

**Comment by cesarsouza** [comment]
Examples for the [ConfusionMatrix class constructor have been added to the main documentation page for the ConfusionMatrix class](http://accord-framework.net/docs/html/T_Accord_Statistics_Analysis_ConfusionMatrix.htm).
