### ISSUE TITLE
Xamarin Android?

### ISSUE THREAD

**Issue by rikkuporta** [accord-net/framework#506]
Hi, i am trying to use this package but I get the error that Accord.Math does not contain assembly references for my project targeting "MonoAndroid, Version=v4.4"
Could you help or provide clarification?

**Comment by cesarsouza** [comment]
Support for .NET Standard 1.4 will finally be added in the next release, which should make the project able to run on Xamarin directly.

**Comment by cesarsouza** [comment]
Support for Xamarin should be available through the NET Standard 1.4 packages, which have been included in the 3.7.0 release.
