### ISSUE TITLE
Add an Example for HiddenMarkovModel Class

### ISSUE THREAD

**Issue by amrgody** [accord-net/framework#515]
Please add an example for HiddenMarkovModel Class.

TODO (optional): using Gaussian mixture in HMM for solving speech recognition problem or any simialr problem with multi-modal feature vectors. I appreciate to illustrate how to create models, train models and test models. Creating the confusion matrix is highly appreciated. 

Help Topic: http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Markov_HiddenMarkovModel.htm

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
