### ISSUE TITLE
Add an Example for IntegralImage2.FromBitmap Method (Bitmap)

### ISSUE THREAD

**Issue by alburaihi** [accord-net/framework#518]
Please add an example for IntegralImage2.FromBitmap Method (Bitmap).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Imaging_IntegralImage2_FromBitmap_4.htm

**Comment by cesarsouza** [comment]
Will be solved with #899

**Comment by cesarsouza** [comment]
An [example for IntegralImage2.FromBitmap is available at the main documentation page for the IntegralImage2 class](http://accord-framework.net/docs/html/T_Accord_Imaging_IntegralImage2.htm).
