### ISSUE TITLE
Add an Example for NonlinearLeastSquares Constructor (NonlinearRegression, ILeastSquaresMethod)

### ISSUE THREAD

**Issue by JefPro** [accord-net/framework#524]
Please add an example for NonlinearLeastSquares Constructor (NonlinearRegression, ILeastSquaresMethod).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Models_Regression_Fitting_NonlinearLeastSquares__ctor_1.htm

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
