### ISSUE TITLE
Add an Example for LevenbergMarquardtLearning.Run Method

### ISSUE THREAD

**Issue by JefPro** [accord-net/framework#525]
Please add an example for LevenbergMarquardtLearning.Run Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Neuro_Learning_LevenbergMarquardtLearning_Run.htm

**Comment by cesarsouza** [comment]
Please refer to the examples in the [LevenbergMardquardtLearning documentation page](http://accord-framework.net/docs/html/T_Accord_Neuro_Learning_LevenbergMarquardtLearning.htm).
