### ISSUE TITLE
K-medoids algorithm

### ISSUE THREAD

**Issue by cesarsouza** [accord-net/framework#53]
Add the k-medoids algorithm in the clustering module.

A description of the k-medoids algorithm can be found in Wikipedia, alongside with worked examples that would help testing and verifying an actual implementation:
- http://en.wikipedia.org/wiki/K-medoids

For practical pourposes, there is also [a BSD licensed k-medoids implementation available on MATLAB Central](http://www.mathworks.com/matlabcentral/fileexchange/28898-k-medoids). Since this implementation is available under the BSD license, anyone willing to work on this feature can leverage the source code on this page and include the original copyright text for the original author, Mo Chen.

In order to implement a new clustering algorithm, start by _copying all the contents of the existent KMeans.cs file, and simply rename the class to KMedoids_. Then, replace the core algorithm with the k-medoids one. This will simplify getting the IUnsupervisedLearning interface implementation straight.

**Comment by cesarsouza** [comment]
Added in #743.

**Comment by cesarsouza** [comment]
Added in v3.7.0.

**Comment by abduallahnoorsayket** [comment]
CAn you please provide any code of k medoids in Lua (torch) ??
