### ISSUE TITLE
Add an Example for Neuron Class

### ISSUE THREAD

**Issue by kamranamin** [accord-net/framework#535]
Please add an example for Neuron Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Neuro_Neuron.htm

**Comment by cesarsouza** [comment]
The Accord.Neuro namespace will eventually be replaced by the implementations in https://github.com/cesarsouza/keras-sharp
