### ISSUE TITLE
Pleas Add an Example for VideoFileWriter.Open Method (String, Int32, Int32, Int32, VideoCodec, Int32, AudioCodec, Int32, Int32, Int32) and my video quality will 360 p

### ISSUE THREAD

**Issue by orhanyazilimci** [accord-net/framework#536]
Please add an example for VideoFileWriter.Open Method (String, Int32, Int32, Int32, VideoCodec, Int32, AudioCodec, Int32, Int32, Int32).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Video_FFMPEG_VideoFileWriter_Open_4.htm

**Comment by orhanyazilimci** [comment]
Please add an example for VideoFileWriter.Open Method (String, Int32, Int32, Int32, VideoCodec, Int32, AudioCodec, Int32, Int32, Int32).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Video_FFMPEG_VideoFileWriter_Open_4.htm

` 
            string CariProjeAdres = Path.GetDirectoryName(Path.GetDirectoryName(System.IO.Directory.GetCurrentDirectory()));

          
             int width=0;
             int height=0;
        
            if (File.Exists(CariProjeAdres + @"\\Frameler\\" + "0.png"))
            {
              
                 width = Image.FromFile(CariProjeAdres + @"\\Frameler\\" + "0.png").Width;
                 height = Image.FromFile(CariProjeAdres + @"\\Frameler\\" + "0.png").Height;

               
                 Accord.Video.FFMPEG.VideoFileWriter writer = new Accord.Video.FFMPEG.VideoFileWriter();
            

                 writer.Open(CariProjeAdres + @"\\Video\\Hazirlanmis.mp4", width, height, 25, VideoCodec.Default, 400000,AudioCodec.MP3,500000,600000,);
_in this section  gives exception... Can anybody write me example?_
                 byte[] SES = File.ReadAllBytes(CariProjeAdres + "\\SES\\HazirlanmisSES.mp3");
                 writer.WriteAudioFrame(SES);

                 


                 
                
             
                 Bitmap image = new Bitmap(width, height, PixelFormat.Format24bppRgb);
 
                 DirectoryInfo dir = new DirectoryInfo(CariProjeAdres + "\\Frameler\\");

            
                 int FrameSayisi = dir.GetFiles().Length;

          
                 for (int i = 0; i < FrameSayisi; i++)
                 {
                     //Frameleri, Üzerinde İşlem yapmak için Tanımlanmış Bitmap Classının içerisine Atıyoruz...
                     image = (Bitmap)Image.FromFile(CariProjeAdres + "\\Frameler\\" + i.ToString() + ".png");

                     // Video Yazıcı vasıtası ile elde edilen resimleri hazırlanacak videoya atıyoruz...
                     writer.WriteVideoFrame(image);
                 }


             

          
                 writer.Close();
                 writer.Dispose();
               
                 MessageBox.Show("Video Hazırlandı...");`

**Comment by cesarsouza** [comment]
This method will be marked as deprecated - however, examples will be added to the new preferred method in the next release.
