### ISSUE TITLE
L1 filtering - GoldfarbIdnani 

### ISSUE THREAD

**Issue by NorthwoodCapitalManagement** [accord-net/framework#539]
Hi,

I am trying to solve a particular optimization problem. It is a trend filtering technique called L1 which you can find here for more details: http://web.stanford.edu/~boyd/papers/pdf/l1_trend_filter.pdf.

I have attached a screenshot of the original problem (y is the signal and x is the trend which we are trying to compute).

![l1_original_problem](https://cloud.githubusercontent.com/assets/14185585/24947403/e865947c-1f66-11e7-9c39-43b42f2db392.png)

 This dual problem is QP and I thought of using your GoldfarbIdnani algorithm to solve it. Please see the second screenshot.

![l1_dual_problem](https://cloud.githubusercontent.com/assets/14185585/24947406/ed2e09ee-1f66-11e7-83b5-f365581c7eae.png)

I have attached a rather simple/not-optimized (in any sense) code sample (in a word format ...). 

[code_sample.docx](https://github.com/accord-net/framework/files/916065/code_sample.docx)

I have also attached a graph showing the input data, the output of the attached code sample and the same problem resolved by an R package (https://github.com/hadley/l1tf). As you can see, the ouput I get from Accord is far from what it should/could be.

![l1_comparison_data_r](https://cloud.githubusercontent.com/assets/14185585/24951079/7c065566-1f73-11e7-85c6-6e01ec9e6d6f.png)

I was wondering if you were able to identify any issue: am I mis-specifying the problem in Accord? Are there any limitations for which this solver wouldn't work? I am surprised to see only 5 iterations steps, is there a way to increase the number of iterations? Do you have any other suggestions?

Many thanks for your help. I am not sure it is even the right place to ask this kind of questions. Feel free to redirect me.

Kind regards,
Charles

Ps: I have created the same issue on StackOverflow if that's the right place for such a question:
http://stackoverflow.com/questions/43364539/accord-net-l1-trend-filtering-goldfarbidnani

Help Topic: http://accord-framework.net/docs/html/M_Accord_Math_Optimization_GoldfarbIdnani__ctor_3.htm

**Comment by NorthwoodCapitalManagement** [comment]
Changing the subtraction into an addition in GetResult: res[i] = input[i] + adjustment[i]; actually makes Accord.Net and R match. I don't really get why so if someone has an explanation I would gladly hear it, but I understand it might be off topic.

**Comment by blaisexen** [comment]
Hello,,

Do you mean to say that there was a bug in the framework? that the subtraction was wrong, the addition is right?

**Comment by NorthwoodCapitalManagement** [comment]
Hi,
Many thanks for your response. I wouldn't go as far as to say that there is a bug in the framework. However, equation (14) in the above screenshot (which I have checked from a mathematical point of view) shows that it should be a subtraction, not an addition. I see two possibilities so far: 1) I have wrongly set-up the problem in Accord (very likely) 2) Accord returns the solution with the wrong sign (which I seriously doubt).  I am happy to help if you think there might be a bug down the line.

**Comment by blaisexen** [comment]
Hi,

cesarsouza is not here, lets wait for him, I hope he comes in.

thank you

**Comment by NorthwoodCapitalManagement** [comment]
Many thanks Cesar for your detailed explanation. Re-reading your very interesting post (http://crsouza.com/2012/04/05/quadratic-programming-in-c/) I should have figured that out myself! Congratulations on a very powerful framework which I will continue to use and explore. 
Charles
