### ISSUE TITLE
Add an Example for BaumWelchLearning(TDistribution, TObservation, TOptions) Class

### ISSUE THREAD

**Issue by neulky** [accord-net/framework#540]
Please add an example for BaumWelchLearning(TDistribution, TObservation, TOptions) Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Markov_Learning_BaumWelchLearning_3.htm

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
