### ISSUE TITLE
visual studio 2012 and accord.net 

### ISSUE THREAD

**Issue by HibaAZIZ** [accord-net/framework#541]
is it possible to run this framework with visual studio 2012 ?!!

**Comment by blaisexen** [comment]
I used vs2010 with .net framework 4.0

**Comment by cesarsouza** [comment]
Yes, the framework can be used with any version of Visual Studio after 2008. Just make sure to use the correct assemblies for the .NET Framework version you want to target. Normally those should be sorted out automatically if you have downloaded the framework using NuGet.

If you need to use VS 2008, you might need to download the special .NET 3.5 version of the framework that is available in the "libsonly" packages in the [releases page](https://github.com/accord-net/framework/releases). 

Regards,
Cesar

**Comment by HibaAZIZ** [comment]
thank you so much to you all for your replies 
i'm using visual studio 2012 . which version of .Net is suitable for this version please?!! 
i downloaded the framework from github directly.
ok i'll try to download it again from NuGet  to get the correct version of visual that i'm using 
best regards.

**Comment by cesarsouza** [comment]
If I remember correctly, VS 2012 came with .NET 4.5. If you use the framework version for .NET 4.5 it should work. But please try with NuGet as it will be able to install the correct packages for you in this case.
