### ISSUE TITLE
Add an Example for HiddenMarkovModel(TDistribution, TObservation) Class

### ISSUE THREAD

**Issue by ellLazar** [accord-net/framework#544]
Please add an example for HiddenMarkovModel(TDistribution, TObservation) Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Markov_HiddenMarkovModel_2.htm

**Comment by cesarsouza** [comment]
Added in release 3.6.0.

**Comment by ellLazar** [comment]
Hello Cesar Souza,
thanks for update, it was very hard for me to implement the HMM in a real world.
hopefully, you can be more responsive in the future.

**Comment by cesarsouza** [comment]
It is hard to keep up with all requests. This is a project that I can only do in my free time, so any help is welcome.
