### ISSUE TITLE
Problem deploying application with Accord.Video.FFMPEG

### ISSUE THREAD

**Issue by AlexGimo** [accord-net/framework#553]
I'm using accord.video.ffmpeg 3.4.0, downloaded via nuget, to save a video with videorecorder class. If I compile (x86) my solution the application is running smoothly in visual studio, instead if I publish the app (same architecture ) when I try to run the setup.exe it installs the program but suddenly crashes. The problem is in the constructor of a class when I do new videorecorder(). It is like If during the deployment process not all the libraries needed are included. Anyonw knows which libraries are missing? Thank, Alex

**Comment by ddumitrascu** [comment]
You need to include all the files you find in bin/Debug folder: avcodec-53.dll etc.

**Comment by AlexGimo** [comment]
Yes, you are right. Actually I had already tried to include libraries but probably I missed one or included in the wrong way. Trying again everything was fine.
Thank you.
