### ISSUE TITLE
Display license on repository top

### ISSUE THREAD

**Issue by y-takashina** [accord-net/framework#556]
There are already license terms in each file, but adding LICENSE file to the repository root will help users confirm license easily.

>// Accord Machine Learning Library
// The Accord.NET Framework
// http://accord-framework.net
//
// Copyright © César Souza, 2009-2017
// cesarsouza at gmail.com
//
// Copyright © Antonino Porcino, 2010
// iz8bly at yahoo.it
//
//    This library is free software; you can redistribute it and/or
//    modify it under the terms of the GNU Lesser General Public
//    License as published by the Free Software Foundation; either
//    version 2.1 of the License, or (at your option) any later version.
//
//    This library is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//    Lesser General Public License for more details.
//
//    You should have received a copy of the GNU Lesser General Public
//    License along with this library; if not, write to the Free Software
//    Found

**Comment by y-takashina** [comment]
Oh, sorry there is a `license.txt`. However, in GitHub, a shortened license name will be displayed on the repository page if there is a `LICENSE` file. It would be better.

https://github.com/blog/2252-license-now-displayed-on-repository-overview

**Comment by cesarsouza** [comment]
Thanks @y-takashina, I didn't know about this GitHub functionality. I will rename the license.txt file to LICENSE so it can be recognized by GitHub.

**Comment by y-takashina** [comment]
The license doesn't seem displayed in my environment.
The LICENSE in this repository is modified a little. Maybe the modification makes it difficult for the GitHub license picker to detect the license.

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
