### ISSUE TITLE
Add an Example for Matrix.Sort(TKey, TValue) Method (TKey[], TValue[,], IComparer(TKey))

### ISSUE THREAD

**Issue by mauricepillet** [accord-net/framework#557]
Please add an example for Matrix.Sort(TKey, TValue) Method (TKey[], TValue[,], IComparer(TKey)).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Math_Matrix_Sort__2.htm

**Comment by cesarsouza** [comment]
Added in 3.8.0.
