### ISSUE TITLE
Q Learning documentation

### ISSUE THREAD

**Issue by GalHorowitz** [accord-net/framework#559]
Hey there. I needed a reinforcment learning library for c sharp, and I found this. I'm trying to use the QLearning class, but doesn't matter where I searched I couldn't find any docs. I understand I create it with (int32 states, int32 actions, ExplorationPolicy) I chose EpsilonGreedy - and then i moved on to using it - There is this getAction method - and it needs an int state: but what is this int? how do I pass it the current state using a lone int?

**Comment by cesarsouza** [comment]
An [example for the QLearning class](http://accord-framework.net/docs/html/T_Accord_MachineLearning_QLearning.htm) has been added in release 3.8.0. It is a documentation-example version of the [Animat (QLearning and Sarsa) sample application](https://github.com/accord-net/framework/wiki/Sample-applications#animat-qlearning-and-sarsa) that comes included with the framework.
