### ISSUE TITLE
C4.5Learning: tree depends on the sorting order when the desicion variable is continuous

### ISSUE THREAD

**Issue by SivanK** [accord-net/framework#57]
For DecisionVariableKind=Continuous, candidates for cut values are determined by this code:
if (o[j] != o[j + 1])
     candidates.Add((v[j] + v[j + 1]) / 2.0);

The order of the output values are determined by the sorting order of the actual values thus can change for several equal values.
For example, after sorting:
Values are: 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 24, 24, 26, 26, 28, 29, 30, 30
Labels are: 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1

Candidates for split in this case are: 2, 2, 2, 3, 3, 3

Another option for sorting would be:
Values are: 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 24, 24, 26, 26, 28, 29, 30, 30
Labels are: 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1
(I've just switched the order of two equal values)

In that case, although the values are exactly the same, the candidates for split would be: 2, 2, 2, 3, 3, 3, 3, 13.5.

This behavior may results in the same decision tree no matter if the values are:
2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 24, 24, 26, 26, 28, 29, 30, 30  OR
2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 240, 240, 260, 260, 280, 290, 300, 300  OR
2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2400, 2400, 2600, 2600, 2800, 2900, 3000, 3000 OR..
Since both the last 3 and the 24 are labeled as 1 (other 3's are labeled as 0)

Any suggestions on what can be done?

Thanks a lot,
Sivan.

**Comment by SivanK** [comment]
Hey,
I've read the article that you're referring to in the code. I believe you were specifically referring to this footnote:
"Fayyad and Irani (1992) prove that, for convex splitting criteria such as information gain, it is not
necessary to examine all such thresholds. If all cases with value vi and with adjacent value vi+1 belong
to the same class, a threshold between them cannot lead to a partition that has the maximum value of
the criterion."

So, I think the problem in my case is that not ALL cases with value=x are in the same class. When not ALL cases of a specific value are in the same class, the footnote above doesn't apply.

**Comment by cesarsouza** [comment]
Hi Sivan!

Thanks! It seems you are completely right! Indeed, that was the footnote I was referring to. In order to fix this, it would be necessary to add this check before deciding not to inspect a given threshold. Please, may I ask if you are interested in contributing a fix for the issue? Even pseudo-code might help. I am just asking because it seems you have already found the answer for this problem, and it might take a while for me to get into the code again and remember everything concerning this code region in order to perform this fix. But don't worry! I can also eventually do it for the next framework release. It will just take a little longer. If, however, you would like to help, please let me know!!

Best regards,
Cesar

**Comment by SivanK** [comment]
Sure, my pleasure :-) 
I'll create a pull request for you to approve.

Thanks,
Sivan.

**Comment by cesarsouza** [comment]
Thanks! I have commited the fix and generate a new pre-release NuGet package. It is already available in the NuGet gallery (once you enable the "Include Prerelease" in the NuGet dialog).

Hope it helps! If you find any other issues please let me know.

Best regards,
Cesar

**Comment by SivanK** [comment]
Thank you so much :-)

On Feb 7, 2015 3:47 PM, César Souza <notifications@github.com> wrote:

Thanks! I have commited the fix and generate a new pre-release NuGet package. It is already available in the NuGet gallery (once you enable the "Include Prerelease" in the NuGet dialog).

Hope it helps! If you find any other issues please let me know.

Best regards,
Cesar

**Comment by cesarsouza** [comment]
Included in release 3.2.
