### ISSUE TITLE
Accord.Controls is referencing wrong version of ZedGraph on NuGet

### ISSUE THREAD

**Issue by nx74205scw** [accord-net/framework#571]
Version of Accord.Controls (latest stable 3.4.0 back through to 3.0.2) on NuGet has dependency on ZedGraph 5.1.6 - however internally in the initializer it has a hard reference to ZedGraph 5.1.5.28844 which causes designer and forms using HistogramView to fail to load in Visual Studio.

Forced deletion of ZedGraph NuGet dll and re-referencing 5.1.5.28844 allows forms and application to work ok, however package refresh/reinstalls break application again.

![zedgraph fail](https://cloud.githubusercontent.com/assets/5557070/25568290/694ddc36-2df7-11e7-8fff-4f6fe07b6c77.JPG)

**Comment by cesarsouza** [comment]
Fixed in release 3.6.0.
