### ISSUE TITLE
Add an Example for MeanShift Class

### ISSUE THREAD

**Issue by Pramitapg** [accord-net/framework#573]
Hi, In all the algorithms like K-means and MeanShift the learn and decide functions are not working.

Please add an example for MeanShift Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_MeanShift.htm

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
