### ISSUE TITLE
Unexplained Divide By Zero exception

### ISSUE THREAD

**Issue by Crisfole** [accord-net/framework#58]
I'm unable to create a code book for the images from the National Data Science bowl; I get a `DivideByZero` exception during the `Compute` phase.

The stack trace indicates the problem is in the `ProcessImage` method of the SURF detector.

I've written an easily runnable linqpad example and posted it as a GIST here: https://gist.github.com/Crisfole/bb636955891327f8b057

To reproduce:

1. Download the `train.zip` data files from the National Data Science bowl. (You may have to create a kaggle account to do this, TOS seem to be ok w/ practicing on their data).
2. Extract the training images somewhere on you computer.
3. Copy-Paste the Gist into Linq-Pad and replace the directory at the top of the `Main()` method with yours.
4. Run.

**Comment by cesarsouza** [comment]
Thanks! It will be fixed in the next release. I will new pre-release package also has been created with the fix.
