### ISSUE TITLE
Reading an ExcelFile with huge number of columns using ExcelReader

### ISSUE THREAD

**Issue by SurKM9** [accord-net/framework#580]
Trying to implement DTW for my gestures data but have issues reading data with varying sequences and varying observation vectors as well.

Sample data looks like this [data.xlsx](https://github.com/accord-net/framework/files/975966/data.xlsx)

Is there anyway i can read the Excel File with varying number of columns without specifying the names of all the columns?

Sample code i implemented to read fixedcolumns file for reference:

           
              DataTable matrix = new ExcelReader("fixedcolumns.xlsx").GetWorksheet("fixedcolumns");
              double[][] inputs = matrix.ToJagged<double>("A","B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", 
              "M", "N", "O", "P");
              int[] outputs = matrix.Columns["Z"].ToArray<int>();

            // Create the Sequential Minimal Optimization learning algorithm
            var smo = new SequentialMinimalOptimization<DynamicTimeWarping,double[]>()
            {
                Complexity = 1.5,

                // Set the parameters of the kernel
                Kernel = new DynamicTimeWarping(alpha: 1, degree: 1)
            };

            // And use it to learn a machine!
            var svm = smo.Learn(inputs, outputs);

            // Now we can compute predicted values
            bool[] predicted = svm.Decide(inputs);

            for (int t = 0; t < predicted.Length; t++)
            {
                Console.WriteLine("{0} , {1}", outputs[t], predicted[t]);
            }

            // And check how far we are from the expected values
            double error = new ZeroOneLoss(outputs).Loss(predicted);
            Console.WriteLine("{0}", error);

I cannot specify all the column names. Moreover, how do i tell the kernel that the length of the vector and sequence is irrelevant?

**Comment by cesarsouza** [comment]
Hi there,

In this case, I guess the best approach would be either to use a special marking to denote the cell value should be ignored (i.e. 0). This way you can read all the data at once, but then iterate over the sequences and copy only the values that are needed to new double[] arrays.

If the DynamicTimeWarping kernel is used with double[] arrays, it and the SVM that uses it should know by themselves that the arrays have dynamic length.
