### ISSUE TITLE
How do I use KModes for category data?

### ISSUE THREAD

**Issue by davidpaulstevens** [accord-net/framework#581]
How do I use KModes without:
a) first transforming my data (otherwise, I may as well use KMeans)
b) not depending on string content (e.g. "Kansas" should be no more like "Arkansas" than "Tennessee"
Let's say I have 1000 observations with three attributes each: US State, color, bird. I would like to cluster them into 10  most like clusters based solely on the nominal state of each attribute.

**Comment by cesarsouza** [comment]
Hi David,

I would suggest sticking to K-Means and transforming your data nonetheless. This is really the default approach and one of the bests to start tacking problems of the form you mention.

For b) please consider using the [Codification](http://accord-framework.net/docs/html/T_Accord_Statistics_Filters_Codification.htm) class to transform your string content into 1-of-K vector representations. Transform your string variables into 1-of-K vectors, then concatenate them before clustering. You might either want to apply some weighting to the different components in your feature vector (i.e. dividing by their L2-norm) or you might want to cluster them independently and then combine the results afterwards.

In your example, this could be done as:

```
// Let's say we have a dataset of US birds:
string[] names = { "State", "Bird", "Color" };

string[][] data =
{
    new[] { "Kansas", "Crow", "Black" },
    new[] { "Ohio", "Pardal", "Yellow" },
    new[] { "Hawaii", "Penguim", "Black" }
};

// Create a codebook for the dataset
var codebook = new Codification(names, data);

// Transform the data into integer symbols
int[][] values = codebook.Transform(data);

// Transform the symbols into 1-of-K vectors
double[][] states = Jagged.OneHot(values.GetColumn(0));
double[][] birds = Jagged.OneHot(values.GetColumn(1));
double[][] colors = Jagged.OneHot(values.GetColumn(2));

// Normalize each variable separately if needed
states = states.Divide(codebook["State"].NumberOfSymbols);
birds = birds.Divide(codebook["Bird"].NumberOfSymbols);
colors = colors.Divide(codebook["Color"].NumberOfSymbols);
```

Now, if you really would like to try the K-Modes approach, you would first need to define one distance function that can compare your data rows. For this, you would have to create a class that implements the 
```IDistance<T[], T[]>``` interface, where T is the data type of the object that you want to use as rows.

For example, let's say you defined your data rows as

```
class DataRow 
{
    public string State { get;set; }
    public string Bird { get; set; }
    public string Color { get; set; }
}
```

One way to define a distance (although certainly not a metric distance) would be to consider how many features match between two DataRow objects:

```
class MyDataRowDistance : IDistance<DataRow, DataRow>
{
    public double Distance(DataRow a, DataRow b)
    {
        int t = 0;
        if (a.State == b.State)
            t++;
        if (a.Bird == b.Bird)
            t++;
        if (a.Color == b.Color)
            t++;
        return t;
    }
}
```

However, I am not sure how this would work out. I would strongly advise sticking with K-Means instead. K-Modes might make more sense for things that are really hard to transform to double[] vectors, such as graphs or trees.

Hope it helps,
Cesar

**Comment by davidpaulstevens** [comment]
Very, very helpful. Many thanks.
