### ISSUE TITLE
Add an Example for NormalDistribution Constructor (Double, Double)

### ISSUE THREAD

**Issue by Benuka** [accord-net/framework#584]
Please add an example for NormalDistribution Constructor (Double, Double).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Distributions_Univariate_NormalDistribution__ctor_2.htm

**Comment by cesarsouza** [comment]
Hello there,

For an example on NormalDistribution's constructor, please check the documentation page for NormalDistribution itself: http://accord-framework.net/docs/html/T_Accord_Statistics_Distributions_Univariate_NormalDistribution.htm
