### ISSUE TITLE
Add an Example for MulticlassClassifierBase.Decide Method (Int32[][], Int32[])

### ISSUE THREAD

**Issue by bugdaryan** [accord-net/framework#589]
Please add an example for MulticlassClassifierBase.Decide Method (Int32[][], Int32[]).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_MulticlassClassifierBase_Decide_8.htm

**Comment by cesarsouza** [comment]
There are countless examples on how to use the Decide function. Basically, any example of a classifier such as [Support Vector Machine](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_SupportVectorMachine.htm) shows an example in the bottom on how to do it. Please let me know if you need a more specific example.
