### ISSUE TITLE
Can't build ScreenCapture example

### ISSUE THREAD

**Issue by TharosTheDragon** [accord-net/framework#598]
When I try to build ScreenCapture in Visual Studio 2017 I get this compiler error:

```
NotifyPropertyWeaver: Failed to extract target assembly path from the BuildEngine. 
Please raise a bug with the below exception text.
The temporary work-around is to change the weaving task as follows 
<WeavingTask ... TargetPath="PathToYourAssembly" />
Exception details: System.Exception: Could not extract targetBuilderCallback from Microsoft.Build.BackEnd.TaskHost
   at BuildEnginePropertyExtractor.GetProjectInstance()
   at BuildEnginePropertyExtractor.GetEnvironmentVariable(String key, Boolean throwIfNotFound)
   at TargetPathFinder.Execute()
```

Does anyone know how to fix this? I'm running Windows 10 64-bit.

**Comment by alonsolai** [comment]
I am same as you on Win7, VS 2017. No Error file and line number. No solution was found from google!

**Comment by cesarsouza** [comment]
Hi there,

This was actually a problem with Fody INotifyPropertyWeaver. Indeed, quite a hard thing to find on google; but the solution was basically to remove all references, scripts and build tasks related to Fody and reinstall it again from scratch. 

Regards,
Cesar
