### ISSUE TITLE
Regularization breaks LogisticRegressionAnalysis in 2.14.0

### ISSUE THREAD

**Issue by marklam** [accord-net/framework#60]
I have a set of data which I could calculate a logistic regression for in 2.13.1, but not in 2.14.0.
I still get a 'converged' result from `Compute`, but the coefficients are all -1.2748188443139669E+194.
If I use the same procedure used in `LogisticRegressionAnalysis`, but use an `IterativeReweightedLeastSquares` whose `Regularization` is set to 0, everything works as in 2.13.1

[I've uploaded the data that shows the problem](https://gist.github.com/marklam/389037915f95c070cd93#file-cannotregress-csv)

**Comment by cesarsouza** [comment]
Thank you! I will write a unit test to reproduce the test and investigate.

**Comment by cesarsouza** [comment]
Hi there, I have fixed the regularization implementation and added a new property in the LogisticAnalysis class to manually override the regularization options if needed. I will be available in the next release but I can also generate a temporary alpha release if there is interest.

Hope it helps!

Best regards,
Cesar

**Comment by cesarsouza** [comment]
A new pre-release NuGet package has been created with the fix. Thanks for reporting the issue!
