### ISSUE TITLE
Add an Example for CrossValidation Class used for generating a training set

### ISSUE THREAD

**Issue by armankhosravi** [accord-net/framework#601]
Please add an example for CrossValidation Class.

I am trying to use the Cross Validation Technique to generate an optimized training set to be used with the C4.5 training algorithm. Unfortunately I can't find the answer on how to do that anywhere. An example would be great help! Thanks.

**Comment by cesarsouza** [comment]
Hi there,

Cross-validation cannot be used to generate training sets. Instead, it is intended to help you identify the best hyper-parameters to use with your learning algorithm.

An [example for cross-validation has been added in v3.6.0](http://accord-framework.net/docs/html/T_Accord_MachineLearning_Performance_CrossValidation_2.htm).
