### ISSUE TITLE
ColorSlider not working in Accord.Controls

### ISSUE THREAD

**Issue by perezale** [accord-net/framework#604]
Hi everyone!

Maybe someone could help us out.

When dragging the ColorSlider to an empty Form, it produces the next error:

"System.ArgumentException" in System.Drawing.dll , Null is not valid for stream.

Following the code, the problem is at this line:

Assembly assembly = this.GetType().Assembly;
arrow = new Bitmap(assembly.GetManifestResourceStream("Accord.Controls.Resources.arrow.bmp"));

Browsing Accord.Controls.dll at the Assembly Explorer we couldn't find the arrow.bmp. And through the repository we found it at framework/Sources/Accord.Controls.Imaging/AForge/Resources
We believe the namespace is wrong because the path is not matching with the actual folder structure.

is there any workaround or are we doing something wrong?

Thanks in advance.

**Comment by cesarsouza** [comment]
Hi @perezale,

Many thanks for reporting the issue and identifying the fix. Please let me know if you find any other issues while importing other controls!

I will try to commit a fix in the next minutes.

Regards,
Cesar
