### ISSUE TITLE
What is the difference between AudioCodec.AAC and AudioCodec.M4A?

### ISSUE THREAD

**Issue by TharosTheDragon** [accord-net/framework#605]
My research seems to indicate that M4A isn't even a codec at all and is just a file extension for mp4 files without video.
http://stackoverflow.com/questions/18110399/what-is-the-difference-between-m4a-and-aac-audio-files
http://www.differencebetween.net/technology/difference-between-aac-and-m4a/

So what is AudioCodec.M4A exactly? What does it do? What is it for?

**Comment by cesarsouza** [comment]
Hi @TharosTheDragon,

The AudioCodec.MP4 actually refers to [MP4ALS, the MP4 Audio Lossless Coding](https://en.wikipedia.org/wiki/Audio_Lossless_Coding). The name choice was a bit unfortunate, but I will improve it for next releases!

Regards,
Cesar

**Comment by cesarsouza** [comment]
Fixed in release 3.6.0.
