### ISSUE TITLE
LowerBoundNewtonRaphson: how to check if converged

### ISSUE THREAD

**Issue by deng0** [accord-net/framework#606]
I'm currently updating some old to code to the new version Accord and I'm wondering how to check if the LowerBoundNewtonRaphson Learning converged when not using the obsolete methods.
Comparing Solution with Previous or checking Gradient?
Sorry, if this is a stupid question...

**Comment by cesarsouza** [comment]
Hi @deng0,

Currently there is no easy way to check whether the algorithm converged in the last call to .Learn(). I am working on currently standardizing the convergence checks in the new API, and unfortunately I haven't updated LowerBoundNewtonRaphson yet.

However, as a quick fix you might be able to check the convergence of LowerBoundNewtonRaphson by accessing one of its private fields through reflection:

```
IConvergence<double> status = (IConvergence<double>)typeof(LowerBoundNewtonRaphson)
                .GetField("convergence", BindingFlags.NonPublic | BindingFlags.Instance)
                .GetValue(lowerBoundNewtonRaphson);
```

In any case, soon I will be adding a commit adding a HasConverged method in LowerBoundNewtonRaphson that can be used to check for convergence.

Regards,
Cesar

**Comment by deng0** [comment]
Thanks for the reply.
Good to know that you are adding it to one of the next releases.
I will stick with the obsolete method for now.

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
