### ISSUE TITLE
Add an Example for UnivariateContinuousDistribution.Fit Method (Double[])

### ISSUE THREAD

**Issue by gjmsoftware** [accord-net/framework#610]
Please add an example for UnivariateContinuousDistribution.Fit Method (Double[]).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Distributions_Univariate_UnivariateContinuousDistribution_Fit.htm

**Comment by cesarsouza** [comment]
Added in 3.8.0.
