### ISSUE TITLE
LSTM Recurrent Neural Network

### ISSUE THREAD

**Issue by functionsoft** [accord-net/framework#612]
Hi César / Accord,

It would be very useful if you could add LSTM RNN Neural Networks to this library.

I found one example implemented in C#.

https://github.com/robosoup/LSTM-Language-Model

Be a great addition to this library.  Seems to be a hot subject at the moment in the ML/AI world.

Thanks & Regards,

Mike

**Comment by cesarsouza** [comment]
Hi there,

LSTMs will be added once #92 and #634 are complete. So far, the current plan is to implement them using TensorFlowSharp.

Regards,
CEsar

**Comment by thelemontree10** [comment]
Hi cesar,

Using tensorflowsharp sounds like a good idea. But you should notice that tensorflow library has a very strange manning of coding. When they update from the old version to the next version, a lots of functions are changed (parameter, name, package, ...). It means that the tensorflowsharp must change to. Some errors detected in tensorflowsharp, I as see, is due to not updating the revised method.

So, I think, you should participate in developing tensorflowsharp (I see that they the authors do not spend too much time like you) OR you should rewrite code by yourself.

Best Regards,

**Comment by functionsoft** [comment]
I'd prefer to see a native C# implementation in the Accord framework rather than a wrapper around another library.

Thanks.

**Comment by cesarsouza** [comment]
Hi @functionsoft, @thelemontree10, 

First of all, thank you very much for the feedback & comments towards having a native LSTM implementation in Accord.NET as opposed to relying on a external library. That's a great sign that the overall framework interfaces are useful/more intuitive than other offerings.

However, I have to say that delegating (to some extent) the development of the neural network library to some third-party library might be beneficial right now. As @thelemontree10 stated, I guess I have dedicated a significant amount of time into making Accord.NET, way more than authors of other libraries.  But this also means I have a significantly larger number of areas to cover, which sometimes can be just too much for a single person to handle.

I have therefore started [keras-sharp](https://github.com/cesarsouza/keras-sharp), which should be regarded as Accord.Neuro 2.0. This library relies on TensorFlowSharp and should be able to provide 1) state-of-the-art implementations and 2) state-of-the-art performance for your applications. The project is just starting, so all the help in developing it is more than welcome. LSTMs will naturally be implemented into this project, and if needed, the Accord.NET project will provide better interfaces for accessing/implementing those networks.

So if you would like to contribute to its development, please download/clone the initial repository for Keras Sharp and try to create a LSTM network for your own applications. If it doesn't work out-of-the-box (which is actually the most likely scenario) please fill in a issue report and I will look into it.

Again, any help in getting the project started is more than welcome.

Again, thanks a lot for all the comments & feedback! If you would like to contribute to Keras Sharp please let me know!

Best regards,
Cesar
