### ISSUE TITLE
"Index out of bounds" error in SingularValueDecomposition.Solve

### ISSUE THREAD

**Issue by ChristerModin** [accord-net/framework#614]
Hi 

First thanks a lot for all your work with this, at it seems, amazing library :)

I've run into trouble though when fitting an overdetermined system with a two-dimensional B-matrix.
Seems as the VLU isn't dimensioned properly with respect to the number of rows in U
Also, the inner loop should have the number of columns in U as upper bound instead of urows.

 
I suggest from line 934 in SingularValueDecomposition.cs :

            int ucols = u.Columns();
            var VLU = new Double[vrows, urows];
            for (int i = 0; i < vrows; i++)
            {
                for (int j = 0; j < urows; j++)
                {
                    Double sum = 0;
                    for (int k = 0; k < ucols; k++)
                        sum += VL[i, k] * u[j, k];
                    VLU[i, j] = sum;
                }
            }         

 BR

Christer Modin

**Comment by cesarsouza** [comment]
Hi Christer,

Many thanks for opening the issue! Can you please provide a sample matrix that triggers the problem so I can write an unit test for it?

Regards,
Cesar

**Comment by ChristerModin** [comment]
Hi Cesar

Of course, how about:

  double[,] A = { { 1 },  { 0 } };
 double[,] B = { { 1 }, { 0 } };
  double[,] X = Accord.Math.Matrix.Solve(A, B, true);

BR

Christer

**Comment by ndcomplete** [comment]
This is very similar to the question I asked previously, which also includes a sample. I'm not sure if the sample provided will highlight the problem, as it is for JaggedSingularValueDecomposition, though I think it's the same underlying issue:

https://github.com/accord-net/framework/issues/602

**Comment by ChristerModin** [comment]
Yep, seems to be similar code with the same issue for all versions of svd-decomposition-solve where B isn't one-dimensional.

**Comment by cesarsouza** [comment]
Fixed in release 3.6.0.
