### ISSUE TITLE
Accord.Video.FFMPEG dependency on .Net 3.5

### ISSUE THREAD

**Issue by arif-pragmasys** [accord-net/framework#615]
I have been using VideoFileWriter class from Accord.Video.FFMPEG in a C# application that is targeted to 
Dot net 4.5. I get a run-time error if Dot net 3.5 is not installed
"Could not load file or assembly 'Accord.Video.FFMPEG.dll' or one of its dependencies. The specified module could not be found."

Trying to understand where this Dot Net 3.5 dependency coming from. Is it something in the ffmpeg wrapper that needs Dot Net 3.5, though my application is targeted to 4.5 

BTW, I have all the dependency dlls in the same directory as my executable, so it works fine if .net 3.5 is installed

**Comment by cesarsouza** [comment]
Hi there,

Thanks for reporting this issue. I couldn't investigate where this dependency is coming from yet, but it definitely shouldn't have been there.

If you have any insights, please also let me know.

Regards,
Cesar

**Comment by arif-pragmasys** [comment]
After investigating it looks like aforge.video.ffmpeg.dll or some related dll to needs Visual Studio 2010 redistributable runtime (32 bit version) installed. Here is the link to download it:
https://www.microsoft.com/en-us/download/details.aspx?id=5555

Probably dot net 3.5 also include these dlls, so it runs fine if dot net 3.5 is installed. The 2 dll mainly needed are msvcr100.dll and msvcrp100.dll, in case someone would like to bundle them in their app. They could be found in windows/system32 in a 32 bit system and windows/sysWOW64 in a 64 bit system.

**Comment by arif-pragmasys** [comment]
Here is the complete list of dlls you need to have to use VideoFileWriter class in dot net 4 or above.

![capture 1](https://cloud.githubusercontent.com/assets/14184782/26700299/83f1655e-46e2-11e7-9d16-2e7d02391750.PNG)

aforge.dll and aforge.video.dll are dot net dlls, so they need to be recompiled for dot net 4 or higher. 
aforge.video.ffmpef.dll is a managed c++ wrapper dll, it also has to be recomplied for dot net 4 or higher. The rest are native dlls, no recompile needed.

**Comment by cesarsouza** [comment]
Thanks a lot for investigating the issue! May I ask which version of the framework are you using? I has been quite some time since the AForge.NET dlls have been replaced by Accord.NET ones.

**Comment by arif-pragmasys** [comment]
aforge 2.2.4

**Comment by arif-pragmasys** [comment]
Is it recommended to use accord ffmpeg instead of aforge ffmpeg for new projects? Does accord ffmpeg works in dot net 4 or above out of the box?

**Comment by cesarsouza** [comment]
Well, AForge.NET had not been updated in years, and since 2015 has been incorporated as part of Accord.NET. Yes, it probably should work in .NET 4.0 out of the box, but please do a backup of your current project before trying an upgrade.

**Comment by cesarsouza** [comment]
Hi there,

May I ask if upgrading to Accord.NET 3.5 fixed the issue? :-)

Regards,
Cesar

**Comment by TharosTheDragon** [comment]
I'm using Accord with .NET 4.7. It seems to work fine without those AForge dll's present.

**Comment by cesarsouza** [comment]
Please re-open if you are still getting the issue.

**Comment by taranglute** [comment]
I am using Accord (v3.6.0) lib and below error. I have moved native directories in needed folder and error is still there.

Additional information: Could not load file or assembly 'Accord.Video.FFMPEG.x64, Version=3.6.0.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by bijington** [comment]
I am also seeing a similar issue here. I have a 32 bit build working on multiple machines however on a Windows 8 Surface tablet I see an error when trying to retrieve video frames from a device with the following error: "Thread was being aborted."

I also then see the following error when trying to use VideoFileWriter:
"Could not load file or assembly 'Accord.Video.FFMPEG.dll' or one of its dependencies. The specified module could not be found." This is using v3.6.0 and I am shipping the following dlls with my application:
avcodec-57.dll
avdevice-57.dll
avfilter-6.dll
avformat-57.dll
avutil-55.dll
postproc-54.dll
swresample-2.dll
swscale-4.dll
ffmpeg.exe
ffplay.exe
ffprobe.exe

My application is compiled to .NET 4.0.

I have also tried copying over the mentioned dlls from above however I have not been able to resolve this issue so far. Any ideas on the cause of this?

**Comment by intellecode** [comment]
Actually, there is a very simple solution to this.
In "app.config" replace this:

<?xml version="1.0"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
  </startup>
</configuration>

with this:

<?xml version="1.0"?>
<configuration>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
  </startup>
</configuration>

**Comment by intellecode** [comment]
didn't go through, so add <startup useLegacyV2RuntimeActivationPolicy="true"> to <startup>

**Comment by intellecode** [comment]
didn't go through, so add: startup useLegacyV2RuntimeActivationPolicy="true" to startup

**Comment by germinton** [comment]
Same problems here: Could not load file or assembly 'Accord.Video.FFMPEG.dll' or one of its dependencies.
I had it working for some hours, but than I took hours, without success and this error.
This sucks.

**Comment by PrakashPaul** [comment]
System.IO.FileNotFoundException: Could not load file or assembly 'Accord.Video.FFMPEG.x64.DLL' or one of its dependencies. The specified module could not be found. 
using Accord.Video.FFMPEG.x64.3.8.0 version. when deployed application in one server win8 copied below dll into application bin and system folder. worked but failed in other server though configuration are same for server. not sure what I am missing.
![image](https://user-images.githubusercontent.com/4025676/54040393-39f70a00-4193-11e9-9851-1431947a4467.png)

**Comment by htmlkiddie** [comment]
Same problem @PrakashPaul 
I tried different versions of Accord and ffmpeg libraries.
Debug/Release x86/x64/AnyCPU. But still same error:
System.IO.FileNotFoundException: Could not load file or assembly 'Accord.Video.FFMPEG.x64.DLL' or one of its dependencies. The specified module could not be found.

**Comment by PrakashPaul** [comment]
VideoFileWriter.Open, adding different frame height and width not able to produce right mp4 out file. #1740

**Comment by li-xiaoyi** [comment]
How to improve the quality of writing video files by VideoFileWriter? In the same way, the video files collected by AForge are cleaner than those collected by ACCORD.
