### ISSUE TITLE
How to calculate the complexity in respect of the input size

### ISSUE THREAD

**Issue by endeffects** [accord-net/framework#622]
Hi,

i'd like to calculate the complexity in respect of the input size. I noticed that with more input data the required time to train can take forever. In example, i can train 10.000 rows within a few minutes, but i had to break after a couple of hours for 50.000.

**Comment by cesarsouza** [comment]
Hi there,

The complexity for SMO is about ```O(n²)``` where ```n``` is the sample size. The complexity for a first order algorithm, such as stochastic gradient descent is ```O(n)```, but it actually depends on how many iterations you are willing to perform.
