### ISSUE TITLE
Add an Example for Chart Class

### ISSUE THREAD

**Issue by anse8893** [accord-net/framework#624]
Please add an example for Chart Class.
the below your sample code is not working..  it doesn't show any chart.  i don't know why..
pls help me on this..

TODO (optional): Describe a specific scenario you would like to see addressed.
            Chart chart = new Chart();
            double[,] testValues = new double[10, 2];
            // fill data series
            for (int i = 0; i < 10; i++)
            {
                testValues[i, 0] = i; // X values
                testValues[i, 1] = Math.Sin(i / 18.0 * Math.PI); // Y values
            }
            // add new data series to the chart
            chart.AddDataSeries("Test", Color.DarkGreen, Chart.SeriesType.ConnectedDots, 3);
            // set X range to display
            chart.RangeX = new Range(0, 9);
            // update the chart
            chart.UpdateDataSeries("Test", testValues);
Help Topic: http://accord-framework.net/docs/html/T_Accord_Controls_Chart.htm

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue. The Chart class came from the AForge.NET Framework, from a time when better charting solutions were not really available for the .NET Framework. This class is mainly intended to support applications that had already been written using AForge.NET and that would benefit from porting to Accord.NET.

At this time, if you I would recommend using a more complete charting solution for .NET such as ZedGraph or [Microsoft's own charting controls](https://code.msdn.microsoft.com/Samples-Environments-for-b01e9c61).
