### ISSUE TITLE
GeneralizedBetaDistribution.ProbabilityDensityFunction does not have an area of 1

### ISSUE THREAD

**Issue by arubiomoreno** [accord-net/framework#630]
The PDF should have an area of 1 by definition. The current implementation has an area of `Support.Length`. The fix is as simple as changing this line:
`return constant * Math.Pow(z, alpha - 1) * Math.Pow(1 - z, beta - 1);`
for this line:
`return constant * Math.Pow(z, alpha - 1) * Math.Pow(1 - z, beta - 1) / Support.Length;`

Edit: check also `GeneralizedBetaDistribution.LogProbabilityDensityFunction`

**Comment by cesarsouza** [comment]
Hi Arubio,

Huge thanks! I will commit the fix in a moment, after all the unit tests finish passing.
