### ISSUE TITLE
ExponentialDistribution.DistributionFunction return values outside [0,1]

### ISSUE THREAD

**Issue by arubiomoreno** [accord-net/framework#632]
The result of the CDF should be checked to be between 0 and 1.
I could do this on the calling side, but the problem that I am ultimately having is that the class `Accord.Statistics.Testing.KolmogorovSmirnovTest` calls this function, gets negative probabilities, and therefore returns values greater than 1.

PS: Thanks a lot for the fast responses & fixes. When should we expect this changes to be on NuGet?

**Comment by cesarsouza** [comment]
Many thanks!

I am planning to do a alpha release on NuGet still this weekend.

Regards,
Cesar

**Comment by cesarsouza** [comment]
By the way, would you have an unit test / parameter values reproducing the issue?

**Comment by cesarsouza** [comment]
Fixed in release 3.6.0.
