### ISSUE TITLE
CUDA support !

### ISSUE THREAD

**Issue by Adesun** [accord-net/framework#634]
Hi,@c
 Thanks for doing such a amazing work.
it is great for dotnet developers, but training time might be a nightmare.
especially for task on images. I found one interesting project [managedCuda](https://github.com/kunzmi/managedCuda) 
which is complete .net wrapper for the CUDA Driver API. 
so maybe it's time to merge it into Accord framework.
best regards!
Adesun

**Comment by larcai** [comment]
[Alea GPU](http://www.aleagpu.com/release/3_0_3/doc/introduction.html) is also a good option.  
With Alea the GPU kernels is generated at compile time from C#
They do have a community version and [Nuget Packages](http://www.aleagpu.com/release/3_0_3/doc/introduction.html)

**Comment by endeffects** [comment]
i tried this and this does not work well with decoupled frameworks. Alot of code has to be changed for a real benefit. Also Alea supports only one GPU for the free community license, so don't expect any great performance boost in comparison to multithreaded cpu.

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue! And also thanks both of you for the suggestions. However, I have to say that it is very likely that support for GPU processing and CUDA will be added through TensorFlowSharp.

(also related: #92)

Regards,
Cesar

**Comment by endeffects** [comment]
I wonder if this will work for OneVsMany also?

**Comment by cesarsouza** [comment]
GPU support will be implemented through [Keras Sharp](https://github.com/cesarsouza/keras-sharp)

@endeffects: sorry, actually I hadn't seen your update! Answering your question, there are currently no plans to add support for computing SVMs using the GPU. However, it might be doable once we have Keras Sharp ready (we could use Keras models using OneVsMany or OneVsOne if desired, for example).

Regards,
Cesar

**Comment by endeffects** [comment]
Thanks for the information. I'll have a look into it when i have finished my base implementation.
