### ISSUE TITLE
Add an Example for QLearning Class

### ISSUE THREAD

**Issue by mite51** [accord-net/framework#638]
Please add an example for QLearning Class.

Maybe a simple scenario like "tic tac toe" or "tower of hanoi"? Or perhaps a more relevant one like a thermostat control to maintain a temperature range while trying to maximize efficiency?

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_QLearning.htm

**Comment by cesarsouza** [comment]
An example for the QLearning class has been added in release 3.8.0. It is a documentation-example version of the [Animat (QLearning and Sarsa) sample application](https://github.com/accord-net/framework/wiki/Sample-applications#animat-qlearning-and-sarsa) that comes included with the framework.
