### ISSUE TITLE
Add an Example for ProportionalHazardsNewtonRaphson Class

### ISSUE THREAD

**Issue by taiboontan** [accord-net/framework#646]
Please add an example for ProportionalHazardsNewtonRaphson Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Regression_Fitting_ProportionalHazardsNewtonRaphson.htm

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
