### ISSUE TITLE
Add an Example for MatReader.Read Method (String)

### ISSUE THREAD

**Issue by AdarshRai198** [accord-net/framework#656]
Please add an example for MatReader.Read Method (String).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_IO_MatReader_Read.htm

**Comment by cesarsouza** [comment]
Documentation for multiple methods of the MatReader class, including Read(string), have been added to the [main documentation page for the MatReader class](http://accord-framework.net/docs/html/T_Accord_IO_MatReader.htm).
