### ISSUE TITLE
Add an Example for MultilabelSupportVectorMachine.Load Method (String)

### ISSUE THREAD

**Issue by hfurukawa47** [accord-net/framework#657]
Please add an example for MultilabelSupportVectorMachine.Load Method (String).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_VectorMachines_MultilabelSupportVectorMachine_Load_1.htm

**Comment by cesarsouza** [comment]
This API has been deprecated. For loading and saving models, please use the [Accord.IO.Serializer](http://accord-framework.net/docs/html/T_Accord_IO_Serializer.htm) class.
