### ISSUE TITLE
Add an Example for LogLikelihoodLoss Class

### ISSUE THREAD

**Issue by zws3mb** [accord-net/framework#660]
Please add an example for LogLikelihoodLoss Class.

TODO (optional): Want to convert from using a LogisticGradientDescent solver (computing error via "Run(double[][] sample, double[] expected)" to using the LogLikelihoodLoss class. It is unclear to me how the Loss classes should be used, since they are not initialized with a reference to dimensionality or a model and the methods seem to only accept expected

Help Topic: http://accord-framework.net/docs/html/T_Accord_Math_Optimization_Losses_LogLikelihoodLoss.htm

**Comment by cesarsouza** [comment]
Added in 3.8.0.
