### ISSUE TITLE
Please add an example CsvWriter Class.

### ISSUE THREAD

**Issue by volley84** [accord-net/framework#663]
Or is there the examples?

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue! May I ask how you would like to use the CsvWriter? For example, are you trying to write matrices, jagged arrays, DataTables, or other specific types to .csv files?

Regards,
Cesar

**Comment by volley84** [comment]
Thanks for your reply. I wrote the code below, but how do you "CsvWriter"?

void WriteFloatToCsv(float[] Data, int ClassText)
        {
            string path = @"Data.csv";
            {
                using (StreamWriter sw = File.AppendText(path))
                {
                    for (int i = 0; i < jointDataF.Length;i++)
                    {
                        sw.Write(jointDataF[i]);
                        sw.Write(",");
                    }
                    sw.Write(ClassText);
                    sw.WriteLine();
                }
            }

Is there still a fix for the code "CsvReader" below?

void ReadCsvToDouble(string path, out double[][] inputs, out int[] outputs)
        {

            double[][] train;
            CsvReader cr = new CsvReader(path,true);
            train = cr.ToJagged();
            inputs = new double[train.Length][];
            for(int i = 0; i<train.Length;i++)
                inputs[i] = new double[train[i].Length-1];

            outputs = new int[train.Length];

            for(int i=0;i<inputs.Length;i++)
                for(int j=0;j<inputs[i].Length;j++)
                    inputs[i][j] = train[i][j];

            for (int i = 0; i < outputs.Length; i++)
                outputs[i] = Convert.ToInt32(train[i][train[i].Length-1]);
        }

**Comment by cesarsouza** [comment]
Hi there,

Here is an example on how to write a matrix to a .csv file:

```csharp
string filename = "matrix.csv";

double[,] values =
{
    { 1,  2,  3,  4 },
    { 5,  6,  7,  8 },
    { 9, 10, 11, 12 },
};

using (CsvWriter writer = new CsvWriter(filename))
{
    writer.WriteHeaders("a", "b", "c", "d");
    writer.Write(values);
}
```

and here is how to read it back using CsvReader:

```csharp
CsvReader reader = new CsvReader(filename, hasHeaders: true);
double[,] actual = reader.ToMatrix();
```

It also work with jagged arrays (double[][]) if you replace ToMatrix with ToJagged:

```csharp
CsvReader reader = new CsvReader(filename, hasHeaders: true);
double[][] actual = reader.ToJagged();
```

**Comment by cesarsouza** [comment]
If you are storing the output labels as the last column of your csv file, you can use the following code to retrieve it:

```csharp
double[][] inputs = actual.Get(null, 0, -1); // null means 'all rows', and 0 to -1 means from first column to the one before the last
int[] outputs = actual.GetColumn(-1).ToInt32(); // will get the last column and convert to int
```

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
