### ISSUE TITLE
Add an Example for MultivariateNormalDistribution.DistributionFunction Method

### ISSUE THREAD

**Issue by kesumu** [accord-net/framework#667]
Please add an example for MultivariateNormalDistribution.DistributionFunction Method.

TODO (optional): Sorry for my poor acknowledge, why this method is not supported for 3+ dimensions data?

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Distributions_Multivariate_MultivariateNormalDistribution_DistributionFunction.htm

**Comment by cesarsouza** [comment]
Examples on how to use the DisstributionFunction method of the MultivariateNormalDistribution are available in the [MultivariateNormalDistribution documentation page](http://accord-framework.net/docs/html/T_Accord_Statistics_Distributions_Multivariate_MultivariateNormalDistribution.htm).
