### ISSUE TITLE
NuGet and Mono

### ISSUE THREAD

**Issue by jeremejevs** [accord-net/framework#668]
Quick question: Why exclude Mono binaries from NuGet packages?

**Comment by cesarsouza** [comment]
Hi there,

Because [it is not currently possible to target plain Mono (for Linux) using NuGet packages](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks). It might be possible to target Xamarin, though, but I have no experience with any of their specialized frameworks, and I do not have a Mac to test whether everything works with MonoMac/Xamarin.Mac.

**Comment by dsyme** [comment]
@cesarsouza We tend to just rely on Travis CI to make sure everything works on Mono+Linux and Mono+OSX for F#, e.g. https://github.com/fsharp/fsharp/blob/master/.travis.yml

I see you have a travis file already.  But you can also set up a matrix so that the build+tests run on Mono "latest" and Mono "weekly" etc.  You can also request OSX too

Out of curiosity why are the Mono binaries different?

**Comment by cesarsouza** [comment]
The framework mostly runs on Mono, except for a few classes and some functionality that has to be excluded. For instance, Mono (at least used to) choke completely when trying to compile the [Naive Bayes framelet](https://github.com/accord-net/framework/blob/development/Sources/Accord.MachineLearning/Bayes/Learning/Base/NaiveBayesLearningBase%605.cs), [VPTreeNodes](https://github.com/accord-net/framework/blob/development/Sources/Accord.MachineLearning/Collections/Base/VPTreeNodeBase.cs) and requires some [special handling in for System.Drawing](https://github.com/accord-net/framework/blob/development/Sources/Accord.Imaging/Tools.cs#L572).

PS: I recognize that the Naive Bayes base classes are pushing the boundaries of generic arguments quite a bit, but the result is that the final models can be perfectly type-safe during use, which I consider a plus as I consider that most new users discover how to use the framework by dot-oriented programming (i.e. intellisense).

**Comment by dsyme** [comment]
>  and requires some special handling in for System.Drawing.

You can use a dynamic check like "runningOnMono" for some of those cases? https://github.com/Microsoft/visualfsharp/blob/82c9492ed9a1c2dbe118220c13dae525936f2f63/tests/service/FscTests.fs#L35

Looking at that list it seems quite small, and you would be better off just throwing exceptions, and having one consistent set of nuget packages.

**Comment by cesarsouza** [comment]
Thanks, indeed this would help with the System.Drawning handling. However, if I remove the other conditional compilation directives, the project would not compile on Linux using Mono and therefore wouldn't run on Travis.

But anyways, I am not really excluding Mono from the NuGet packages. I believe that Mono can run the .dlls that target .NET 4.0, 4.5 and 4.6 even if they had been compiled by the .NET compilers on Windows, right? Then in this case, using a dynamic check like you suggested would really suffice. I will look into that, thanks!

**Comment by dsyme** [comment]
> But anyways, I am not really excluding Mono from the NuGet packages. I believe that Mono can run the .dlls that target .NET 4.0, 4.5 and 4.6 even if they had been compiled by the .NET compilers on Windows, right? Then in this case, using a dynamic check like you suggested would really suffice. I will look into that, thanks!

Yes, looking at your code your binaries should be fine to run. The problems usually come with native binaries (e.g. Intel MKL etc.) if you use it

**Comment by jeremejevs** [comment]
Thanks for the information, @cesarsouza! Indeed, I thought that the `mono` directory in the regular framework releases was **for** Mono, not **by** Mono. Please don't start moving/renaming/clarifying things on my account though, I'm a complete .NET/Mono novice, with a tendency for "please keep your tutorials and starter guides away from me" learning approach, and I'm making a lot of invalid assumptions.
