### ISSUE TITLE
LinearDualCoordinateDescent is very slow to train a model when the Complexity property is set

### ISSUE THREAD

**Issue by alexandrekow** [accord-net/framework#679]
Hello,

I tried to train a model with the [Liblinear example provided in samples](https://github.com/accord-net/framework/tree/development/Samples/MachineLearning/Liblinear%20(SVMs)):

When I train my model with  -c 1, I would expect the code to set the Complexity parameter to 1, but instead it does not, which results in creating the following learner:

```
return new LinearDualCoordinateDescent<Linear, Sparse<double>>()
{
    Loss = Loss.L2,
    PositiveWeight = 1,
    NegativeWeight = 1,
    **UseComplexityHeuristic = true**
};
```
In this case it takes 20 seconds to train my model.

When I try to train the same model with 
```
return new LinearDualCoordinateDescent<Linear, Sparse<double>>()
{
    Loss = Loss.L2,
    Complexity = 1,
    UseComplexityHeuristic = false
};
```
it takes **13 min and 50 seconds.**

The same model takes 2 seconds to train with C++ Liblinear.

- Why such a difference when setting the Complexity parameter?
- Why is the code so much slower than the C++ version?

Thanks,

**Comment by cesarsouza** [comment]
Hi Alexandre,

Many thanks for opening the issue. Are you running the code in release mode, and outside Visual Studio (i.e. by double-clicking the .exe instead of hitting F5 in VS)?

Regards,
Cesar

**Comment by cesarsouza** [comment]
Also, may I ask which dataset you were using when performing those tests?

Regards,
Cesar

**Comment by alexandrekow** [comment]
Hello. Sorry for the late reply I did not receive a notification! I do not remember if I was in debug mode or not. I will check once I am at work and answer you on this matter. The tests are performed on a custom dataset, I will try to see if I can reproduce with a more widely available dataset.

**Comment by alexandrekow** [comment]
Hello,

I am back on this matter. 

I run the program by double-clicking the .exe instead of hitting F5 in VS. 

The dataset is a private dataset consisting of textual data.
The y training data is an array of 33951 bool and the x data is a Sparse<double> object representing a matrice of 33951 rows and 54531 columns.  

I think you can easily use the [news20 ](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass.html#news20) dataset or rcv1v2 to reproduce the issue.

Best regards,

Alexandre
