### ISSUE TITLE
BalancedKMeans stuck

### ISSUE THREAD

**Issue by sdluxeon** [accord-net/framework#684]
Hello I have the following data and the learning is stuck...
Any Ideas?
Am I using it wrong?
```
var balancedKMeans = new Accord.MachineLearning.BalancedKMeans(3);
balancedKMeans.MaxIterations = 1;
var matrix = new double[34][];
matrix[0] = new double[] { 1, 1, 26524 };
matrix[1] = new double[] { 1, 1, 87 };
matrix[2] = new double[] { 1, 1, 260 };
matrix[3] = new double[] { 1, 1, 1179 };
matrix[4] = new double[] { 1, 1, 264 };
matrix[5] = new double[] { 1, 1, 227 };
matrix[6] = new double[] { 1, 1, 176 };
matrix[7] = new double[] { 1, 1, 16 };
matrix[8] = new double[] { 1, 1, 995 };
matrix[9] = new double[] { 1, 1, 438 };
matrix[10] = new double[] { 1, 1, 28 };
matrix[11] = new double[] { 1, 1, 957 };
matrix[12] = new double[] { 1, 1, 91 };
matrix[13] = new double[] { 1, 1, 666 };
matrix[14] = new double[] { 1, 1, 1157 };
matrix[15] = new double[] { 1, 1, 968 };
matrix[16] = new double[] { 1, 1, 34 };
matrix[17] = new double[] { 1, 1, 1385 };
matrix[18] = new double[] { 1, 1, 430 };
matrix[19] = new double[] { 1, 1, 1247 };
matrix[20] = new double[] { 1, 1, 1536 };
matrix[21] = new double[] { 1, 1, 1074 };
matrix[22] = new double[] { 1, 1, 1316 };
matrix[23] = new double[] { 1, 1, 217 };
matrix[24] = new double[] { 1, 1, 475 };
matrix[25] = new double[] { 1, 1, 1036 };
matrix[26] = new double[] { 1, 1, 343 };
matrix[27] = new double[] { 1, 1, 987 };
matrix[28] = new double[] { 1, 1, 189 };
matrix[29] = new double[] { 1, 1, 157 };
matrix[30] = new double[] { 1, 1, 903 };
matrix[31] = new double[] { 1, 1, 17 };
matrix[32] = new double[] { 1, 1, 1323 };
matrix[33] = new double[] { 1, 1, 668 };

var learnResult = balancedKMeans.Learn(matrix);//stuck
Console.WriteLine(balancedKMeans.Labels.Count());
```

**Comment by cesarsouza** [comment]
Hi @sdluxeon,

Thanks for opening the issue! It seems that you are using it right since you are specifying a minimum number of iterations which should have prevented it from getting stuck. Have you tried/been able to follow the code with a debugger?

It could be that the algorithm is actually stopping, but the code is getting stuck while computing cluster information, which is done after the clustering is finished. Can you try to set ComputeCovariances and ComputeError to false and see if you still get the issue?

I am trying to prepare a new release, so I can't investigate this exactly right now. Hopefully the making the new release won't take long.

**Comment by sdluxeon** [comment]
It stucks at find_all_zeros in step four, it's been raining for 16 hours now


	Accord.Math.dll!Accord.Math.Optimization.Munkres.find_all_zeros()	Unknown
 	Accord.Math.dll!Accord.Math.Optimization.Munkres.step_four()	Unknown
 	Accord.Math.dll!Accord.Math.Optimization.Munkres.RunStep(int step)	Unknown
 	Accord.Math.dll!Accord.Math.Optimization.Munkres.run(double[][] m)	Unknown
 	Accord.MachineLearning.dll!Accord.MachineLearning.BalancedKMeans.Learn(double[][] x, double[] weights)	Unknown
 	Polaris.exe!Polaris.WebForms.Program.Main() Line 59	C#

**Comment by cesarsouza** [comment]
Hi there,

Many thanks for the call stack! Please don't let it running for this long; it is obviously a bug in the Munkres algorithm implementation.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Well, actually this is weird, I couldn't manage to reproduce the issue. Can you try to upgrade to the latest release (3.6.0, released yesterday) and see if the issue persists?

Regards,
Cesar

**Comment by cesarsouza** [comment]
The bug depends on the seed initialization. I am investigating it now.

**Comment by cesarsouza** [comment]
The problem is that value of the Tolerance property of the Munkres algorithm was not being used in one of the cost comparisons.

**Comment by sdluxeon** [comment]
Thank you very much for the support! When do you expect to have this fixed?

**Comment by cesarsouza** [comment]
You can already download a pre-release package with the fix. Please enable the "include pre-release" checkbox when searching for the Accord.NET packages in the NuGet browser, and install the latest available option.

Please let me know if it works!

**Comment by cesarsouza** [comment]
Added in the 3.7.0. release.
