### ISSUE TITLE
Add an Example for Codification.Translate Method (String, Int32)

### ISSUE THREAD

**Issue by Hamxa18** [accord-net/framework#686]
Please add an example for Codification.Translate Method (String, Int32).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Filters_Codification_Translate_1.htm

**Comment by cesarsouza** [comment]
The Translate method is obsolete. As mentioned in the message, please use the Revert(columnName, codeword) method instead.
