### ISSUE TITLE
Having hard time using NuGet Package Manager to Install New Updates of Accord.Net

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#691]
Last year I downloaded direct the installer .Exe > "Accord.NET-3.3.0-installer.exe"

So, I installed and used Accord.Net directly.

Now, I used different computer and I want to install it directly using the latest update version 3.6.0...

@cesarsouza can you send a link that we can use or install it directly from any other computer.

thank you.

**Comment by cesarsouza** [comment]
Hi @blaisexen! 

What kind of errors are you getting when trying to install the project using NuGet?

Regards,
Cesar

**Comment by blaisexen** [comment]
PM> Install-Package Accord
Install-Package : The current environment doesn't have a solution open.
At line:1 char:16
+ Install-Package <<<<  Accord
    + CategoryInfo          : InvalidOperation: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetNoActiveSolution,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by cesarsouza** [comment]
You have to create or open a project first. After you have have a project open in visual studio, right click the "References" item in your project, in the the Solution Explorer window, and click "Manage NuGet packages":

![image](https://user-images.githubusercontent.com/528455/27992936-d2843586-649f-11e7-86bd-07bace94e965.png)

**Comment by cesarsouza** [comment]
From there you can click on the "Browse" tab and search for any package you would like to install.

**Comment by cesarsouza** [comment]
Hi, I am assuming this issue has been fixed. If it hasn't, please re-open this issue again.

**Comment by blaisexen** [comment]
Yes, thank you, sorry for the inconvenienced.
