### ISSUE TITLE
Add support for weighted least squares

### ISSUE THREAD

**Issue by cesarsouza** [accord-net/framework#694]
And update https://stackoverflow.com/questions/41619834/why-weights-in-accrod-net-simplelinearregression-have-no-effect

**Comment by peters** [comment]
@cesarsouza Would a bounty help speed this one along? And if so, how large? :)

**Comment by cesarsouza** [comment]
One thousand euros :wink: 

I am just kidding - actually the support for weights in least squares has already been implemented, but I forgot to reference this issue in the commit: https://github.com/accord-net/framework/commit/3ed8e195f57582281b3baea367351c686670bdfe

If you need it urgently, you can try to clone the framework and compile from the sources (it should be only a matter of pressing F5 in VS). But I can also try to generate a new pre-release package if you prefer, but it might indeed take a while.

Regards,
Cesar

**Comment by peters** [comment]
@cesarsouza Check your gmail ;) Would you mind creating a pre-release package? 🥇

**Comment by peters** [comment]
@cesarsouza From a geometric perspective when faced with matrix singularity would you recommend adding some random noise (e.g. +- 5 RNG) to each x/y coordinate or simply removing each pair `Point` that causes a singularity to occur in the first place? 

Source: https://stats.stackexchange.com/a/70910

**Comment by cesarsouza** [comment]
I am starting to prepare a new pre-release, but it might take some moments until everything compiles and is uploaded to NuGet :-)

Regarding the question, I am not sure about the geometric perspective part, but in case I faced a singular matrix problem when doing linear regression I would just opt to use the SVD to solve it instead. If I am not mistaken, using the SVD should be akin to dropping the linear dependent vectors from the matrix before solving the system, but you wouldn't have to worry about doing this manually.

You can solve the linear system using SVD by setting the [IsRobust property](http://accord-framework.net/docs/html/P_Accord_Statistics_Models_Regression_Linear_OrdinaryLeastSquares_IsRobust.htm) of the OrdinaryLeastSquares class to true before calling ```.Learn()```.

Regards,
Cesar

**Comment by peters** [comment]
@cesarsouza That makes sense, thanks for the tip. I probably should have mentioned that i was using `PolynomialLeastSquares` not `OrdinaryLeastSquares` 🤣

**Comment by cesarsouza** [comment]
Oh yeah that would be a nice thing to mention :-) but the technique is completely the same in both cases. It is nice that you mentioned because the IsRobust was missing from the PolynomialLeastSquares class. I've just added it.

**Comment by cesarsouza** [comment]
I am uploading the new packages to NuGet, they should be available in about 20-30 minutes :-)

**Comment by peters** [comment]
@cesarsouza Hehe 🔢 Wow, that was fast :) Looking forward playing around with `Weights`  and `IsRobust`. I think it will be a yield a significant when it comes with some edge-cases (NDA) I've been very eager to solve.

**Comment by cesarsouza** [comment]
Included in release v3.7.0.
