### ISSUE TITLE
Add an Example for ConditionalRandomField(T) Constructor

### ISSUE THREAD

**Issue by PraveenDuvvuri** [accord-net/framework#698]
Please add an example for ConditionalRandomField(T) Constructor.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Models_Fields_ConditionalRandomField_1__ctor.htm

**Comment by cesarsouza** [comment]
Thanks for opening the issue. Instead of adding an example for the constructor, I will be adding an example to the main ConditionaRandomField documentation page.
