### ISSUE TITLE
Merge with AForge.NET

### ISSUE THREAD

**Issue by cesarsouza** [accord-net/framework#70]
In the early days, Accord.NET was created and designed as an extension framework for AForge.NET. However, since 2012, AForge.NET public support was ended. Thus, the current plan is to incorporate AForge.NET directly in Accord.NET, merging the two. 

This will solve https://github.com/accord-net/base/issues/3

**Comment by cesarsouza** [comment]
Since this would be a major breaking change, take this opportunity to:

 - Add  a static Vector class to accommodate vector operations (like the Matrix class)
 - Add a static Jagged class to accomoddate Jagged matrix operations (like the Matrix class)
 - Add a static Random class to hold randomization methods (such as Shuffling, RandomGroups, etc)

**Comment by cesarsouza** [comment]
Also make all distributions implement the INumberGenerator interface.

**Comment by aloisdg** [comment]
Nice idea !

**Comment by mathias-brandewinder** [comment]
A merge sounds reasonable; at that point, it's not entirely clear why some things are in one or the other library, and it makes finding things in various namespaces harder.
One thought: if additional algebra operations are going to be added, it might be worth re-visiting the idea of integrating with Math.NET? While Accord has expanded on the machine learning side, Math.NET has added some nice algebra features. One in particular is very interesting: the MKL provider (http://christoph.ruegg.name/blog/mathnet-numerics-with-native-linear-algebra.html)

**Comment by ethanwa** [comment]
Love this idea. One of the things I'd love to see moved over is FLANN.

**Comment by binbsr** [comment]
I actually love addition of algebraic operations. I have been using my own
custom methods like submatrix(), shuffle() etc. Waiting for the blend...

**Comment by cesarsouza** [comment]
The AForge.NET codebase has been merged into the project. At this current stage, the two projects have been just blended in, and all previous namespaces (i.e. AForge.* namespaces) are still preserved.

The current plan is to ease the transition of projects linking against AForge.NET so they could be updated to refer to Accord.NET instead with minimum effort. As such, a new intermediary release will be produced without changing any AForge.NET namespace locations. This new release would be a direct drop-in replacement for AForge.NET, minimizing the number of breaking changes caused by the merge.

After this intermediary release, the two codebases will be integrated more closely, merging namespaces, removing duplicated functionality and extending existent features.

**Comment by aloisdg** [comment]
Great news !

**Comment by binbsr** [comment]
That's great...

**Comment by hzawary** [comment]
Ideal idea:) but why I don't see some classes since merge those, e.g. SOM or etc. I think the better one is adding whole of AForge namespaces.

**Comment by cesarsouza** [comment]
It is in the works! :smile:

**Comment by hzawary** [comment]
Thanks to response, in actually I can't set NumberOfVertices to more than 3
points, caused the exception! In addition, vertices set to 20 in
initialization class. Exist repugnance!

private int vertices = 20;

    /// <summary>
    /// Gets or sets the number of vertices.
    /// </summary>
    ///
    public int NumberOfVertices
    {
        get { return vertices; }
        set
        {
            if (value <= 0 || value > 3)
                throw new ArgumentOutOfRangeException("value",
                    "Number of vertices should be between 0 and 3.");

            vertices = value;
        }
    }


On Tue, Jan 5, 2016 at 9:38 PM, César Souza <notifications@github.com>
wrote:

> It is in the works! [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/accord-net/framework/issues/70#issuecomment-169084655>
> .
>



-- 
_______________________________________________________
Hashem Zavvari, BSc SWE.
Present, MSc SWE student at Research & Science branch of IAU.
Islamic Republic of Iran, Mashhad.

**Comment by AlexJCross** [comment]
Can this branch be deleted?

**Comment by cesarsouza** [comment]
Yep!
