### ISSUE TITLE
GeneralizedParetoDistribution shape param 

### ISSUE THREAD

**Issue by nwiman** [accord-net/framework#715]
Hi,
why has the shape param in the GeneralizedParetoDistribution a limit in the latest release?

[Positive(minimum: 2)] double shape
if (shape <= 1)
            throw new ArgumentOutOfRangeException("**scale**", "Shape must be higher than 1.");

Guess that the scale in ArgumentOutOfRangeException is just a typo.

best regards
Weeman

**Comment by cesarsouza** [comment]
Hi,

Thanks for opening the issue. It was added by mistake and will be reverted. Would it be feasible for you to keep using the previous version until its fixed?

Regards,
Cesar

Regards,
Cesar

**Comment by nwiman** [comment]
No problem, i'm on the rc right now beacuse i need the functionality to inject another system.random.

Cheers
Weeman

**Comment by cesarsouza** [comment]
New pre-release packages (3.6.4-alpha) have just been uploaded to NuGet, which should hopefully contain a fix for the above issue. Thanks again for reporting!

**Comment by cesarsouza** [comment]
Included in 3.7.0.
