### ISSUE TITLE
UnmanagedImage uses QuadrilateralTransformation to present bugs

### ISSUE THREAD

**Issue by OGeeks** [accord-net/framework#716]
When using the UnmanagedImage format, use QuadrilateralTransformation to extract the image. If the connection between the first two points is between 1 and 3 quadrants(The object tilts to the right with an error, but the left is no problem), there is a problem with the extracted range. When checking the data of the four points, the following code is temporarily used to make up :

private static void QuadrantDetection(ref List<IntPoint> corners)
{
            IntPoint p0 = corners[0];

            if (p0.DistanceTo(corners[1]) > p0.DistanceTo(corners[3]))
            {
                corners.RemoveAt(0);
                corners.Add(p0);
            }
}
This problem is only in the UnmanagedImage format, and bitmap does not have this problem.
![-1](https://user-images.githubusercontent.com/22830222/28262966-adb4cb3e-6b17-11e7-8537-abea667149c1.jpg)

**Comment by OGeeks** [comment]
I made a mistake.................

**Comment by blaisexen** [comment]
that's very good, we are not perfect!
