### ISSUE TITLE
ArrayToImage and MatrixToImage have redundant but different implementations

### ISSUE THREAD

**Issue by heltonbiker** [accord-net/framework#719]
Both `ArrayToImage` and `MatrixToImage` classes implement interfaces with jagged arrays in the signature:

        IConverter<double[][], Bitmap> 
        IConverter<double[][], UnmanagedImage>
        IConverter<float[][], Bitmap>
        IConverter<float[][], UnmanagedImage>
        IConverter<byte[][], Bitmap>
        IConverter<byte[][], UnmanagedImage>

And the implementations are not the same.

**Comment by heltonbiker** [comment]
For example, the first `Convert` method is implemented like this in `ArrayToImage`:

        public void Convert(double[][] input, out Bitmap output)
        {
            PixelFormat format;
            int channels = input[0].Length;

            switch (channels)
            {
                case 1:
                    format = PixelFormat.Format8bppIndexed;
                    break;

                case 3:
                    format = PixelFormat.Format24bppRgb;
                    break;

                case 4:
                    format = PixelFormat.Format32bppArgb;
                    break;

                default:
                    throw new ArgumentException("Unsupported image pixel format.", "input");
            }


            output = new Bitmap(Width, Height, format);

            BitmapData data = output.LockBits(ImageLockMode.WriteOnly);

            int pixelSize = System.Drawing.Image.GetPixelFormatSize(format) / 8;
            int offset = data.Stride - Width * pixelSize;
            int src = 0;

            unsafe
            {
                byte* dst = (byte*)data.Scan0.ToPointer();

                for (int y = 0; y < Height; y++)
                {
                    for (int x = 0; x < Width; x++, src++)
                    {
                        for (int c = channels - 1; c >= 0; c--, dst++)
                        {
                            *dst = (byte)Vector.Scale(input[src][c], Min, Max, (byte)0, (byte)255);
                        }
                    }
                    dst += offset;
                }
            }

            output.UnlockBits(data);
        }

But it is implemented like this in `MatrixToImage`:

        public void Convert(double[][] input, out Bitmap output)
        {
            int width = input.Columns();
            int height = input.Rows();

            if (Format == PixelFormat.Format8bppIndexed)
                output = Accord.Imaging.Image.CreateGrayscaleImage(width, height);
            else output = new Bitmap(width, height, Format);

            BitmapData data = output.LockBits(ImageLockMode.WriteOnly);

            int pixelSize = System.Drawing.Image.GetPixelFormatSize(Format) / 8;

            int offset = data.Stride - width * pixelSize;

            unsafe
            {
                byte* dst = (byte*)data.Scan0.ToPointer();

                for (int y = 0; y < height; y++)
                {
                    for (int x = 0; x < width; x++)
                    {
                        double v = 255 * (input[y][x] - Min) / (Max - Min);
                        byte value = unchecked((byte)v);

                        for (int c = 0; c < pixelSize; c++, dst++)
                            *dst = value;
                    }

                    dst += offset;
                }

                if (pixelSize == 4)
                {
                    dst = (byte*)data.Scan0.ToPointer();

                    for (int y = 0; y < height; y++)
                    {
                        for (int x = 0; x < width; x++, dst += pixelSize)
                            dst[RGB.A] = 0;
                        dst += offset;
                    }
                }
            }

            output.UnlockBits(data);
        }

**Comment by heltonbiker** [comment]
The same seems to happen with classes `ArrayToMatrix` and `ImageToMatrix`.

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue! As far as I recall, the implementations are not redundant:

 - ArrayToMatrix interprets the double[][] as an array of pixel values, meaning the first dimension corresponds to the number of pixels in the to-be matrix and the second dimensions to the number of channels in the pixels (i.e. 3 for RGB, 4 for RGBA). 
 - ImageToMatrix interprets the double[][] as a matrix of pixel values, meaning the first dimension corresponds to the height of the image and the second dimension to the width of the image.

I guess this should be made clearer in the documentation.

Regards,
Cesar

**Comment by heltonbiker** [comment]
Well, I guess this solves the issue then. I'm not sure if the docs omit the distinction, or the confusion was due to my unfamiliarity with the API regarding what is understood by "Matrix (of pixels, apparently)", vs "Array (of bytes apparently)". Your explanation made it clear, thanks!
