### ISSUE TITLE
Brent search successfully finds an incorrect root

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#725]
Brent search incorrectly `FindRoot()` when both bounds result in f(x) > 0. 

The following is lifted _directly_ from the [documentation ](https://github.com/accord-net/framework/wiki/Mathematics#numeric-optimization)on the Wiki (before I corrected it yesterday). It was intending to demo the `FindRoot()` function but was, itself, giving the incorrect answer.

```csharp
Func<double, double> function = x => x * x * x + 2 * x * x - 10 * x;
var search = new BrentSearch(function, -4, 3);

// Finally, we can query the information we need
bool max = search.Maximize();  // occurs at -2.61
bool min = search.Minimize();  // occurs at  1.27
bool root = search.FindRoot(); // occurs at -0.50

Console.WriteLine(search.Value); // value is 5.375 not 0. This is *wrong*
```

This is happening because the function crosses the y-axis twice. Once at x=0 and again at x=2.32.
```csharp
double lower = function(-4); // 8
double upper = function(+3); // 15
```

The correct behaviour should be:
- Find one of the two roots stated above; or
- Check the sign of the bounds and throw an exception; or
- Check the sign of the bounds and return `false`

`root` currently comes back as `true` which is very misleading / incorrect.

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Thanks a lot for the issue report, and thanks even more for fixing the Wiki. This will be fixed in the next release (but will also most likely be included in the next pre-release, to happen in the next very few days).

Regards,
Cesar

**Comment by cesarsouza** [comment]
By the way - sorry for the delay in answering, I was mostly without proper Internet access in the past 10 days.

**Comment by AlexJCross** [comment]
That's no problem at all and thanks for looking into it. 

Thinking about it some more, I think the best option would be to have the search return `false` and add a `Status` property explaining why it failed. This would be consistent with the behaviour of the multivariable solvers in the library. If you need a hand, I can probably send a PR this weekend.

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Thanks a lot, indeed this seems like the best option for now. If you wouldn't mind, then please submit a pull request. It is sometimes a bit hard to find enough time to solve all the issues in a timely fashion, so all the help would be welcome!

Regards,
Cesar

**Comment by AlexJCross** [comment]
Hi @cesarsouza 

I'll see if I can squeeze it in this weekend and keep you posted.

Thanks,
Alex

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Was this included in any of the previous pull requests? If not I might give it a try today.

Regards,
Cesar

**Comment by AlexJCross** [comment]
Hi @cesarsouza 

Sorry for being a bit slow on this (I promise I hadn't forgotten!). I've been moving house so am finding it harder than expected to get computer access at the mo. 

As I recall, I looked into this but it wasn't completely clear what to do. I think the ideal solution was to return false and add a Status property as we said. However, when I looked into it a bit more, I think I concluded that, at present, it was impossible for the current version to ever return false (instead it would always throw an exception). 

In that respect, if I added proper error handling to the bool Find(...) method and a nice Status property it would techincically be a breaking change because a method that formerly threw an exception would no longer do so. If anyone was using the Brent search and had a try block to guard against failures, this could go undetected. 

So it's a trivial fix but I wasn't completely sure what the best approach is here. I didn't want my first PR to Accord to be a breaking change :) If you have thoughts and would like to go ahead, by all means do. That would be great. If you're short on time I will def get round to it by Monday. Thanks alex

**Comment by AlexJCross** [comment]
Hi @cesarsouza,

I will submit a PR for this shortly but I wanted to check a few things with you. Here's a breakdown of what's been done.

_A note on precision: I have not changed the inner workings of the algorithm in any way so the numbers should be identical._

#### Brent
I have reworked this so that the core routine now returns a `struct` that holds the `Solution`, `Value` and `Status` There were a couple of reasons to do this:
1. The `Value` is already being calculated so you get it for free. Previously, it was being recalculated in the `FindRoot()` method which was inefficient.
2. It's not so easy to give an informative `Status` message (when the search fails) after the routine has finished --- you'd have to interrogate the `ConvergenceException` error messages which is horrible. Much easier for the failing method to explain itself.
 
New feature: I've added a `MaxIterations` property and defaulted it to 500 which is waaay above what any reasonable Brent solve should take. Actually, it did break one test but that's because there was an issue, GH-816 - so it's already proven quite helpful :)

Performance: As noted, the `FindRoot()` method is a little faster because it does one less evaluation. I think this is splitting hairs but, technically, the public static method is slightly slower (because it returns a `struct` rather than a `double`). I hope that's not a problem but let me know if you think otherwise!

Breaking change: I haven't quite decided whether this a breaking change. In the existing implementation, it's impossible for `bool FindRoot()` to ever return `False` (it just throws if it fails). It now behaves as expected but this means that anyone who was testing for success via a `try-catch` block might find that their `catch` block no longer catches anything. Again, I don't think this is a big deal but let me know if you have any concerns.

Also, some minor corrections to the documentation as it was incorrectly documenting the return types.

##### Unit tests added
 - `BrentSearchTest.CreateSearchWithParametersSetPropertiesSetsCorrectly()` checks the `BrentSearch` has been initialised correctly.
 - `FindTest()` Added a test of the `Find` method (test via the static method and the instance method). 
 - `FindRootTest()` Added instance method check.
 - `MaximizeTest()` ditto on comment above.
 - `MinimizeTest()` ditto on comment above.
 - `FindRootBoundedTwiceFailsToSolve()` Checks that the search returns `False` if the root is bracketed twice.
 - `FindRootNotBoundedFailsToSolve()` Checks that the search returns `False` if the root is not bracketed at all.
 - `FindRootBoundedTwiceThrowsNonConvergenceException()` Checks that it now throws a `ConvergenceException` as required.
 - `FindRootNotBoundedThrowsNonConvergenceException()` ditto on comment above.
 - `FindRootWithLowMaxIterationsThrowsConvergenceException()` Checks that it throws if the `MaxIterations` is exceeded.
 - `MaximizeWithLowMaxIterationsThrowsConvergenceException()` ditto on comment above.
 - `MaximizeWithLowMaxIterationsFailsToSolveButGivesLastKnownSolution()` Checks that it returns `False` if the `MaxIterations` is exceeded. It returns the best solution found to date which I think is helpful.
 - `FindRootWithLowMaxIterationsFailsToSolveButGivesLastKnownSolution()` ditto on comment above.

##### Breakages
A number of tests broke as a result of my changes. Here are the fixes I had to put in place:
 - `BetaPrimeDistribution` I changed the support range because it was tripping on `MaxIterations`. This was happening because the bounds were not quite right (GH-816).
 - `UnivariateContinuousDistribution` a minor corner case where the Brent solver was being called with lower=upper=root no longer works. Fixed it, made it a bit faster.
 - `BaseOneSamplePowerAnalysis` was doing some gymnastics to determine if the found solution was incorrect. Simple fix - much clearer now as well.

# BUILD FAILING
I've tried to fix all breakages but I thought I'd ask you about this as I'm afraid I don't have familiarity with the Mann-Whitney distribution.
`Accord.Tests.Statistics.MannWhitneyDistributionTest.MedianTest_approximation()` is **failing**. I'm 99% sure it was never doing the right thing anyway but perhaps you could confirm or let me know otherwise? In the unit test, it is failing to compute the exact `Median` in the case where the number of observations in the second sample are less than in the first.  From what I have gathered [reading through the code](https://github.com/AlexJCross/framework/blob/development/Sources/Accord.Statistics/Distributions/Univariate/Continuous/MannWhitneyDistribution.cs#L222), n1 should really be less than n2. Before it was returning `double.MinValue` -- I don't think that looks right -- and now it simply throws a `ConvergenceException`.

If you agree, I think the way to fix this is to overwrite the `protected internal virtual double InnerInverseDistributionFunction(double p)` method and reverse the logic for computing the lower and upper bounds. Playing around with this, it looks like it will converge on 4 which, to me, sounds much more reasonable than `double.MinValue` but I'm not a statistician so may very well be wrong!

Let me know your thoughts and I'll be happy to update and submit.

Thanks,
Alex

**Comment by AlexJCross** [comment]
Hey @cesarsouza,

If you get a mo, would be great to get your thoughts on this. 

It's all ready to go bar one failing test that I'm not completely sure of. If it's easier, I could mark that test as Explicit (or the appropriate attribute - I forget) and simply merge it in? Can then create an issue for that?

Thanks!
Alex

Ps - sorry no commits from me lately. 100% tied up with house move I simply haven't been able to get to my laptop.

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Many thanks for the reminder about the issue and sorry for the delay in answering!

If I understood correctly, the test _only_ fails when ```n1 > n2``` right? In this case, please feel free to overwrite ```InnerInverseDistributionFunction(double p)``` and call a different function when this case happens, but please keep calling the original, ```base.InnerInverseDistributionFunction(p)``` when it doesn't. Please also emit a Trace.Warning() when ```n1 > n2``` like in the code you have linked.

The point is that most users would never have to use the MannWhitneyDistribution directly. This class is mostly intended to be used through the MannWhitneyWilcoxonTest, [which should have been already handling the case where ```n1 > n2```](https://github.com/accord-net/framework/blob/master/Sources/Accord.Statistics/Testing/TwoSample/MannWhitneyWilcoxonTest.cs#L239). If I recall correctly, the only reason the code is emitting a warning instead of an exception in the case you linked was to keep compatibility, so it may make sense to do the same here for the overriden inverse probability distribution.

The warnings will be replaced by exceptions once all the current obsolete/deprecated methods are finally removed in the next major release (i.e. Accord.NET 4.0).

Regards,
Cesar

**Comment by AlexJCross** [comment]
@cesarsouza  thanks for your response. I will look at this now and try to get it over the line 👍

**Comment by cesarsouza** [comment]
Added in 3.8.0.
