### ISSUE TITLE
DotAndDot performance for small problem sizes

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#726]
The current implementation of `DotAndDot(...)` computes the dot product of a vector with a matrix and then computes the dot product of the second vector with the resultant vector. This is inefficient; there is no need to create a resultant vector here.

This only affects small problems where the cost of allocation is comparable to the cost of matrix multiplication but it is more than twice as slow as an efficient implementation for a size of two.

================

The code below shows an implementation where `DotAndDot(...)` does not create an intermediate vector:

```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static double DotAndDotFast(this double[] rowVector, double[,] matrix, double[] columnVector)
{
    double s2 = 0;

    for (int i = 0; i < rowVector.Length; i++)
    {
        double s = 0;
        for (int j = 0; j < columnVector.Length; j++)
            s += matrix[i, j] * columnVector[j];

        s2 += rowVector[i] * s;
    }
    return s2;
}
```

and the code to test it

```csharp
const int Size = 3, N = 10000000;
var SR = Matrix.Random(Size, Size);
double[] x = Vector.Random(Size);

// JIT the code
for (int i = 0; i < 100; i++)
{
    double result5 = x.DotAndDot(SR, x);
    double result6 = x.DotAndDotFast(SR, x);
}

double res = 0;
var sw = Stopwatch.StartNew();

for (int i = 0; i < N; i++)
    res += x.DotAndDot(SR, x);

long time1 = sw.ElapsedMilliseconds;
Console.WriteLine($"Time taken is {time1:n0}ms");                   // Time taken is 1,430ms

res = 0;
sw.Restart();
for (int i = 0; i < N; i++)
    res += x.DotAndDotFast(SR, x);

long time2 = sw.ElapsedMilliseconds;

Console.WriteLine($"Time taken is {time2:n0}ms");                   // Time taken is 754ms
Console.WriteLine($"Accord is x{(double)time1 / time2:n3} slower"); // Accord is x1.897 slower
```

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Amazing! Thanks a lot for the contribution. Indeed, some of the methods in the Matrix class were still meant to be optimized, and your contribution was more than welcome. I've just updated the T4 templates to use your implementation instead of the naive method they were using before.

I will commit the changes in a few minutes.

Regards,
Cesar

**Comment by AlexJCross** [comment]
Thanks v much! I have a problem with millions of 5x5 `DotAndDot` operations so this will be very helpful for me :)

Yes, I was reading the T4 template code over the weekend and can see a number of the methods have `<#// TODO: Optimize#>` commented. The `double[,]` `double[,]` implementations of `Dot` pin the arrays and use pointer arithmetic but the vector operations do not. 

I had a look at these and sped up the operations `y=Ax`, `y'=x'A`, `t=u'Qv` quite substantially. For large problems, twice as fast as the current implementations  using pointer arithmetic and three times faster (for `doubles`) with some loop unrolling. Very happy to share this work and/or submit a PR with updated templates if you're interested? Can raise an issue this evening when back at my computer.

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Normally it shouldn't be necessary to pin vectors represented as arrays and matrices represented as jagged arrays, because, if coded correctly, their access operations can be optimized by the JIT compiler quite well. Can you please share some of the optimizations that you have made, so I can take a look?

Also, just to make sure (as I think you are already doing like this), but are you testing the optimizations by building your test application in release mode, and by launching your .exe outside of Visual Studio (i.e. by double clicking on the .exe, rather than by hitting F5 from inside VS?)

Regards,
Cesar

**Comment by AlexJCross** [comment]
Hi Cesar,

Agree with everything you have said 100%. Apologies if my earlier post was unclear. I meant the matrix-vector operations as opposed to the matrix-matrix operations (which have already been done) and the vector-vector operations (where the overhead of pinning would outweigh the benefits). I haven't touched the jagged arrays for that reason (although I suspect something can be done there too). 

When I am home this evening I will post my code and a table of results for different sizes N. If you like the results I can provide tests/templates etc.

Yes, release without attaching debugger :p

**Comment by AlexJCross** [comment]
Hi Cesar,

As promised, I have submitted some timings and code. Assuming I've not made a mistake, quite a big speed up. Link to my code [here](https://github.com/AlexJCross/SpeedTests) (it's just draft for now). If you run it, it will show loads of benchmarks and save an output file of these tables. Happy to update the templates if you like this. I think it would be a really good upgrade to the library.


#### Vector-Matrix

This shows a comparison of Accord's `vector.Dot(matrix, result)` versus a proposed change pinning the arrays and using pointer arithmetic. 

Size is the size of the matrix (so 32 means a `32 x 32` square matrix). Trials is the number of simulations run. The timings are shown next and then the speed multiplier is shown. So the bottom row shows it is 17 times faster to pin the array than Accord's current method.

|Size|Trials|Accord (ms)|Proposed (ms)|Multiplier|
|----------|:-------------:|------:|------:|------:|
|8|4194304|750|368|x2|
|16|1048576|722|291|x2.5|
|32|262144|684|242|x2.8|
|64|65536|746|242|x3.1|
|128|16384|782|238|x3.3|
|256|4096|1049|227|x4.6|
|512|1024|1095|225|x4.9|
|1024|256|2936|256|x11.5|
|2048|64|3781|254|x14.9|
|4096|16|4373|255|x17.1|

#### Matrix-Vector

This shows a comparison of Accord's `matrix.Dot(vector, result)` versus a proposed change pinning the arrays and using pointer arithmetic. 

|Size|Trials|Accord (ms)|Proposed (ms)|Multiplier|
|----------|:-------------:|------:|------:|------:|
|8|4194304|712|290|x2.5|
|16|1048576|707|225|x3.1|
|32|262144|714|206|x3.5|
|64|65536|702|199|x3.5|
|128|16384|696|185|x3.8|
|256|4096|688|182|x3.8|
|512|1024|717|179|x4|
|1024|256|697|205|x3.4|
|2048|64|697|199|x3.5|
|4096|16|698|200|x3.5|

Thanks,
Alex

**Comment by cesarsouza** [comment]
Hi @AlexJCross, 

Indeed, amazing work! Thanks a lot for the effort - yes, those improvements would be more than welcome in the framework. 

However, updating the templates can sometimes be tricky, please let me know if you need any help.

Regards,
Cesar

**Comment by AlexJCross** [comment]
Great. I'll get working on it. I think this issue can be closed as you have checked it in to develop. I'll create a separate issue for this stuff so i can commit against it.
