### ISSUE TITLE
Error in ExhaustiveBlockMatching

### ISSUE THREAD

**Issue by mhdabdelrhman** [accord-net/framework#729]
ExhaustiveBlockMatching.cs  Line 324 
if ( ( blockSearchX < 0 ) || ( blockSearchY + blockSize >= width ) )
must to change to 
if ( ( blockSearchX < 0 ) || ( blockSearchX + blockSize >= width ) )

**Comment by cesarsouza** [comment]
Hi @mhdabdelrhman, 

Thanks a lot for opening the issue! That was an excellent catch, the ExhaustiveBlockMatching class actually originated from the AForge.NET Framework, meaning it has been in use for more than ~7y and this issue had never been noticed before. 

Please, can I ask if you can provide an example that triggers and demonstrates the issue?

Regards,
Cesar

**Comment by cesarsouza** [comment]
A new pre-release package (3.6.4-alpha) has just been uploaded to NuGet. It should contain a fix for this issue. Thanks again!

**Comment by mhdabdelrhman** [comment]
Thank you.

_Sent from my Asus ASUS_Z00LD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by cesarsouza** [comment]
Fixed in 3.7.0.
