### ISSUE TITLE
Binary-Split with normalized FREAK. How-to?

### ISSUE THREAD

**Issue by paspatous** [accord-net/framework#730]
For the FREAK detector in the BoW image classification sample, it is mentioned that using Binary-Split with normalized FREAK features would possibly work better than the k-modes. However, it is not clear in the documentation how this option can actually be implemented/incorporated in the code.

**Comment by cesarsouza** [comment]
An example showing how to use the FREAK detector and the BinarySplit clustering algorithm has been added to the [documentation page for the BagOfVisualWords class](http://accord-framework.net/docs/html/T_Accord_Imaging_BagOfVisualWords.htm).
