### ISSUE TITLE
Dilatation?

### ISSUE THREAD

**Issue by fdncred** [accord-net/framework#731]
Is Dilation spelled right? I'm not sure what Die-luh-tay-shun is. Maybe I'm just ignorant but I thought it was Die-lay-shun.

**Comment by cesarsouza** [comment]
@fdncred do not worry, you are absolutely right. The correct name for this class would be Dilation and not Dilatation. This is one of the classes that were inherited from the AForge.NET Framework and have not yet been touched upon, so I hadn't had the chance to correct its name yet.

**Comment by cesarsouza** [comment]
Curiously, dilatation is an actual English word which seems to be used in the medical sciences. But it is also a common mistranslation from Latin-based languages (i.e. "dilatation" in French, "dilatação" in Portuguese).

**Comment by fdncred** [comment]
Interesting. I just wanted to put it on the queue to be corrected sometime.  Thanks.

**Comment by cesarsouza** [comment]
Hi,

For the time being, I've just re-opened the issue so it can be tracked and solved in the next release. If you find any other issues, including typos and incorrect class names, particularly in the classes that advent from AForge.NET please let me know!

Regards,
Cesar

**Comment by cesarsouza** [comment]
Fixed in 3.7.0.
