### ISSUE TITLE
Deep learning sample does not build

### ISSUE THREAD

**Issue by AliGhazvini** [accord-net/framework#733]
When _ try to build the deep learning sample app I keep getting this error:
_1>C:\Users\aligh\projects\Accord.NET-3.5.0-archive\Samples\Neuro\Deep Learning\MainWindow.xaml(31,6): error MC3074: The tag 'MetroWindow.WindowCommands' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 31 Position 6.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

What am I missing?

alighazvini@outlook.com
--

**Comment by AliGhazvini** [comment]
alighazvini@outlook.com

**Comment by AliGhazvini** [comment]
The different distributions of the Accord packages some of them seem not to be able to build the Deep Learning example.
When I install it from Framework-development it seems to work but after updating the packages through Nuget then the same error as above happens again.

**Comment by cesarsouza** [comment]
Hi @AliGhazvini,

Thanks a lot for opening the issue, and sorry for the delay in answering. I actually couldn't take the time to look into this issue yet, but I think I might need to point out that the deep learning sample application is about to be rewritten (together with the rest of the Accord.Neuro namespace) to use https://github.com/cesarsouza/keras-sharp instead. As such, it might not make much sense to invest too much time in getting the sample to work at this particular point in time.

Regards and sorry for the inconvenience,
Cesar
