### ISSUE TITLE
Add examples for C45Learning Class with missing data and thresholds

### ISSUE THREAD

**Issue by cobysy** [accord-net/framework#737]
Could you provide an example for how to use the C45Learning Class where the learning data is missing data for some rows?

Also if it is possible construct a cookbook in instances where I have continuous attributes with thresholds in the rules (e.g. equals, greater than, etc.)

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_DecisionTrees_Learning_C45Learning.htm

**Comment by cesarsouza** [comment]
A new pre-release package (3.6.4-alpha) has just been uploaded to NuGet. It should contain a fix for this issue. An [example on how to use C4.5 with missing data using this latest pre-release can be found here](https://github.com/accord-net/framework/blob/95ee5808c0538134b9a4e78ef9f534cd7a3354a1/Unit%20Tests/Accord.Tests.MachineLearning/DecisionTrees/C45LearningTest.cs#L406) and will be included in the main documentation pages of the next stable release.

**Comment by cesarsouza** [comment]
Added in 3.7.0. 

The [C4.5 learning documentation has been updates on how to learn decision trees with cross-validation (CV) and grid-search cross validation (GSCV)](http://accord-framework.net/docs/html/T_Accord_MachineLearning_DecisionTrees_Learning_C45Learning.htm).

An example on [how to create a codebook with continuous attribute rules has been added to the Discretization filter documentation page](http://accord-framework.net/docs/html/T_Accord_Statistics_Filters_Discretization_2.htm).
