### ISSUE TITLE
Add an Example for MultipleLinearRegression.CoefficientOfDetermination Method

### ISSUE THREAD

**Issue by Amalkhairy** [accord-net/framework#739]
Please add an example for MultipleLinearRegression.CoefficientOfDetermination Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Models_Regression_Linear_MultipleLinearRegression_CoefficientOfDetermination.htm

**Comment by cesarsouza** [comment]
An example on how to use the CoefficientOfDetermination method (among other methods to obtain this coefficient, such as by using the [RSquaredLoss class](http://accord-framework.net/docs/html/T_Accord_Math_Optimization_Losses_RSquaredLoss.htm) is available in the [documentation page for the MultipleLinearRegression class](http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Regression_Linear_MultipleLinearRegression.htm).
