### ISSUE TITLE
Accord.Statistics multilinear regression: unhandled Index of Out Range exception thrown

### ISSUE THREAD

**Issue by suoranta** [accord-net/framework#741]
Code using Accord.Statistics:
```
double[][] X = new double[2][];
double[] Y = new double[6];
... // populate X, Y with values
MultipleLinearRegression regression = ols.Learn(X, Y);
```
X is populated with two arrays of double[6] that hold values. Learn throws Index of Out Range exception that occurs
> at Accord.Math.Decompositions.JaggedSingularValueDecomposition.Solve(Double[] value)
> at Accord.Statistics.Models.Regression.Linear.OrdinaryLeastSquares.Learn(Double[][] x, Double[] y, Double[] weights)

It does not appear that the exception would be related to the specific values that I'm using. I originally had just one independent variable in X (simple linear regression done through MLR method) and that produced the same exception. Just to make sure I hadn't misunderstood the correct usage, I also tried transposing X, but that produces exception "Matrix is rank deficient" as expected.

**Comment by cesarsouza** [comment]
Hi @suoranta,

If I understood correctly, in your example you have 2 rows for the X (input) instances but 6 rows for their expected values. The method really expects the input and output data to have the same number of rows. If you are receiving a "Matrix is rank deficient" exception even when you have the same number of rows for both input and output data, try specifying "Robust = true" to compute the OLS regression using the SVD and thus sidestepping any issues regarding the rank/linear dependency in your original training data.

Please let me know if this helps.

Regards,
Cesar

**Comment by suoranta** [comment]
@cesarsouza Thanks, "Robust =True" did solve this.
