### ISSUE TITLE
Cannot change degree of a default Polynomial kernel

### ISSUE THREAD

**Issue by philcontrolf1** [accord-net/framework#745]
Once a Polynomial kernel has been created with the default degree of zero, this can never be changed. Trivial example:

    public static void Main(string[] args)
    {
        var polynomial = new Polynomial();
        polynomial.Degree = 3;
    }

Expected result: polynomial degree is changed to 3 as that is a valid value.
Actual result: System.ArgumentOutOfRangeException 'Degree must be positive'

Fairly obviously being caused by the check at Polynomial.cs:72:

    if (degree <= 0)
        throw new ArgumentOutOfRangeException("value", "Degree must be positive.");

and the obvious fix would be to make the check be on `value` (the new value) rather than `degree` (the old value). I'll make a PR if you want one, but doesn't really seem worth it for such a small change.

**Comment by cesarsouza** [comment]
Hi @philcontrolf1,

Thanks a lot for opening the issue. Indeed, that was a silly mistake, probably originated by copying and pasting from a previous argument check coming from the class constructor's body.

I will commit a fix soon. If you find any other similar issues, please let me know. 

Regards,
Cesar

**Comment by cesarsouza** [comment]
A new pre-release package (3.6.4-alpha) has just been uploaded to NuGet. It should contain a fix for this issue.

**Comment by cesarsouza** [comment]
Added in 3.7.0.
