### ISSUE TITLE
Add an Example for CrossValidation Class

### ISSUE THREAD

**Issue by HaoranXue** [accord-net/framework#746]
Please add an example for CrossValidation Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_CrossValidation.htm

**Comment by cesarsouza** [comment]
Added in 3.7.0. New [examples for cross-validation are available here](http://accord-framework.net/docs/html/T_Accord_MachineLearning_Performance_CrossValidation_4.htm) and new [examples for grid-search with cross-validation here](http://accord-framework.net/docs/html/T_Accord_MachineLearning_Performance_GridSearch_3.htm).
