### ISSUE TITLE
64 bit release for .NET 4.0

### ISSUE THREAD

**Issue by bijington** [accord-net/framework#749]
Hi,

I have recently switched from AForge over to Accord as it has support for H264 codecs which is ideal however I need to be able to support both 32 and 64 bit builds in a .NET 4.0 application. I have tried grabbing the necessary 64 bit dlls from nuget however they only compile down to .NET 4.5. Is there a reason you haven't gone lower? If not is it possible to compile it into the nuget package? I am having difficulties getting your source checked out and compiling in .NET 4.0. There are a number of errors however I believe they are related to my environment and not necessarily the .NET version.

Thanks
Shaun

**Comment by bijington** [comment]
In actual fact I have just discovered that 3.6.3-alpha does contain a .NET 4.0 version of the dll I am after. Do you know when this is likely to become a 'stable' release?

**Comment by cesarsouza** [comment]
Hi @bijington, 

You can use the alpha version in your application right now if you need. There aren't many differences between a stable or alpha release, besides a more increased change of having breaking API changes between alpha releases than stable releases. However, I do not foresee any changes in the H264 APIs right now, so it is very likely that the next 'stable' release will have exactly the same API as 3.6.3-alpha.

Regards,
Cesar

**Comment by bijington** [comment]
Perfect thank you.

**Comment by cesarsouza** [comment]
Available in 3.7.0.
