### ISSUE TITLE
Add an Example for UnivariateContinuousDistribution.Fit Method (Double[])

### ISSUE THREAD

**Issue by InkdudeYanai** [accord-net/framework#750]
Please add an example for UnivariateContinuousDistribution.Fit Method (Double[]).
Its hard to understand, If I have an array of points with x and y, how do I applay the fit method with them, what do I put in the double array? an example will help a lot.

**Comment by cesarsouza** [comment]
Hi @InkdudeYanai,

Thanks for opening the issue! Univariate distributions, by definition, can only have one dimension, such as only ```x```, or only ```y```. If you have an array of points with ```x``` and ```y``` then I guess you need a multivariate distribution.

If this is correct, then you might have to choose one distribution from [the list of multivariate distributions available in the framework](http://accord-framework.net/docs/html/N_Accord_Statistics_Distributions_Multivariate.htm), create a new instance of it, then call the .Fit method passing your array of (x, y) points. 

For example, in the case that you would like to model your data using a multivariate Normal distribution, there is an [example at the bottom of its documentation page showing multiple ways of it can be done](http://accord-framework.net/docs/html/T_Accord_Statistics_Distributions_Multivariate_MultivariateNormalDistribution.htm).

If that doesn't answer your question, please let me know!

Regards,
Cesar
