### ISSUE TITLE
Add an Example for BinaryLikelihoodClassifierBase(TInput).Probability Method (TInput[], Boolean[], Double[])

### ISSUE THREAD

**Issue by Fthi-S3074641** [accord-net/framework#754]
Please add an example for BinaryLikelihoodClassifierBase(TInput).Probability Method (TInput[], Boolean[], Double[]).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_BinaryLikelihoodClassifierBase_1_Probability_6.htm

**Comment by cesarsouza** [comment]
Hi @Fthi-S3074641,

This is just a method for returning probabilities, which can be called from several models. If there is any model in particular you would be interested, please re-open the issue with more details.

Regards,
Cesar

**Comment by Fthi-S3074641** [comment]
Thank you very much for the response but I already figured how to use it.
Love Accord now.

On 9 Aug 2017 20:22, "César Souza" <notifications@github.com> wrote:

Closed #754 <https://github.com/accord-net/framework/issues/754>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/accord-net/framework/issues/754#event-1199615014>, or mute
the thread
