### ISSUE TITLE
Bug in cross product calculation

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#755]
The cross-product calculation does not assign the result to the `result` parameter but instead returns a new result. This can be seen [here](https://github.com/accord-net/framework/blob/3d36c754f3a4ea6e4f47a8b27b0d4e1c4d444cb1/Sources/Accord.Math/Matrix/Matrix.Product.tt#L1933).

```csharp
        public static double[] Cross(double[] a, double[] b, double[] result)
        {
            return new double[] 
            {
                (double)((double)a[1]*(double)b[2] - (double)a[2]*(double)b[1]),
                (double)((double)a[2]*(double)b[0] - (double)a[0]*(double)b[2]),
                (double)((double)a[0]*(double)b[1] - (double)a[1]*(double)b[0])
            };
        }
```

**Comment by cesarsouza** [comment]
Hi @AlexJCross, thanks a lot for identifying the issue! Are you planning to submit a pull request for this issue as well?

I am about to submit some large changes in the project (to add support for .NET Standard 1.4) that might touch a lot of files, including some files you might be currently working on. I hope they will not disrupt your current work!

Regards,
Cesar

**Comment by AlexJCross** [comment]
Hi @cesarsouza,

Thanks for letting me know. If you need to make any changes then please go right ahead and I am sure I can resolve any merge issues sensibly. 

In terms of submitting a PR for GH-755, it was such a small correction to the same file (I noticed it while working through Product.tt) I thought I'd include it in that PR. Are you happy for me to address two issues in one pull review or would you like them in separate reviews? (If not, feel free to copy-paste the fix above). 

Regarding GH-752, I think it makes sense for me to limit the scope of the optimisations for now and send a PR shortly. Some of the optimisations I would like to do involve editing the T4 code and others will impact precision in a few cases. Rather than cherry picking the commits we like, it will be easier if I submit all the non-controversial changes in one go and then create separate issues for the others. That way, I can set out exactly what I want to change and why and you can let me know if you're happy with the proposals. Does that work for you?

Regards,
Alex

Ps - moving house this week so should have more time and computer access from next week or so.

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Please feel free to address multiple issues in the same PR, I would prefer whichever way would make it easier for you.

Thanks a lot,
Cesar
