### ISSUE TITLE
Add an Example for ProportionalHazardsAnalysis.LogLikelihood Property

### ISSUE THREAD

**Issue by kapildevgoyal** [accord-net/framework#756]
Please add an example for ProportionalHazardsAnalysis.LogLikelihood Property.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/P_Accord_Statistics_Analysis_ProportionalHazardsAnalysis_LogLikelihood.htm

**Comment by cesarsouza** [comment]
An example showing how to retrieve the value of the LogLikelihood property has been added to [documentation page for the main ProportionalHazardsAnalysis class](http://accord-framework.net/docs/html/T_Accord_Statistics_Analysis_ProportionalHazardsAnalysis.htm). However, there seems to be a small formatting problem involving the two code versions for C# and VB.NET.
