### ISSUE TITLE
Setting alpha/significance for GrubbTest

### ISSUE THREAD

**Issue by dee-fee** [accord-net/framework#759]
The ctor for GrubbTest automatically calculates everything from the supplied input data and outlier test type (min, max, or either). There's no opportunity to set the alpha/significance value for the distribution used (or in the parlance of this framework, the Size of the distribution) so you're stuck with the default value of 0.05

**Comment by cesarsouza** [comment]
Hi @dee-fee,

Thanks a lot for opening the issue! Have you tried to set the .Size property of the GrubbTest class to a different value after the test has been created? I.e. for example:

```csharp
// Consider the following sample:
double[] sample =
{
    199.31, 199.53, 200.19, 200.82, 201.92, 201.95, 202.18, 245.57
};

// Null Hypothesis: there are no outliers in the data
// Alternative    : there is at least one outlier

var grubbs = new GrubbTest(sample, GrubbTestHypothesis.TheMaximumIsAnOutlier)
{
    Size = 0.01
};
```

Even though the main statistics of the Grubb's test would have been calculated by the consutructor, the alpha/significance/size should still have been configurable by adjusting the Size property, which would cause the ```grubbs.CriticalValue``` property to also change values accordingly.

If you are not experiencing this in your application, may I please ask if you could submit some data that reproduces the issue, together with some code demonstrating how the GrubbTest is being used?

Thanks a lot!

Regards,
Cesar

**Comment by dee-fee** [comment]
My mistake, I was reading through the code and missed the OnSizeChanged() call in the Size property setting, I didn't actually run any tests.
