### ISSUE TITLE
Accord.Video.FFMPEG Dependency failed to load

### ISSUE THREAD

**Issue by bijington** [accord-net/framework#763]
I am also seeing a similar issue to [here](https://github.com/accord-net/framework/issues/615) (sorry I couldn't reopen that other issue so I have raised this). I have a 32 bit build working on multiple machines however on a Windows 8.1 Surface tablet I see an error when trying to retrieve video frames from a device with the following error: "Thread was being aborted."

I also then see the following error when trying to use VideoFileWriter:
"Could not load file or assembly 'Accord.Video.FFMPEG.dll' or one of its dependencies. The specified module could not be found." This is using v3.6.0 and I am shipping the following dlls with my application:
avcodec-57.dll
avdevice-57.dll
avfilter-6.dll
avformat-57.dll
avutil-55.dll
postproc-54.dll
swresample-2.dll
swscale-4.dll
ffmpeg.exe
ffplay.exe
ffprobe.exe

My application is compiled to .NET 4.0. It is a 32 bit build running on a 64 bit Windows 8.1 Pro tablet.

I have also tried copying over the mentioned dlls from above however I have not been able to resolve this issue so far. Any ideas on the cause of this?

**Comment by cesarsouza** [comment]
Hi @bijington,

Many thanks for opening the issue. As I cannot reproduce the error in any of my current machines, do you think you could try [following the steps described here](https://web.archive.org/web/20130328034650/http://tech.blinemedical.com/debug-could-not-load-file-or-assembly-or-one-of-its-dependencies/) so we could try to pinpoint where exactly the problem is?

**Comment by cesarsouza** [comment]
This blogs links to a tool that might be able to help us discover which .dll is causing the issue: https://github.com/blinemedical/Dependz

**Comment by bijington** [comment]
Hi Cesar,

Thanks for the response. Unfortunately I am away from this project for the next week but I will get straight on to it when I am back.

Thanks

Shaun

**Comment by davidvenglish** [comment]
I ran into this issue this week. I needed to install the 2015 C++ Redistributable to resolve it.

**Comment by bijington** [comment]
@davidvenglish That fixed it thanks! I had 2012, 2013 and x64 2015 but not x86 (doh).

I now have some serious performance issues with the camera. I'll need to test this one a little further though.

**Comment by cesarsouza** [comment]
Many thanks @davidvenglish! 

I've updated the readme to include a link to the 2015 C++ Redistributable.

Regards,
Cesar
