### ISSUE TITLE
Add an Example for BagOfWords.CodeToString Property

### ISSUE THREAD

**Issue by mesdi** [accord-net/framework#766]
Please add an example for BagOfWords.CodeToString Property.

**Comment by cesarsouza** [comment]
Hi there,

BagOfWords.CodeToString is just a dictionary mapping codewords (integers) into string tokens (i.e. mapping 0 to "Lorem" considering the [first example in the BagOfWords class documentation](http://accord-framework.net/docs/html/T_Accord_MachineLearning_BagOfWords.htm)).

It is a rather simple property, so I will probably not be adding an example for it right now - but if you need a specific example for a specific situation you would like to see addressed, please reply. 

Regards,
Cesar
