### ISSUE TITLE
DebugVisualizers

### ISSUE THREAD

**Issue by fdncred** [accord-net/framework#767]
How about updating the DebugVisualizers? I'm trying to compile them now and it's not as easy as it should be.

Thanks,
Darren

**Comment by cesarsouza** [comment]
Hi Darren,

If you find more about how they were supposed to work, please let me know. I've imported them once I merged with the AForge.NET project but I have barely taken a look at them ever since. Sorry for not being more helpful, but that's a reality - if you manage to find more about them, and if you think they would be useful for the users of the framework, please update this thread with your findings so I could update their documentation (and/or maybe discover better ways to make them available for other users).

Regards,
Cesar

**Comment by fdncred** [comment]
Hey Cesar,
I was able to get the DebugVisualizers compiled and working. To be honest, it's nice to have them, but they're not very good visualizers. 

I'd like to incorporate yours into the [one](https://github.com/Jaex/ImageVisualizer) I use for Bitmaps so that it would work with Bitmap/Image and UnmanagedImage. I have customized it so it doesn't match the github version anymore.

To take this a step further, it would be nice to have a visualizer for Matrices as well. There are probably other objects in your framework that would be nice to visualize as well. 

Perhaps we can start with Bitmap/Image/UnmanagedImage/Histogram and maybe add Matrix later.

I'm happy to contribute what I've done but I'm not sure of the licensing implications of the other visualizer that I use. Let me know your thoughts.

Darren

**Comment by cesarsouza** [comment]
Hi Darren,

By license implications, do you refer to the fact that the one you have linked is currently under the GPL and the ones in Accord.NET are LGPL?

If that is the issue, I don't think there would be any problem at all in converting the current visualizers in Accord.NET to GPL. In fact, [this is something that is actually foreseen in the LGPL license text](https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility), so there shouldn't be any problem in this regard. 

The project has a few other visualizations that could be adapted if you would be interested, such as for example, the ones in the Accord.Controls namespace:

 - [HistogramBox](http://accord-framework.net/docs/html/T_Accord_Controls_HistogramBox.htm)
 - [ArrayDataView (visualizer for matrices)](http://accord-framework.net/docs/html/T_Accord_Controls_ArrayDataView.htm),
 - [DecisionTreeView](http://accord-framework.net/docs/html/T_Accord_Controls_DecisionTreeView.htm),
 - [DataGridBox](http://accord-framework.net/docs/html/T_Accord_Controls_DataGridBox.htm)
 - [DataBarBox](http://accord-framework.net/docs/html/T_Accord_Controls_DataBarBox.htm),
 - [WaveChartBox](http://accord-framework.net/docs/html/T_Accord_Controls_WavechartBox.htm)

Regards,
Cesar

**Comment by cesarsouza** [comment]
Updated DebuggerVisualizers have been added in v3.7.0. Thanks for the contribution Darren!
