### ISSUE TITLE
Add an Example for ID3Learning.Learn Method

### ISSUE THREAD

**Issue by alberwan** [accord-net/framework#776]
Please add an example for ID3Learning.Learn Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_DecisionTrees_Learning_ID3Learning_Learn.htm

**Comment by cesarsouza** [comment]
Thanks for opening the issue. Examples for ID3Learning are available [at the ID3Learning documentation page](http://accord-framework.net/docs/html/T_Accord_MachineLearning_DecisionTrees_Learning_ID3Learning.htm). If you have some specific scenario that you would like to see addressed, please re-open the issue!
