### ISSUE TITLE
Bug in LinearConstraintCollection documentation

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#777]
The documentation for `LinearConstraintCollection` is [incorrect](https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Optimization/Constrained/Constraints/LinearConstraintCollection.cs#L150).

It states that the inequality constraints should come first but puts equality constraints first. I believe the documentation should read `The number of equalities at the start of the matrix <paramref name="a"/>.`

Thanks.

**Comment by cesarsouza** [comment]
Hi @AlexJCross, thanks a lot!

**Comment by cesarsouza** [comment]
Updated in v3.7.0. Thanks! https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Optimization/Constrained/Constraints/LinearConstraintCollection.cs#L150
