### ISSUE TITLE
BoundedBroydenFletcherGoldfarbShanno

### ISSUE THREAD

**Issue by ZanderFick** [accord-net/framework#778]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [x ] bug report
  - [x ] feature request

**Issue description**

Lower and Upperbounds properties have no Set accessors.

      public double[] UpperBounds
        {
            get { return upperBound; }
        }

        public double[] LowerBounds
        {
            get { return lowerBound; }
        }

**Comment by cesarsouza** [comment]
Hi @ZanderFick,

Thanks for opening the issue. Since those are arrays, you can actually setup the bounds using
```
bfgs.UpperBounds[0] = any_value;
```
directly.

However, I guess that having set accessors also wouldn't hurt in this case, so I might add them in the next release.

Regards,
Cesar

**Comment by ZanderFick** [comment]
Hi Cesar

Thanks a lot for letting me know!

Your work is fantastic!

Zander

Sent from Windows Mail

**Comment by cesarsouza** [comment]
Updated in 3.7.0: http://accord-framework.net/docs/html/P_Accord_Math_Optimization_BoundedBroydenFletcherGoldfarbShanno_UpperBounds.htm
