### ISSUE TITLE
Adding a range search method for KDTree

### ISSUE THREAD

**Issue by hzawary** [accord-net/framework#784]
Hi again,

As before mentioned, discard that the pull-request and let it as issue.
I've investigating about range search using Kd-Tree, since doesn't exist in Accord.Collections.KDTree class. Finally I implements an extension range search 2D for it. But I'm not sure about performance, complexity and the best algorithm or method.

```
        public static void KdTreeRangeQueryDemo()
        {
            // This is the same example found in Wikipedia page on
            // k-d trees: http://en.wikipedia.org/wiki/K-d_tree

            var image = UnmanagedImage.Create(800, 600, PixelFormat.Format24bppRgb);

            var rnd = new Random();

            // Suppose we have the following set of points:

            var points = new double[300000][];
            var listPoints = new List<IntPoint>(points.Length);
            for (int i = 0; i < points.Length; i++)
            {
                var point = new IntPoint(rnd.Next(0, image.Width), rnd.Next(0, image.Height));

                points[i] = new double[] { point.X, point.Y };

                listPoints.Add(point);
            }

            var region = new Rectangle(676, 441, 70, 55);

            new PointsMarker(listPoints, Color.DodgerBlue, 1).ApplyInPlace(image);
            new RectanglesMarker(region) { MarkerColor = Color.GreenYellow }.ApplyInPlace(image);

            var sw1 = new Stopwatch();
            sw1.Restart();
            var query1 = listPoints.FindAll((obj) =>
            {
                return
                obj.X > region.Left && obj.X < region.Right &&
                obj.Y > region.Top && obj.Y < region.Bottom;
            });
            sw1.Stop();

            listPoints.Clear();

            var sw2 = new Stopwatch();
            sw2.Restart();
            // To create a tree from a set of points, we use
            var tree = KDTree.FromData<int>(points, new Accord.Math.Distances.Manhattan(), true);
            sw2.Stop();

            var sw3 = new Stopwatch();
            sw3.Restart();
            var query2 = tree.Root.QueryKDTree2D(region);
            sw3.Stop();

            listPoints.AddRange(query2);

            var title = $"Create KDTree: {sw2.ElapsedMilliseconds}ms, Query KDTree: {sw3.ElapsedMilliseconds}ms, FindAll: {sw1.ElapsedMilliseconds}ms for {points.Length} random points.";
            new PointsMarker(query2 /*query1*/, Color.Tomato, 1).ApplyInPlace(image);

            ImageBox.Show(title, image, System.Windows.Forms.PictureBoxSizeMode.AutoSize);
        }

        public static IList<IntPoint> QueryKDTree2D(this KDTreeNode<int> node, Rectangle region)
        {
            return node.QueryKDTree2D(region, region);
        }

        private static IList<IntPoint> QueryKDTree2D(this KDTreeNode<int> node, Rectangle region, Rectangle subRegion)
        {
            var result = new List<IntPoint>();

            if (node != null && region.IntersectsWith(subRegion))
            {
                //if (node.Position.Length != 2)
                //    new DimensionMismatchException("node", "The node should have a 2D vector.");

                var point = new IntPoint((int)node.Position[0], (int)node.Position[1]);

                if (point.X > region.Left && point.X < region.Right &&
                    point.Y > region.Top && point.Y < region.Bottom)
                    result.Add(point);

                result.AddRange(node.Left.QueryKDTree2D(region, LeftRect(ref subRegion, ref node)));
                result.AddRange(node.Right.QueryKDTree2D(region, RightRect(ref subRegion, ref node)));
            }

            return result;
        }
        // helper: get the left rectangle of node inside parent's rect
        private static Rectangle LeftRect(ref Rectangle rect, ref KDTreeNode<int> node)
        {
            return node.Axis != 0 ?
                Rectangle.FromLTRB(rect.Left, rect.Top, rect.Right, (int)node.Position[1]) :
                Rectangle.FromLTRB(rect.Left, rect.Top, (int)node.Position[0], rect.Bottom);
        }
        // helper: get the right rectangle of node inside parent's rect
        private static Rectangle RightRect(ref Rectangle rect, ref KDTreeNode<int> node)
        {
            return node.Axis != 0 ?
                Rectangle.FromLTRB(rect.Left, (int)node.Position[1], rect.Right, rect.Bottom) :
                Rectangle.FromLTRB((int)node.Position[0], rect.Top, rect.Right, rect.Bottom);
        }
```
The result of above codes:
![kdtreequeryextension](https://user-images.githubusercontent.com/13867408/29283189-db2f3368-813a-11e7-97b8-9d24c377b221.png)

`public static void KdTreeRangeQueryDemo()`: **Show how usage of them.**

`public static IList<IntPoint> QueryKDTree2D(this KDTreeNode<int> node, Rectangle region)`: **An extension for KDTreeNodes.**

`private static IList<IntPoint> QueryKDTree2D(this KDTreeNode<int> node, Rectangle region, Rectangle subRegion)`: **An recursive function in private.**

**// helper: get the right rectangle of node inside parent's rect**
`private static Rectangle LeftRect(ref Rectangle rect, ref KDTreeNode<int> node)`

**// helper: get the right rectangle of node inside parent's rect**
`private static Rectangle RightRect(ref Rectangle rect, ref KDTreeNode<int> node)`

See the codes if necessary this functionality for adding to Accord.NET framework. Also it's be excellent if support more than 2D.

Regards,
H.Zawary

**Comment by cesarsouza** [comment]
Hi Hashem,

Thanks a lot. I will add a generalized version of your method for N-dimensional spaces and make sure you are listed in the copyright headers of the files I modify!

Thanks again for the contribution!

Regards,
Cesar

**Comment by cesarsouza** [comment]
Added in v3.7.0: http://accord-framework.net/docs/html/M_Accord_Collections_KDTreeBase_1_GetNodesInsideRegion.htm

**Comment by hzawary** [comment]
Excellent, that's great :)
But I'm not sure about number of recall functions and complexity O(√n) of algorithm!
[kd tree range search](https://www.google.com/search?rlz=1C1GGRV_enIR757IR757&biw=1360&bih=648&q=kd+tree+range+search&oq=kd+tree+range+search&gs_l=psy-ab.3..0l4.783524.789428.0.790868.15.15.0.0.0.0.1074.3314.2-2j2j1j1j0j1.7.0....0...1.1.64.psy-ab..8.7.3313...0i67k1.tRje7VWCaGM)
[Range Searching](https://www.cs.cmu.edu/~ckingsf/bioinfo-lectures/kdrangenn.pdf)

**Comment by cesarsouza** [comment]
Thanks for the updates Hashem! For the 2D case, it should have exactly the same complexity as the one you have contributed. The implementation should have been completely equivalent, though if you would like to test it a bit more and if you happen to find issues, please let me know!

**Comment by hzawary** [comment]
You're welcome, thanks for consideration :) I've nothing to say if you confirm it. As can see in the 300000 points experiment, at least 40% improved time for a 2D small region rather than the Linq method. If we have a mass of points with a small region to search then time should be lower than the Linq one!
