### ISSUE TITLE
Add an Example for Tools.RandomGroups Method (Int32, Double) alternative

### ISSUE THREAD

**Issue by shafayatnabi** [accord-net/framework#785]
Please add an example for Tools.RandomGroups Method (Int32, Double).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Tools_RandomGroups.htm

**Comment by cesarsouza** [comment]
An example has been added for the replacement method [Classes.Random instead](http://accord-framework.net/docs/html/M_Accord_Statistics_Classes_Random.htm).
