### ISSUE TITLE
Add an Example for HiddenMarkovModel(TDistribution, TObservation).Predict Method (TObservation[])

### ISSUE THREAD

**Issue by ArmagedonFlamer** [accord-net/framework#787]
Please add an example for HiddenMarkovModel(TDistribution, TObservation).Predict Method (TObservation[]).

TODO (optional): Predicting next observation, given the sequence of discrete observations, e.g. having the sequence 1,3,5,7,9 and returning 11 as the result.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Statistics_Models_Markov_HiddenMarkovModel_2_Predict.htm

**Comment by cesarsouza** [comment]
Added in 3.8.0.
