### ISSUE TITLE
Add an Example for AugmentedLagrangian Class

### ISSUE THREAD

**Issue by rosary10arrr** [accord-net/framework#788]
Please add an example for AugmentedLagrangian Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Math_Optimization_AugmentedLagrangian.htm

**Comment by cesarsouza** [comment]
Hi there,

There are already 2 different examples on how to use the AugmentedLagrangian class in the [AugmentedLagrangian documentation page](http://accord-framework.net/docs/html/T_Accord_Math_Optimization_AugmentedLagrangian.htm). If you need an example for a specific scenario you are trying to implement, please re-open the issue!

Regards,
Cesar
