### ISSUE TITLE
A little explanation ClassifierBase(TInput, TClasses).Decide Method (TInput[])

### ISSUE THREAD

**Issue by Fthi-S3074641** [accord-net/framework#795]
TODO (optional): From what I have played with; I can either use the Decide() function to get the boolean result or, I can use the Probabilities() function to retrieve the confidence values and manually make a decision in my code.

I want to know what kind of thresholding method/strategy the function Decide uses. For instance, does it use 0.5 as a threshold for the confidence values?

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_ClassifierBase_2_Decide_1.htm

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue!

The final implementation will depend on the final classification model that happens to implement the IClassifier interface and/or ClassifierBase base classes. However, the framework offer default implementations for when those are not overridden by each classifier:

- If the model is a binary score-based classifier, then the output of decide will be based on the sign of the output of the score function for a given sample.
- If the model is a binary probabilistic classifier, then the output of decide will be based on whether the value is less than or greater than 0.5 as you have mentioned.
- If this is a multi-class score-based classifier, then the output of decide will be based on the maximum score or probability among all classes (which should always coincide).
- If the model is a multi-label classifier, then decide will be based on the sign of the score for each of the classes.

Please let me know which model exactly you would like to know more about, and I can describe how its Decide function is computed.

Regards,
Cesar

**Comment by Fthi-S3074641** [comment]
Dear Cesar,

Thank you very much. I think this will do for now. For the record, I am
using a binary classifier.

Greetings, Fthi
