### ISSUE TITLE
Add an Example for NaiveBayes.Save Method (Stream)

### ISSUE THREAD

**Issue by sadeghsh** [accord-net/framework#796]
Please add an example for NaiveBayes.Save Method (Stream).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_Bayes_NaiveBayes_Save.htm

**Comment by cesarsouza** [comment]
Thanks for opening the issue! Please take a look at the documentation page for [Accord.IO.Serializer](http://accord-framework.net/docs/html/T_Accord_IO_Serializer.htm) for examples on how to load and save models in the framework.
