### ISSUE TITLE
Missing dependency for Accord.Neuro in NuGet

### ISSUE THREAD

**Issue by bradknox** [accord-net/framework#800]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [x] bug report
  - [ ] feature request

**Issue description**

Accord.Genetic isn't listed as a dependency for Accord.Neuro on NuGet (https://www.nuget.org/packages/Accord.Neuro/), though it is:
https://github.com/accord-net/framework/blob/development/Sources/Accord.Neuro/AForge.Neuro/Learning/EvolutionaryLearning.cs

**Comment by cesarsouza** [comment]
Many thanks @bradknox

**Comment by cesarsouza** [comment]
Fixed in 3.8.0.
