### ISSUE TITLE
Unsafe code exposed in the public API

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#805]
Some of the methods added in GH-752 expose the `unsafe` keyword in the public API. That is, the signature is `public static unsafe`. I am really very sorry about this :( - I did not realise this and it will only affect a small number of users - but it will cause a problem for users who cannot run code in an unsafe environment (for instance, Silverlight users will be affected). The fix is to move the unsafe code inside the method calls.

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Please do not worry. I will be including it in a 3.7.1 (bugfix) release quite soon.

Thanks a lot for the pull request (and if you would like and I haven't asked you before, please let me know of a name and contact e-mail that I can [add you to the list of contributors of the framework](https://github.com/accord-net/framework/blob/development/Contributors.txt)!)

Regards,
Cesar

**Comment by AlexJCross** [comment]
Hi @cesarsouza,

Ok thanks v much for the message. I hope the hit fix isn't too much trouble. 

Sure - by all means do!

Alex Cross
Alexjcross90@gmail.com
