### ISSUE TITLE
ZhangSuenSkeletonization filter not exist to use

### ISSUE THREAD

**Issue by hzawary** [accord-net/framework#812]
Hi dear Dr,

Obviously, **[ZhangSuenSkeletonization](framework/Sources/Accord.Imaging/AForge.Imaging/Filters/Other/ZhangSuenSkeletonization.cs)** filter doesn't exist in 'Accord.Imaging.Filters' modules to use! but it's exist on the source code under 'Accord.Imaging/AForge.Imaging/Filters/Other'! please check it.

Best,
H.Zawary :)

**Comment by cesarsouza** [comment]
Hi @hzawary,

Thanks a lot! It turns out that, somehow, the file was not being included in the project. It should have been included in the release for .NET Core 2.0 though.

I will commit a fix soon. Thanks again!

Regards,
Cesar

**Comment by cesarsouza** [comment]
The [Zhang-Suen Skeletonization filter](http://accord-framework.net/docs/html/T_Accord_Imaging_Filters_ZhangSuenSkeletonization.htm) has been added in the 3.8.0 release. Its documentation page can be found at http://accord-framework.net/docs/html/T_Accord_Imaging_Filters_ZhangSuenSkeletonization.htm
