### ISSUE TITLE
Beta Prime Distribution - Support values issues

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#816]
The `BetaPrimeDistribution` has `Support` between `[0, double.MaxValue]`. See [here](https://github.com/accord-net/framework/blob/development/Sources/Accord.Statistics/Distributions/Univariate/Continuous/BetaPrimeDistribution.cs#L224). This isn't wrong as such, but the convention is to write `[0, double.PositiveInfinity]`. For instance [here](https://github.com/accord-net/framework/blob/development/Sources/Accord.Statistics/Distributions/Univariate/Continuous/LognormalDistribution.cs#L233), and [here](https://github.com/accord-net/framework/blob/development/Sources/Accord.Statistics/Distributions/Univariate/Continuous/CauchyDistribution.cs#L238), and [here](https://github.com/accord-net/framework/blob/development/Sources/Accord.Statistics/Distributions/Univariate/Continuous/NormalDistribution.cs#L308) etc.

The result is that the `InverseDistributionFunction(p)`, the `Median` calculations and a few others are horrendously slow because the distribution is [assumed to be bounded from above and below](https://github.com/accord-net/framework/blob/development/Sources/Accord.Statistics/Distributions/Univariate/Base/UnivariateContinuousDistribution.cs#L788) when it should only be bounded from below. As a result, the Brent Search takes thousands of iterations to converge when it should only take a handful.

I spotted this because it's causing some tests to fail in my branch GH-725. I'll commit the fix shortly...

Thanks,
A

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Thanks a lot, and thanks a lot about all the previous submissions. Do you mind if I could contact you by email?

Regards,
Cesar

**Comment by AlexJCross** [comment]
sure

**Comment by cesarsouza** [comment]
Added in 3.8.0.
