### ISSUE TITLE
Add an Example for LinearConstraint Class

### ISSUE THREAD

**Issue by ongbengtiong** [accord-net/framework#818]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

If you would like to submit an issue, please include a sample of the code you are trying to execute, as well as any data you might be using in your experiment, such as data tables, images, anything that might be necessary to reproduce the problem.
  
Note: If you would like to support the development for this feature or resolution of this bug, consider adding a bounty to it later in https://www.bountysource.com/teams/accord-net/issues

**Comment by cesarsouza** [comment]
Will be added after #820 and #821

**Comment by AlexJCross** [comment]
yep i'll aim to do this in the coming week.

**Comment by cesarsouza** [comment]
Added in 3.8.0. The [LinearConstraint example is available here](http://accord-framework.net/docs/html/T_Accord_Math_Optimization_LinearConstraint.htm).
