### ISSUE TITLE
Quadratic Objective Function to support basic vector operations

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#819]
### Feature request

It would be quite nice if the quadratic objective function supported basic vector operations (vectors in the mathematical sense) such as addition and scalar multiplication. It's quite common to want to combine various quadratic objective functions possibly with a weighting. A proposed API would be:

```csharp
var target1 = new QuadraticObjectiveFunction(quadraticTerms1, linearTerms1);
var target2 = new QuadraticObjectiveFunction(quadraticTerms2, linearTerms2);
double weight1 = 0.4, weight2 = 0.6;

QuadraticObjectiveFunction weightedTarget = (weight1 * target1) + (weight2 * target2);
```

Mathematically, this is trivial because `f=x(Q+P)x+(c+d)x=xQx+xPx+cx+dc=f1+f2` but, syntactically, it would be really nice to write the maths and not have to scale and add individual matrices and vectors etc. If you like it, I'll add it. It's probably a quick job but there are some dictionaries floating around in that function that will need to be handled with care.

p.s. - [This line](https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Optimization/QuadraticObjectiveFunction.cs#L351) looks a bit suspicious to me. That only works if Q is symmetric but the class permits you to pass in a non-symmetric matrix. It should either calculate 0.5*(Q+Q')*x or throw an `Exception` if non-symmetric matrices are passed in. I would propose the latter. Assuming the latter, `Q.Dot(input)` would be much faster.

Thanks,
Alex

**Comment by cesarsouza** [comment]
Hi Alex,

Actually this quite opened my mind. I hadn't considered that the objective functions could actually be built in this way, quite easily. If you want you can limit the functionality for the case where the dictionaries coincide (i.e. the case you have written above when quadraticTerms1, quadraticTerms2, linearTerms1, linearTerms2 have the same number of columns).

That's a truly amazing feature, but we would need quite a few examples to explain what can be done with it!

Regards,
Cesar

**Comment by AlexJCross** [comment]
> If you want you can limit the functionality for the case where the dictionaries coincide (i.e. the case you have written above when quadraticTerms1, quadraticTerms2, linearTerms1, linearTerms2 refer to the same variables).

ha - I wrote some draft code for this yesterday and that's exactly what I did ;)
