### ISSUE TITLE
Read PGM image 

### ISSUE THREAD

**Issue by HadeelHassan** [accord-net/framework#830]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

If you would like to submit an issue, please include a sample of the code you are trying to execute, as well as any data you might be using in your experiment, such as data tables, images, anything that might be necessary to reproduce the problem.
  
Note: If you would like to support the development for this feature or resolution of this bug, consider adding a bounty to it later in https://www.bountysource.com/teams/accord-net/issues

**Comment by HadeelHassan** [comment]
Hi 
I have dataset of images with PGM formats, i went to website of accord.net but i didnot understand how to use PNMcodec to read images, i want to convert images to bmp or jpg to deal with them 
thanks
Hadeel

**Comment by cesarsouza** [comment]
Hi @HadeelHassan,

The current documentation for PNMCodec is really not that good. I will try to come up with some better examples!

Regards,
Cesar

**Comment by HadeelHassan** [comment]
@cesarsouza 
that is so kind from you 
thanks
Hadeel

**Comment by cesarsouza** [comment]
Hi @HadeelHassan,

So, it turns out that instead of using PNMCodec directly, you should be using the ImageDecoder class. Let's say that you have an image at "C:\Images\example.pgm". Then you can load it as a Bitmap using:

```csharp
Bitmap actual = ImageDecoder.DecodeFromFile(@"C:\Images\example.pgm");
```

However, I've just noticed that the framework only supports files that use the PNM format 5 or 6. If it doesn't work for you, please attach a sample image to this issue in the format you need and I can see if we can add support for it.

Regards,
Cesar

**Comment by HadeelHassan** [comment]
@cesarsouza 
hi cesar 
yeeeeeees, i tried your code just yet , it is working , thank you very very much
Hadeel
![pgm file](https://user-images.githubusercontent.com/26030419/29945100-889870b2-8ea8-11e7-9072-5dc2f56762ac.jpg)

**Comment by cesarsouza** [comment]
PGM images can now be open directly by using ```Accord.Imaging.Image.FromFile("image.pnm")```. An example has been added to the [documentation page of the FromFile static method](http://accord-framework.net/docs/html/M_Accord_Imaging_Image_FromFile.htm).
