### ISSUE TITLE
Problem with Naive Bayes - Index was outside the bounds of the array

### ISSUE THREAD

**Issue by whitemouse2100** [accord-net/framework#831]
[examples.xlsx](https://github.com/accord-net/framework/files/1267689/examples.xlsx)
Dear 
I am a new guy in machine learning. I have a problem with Naive Bayers. I use code in tutorial about Naive Bayers. 
This is my code:
  if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                string FolderPath = openFileDialog1.FileName;
                DataTable DanhSach = new ExcelReader(FolderPath).GetWorksheet("Classification - Yin Yang");
                double[][] inputs = DanhSach.ToJagged<double>("X", "Y");
                // double[][] outputs = DanhSach.ToJagged<double>("G", "K");
                int[] outputs = DanhSach.Columns["G"].ToArray<int>();

                //ScatterplotBox.Show("Yin-Yang", inputs, outputs).Hold();
                var teacher = new NaiveBayesLearning<NormalDistribution>();
                var nb = teacher.Learn(inputs, outputs);
                int numberOfClasses = nb.NumberOfClasses; // should be 2 (positive or negative)
                int nunmberOfInputs = nb.NumberOfInputs;  // should be 2 (x and y coordinates)

                // Classify the samples using the model
                int[] answers = nb.Decide(inputs);

                // Plot the results
                ScatterplotBox.Show("Expected results", inputs, outputs);
                ScatterplotBox.Show("Naive Bayes results", inputs, answers)
                    .Hold();

            }
I have attach file data which I download from tutorial.

Then I build this codes. And I have a bug is "Index was outside the bounds of the array". I don't know why. Please help me. Thanks very much.

**Comment by cesarsouza** [comment]
Hi @whitemouse2100,

Thanks for opening the issue. The problem is that the classes are being represented as -1 and +1, while the Naive Bayes and other binary classification methods might be expecting them to be given either as booleans or as 0 and 1s. For the moment, please try converting the outputs vector to a bool[] array using, for example:
```csharp
bool[] booleanOutputs = Classes.Decide(output);
```
and then passing this new booleanOutputs parameter to the .Learn() method.

This is probably related to #811, which has not been included in a release yet.

Can you please let me know where this example currently is? Is it from the Naive Bayes sample application?

Regards,
Cesar

**Comment by whitemouse2100** [comment]
Thanks you very much. I change all data from -1 and +1 to 0 and 1. And projects run well. But I cannot convert vector from int to bool. I don't know use function which can convert vector from int to bool. Please help me.
And this is example which I read:
https://github.com/accord-net/framework/wiki/Classification

**Comment by cesarsouza** [comment]
Hi @whitemouse2100,

You can convert from int to bool using [Classes.Decide(int32)](http://accord-framework.net/docs/html/M_Accord_Statistics_Classes_Decide_3.htm). As you can see, there is an overload that takes an int and translates it to a bool: http://accord-framework.net/docs/html/M_Accord_Statistics_Classes_Decide_3.htm

Regards,
Cesar

**Comment by cesarsouza** [comment]
Hi @whitemouse2100,

You can convert from int to bool using [Classes.Decide(int32[])](http://accord-framework.net/docs/html/M_Accord_Statistics_Classes_Decide_4.htm). As you can see, there is an overload that takes an array of integers (i.e. int[]) and translates it to an array of bool (i.e. bool[]): http://accord-framework.net/docs/html/M_Accord_Statistics_Classes_Decide_4.htm

Regards,
Cesar

**Comment by whitemouse2100** [comment]
Thanks very much

2017-09-05 4:53 GMT+07:00 César Souza <notifications@github.com>:
