### ISSUE TITLE
Add an Example for BagOfVisualWords Constructor (Int32)

### ISSUE THREAD

**Issue by 18070023526** [accord-net/framework#833]
Please add an example for BagOfVisualWords Constructor (Int32).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Imaging_BagOfVisualWords__ctor_1.htm

**Comment by blaisexen** [comment]
Dude,
you can find lot of samples inside the "Samples" folder "C:\Program Files (x86)\Accord.NET\Framework\Samples\"

and that includes that!
good luck

**Comment by cesarsouza** [comment]
Added in 3.8.0. All examples for the BagOfWords class can be found in the [documentation for BagOfVisualWords](http://accord-framework.net/docs/html/T_Accord_Imaging_BagOfVisualWords.htm).
