### ISSUE TITLE
Modifying BoundedBroydenFletcherGoldfarbShanno Class

### ISSUE THREAD

**Issue by aeternam7** [accord-net/framework#835]
hi
i'm trying to modelling Garch(1,1) with this class
so i'm trying to replicate this R code

dp <- garch_test$X__1
llh <- function(par) { mu <- par[1]; omega <- par[2]; alpha <- par[3]; beta <- par[4]; e2 <- (dp-mu)^2;  e2t <- omega + alpha*c(mean(e2), e2[-length(dp)]); s2 <- filter(e2t, beta, "recursive", init = mean(e2)); 0.5*sum( log(2*pi) + log(s2) + e2/s2) }
mu <- mean(dp); omega <- 0.1*var(dp); alpha <- 0.1; beta <- 0.8
par <- c(mu, omega, alpha, beta)
small <- 1e-6
low <- c(-10*abs(mu), small, small, small)
up <- c(10*abs(mu), 100*abs(mu), 1-small, 1-small)
fit <- nlminb(start=par, objective=llh, lower=low, upper=up, control=list(x.tol = 1e-8,trace=0))
names(fit$par) <- c("mu", "omega", "alpha", "beta")
round(fit$par, 6)

nlminb optimization function always converge to the same values; it has upper and lower bounds and a starting point; it does not use analytic derivatives (gradient), but numerical derivatives; STATA package also converge to the same values, alternating BBFG and BHHH methods

i've been testing this class with upper/lower bounds and no gradient defined

it sometimes converge to the same values of nlminb and STATA; not always

i wonder if adding a starting point it would improve stability; so would like to add a property (starting point) and modify this lines

            // We now define the starting point.
            {
                for (i = 0; i < n; i++)
                    x[i] = Solution[i];
}

is this the right way? do i have to take into considerations other part of the codes?

thanks in adavance

**Comment by aeternam7** [comment]
i finally modified the code to allow a starting point


        {
            this.upperBound = new double[numberOfVariables];
            this.lowerBound = new double[numberOfVariables];
            this.startingpoint = new double[numberOfVariables];

            for (int i = 0; i < upperBound.Length; i++)
                lowerBound[i] = Double.NegativeInfinity;

            for (int i = 0; i < upperBound.Length; i++)
                upperBound[i] = Double.PositiveInfinity;

            for (int i = 0; i < startingpoint.Length; i++)
                startingpoint[i] = double.NaN;

        }

--------------------------

            // We now define the starting point.
            bool hasStartingPoint = !Double.IsNaN(StartingPoint[0]);
            if (hasStartingPoint)
            {
            for (i = 0; i < n; i++)
                    x[i] = StartingPoint[i];
            }
            else
            {
                for (i = 0; i < n; i++)
                    x[i] = Solution[i];
            }


using a starting point stabilize the algorithm, but make it innaccurate unless you provide a starting point near to solution; thats why STATA alternate BFGS and BHHH

anyway, i think its a good option to allow final-user to use a starting point

**Comment by AlexJCross** [comment]
Hi @aeternam7 ,

Thanks for raising the issue. Apologies if I have misunderstood - I cannot read R code I am afraid - but are you simply trying to provide a starting point for your Bounded BFGS? If so, Accord already support this out the box:

```csharp
double[] startingPoint = { -1.2, 1 };
var lbfgs = new BoundedBroydenFletcherGoldfarbShanno(n, f, g);
bool success = lbfgs.Minimize(startingPoint);
```

If I have understood you correctly, it seems that you are having trouble getting the optimiser to converge on the global minimum. If a problem has many local minima, it is sometimes easiest to try a few different starting points and take the best solution. Something like the below may be of use to you (but this is obviously situation specific):

```csharp
double currentValue = double.PositiveInfinity;
double[] solution = null;
for (int i = 0; i < numGuesses; i++)
{
    var startingPoint = Vector.Random(3); // or some logic for choosing sensible starting points...

    if (lbfgs.Minimize(startingPoint)  && lbfgs.Value < currentValue)
    {
        currentValue = lbfgs.Value;
        solution = lbfgs.Solution.Copy();
    }
}
```

Hope that helps!

**Comment by aeternam7** [comment]
ah, didnt know about passing a starting point; that's good, so i don't have to modify the code

i'll try you idea

thanks

**Comment by AlexJCross** [comment]
That's right - no need to modify the code to provide a starting point. 

Hopefully this works for you. If it does, please mark the issue as closed.

Thanks very much!
