### ISSUE TITLE
How to combined hog and lbp as the classifier 

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#837]
**What would you like to submit?** (put an 'x' inside the bracket that applies)
  - [x ] question
  - [ ] bug report
  - [ ] feature request

var xBow1 = BagOfVisualWords.Create(new HistogramsOfOrientedGradients(9, 3, 6), new BinarySplit(10));

var xBow2 = new BagOfVisualWords<FeatureDescriptor>(new LocalBinaryPattern(3,6), new BinarySplit(10));

bow = xBow?.Learn(images.ToArray());

**Comment by cesarsouza** [comment]
Hi @blaisexen,

There are different ways on how features can be combined, but in my experience, usually the best way is achieved by concatenating the double[] representations from the first bow and the second bow into a larger, single double[] vector. In other words, you learn each BoW separately, you extract the representations using both bows, and then you concatenate those two representations together into a single double[] before passing them to a SVM.

Hope it helps,
Cesar

**Comment by blaisexen** [comment]
I understand, thank you.
