### ISSUE TITLE
Issue with Principal Component Analysis and the Standardize Option

### ISSUE THREAD

**Issue by StephenCullum** [accord-net/framework#846]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ x] question
  - [ x] bug report
  - [ ] feature request

Apologies if I am missing something fundamental here, I am comfortable using PCA but my background is not too statistical in nature so the implementation details are somewhat alien to me.

I am using PCA to identify the principal components amongst a selection of software metrics for some research I am carrying out at University (449 rows x 39 columns).  Mean centring the data works fine, but metrics such as LinesOfCode (0-1367) are coming out as much stronger components than say LackOfCohesionOfMethods (0-1).  I believe the data is being skewed due to the values ranges.  To address this, I want to Standardize the data, however using this option results in an Eigenvectors Matrix populated with zeros in column 0 and NaN in the rest.  The feeds through to all components being set to NaN.  Other data does not exhibit this problem and will process with both the Centre and Standardize options.

To confirm that this was not due to how I was calling the API (operator error), I can replicate the results when using the Accord.NET Principle Component Analysis sample application. 

![capture](https://user-images.githubusercontent.com/27360068/30125181-8289cdb6-932f-11e7-8c11-4f0f63e6078c.JPG)

Any recommendations on a workaround, bug fix or explanation or where I could be going wrong would be gratefully received.  I have attached a sample of data with this particular issue.

With Kind Regards

Stephen

[example.zip](https://github.com/accord-net/framework/files/1282006/example.zip)

**Comment by cesarsouza** [comment]
Hi Stephen,

Many thanks for opening the issue! I believe the cause of the NaNs when you use the standardize option is the presence of a column where all values are exactly the same and therefore has a standard deviation of zero: AccessScopeProtectedOrInternal. Please try removing this column from your data before computing the analysis.

Please let me know if it helps!

Regards,
Cesar

**Comment by StephenCullum** [comment]
Hi Cesar,

Thank you so much for the assistance.  Problem solved :)  Apologies for wasting your time.

With Kind Regards

Stephen
