### ISSUE TITLE
What do you think is the best and better method for face identification? MSVM or Deep Belief Network?

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#855]
**What would you like to submit?** (put an 'x' inside the bracket that applies)
  - [x ] question
  - [ ] bug report
  - [ ] feature request

@cesarsouza ,
What do you think is the best and better method for face identification? MSVM or Deep Belief Network?

hi, 
I had try msvm with face identification/recognition classification using with msvm on bow.

but I found it not good, multiclass seems many had identified wrong, multilabel is harder can identify.

I want to learn about DBN but you didn't have any samples like you have in Imaging Classification with BOW.

if you have a chance to write a sample using DBN for image classification please do it and let we test how good it is compare to msvm.

i hope,
thank you.

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Please do not use methods and classes from the Accord.Neuro namespace at this time. They are going to be replaced with the implementations from [Keras Sharp](https://github.com/cesarsouza/keras-sharp) project in the near future.

Regards,
Cesar

**Comment by blaisexen** [comment]
@cesarsouza ,
I hope I can wait before I released a new project for the first time using accord.net,

but I really like to know dbn vs svm,
thank you,

p.s for face detection I used emgu-opencv, because it's more steady.

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Sorry, I forgot to answer your question: Nowadays, deep belief networks are almost useless, being mostly surpassed by deep neural networks trained using standard SGD. It is very likely that the best possible results you could get today would be using deep neural networks, or a combination of features extracted using deep neural networks and a final classification stage using a SVM.

Regards,
Cesar

**Comment by blaisexen** [comment]
@cesarsouza 

hi,
do you mean

http://accord-framework.net/docs/html/T_Accord_Neuro_Learning_LevenbergMarquardtLearning.htm

is a sample of deep neural network? or that is a deep belief network?

sorry I'm confused what Neuro_Learning_LevenbergMarquardtLearning applies!

**Comment by cesarsouza** [comment]
Hi @blaisexen,

The Levenberg-Marquardt algorithm is for shallow (non-deep) networks only. Unfortunately, at this moment is not possible to do deep learning with the framework. This situation should change once the Keras Sharp project is implemented, though.

If you want to achieve a very good method for face identification, you can try to load a pre-trained deep convolutional neural network using [TensorFlowSharp](https://github.com/migueldeicaza/TensorFlowSharp) and use it to extract features from your images (i.e. in a similar way might have been extracting features for BoW right now), and then classify those features using a SVM. But that might be quite a bit of work at this moment, and requires some knowledge about current deep neural networks architectures in general.

Regards,
Cesar

**Comment by blaisexen** [comment]
@cesarsouza 

Ok,
I'm sorry I'm confused, I used to view all the sample from the program files folder you've made and I found out Deep learning...

But anyway thank you so much,

p.s 
Hoping to end up this project using Accord.Net MultiClass_SVM for face identification with a lot more from you.

**Comment by cesarsouza** [comment]
Sorry, I expressed myself wrong. It is actually possible to do deep learning using Accord.NET, but not the kind that is useful nowadays. The [deep learning method present in the framework was introduced in 2006](https://papers.nips.cc/paper/3048-greedy-layer-wise-training-of-deep-networks.pdf) but was mostly rendered obsolete [after 2012 when a new class of deep learning networks came out](https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks). The framework offers only the first one, but as I said, it is not very useful nowadays.

Regards,
Cesar

**Comment by blaisexen** [comment]
@cesarsouza 

Ok I understand you, but I'll be waiting for Keras Sharp Image Classification sample just like you did in Multiclass SVM Classification.

For now I'll play with Accord SVM.

thank you,
