### ISSUE TITLE
Add an overload to IsSymmetric that accepts a tolerance

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#856]
Currently `IsSymmetric()` is implemented as a generic method on `IComparable`. It would be good if it accepted a tolerance. For large symmetric matrices, it feels restrictive if a tiny floating point error caused this to return `false`.

Will need to be a T4 template job (or just a few special cases like `double` and `float`) as `IComparable` does not allow difference comparisons (AFAIK). I imagine it is faster if it's not generic. Proposed API:

```csharp
/// Some lovely comments...
/// param isRelative: whether matrix is symmetric based on the relative or absolute error
public static double IsSymmetric(this double[,] a, double tol = 0, bool isRelativeError = false)
```

so you could say, `M[i,j]` cannot be different to `M[j,i]` by more than 0.0001% or maybe 1e-12 etc.

## Question
@cesarsouza  Is this useful or am I being paranoid (I want it for #832)? Can you envisage any scenario where a matrix that should be symmetric is not **exactly** symmetric because of tiny rounding errors? if you can, assign this to me, if you can't, feel free to close this issue.

Thanks!
Alex

**Comment by AlexJCross** [comment]
Not paranoid ;)
I've never seen this get past the third loop.

```csharp
[Test]
public void IsSymmetricTest2()
{
    for (int i = 0; i < 1000; i++)
    {
        double[,] a = Matrix.Random(2);
        double[,] b = Matrix.Random(2);

        var result = a.Add(b).Add(a.Transpose()).Add(b.Transpose());

        if (!result.IsSymmetric())
            throw new NonSymmetricMatrixException();
    }
}
```

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Thanks for opening the issue 😄 No, you are not paranoid. It is quite common for almost symmetric - but not quite symmetric - matrices to exist. However, I would suggest using the same API as the [IsEquals method, using "atol" and "rtol" parameters](http://accord-framework.net/docs/html/M_Accord_Math_Matrix_IsEqual_39.htm). The reason for that is that this is [similar to the API used in sklearn and scipy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html) and that therefore some users might be more used to.

However, unless you need such a method for the other issues you have been working on, maybe you could leave this one as a future task. I can also try to take care of this issue - but if you think you would like to give you a try, please feel free to do so!

Regards,
Cesar

**Comment by AlexJCross** [comment]
I like it (never knew the IsEquals can compare relative!):
````csharp
public static double IsSymmetric(this double[,] a, double atol = 0, double rtol = 0)
````
Ok, well I need it for an issue so I'll check in something but it might be an internal static for now. If you get time to industrialise it before me, by all means do.

Thanks v much,
Alex

**Comment by cesarsouza** [comment]
It wasn't too hard to adapt it from the existing IsEqual implementations, I might be able to commit it in the following minutes. Tests are still running though.

**Comment by AlexJCross** [comment]
Thanks!

**Comment by cesarsouza** [comment]
Added in 3.8.0.
