### ISSUE TITLE
Consistency in linear constraint convention

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#860]
Hi @cesarsouza,

Sorry if this is not clear. I just wanted to make a note of this before I forget it completely. I'll revert tomorrow if it's not clear. This isn't a bug (well...). Just an inconsistency I thought I'd feedback. 

The LinearConstraintCollection and GoldfarbIdnani are inconsistent in their approach to constraints. 
GoldfarbIdnani uses assumes a matrix-vector constraint set where the first n are equality constraints and the remainder are GreaterThanOrEqualTo. 

However the LinearConstraintMatrix.FromMatrix() method has an identical API, takes the first n to be equality constraints BUT takes the remainder to be LessThanOrEqualTo. 

This behaviour is not consistent and not documented so it's very difficult for a user to spot this inconsistency (it took me a long time to figure out where my code was going wrong today). I haven't checked the repercussions of this but my instinct tells me the FromMatrix() method should change to be consistent with the convention of GoldfarbIdnani. If they're not self-consistent then I'm not really clear what purpose the FromMatrix method is serving. 

Thanks,
Alex

**Comment by cesarsouza** [comment]
Hi Alex,

Almost sure this is a bug, and thank you very much for catching that. According to [QuadProg's documentation]((https://cran.r-project.org/web/packages/quadprog/quadprog.pdf)), the constraints are indeed in the form ``` A^T b >= b0``` and therefore should have been interpreted as such.

The FromMatrix method was mostly being used to check constant violations from the existing unit tests, and they are not used in the main body of any of the optimization methods. I think it should be safe to change them directly.

Thanks,
Cesar

**Comment by AlexJCross** [comment]
Ok happy change this - I hope no one is currently using it! I imagine it will prove useful once I get #820 working.

**Comment by cesarsouza** [comment]
Fixed in 3.8.0.
