### ISSUE TITLE
Bug in linear constraint gradient - vector has incorrect dimensions

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#871]
Assuming I have understood correctly (apologies if I'm confused!), the `LinearConstraint` class is muddling the meaning of `NumberOfVariables` and running into trouble. Basically, it accepts `numberOfVariables` as a [first argument in the constructor](https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Optimization/Constrained/Constraints/LinearConstraint.cs#L148) but it's not really consistent in its interpretation of what that means. 

The ambiguity arises because the linear constraint has a compressed representation of the `CombinedAs` property with the `VariablesAtIndices` storing the non-zero indices involved in the constraint. So, for the most part, `NumberOfVariables` is taken to be the number of variables actually involved in the constraint (i.e. the non-zero indices), but the `Gradient(x)` relies on the `CombinedAs` property being the full gradient ([which it isn't](https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Optimization/Constrained/Constraints/LinearConstraint.cs#L354)).

Example below:

```csharp
[Test]
public void ConstructorTest4()
{
    double[] constraint = { 2, 1 }; // Create a constraint in 2 variables
    int[] indices = { 1, 3 };       // Denote the indices that these apply to
    double[] extended = { 0, 2, 0, 1, 0 }; // In full, it would look like this
    double[] x = { 2, 3, 4, 3, 2 }; // Here's some x to try it out with

    // First we initialise with the number of variables involved in the
    // constraint. This is 2, not 5. If we go for 5, the property setters
    // throw
    var linearConstraint = new LinearConstraint(constraint.Length) 
    {
        CombinedAs = constraint,            // set the constraint
        VariablesAtIndices = indices,       // supply the indices
        ShouldBe = ConstraintType.EqualTo,  // set the type...
        Value = 5                           // ...equal to 5
    };

    double f = linearConstraint.Function(x);
    double[] grad = linearConstraint.Gradient(x);

    Assert.AreEqual(extended.Dot(x), f);    // this works :-)
    Assert.True(grad.IsEqual(extended));    // but this is wrong. 2d vector should be 5d.
}
```

I have some suggestions on how this can be fixed. Perhaps it would make sense for me to email you. However, it's probably worth mentioning that for problems with lots of constraints and with lots of variables involved in each constraint, this compressed constraint is very inefficient to calculate. In my benchmarks, I found it was doubling the runtime of the AugmentedLagrangian solver (versus a simple dot product) given it has to do a double lookup.

Thanks,
A

**Comment by cesarsouza** [comment]
Added in 3.8.0.
