### ISSUE TITLE
After training with Adaboost,cant test if the error is 0

### ISSUE THREAD

**Issue by sjeanph** [accord-net/framework#875]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**
So I've been using Adaboost and  after training I want to check to see what the error is.But when I use either of these lines: 

Assert.AreEqual( 0 , error);
 or
Assert.AreEqual(0 , classifier.Models.Count);

I get this error:

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=nunit.framework
  StackTrace:
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.AreEqual(Object expected, Object actual)
   
But if I take off those lines it runs.But I want to check to see if the actual error is 0.Know how I can fix it?Thanks in advance!

**Comment by cesarsouza** [comment]
Hi @sjeanph,

Thanks for opening the issue! The Assert methods are from [NUnit](http://nunit.org), the unit test engine used by the framework. You are not required to use NUnit to check whether the error is zero. Instead, you can simply print the value to the console, set a breakpoint, or do a standard "if" check similar to
```csharp
if (error.IsEqual(error, rtol: 1e-6))
    Console.WriteLine("Equals to zero: {0}".Format(error));
else
   Console.WriteLine("Different from zero: {0}".Format(error));
```
Note: You might need to import Accord and Accord.Math to run the code above.

Hope it helps,
Cesar
