### ISSUE TITLE
Accord.Math.Transforms.FourierTransform2.DFT2 Is bugged

### ISSUE THREAD

**Issue by ivan236634452** [accord-net/framework#878]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [x] bug report
  - [ ] feature request

**Issue description**

File: Accord.Math/Transforms/FourierTransform2.cs
Method:  public static void DFT2(Complex[][] data, FourierTransform.Direction direction)

...
int n = data.Length;
int m = data[0].Length;
...
// process rows
var row = new Complex[m];
for (int i = 0; i < n; i++)
...
// process columns
var col = new Complex[n];
for (int j = 0; j < n; j++) // <- Must be m instead of n.
...

As it is now, columns are processed partially, or IndexOutOfRangeException is thrown.

**Comment by cesarsouza** [comment]
Hi @ivan236634452,

Many thanks for opening the bug report, and many more thanks for including a possible solution! Please, may I ask if you could also post a simple data example that triggers the issue such that I could include it as an additional unit test in the framework?

Thanks a lot!

Regards,
Cesar

**Comment by ivan236634452** [comment]
Simple - sure :)
`
// Should not throw:
			FourierTransform2.DFT2(new []
			{
				new[] { Complex.Zero, Complex.Zero },
				new[] { Complex.Zero, Complex.Zero },
				new[] { Complex.Zero, Complex.Zero },
			}, FourierTransform.Direction.Forward);

// Also should not throw:
			FourierTransform2.DFT2(new[]
			{
				new[] { Complex.Zero, Complex.Zero, Complex.Zero },
				new[] { Complex.Zero, Complex.Zero, Complex.Zero },
			}, FourierTransform.Direction.Forward);
`

But considering there are no tests at all for 2D Fourier transforms and no naive method to back-up the actual results, I'm not sure it would do any good by itself. And I don't have enough free time to make an analog of Accord.Tests.Math.FourierTransformTest.cs for this case.

**Comment by cesarsouza** [comment]
Thanks a lot!

I've committed an initial test to first overcome the initial issue you've raised, but I should be able to afterwards commit a few more unit tests confirming whether the calculated results are indeed right.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Fixed in 3.8.0.
