### ISSUE TITLE
QR Decomposition not caching work intensive properties

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#882]
The `LuDecomposition` and `CholeskyDecomposition` classes expose properties with a simple Lazy evaluation pattern on the factored matrices. The `QrDecomposition` does not do this. Any unsuspecting user attempting to iterate through, say, the `UpperTriangleFactor` directly is in for a nasty shock as the matrix could potentially be rebuilt thousands of times. 

Propose lazy cache on QR properties (or method call if caching undesirable). On phone but can post code snippet later if this is not clear. SVD has a few issues as well. 

Thanks
Alex

**Comment by cesarsouza** [comment]
Hi Alex,

I agree with your suggestion. If you do not want to lose time with this I can do it myself, unless you already have this change triggered in your current version of the code!

Regards,
Cesar

**Comment by AlexJCross** [comment]
hey @cesarsouza. Haha if you asked me an hour ago I would have said yes but I have just started typing the T4 templates. If it's not urgent, I can have it sorted in the next couple of days. Or possibly this eve if I'm not too tied up. I'll push quickly. let me know!

**Comment by cesarsouza** [comment]
Haha it is ok! In the moment I am trying to fill the many documentation requests that pop'd out in the last months, as well as trying to get NuGet support in Unity correctly (so we can attract even more users).

Regards,
Cesar

**Comment by cesarsouza** [comment]
Added in 3.8.0.
