### ISSUE TITLE
Add an Example for Signal.GetEnergy Method

### ISSUE THREAD

**Issue by sundaravadhananb** [accord-net/framework#885]
Please add an example for Signal.GetEnergy Method.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Audio_Signal_GetEnergy.htm

**Comment by cesarsouza** [comment]
Added in 3.8.0.

**Comment by sundaravadhananb** [comment]
Thank you so much for your prompt help !

**Comment by cesarsouza** [comment]
Hi @sundaravadhananb, 

Sorry, I guess it was not that much promptly since you opened the issue about a month ago! 😅 But I hope it can still be of some help!

Regards,
Cesar
