### ISSUE TITLE
Add an Example for VideoFileWriter.WriteAudioFrame Method

### ISSUE THREAD

**Issue by Drag0nite** [accord-net/framework#889]
Please add an example for VideoFileWriter.WriteAudioFrame Method.

TODO (optional): To record screen activities along with the speaker output

Help Topic: http://webcache.googleusercontent.com/search?q=cache:http://accord-framework.net/docs/html/M_Accord_Video_FFMPEG_VideoFileWriter_WriteAudioFrame.htm&gws_rd=cr&dcr=0&ei=rt_HWbKXPILSvwTIpqzABg

**Comment by cesarsouza** [comment]
Duplicate of #418
