### ISSUE TITLE
Add an Example for MultinomialLogisticRegressionAnalysis Class

### ISSUE THREAD

**Issue by sohrab4748** [accord-net/framework#890]
Please add an example for MultinomialLogisticRegressionAnalysis Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Statistics_Analysis_MultinomialLogisticRegressionAnalysis.htm

**Comment by cesarsouza** [comment]
Added in 3.8.0.
