### ISSUE TITLE
All the samples can't be downloaded

### ISSUE THREAD

**Issue by 773173224** [accord-net/framework#894]
All the samples can't be downloaded,please help.
url:http://accord-framework.net/samples.html
browser:IE、Google Chrome

**Comment by blaisexen** [comment]
hi,
Live samples(in .Exe) can be found at this installer
https://github.com/accord-net/framework/releases/download/v3.3.0/Accord.NET-3.3.0-installer.exe

**Comment by cesarsouza** [comment]
Hi @773173224, 

I could download them without problems from different machines. Can you please let me know which error do you get?

@blaisexen thanks a lot for point that out, but I have to say the version provided by this installer is already outdated compared to the latest versions of the samples. But thanks for the help!

Thanks!
Cesar

**Comment by blaisexen** [comment]
@cesarsouza 
Sorry,
I was thinking that he might want to see a live application from the samples on that installer, because one's I also use that before.

 I deleted now the old link

**Comment by cesarsouza** [comment]
@blaisexen are you able to download the sample applications from that link? i.e. https://1drv.ms/u/s!AoiTwBxoR4OAoIpwEGlc0iEYsruBdA

**Comment by cesarsouza** [comment]
It should open OneDrive, but the download should begin shortly afterwards.

**Comment by blaisexen** [comment]
@cesarsouza 
Download test......
Yes! and I think @773173224  can download it too.

**Comment by cesarsouza** [comment]
Thanks a lot @blaisexen !
