### ISSUE TITLE
Broadcasting in Accord

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#902]
Does Accord provide any support for [broadcasting](http://www.scipy-lectures.org/intro/numpy/operations.html#broadcasting)? It's an incredibly useful operation. What's the easiest way to, say, subtract a row vector from a matrix?

`var result = matrix.Apply((val, _, j) => val - vec[j]);`

What about `vec` `vec'` operations?

Thanks!

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

The framework supports broadcasting operations, but only for 2D matrices. If you would like to subtract a row vector from a matrix, you can use the Elementwise class. For example:

```csharp
var result = Elementwise.Subtract(matrix, vec, dimension: 1);
```
or 
```csharp
Elementwise.Subtract(matrix, vec, dimension: 1, result: matrix);
```
to do it in place.

The Elementwise class is not currently included in the online documentation. This is a known issue, that I actually have not yet registered here in the tracker.

Regards,
Cesar

**Comment by AlexJCross** [comment]
ah excellent. Thanks! This framework has so much functionality I'm still learning my way around.

Thanks for the quick response.
