### ISSUE TITLE
IP camera

### ISSUE THREAD

**Issue by HadeelHassan** [accord-net/framework#905]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

If you would like to submit an issue, please include a sample of the code you are trying to execute, as well as any data you might be using in your experiment, such as data tables, images, anything that might be necessary to reproduce the problem.
  
Note: If you would like to support the development for this feature or resolution of this bug, consider adding a bounty to it later in https://www.bountysource.com/teams/accord-net/issues

**Comment by HadeelHassan** [comment]
Hi 
I have Axis IP Camera, how can i connect it by C#, i searched Accord.net documentation but i didnot find any thing about IP camera, Can you help me please??
Regards
Hadeel

**Comment by cesarsouza** [comment]
Hi Hadeel,

You can use IP cameras using [JPEGStream](http://accord-framework.net/docs/html/T_Accord_Video_JPEGStream.htm) and other related classes. If you want, please take a look at the [VideoPlayer sample application](https://github.com/accord-net/framework/wiki/Sample-applications#video-player) available at the wiki. You should be able to open a stream from an IP address with it.

Regards,
Cesar

**Comment by HadeelHassan** [comment]
Hi @cesarsouza 
Thank you very very much, I did it, and it is working now

**Comment by cesarsouza** [comment]
Cool!

I am really glad the JPEGStream class has worked for you. If you need any further help, please open a new issue request here at the tracker.

Also, this is a long shot, but if you would like to contribute a little bit back to the framework, please do not hesitate to post as well an example of the source code that has worked for you. I am sure it will be useful for other framework users as well. But please only do this if you would like, of course! 😄 

Regards,
Cesar

**Comment by DaniloDaniel** [comment]
Hi friends,
I have a quetion, how I can work with the  RTSP protocol?
Greeting and thanks.

**Comment by cesarsouza** [comment]
Hi @DaniloDaniel,

Working with RTSP might be a bit more complicated than simply using an IP camera that supports the much simpler JPEG Stream protocol.

However, doing so is certainly not impossible. I think that the first step would be to get a library for RTSP in C# working, such as the one shown in this [CodeProject's article entitled "Managed Media Aggregation using Rtsp and Rtp"](https://www.codeproject.com/Articles/507218/Managed-Media-Aggregation-using-Rtsp-and-Rtp) ([project available in CodePlex](https://net7mma.codeplex.com)) or [SharpRTSP](https://github.com/ngraziano/SharpRTSP). Then, it should be possible to write a new class in Accord.Video.FFMPEG that accepts a stream being received by one of those libraries and forward the received packets to FFMPEG so it could perform the actual video decoding.

If you would like, please open a new issue here in the issue tracker asking for this feature so we can track its progress!

Regards,
Cesar
