### ISSUE TITLE
Problem with Deep Networks Example

### ISSUE THREAD

**Issue by Teoeo** [accord-net/framework#91]
Hello!

I recently tried to do some experiment with Deep Neural Networks so I downloaded example of Deep Belief Networks and Boltzmann Machines from Accord main page and got some errors:
1. First was problem with Nuget:
![1nugetproblem](https://cloud.githubusercontent.com/assets/6186628/7139995/6ea24b52-e2c9-11e4-8a93-910a452085e0.jpg)
2. But it was easily fixable by removing this code lines from Deep Learning.csproj and manually adding references to AForge:
![2nugetsolution](https://cloud.githubusercontent.com/assets/6186628/7142452/ed4675be-e2d8-11e4-9040-945f5471e71f.jpg)
3. Then i got problem with Extract(string text) method in Optdigits.cs (It looks like wrong separators):
![3linesprobleminextractinoptdigitscs](https://cloud.githubusercontent.com/assets/6186628/7142565/d1618efa-e2d9-11e4-8142-f33fb9b19dec.jpg)
4. So i tried to fixed it (with separator "\n"). But as You can see on screenshot - i ended with strange one char lines - which look like special separator from one whole digit to next whole digit:
![4firstfixtry](https://cloud.githubusercontent.com/assets/6186628/7142609/210e8afc-e2da-11e4-80c5-be13e9a1c044.jpg)
5. So finally i tried to take only lines with certain width but it made final program worked like this:
![5secondfixresult](https://cloud.githubusercontent.com/assets/6186628/7142660/81763930-e2da-11e4-92ec-8bc89ea5c099.jpg)

Could You help me? This example looks to good to be broken :)

**Comment by cesarsouza** [comment]
:) Sorry, it is certainly broken. Additionally to the fix you have done, please look at the method Load() and try to find a line that reads like this:
```
char[] buffer = new char[(32 + 2) * 32];
```
change it to
```
char[] buffer = new char[(32 + 1) * 32];
```

I am sorry for that. The problem is that I disabled the automatic conversion of line endings done by Git, and files that before were CRLF ("\r\n") are now only LF.("\n").

**Comment by Teoeo** [comment]
Thanks for help! (and great framework!)
