### ISSUE TITLE
Issue: Character case of folder name

### ISSUE THREAD

**Issue by Chinese-Xu** [accord-net/framework#911]
Target folder:
[framework/Sources/Extras/](https://github.com/accord-net/framework/tree/development/Sources/Extras)

When I clone Accord.NET to my Win10,  folder with name "NonCommercial" and "Noncommercial" were merged.

Then in GIT, two files be marked as "untracked".
Accord.Imaging (Noncommercial) (NETStandard).csproj
Accord.Math (Noncommercial) (NETStandard).csproj

Except folder “Imaging” and "Math", which use "NonCommercial", all other folder names use "Noncommercial" instead.

Thanks,
Wiley Xu

**Comment by cesarsouza** [comment]
Hi Wiley,

Thanks a lot for opening the issue! I will clone it in a Unix system and merge those folders. Thanks for catching that!

Regards,
Cesar

**Comment by Chinese-Xu** [comment]
Verified.

1. Execute "git pull" to get new code.
2. Got error messages.
error: The following untracked working tree files would be overwritten by merge:
        Sources/Extras/Accord.Imaging.Noncommercial/Accord.Imaging (Noncommercial).csproj
        Sources/Extras/Accord.Imaging.Noncommercial/Accord.snk
        Sources/Extras/Accord.Imaging.Noncommercial/FastGuidedFilter.cs
        Sources/Extras/Accord.Imaging.Noncommercial/License.txt
        Sources/Extras/Accord.Imaging.Noncommercial/Properties/AssemblyInfo.cs
        Sources/Extras/Accord.Math.Noncommercial/Accord.Math (Noncommercial).csproj
        Sources/Extras/Accord.Math.Noncommercial/Accord.snk
        Sources/Extras/Accord.Math.Noncommercial/License.txt
        Sources/Extras/Accord.Math.Noncommercial/NonlinearConjugateGradient.cs
        Sources/Extras/Accord.Math.Noncommercial/Properties/AssemblyInfo.cs
Please move or remove them before you merge.
Aborting

3. Remove target files manually
4. Run "git pull" again
5. Got excepted results
6. Verify folder names and rename to "Noncommercial"

Windows user should remove files under "NonCommercial" before pull and merge code from git.
Also need to verify target folder names are rename to "Noncommercial".  If not, rename it manually.

**Comment by cesarsouza** [comment]
Fixed in 3.8.0.
