### ISSUE TITLE
Add an Example for ImageBox.Show Method (Image)

### ISSUE THREAD

**Issue by SteveBrown1961** [accord-net/framework#912]
Please add an example for ImageBox.Show Method (Image).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Controls_ImageBox_Show_8.htm

**Comment by blaisexen** [comment]
hi,
it can be found under this file,
[(https://github.com/accord-net/framework/blob/development/Samples/Imaging/Classification%20(BoW)/MainForm.cs)]

or from this folder of Image Classification,
[https://github.com/accord-net/framework/tree/development/Samples/Imaging/Classification%20(BoW)]

**Comment by cesarsouza** [comment]
Thanks a lot @blaisexen!
