### ISSUE TITLE
KNearestNeighbors can not be serialized

### ISSUE THREAD

**Issue by minhtdhktqs** [accord-net/framework#913]
my code  in VB.net: 
Private k_n_n As KNearestNeighbors
I want to save it to a .txt file by this code: 
 Accord.IO.Serializer.Save(k_n_n, "KNN.txt")
but I got a error.

An unhandled exception of type 'System.Runtime.Serialization.SerializationException' occurred in mscorlib.dll
Additional information: Type 'Accord.Collections.BinaryNode`1[[Accord.Collections.KDTreeNode`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Accord.MachineLearning, Version=3.7.2.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7]]' in Assembly 'Accord, Version=3.7.2.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7' is not marked as serializable.

how to fix it? thanks

**Comment by cesarsouza** [comment]
Hi @minhtdhktqs,

Thanks for opening the issue! It seems that the one of the classes that are part of KNearestNeighbors classifier is missing a [Serializable] attribute. This is going to be fixed in the next pre-release.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Added in 3.8.0.

**Comment by minhtdhktqs** [comment]
thanks. I will check and upgrade. 

    Vào ngày 17:43 Thứ Bảy, 21 tháng 10 2017, César Souza <notifications@github.com> đã viết:
 

 Added in 3.8.0.—
