### ISSUE TITLE
[bug report] Two C++ projects require "Platform toolset v141" which only available on VS2017

### ISSUE THREAD

**Issue by Chinese-Xu** [accord-net/framework#917]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [x] bug report
  - [ ] feature request

**Issue description**
Failed projects:
Accrod.Video.FFMPEG(GPL)
Accord.Tests.Video.FFMPEG
Accrod.Tests.Math.Cpp
Accrod.Tests.Math.Interop

The platform toolset of Projects "Accrod.Video.FFMPEG(GPL)" and "Accrod.Tests.Math.Cpp" are setup with value "v141".  But in Visual Studio 2015, only v140 and v140_xp are available. "v141" be available in VS 2017.

Projects "Accord.Tests.Video.FFMPEG" and "Accrod.Tests.Math.Interop" are depend on above assembly.  So totally 4 projects failed.

To resolve this issue, open project properties dialog, in "General" section, change the value of "Platform toolsets" to "Visual Studio 2015 (v140)" and rebuild all c++ projects.

Related unit tests are passed after build with "Visual Studio 2015 (v140)"

Thanks,
Wiley Xu

**Comment by cesarsouza** [comment]
Hi Wiley,

Thanks a lot! I will standardize the project to use v140 and update the documentation. 

Regards,
Cesar

**Comment by AlexJCross** [comment]
Hi César,

Weekdays in working hours, I might add a few issues in the tracker that are not all that well described (like the one earlier). I hope that's ok - it's just a reminder so I don't forget when I get home. 

I can't use GitHub at work so I have to use my (crappy) phone and it's not v easy to add snippets/relevant links etc. on such a tiny screen. I'll add some more colour to that latest issue this eve (or more likely the weekend) and pick it up if you haven't already. 

Cheers,
Alex

**Comment by Chinese-Xu** [comment]
Verified.

**Comment by cesarsouza** [comment]
Added in 3.8.0.
