### ISSUE TITLE
Add an Example for LevenbergMarquardtLearning.RunEpoch Method

### ISSUE THREAD

**Issue by yongzhi0113** [accord-net/framework#918]
Please add an example for LevenbergMarquardtLearning.RunEpoch Method.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_Neuro_Learning_LevenbergMarquardtLearning_RunEpoch.htm

**Comment by blaisexen** [comment]
hi,
you can find the sample here:
https://github.com/accord-net/framework/tree/development/Samples/Neuro/Classification%20(ANN)
