### ISSUE TITLE
Build failed for Samples.sln on VS 2015

### ISSUE THREAD

**Issue by Chinese-Xu** [accord-net/framework#919]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**
Visual Studio 2015 with .NET 4.6.2
Build failed for project "1.1. Binary" under "framework\Samples\Tutorials\1. Classification".

In Progran.cs line 76

// Read the sparse inputs and outputs from the file
var (inputs, outputs) = reader.ReadSparseToEnd();

Error message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'var' does not exist in the current context	1.1. Binary	D:\WorkSpace\framework\Samples\Tutorials\1. Classification\1.1. Binary\Program.cs	76	Active
Error	CS0103	The name 'inputs' does not exist in the current context	1.1. Binary	D:\WorkSpace\framework\Samples\Tutorials\1. Classification\1.1. Binary\Program.cs	76	Active

The syntax at line 76 may supported from .NET4.7/C#7.

We should find out some way to avoid confusing new user which still working on VS2015.

Thanks,
Wiley Xu

**Comment by Chinese-Xu** [comment]
Verified.

**Comment by cesarsouza** [comment]
Added in 3.8.0.
