### ISSUE TITLE
Debug unit tests failing because of checked code in RNG

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#924]
I added some tests to check the `ObjectNullReferenceException` when the RNG was seeded (GH-921). In **debug build**, the code is `checked` so this code can randomly fail with an overflow exception.  There weren't any tests for this code before and it's random so I didn't spot it yesterday.

There are three places where this occurs. I've added unit tests that generate 100 random numbers to check this is fixed now. Also, I set the seed to a number that would otherwise overflow for reproducibility purposes.

`TestZigguratExponentialGenerator_Unseeded_NeverOverflows()`
`TestZigguratGenerator_Unseeded_NeverOverflows()`

**Comment by cesarsouza** [comment]
Added in 3.8.0.
