### ISSUE TITLE
Add an Example for SpeededUpRobustFeaturesDescriptor Class

### ISSUE THREAD

**Issue by babiamoreira** [accord-net/framework#929]
Please add an example for SpeededUpRobustFeaturesDescriptor Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Imaging_SpeededUpRobustFeaturesDescriptor.htm

**Comment by cesarsouza** [comment]
Olá @babiamoreira,

Obrigado por abrir este ticket! Um novo exemplo já será adicionado no próximo release do framework. O exemplo que será adicionado será este aqui:

```csharp
// Let's load an example image, such as Lena,
// from a standard dataset of example images:
var images = new TestImages(path: localPath);
Bitmap lena = images["lena.bmp"];

// Create a new SURF with the default parameter values:
var surf = new SpeededUpRobustFeaturesDetector(threshold: 0.0002f, octaves: 5, initial: 2);

// Use it to extract the SURF point descriptors from the Lena image:
List<SpeededUpRobustFeaturePoint> descriptors = surf.ProcessImage(lena);

// We can obtain the actual double[] descriptors using
double[][] features = descriptors.Apply(d => d.Descriptor);

// Now those descriptors can be used to represent the image itself, such
// as for example, in the Bag-of-Visual-Words approach for classification.
```

O SURF também pode ser usado em conjunto com a codificação Bag-of-Words para obter feature vectors de tamanho fixo para serem utilizados em tarefas de classificação, por exemplo. Um exemplo está disponível no [primeiro exemplo da documentação da classe BagOfVisualWords](http://accord-framework.net/docs/html/T_Accord_Imaging_BagOfVisualWords.htm).

Até mais,
Cesar

**Comment by cesarsouza** [comment]
Added in 3.8.0.
