### ISSUE TITLE
Add an Example for ChiSquareTest Class

### ISSUE THREAD

**Issue by Femilshajin** [accord-net/framework#936]
Please add an example for ChiSquareTest Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Statistics_Testing_ChiSquareTest.htm

**Comment by AlexJCross** [comment]
Hi @Femilshajin,

There is already an example on the page that you linked. Please reopen if it doesn't address your needs.
