### ISSUE TITLE
Wrong document in RectifiedLinearFunction.cs

### ISSUE THREAD

**Issue by Chinese-Xu** [accord-net/framework#938]
- [ ] question
  - [x] bug report
  - [ ] feature request

**Issue description**
Location:
Line 38 at framework/Sources/Accord.Neuro/Activation Functions/RectifiedLinearFunction.cs

    /// <summary>
    ///   Rectified linear activation function.
    /// </summary>
    ///
    /// <remarks>
    ///   <para>This class implements a rectified linear activation 
    ///   function as given by the piecewise formula:</para>
    /// 
    ///   <code lang="none">
    ///   f(x) = 0, if x > 0         <== Line 38
    ///   f(x) = x, otherwise
    ///   </code>

Based on the implement referenced in below.  f(x) should be equals to x if x > 0, and returns 0 otherwise.

        /// <summary>
        ///   Calculates function value.
        /// </summary>
        ///
        /// <param name="x">Function input value.</param>
        /// 
        /// <returns>Function output value, <i>f(x)</i>.</returns>
        ///
        /// <remarks>The method calculates function value at point <paramref name="x"/>.</remarks>
        ///
        public double Function(double x)
        {
            if (x > 0)
                return x;
            return 0;
        }

**Comment by AlexJCross** [comment]
Thanks very much for spotting this and the PR.

**Comment by cesarsouza** [comment]
Added in 3.8.0.
