### ISSUE TITLE
Accord.Video.FFMPEG.VideoFileReader should provide frame-based random access

### ISSUE THREAD

**Issue by cesarsouza** [accord-net/framework#948]
The VideoFileReader class in Accord.Video.FFMPEG can only be used to read a video file sequentially, i.e. it is not possible to jump to a particular frame given a frame index. The class should be updated to make this possible.

**Comment by cesarsouza** [comment]
Added in 3.8.0.

**Comment by andreionutz** [comment]
used this with videos encoded with XVID. thank you! unfortunately it does not work for videos encoded H264. can you check this?
