### ISSUE TITLE
Accord.Net forum

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#953]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question

hi,
@cesarsouza 

I would like to know if there is a accord.net forum?

if not can I post something like
"a group of users to project simple codes for face recognition using accord.net"

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Yes, there is a group for user-level discussions at https://groups.google.com/forum/#!forum/accord-net. But please note that the best venue to ask questions to developers is here in the issue tracker.

Regards,
Cesar

**Comment by blaisexen** [comment]
@cesarsouza 

thanks
