### ISSUE TITLE
Proper Image Viewing

### ISSUE THREAD

**Issue by fdncred** [accord-net/framework#96]
Love the framework!  Thank you so much.  

As wonderful as this code is it would be nice to have a proper viewing control instead of just relying on PictureBox and the AForge ImageBox.

Here is a good example
https://github.com/cyotek/Cyotek.Windows.Forms.ImageBox

Thanks,
Darren

**Comment by cesarsouza** [comment]
Thanks for the suggestion, this seems like a very good idea! Do you know Cyotek's authors? Perhaps it might be worth to ask if they wouldn't be interested in integrating this project within the framework. Their code seems to be licensed as MIT, so there shouldn't be any problem in integrating it directly as well!

**Comment by fdncred** [comment]
You're welcome.  Unfortunately, I do not know the Cyotek authors.  I wish they would integrate it but I'm not in a position to ask them nor am I in a position to do the integration myself (or I'd just do it).  I'm not familiar enough with out .Net components work.  

Ideally it would just be an assembly that we could to an Accord.Net project, drag the component on the form, and it just work without a lot of added methods.

**Comment by cesarsouza** [comment]
An update for interested users: The Cyotek project is licensed under the MIT license, meaning it should be possible to add a new Accord.Controls.<something> project to Accord.NET adding Cyotek's ImageBox under an API that is similar to the existing ImageBox / PictureBox classes currently in the framework.

**Comment by fdncred** [comment]
Closed via  1b27ff9

**Comment by justingruenberg** [comment]
https://github.com/accord-net/framework/blob/development/Tools/TestApp/Form1.cs

Seems to be causing the build to fail.  Can that entire directory be deleted?

**Comment by justingruenberg** [comment]
Just going by CI
https://ci.appveyor.com/project/cesarsouza/framework/build/3.8.2.265/job/ritt14ybe88lbef6/messages
https://travis-ci.org/accord-net/framework/jobs/399621487

**Comment by fdncred** [comment]
Fixed with 1b3bd76
