### ISSUE TITLE
Filters (Images) Sample

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#968]
- [x ] question

hi,

I noticed in the Filters (Images) sample has a setting of the brightness, saturation, and other as well,
is there a way also not by setting but getting also,
like getting the brightness and sharpness of the image?

**Comment by cesarsouza** [comment]
Hi @blaisexen,

The framework doesn't offer this right now, but they should be simple to implement. The only complicating factor is that there are actually multiple ways to obtain a value representing the brightness or the sharpness of an image. 

For instance, one possibility to obtain the brightness of an image is to first transform it to HSL and compute the average of the luminance component of the HSL representation in the entire image. For the sharpness, I guess the easiest way would be to compute the gradients of the image and compute its average in each channel of the image, and then compute the average between all channels in the image.

If you would like to give it a try, please feel free to submit this functionality in a pull request. You can [convert RGB values to HSL using the HSL class](http://accord-framework.net/docs/html/T_Accord_Imaging_HSL.htm). You can [compute the (approximate) gradients of a grayscale image using the SobelEdgeDetector](http://accord-framework.net/docs/html/T_Accord_Imaging_Filters_SobelEdgeDetector.htm).

Regards,
Cesar

**Comment by blaisexen** [comment]
@cesarsouza 
I will try to understand the codes, I'm not a pro or expert, I'm just a system integrator beginner
