### ISSUE TITLE
Accord.Video.FFMPEG leaks unmanaged memory

### ISSUE THREAD

**Issue by nesteruk** [accord-net/framework#969]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

I'm using a very simple piece of code to render a video:

```
using (var writer = new VideoFileWriter())
      {
        writer.Open(file.FullName, (int) size.Width, (int) size.Height,
          new Rational(15.0), codecId, 8000000);
        float t = 0;
        uint idx;
        for (idx = 0; t < totalTime && idx < totalFrames; ++idx, t += timeStep)
        {
          using (var rendered = RenderFrame(t, scene.Size))
          {
            // just like in TypograFix, copy frame to an ordinary Bitmap
            using (var bmp = new Bitmap((int) size.Width, (int) size.Height))
            {
              var data = bmp.LockBits((RectangleArea) size, ImageLockMode.WriteOnly,
                PixelFormat.Format32bppArgb);
              var bytesPerPixel = 4;
              rendered.CopyPixels(data.Stride, new DataPointer(data.Scan0,
                data.Stride * data.Height * bytesPerPixel));
              bmp.UnlockBits(data);
              writer.WriteVideoFrame(bmp, idx);
            }
          }
        }
        writer.Close();
      }
```

While the videos render fine, it seems that every single frame (and there are lots of them!) persist in memory. I profiled the application in dotMemory, and all that memory that gets consumed is unmanaged. It doesn't get released even on the writer being closed, and on complicated videos I simply run out of RAM while rendering.

**Comment by cesarsouza** [comment]
Hi @nesteruk, 

Many thanks for opening the issue! Do you think you could please share the contents of the RenderFrame method as well?

Thanks!

By the way, [a new version of the Accord.NET Framework has just been released](https://www.nuget.org/packages/Accord/3.8.0). In this new version (3.8.0), it is now possible to reuse a BitmapData object when sending frames to be encoded, [as shown in this example](http://accord-framework.net/docs/html/T_Accord_Vision_Detection_HaarObjectDetector.htm). This can be used to decrease memory usage since it avoids having to create an extra Bitmap object for every frame to be encoded.

Regards,
Cesar

**Comment by blaisexen** [comment]
@nesteruk 
new version (3.8.0),

maybe corrupted?

I downloaded 3 times and says during unrar corrupted,

I hope it's not for you.!

**Comment by nesteruk** [comment]
hi @cesarsouza here is `RenderFrame()` from my example above:

```
public SharpDX.WIC.Bitmap RenderFrame(float atTime, Size size, SharpDX.WIC.Bitmap bitmap = null)
    {
      if (bitmap == null)
      {
        bitmap = new SharpDX.WIC.Bitmap(imagingFactory, (int) size.Width,
          (int) size.Height, wicPixelFormat, BitmapCreateCacheOption.CacheOnLoad);
      }
      var renderTarget =
        new WicRenderTarget(D2DFactory, bitmap, new RenderTargetProperties());

      renderTarget.BeginDraw();
      {
        var brush = new SolidColorBrush(renderTarget, scene.BackgroundColor[atTime]);
        renderTarget.FillRectangle(
          new RawRectangleF(0, 0, size.Width, size.Height), brush);

        RenderSceneObjects(renderTarget, atTime);
      }
      renderTarget.EndDraw();

      return bitmap;
    }
```

I'm already using the latest Accord version (I tried 3.8.0 as well as alpha) and am still leaking tonnes of memory.

Basically, on each `WriteVideoFrame()` we lose a bit of memory and that memory isn't reclaimed even when the video is finished.

**Comment by nesteruk** [comment]
Whoops, just realized my own mistake. The above RenderTarget captures the bitmap and isn't explicitly disposed. Sorry!
