### ISSUE TITLE
Accord.Statistics.Distributions.Univariate in IronPython 2.7.5.0 not listing all distributions

### ISSUE THREAD

**Issue by binary10** [accord-net/framework#97]
It's not necessarily the responsibility of this project to fix this, however I'm posting this issue in case others experience it.

I'm using IronPython to access the distributions in Accord, however not all distributions are being carried through when the assembly is loaded.
```python
import clr
import sys
sys.path.append('C:\\Program Files (x86)\\Accord.NET\\Framework\\Release\\net40')

clr.AddReference('Accord')
clr.AddReference('Accord.Statistics')

import Accord
import Accord.Statistics

dir(Accord.Statistics.Distributions.Univariate)     # List all distributions available
# I see the following output 
# ['AndersonDarlingDistributionType', 'HazardEstimator']
```

**Comment by binary10** [comment]
```python
import clr
import sys

# Add C# Library Paths
sys.path.append('C:\\Program Files (x86)\\Accord.NET\\Framework\\Release\\net40')
sys.path.append('C:\\Program Files (x86)\\AForge.NET\\Framework\\Release')
clr.AddReference('AForge.Math')
clr.AddReference('Accord.Statistics')


# Import like first-class Python modules
import AForge.Math      # This was a dependent base class
import Accord.Statistics

# Now all Univariate distributions appear
dir(Accord.Statistics.Distributions.Univariate)
# ['AndersonDarlingDistribution', 'AndersonDarlingDistributionType', 'BernoulliDistribution', 'BetaDistribution', 'BinomialDistribution', 'BirnbaumSaundersDistribution', 'CauchyDistribution', 'ChiSquareDistribution', 'Continuous', 'DegenerateDistribution', 'EmpiricalDistribution', 'EmpiricalHazardDistribution', 'ExponentialDistribution', 'FDistribution', 'FoldedNormalDistribution', 'GammaDistribution', 'GeneralContinuousDistribution', 'GeneralDiscreteDistribution', 'GeneralizedBetaDistribution', 'GeneralizedNormalDistribution', 'GeometricDistribution', 'GompertzDistribution', 'GumbelDistribution', 'HazardEstimator', 'HyperbolicSecantDistribution', 'HypergeometricDistribution', 'InverseChiSquareDistribution', 'InverseGammaDistribution', 'InverseGaussianDistribution', 'KolmogorovSmirnovDistribution', 'LaplaceDistribution', 'LevyDistribution', 'LogLogisticDistribution', 'LogisticDistribution', 'LognormalDistribution', 'MannWhitneyDistribution', 'Mixture', 'NakagamiDistribution', 'NegativeBinomialDistribution', 'NoncentralTDistribution', 'NormalDistribution', 'ParetoDistribution', 'PoissonDistribution', 'PowerLognormalDistribution', 'PowerNormalDistribution', 'RayleighDistribution', 'ShapiroWilkDistribution', 'ShiftedLogLogisticDistribution', 'SkewNormalDistribution', 'TDistribution', 'TriangularDistribution', 'TukeyLambdaDistribution', 'UniformContinuousDistribution', 'UniformDiscreteDistribution', 'UnivariateContinuousDistribution', 'UnivariateDiscreteDistribution', 'VonMisesDistribution', 'WeibullDistribution', 'WilcoxonDistribution', 'WrappedCauchyDistribution']
```

I was able to solve this with the help of seeing the compiler output of the same program written in C#.

**Comment by cesarsouza** [comment]
Thanks for reporting this issue! It seems the problem was caused because AForge.NET libs were not referenced, is that right?

If that's the case, this will be fixed in the next release as AForge.NET libs have now been merged with this framework.

Thanks for reporting the issue!

**Comment by binary10** [comment]
Hi Cesar, yes the problem was caused because I had not imported the AForge reference. Good to know that the new release will include those libraries. I'm really enjoying being able to access these libraries from Python!

**Comment by cesarsouza** [comment]
Great! If you also find any additional issues, please let me know. If you are particularly interested in the Distributions namespaces, perhaps you also find this article interesting:

 - http://www.codeproject.com/Articles/835786/Statistics-Workbench

It demonstrates how to use the distributions in the framework and provides an [application that can automatically discover new distributions, load, instantiate them, etc all using reflection](http://www.codeproject.com/Articles/835786/Statistics-Workbench). Hope it helps! (if it does, please help rating the article a 5 :wink:)

**Comment by binary10** [comment]
Cool, you even published that today! I will have to work through it and send you any comments. I enjoy your clear writing style (I also read your PCA paper and found it to be very helpful). I'm finding your project very helpful in my studies of statistics and multivariate statistics. Thank you!

**Comment by binary10** [comment]
Cesar, here is a link to the integration I was able to achieve between IronPython, Accord and Linq
https://gist.github.com/binary10/815c6eb3aee9812b4b5e
