### ISSUE TITLE
How to install Accord.IO.MatReader ?? its not available even through Nuget package manager

### ISSUE THREAD

**Issue by Saptarshi-Nag** [accord-net/framework#972]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - ['x'] question
  - [ ] bug report
  - [ ] feature request

**Issue description**
I have installed the Accord.Math and Accord.IO through nuget PAckage manager, But I am not able to see files for IO/MatReader, How do one install these files meant for MATLAB file handling ?

**Comment by cesarsouza** [comment]
Hi @Saptarshi-Nag,

Thanks for opening the issue! I see you have closed it, have you found the solution?

Regards,
Cesar
