### ISSUE TITLE
Debugging Non-LGPL Unit Tests

### ISSUE THREAD

**Issue by fdncred** [accord-net/framework#974]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**
Hey @cesarsouza,
I noticed you added some tests in the latest release. I'm specifically looking at MatingTrackerTest.cs. I'm trying to debug it and I'm not having any luck. I'm sure it's due to my ignorance. I can compile Accord.Tests.Video.FFMPEG (and all other tests) just fine. When I load the VS2017 Test Explorer and build, it doesn't see any tests. I put a break point on the ProcessFrame() method and it never gets hit. I right click on the code and click Debug Tests, and it never gets hit that way either. When you have a second, can you please tell me what I'm doing wrong?
Thanks,
Darren

**Comment by fdncred** [comment]
I just discovered that you're using nunit so I installed the Nunit 3 Test Adapter extension. That's all it took. Hopefully I didn't waste your time.

**Comment by cesarsouza** [comment]
Hi @fdncred, 

No worries, indeed the code uses NUnit. What do you normally use for testing?

Regards,
Cesar

**Comment by fdncred** [comment]
Hey @cesarsouza, My default is to use the built in test functionality of VS2017 but I have no problems with Nunit. I'm not big into unit testing but I see how it would benefit a project like yours.
Darren
