### ISSUE TITLE
Add an Example for Tools Class

### ISSUE THREAD

**Issue by cornex-04** [accord-net/framework#986]
Please add an example for Tools Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/T_Accord_Statistics_Tools.htm

**Comment by cesarsouza** [comment]
Hi @cornex-04,

Thanks for opening the issue! However, the Tools class contains a collection of static methods for different purposes. Please specify which method you would be more interested in having an example for.

Regards,
Cesar

**Comment by cornex-04** [comment]
Hello @cesarsouza 

I have doubts and I would like you to provide some examples with descriptive statistical analysis methods such as arithmetic mean, geometric mean, harmonic mean, minimum, maximum, range of data range, variance, standard deviation, asymmetry, kurtosis, modal, interquartile range, quartiles, percentiles.
