### ISSUE TITLE
Add an Example for DecisionTree.Save Method (Stream)

### ISSUE THREAD

**Issue by DuotongYang** [accord-net/framework#988]
Please add an example for DecisionTree.Save Method (Stream).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: http://accord-framework.net/docs/html/M_Accord_MachineLearning_DecisionTrees_DecisionTree_Save.htm

**Comment by DuotongYang** [comment]
Hi I saved my object as a stream however the it showed zero bite.

**Comment by cesarsouza** [comment]
Hi @DuotongYang,

Thanks for opening the issue! However, this method is deprecated. You can save and load DecisionTrees using the [Serializer class as described in the documentation page you've linked](http://accord-framework.net/docs/html/M_Accord_IO_Serializer_Save__1_2.htm).

Regards,
Cesar
