### ISSUE TITLE
MultiClassSupportVectorMachine gridsearch example

### ISSUE THREAD

**Issue by vonboettichert** [accord-net/framework#991]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

Hi Ceasar,

I'm trying to set up a gridsearch for a MultiClassSupportVectorMachine that uses a Gaussian kernel. I'm not entirely sure how to do this, since the multiclassSVM uses a 'MulticlassSVMLearning learner, in which I can set a further learner, i.e. SequentialMinimalOptimization<IKernel> learner, which would make use of the gridsearchrange parameters.

Could you please help me by setting up an example, specifically for the MultiClassSVM?

Thank you for your great work!
Kind regards,
Thorsten

**Comment by vonboettichert** [comment]
Hi again,

After a bit of struggling this here seems to work:

` var gridsearch1 = new GridSearch<MulticlassSupportVectorMachine<IKernel, double[]>, double[], int>()
            {
                // Here we can specify the range of the parameters to be included in the search
                ParameterRanges = _kernelParameter.GetParameterRangeCollection(),
                
                // Indicate how learning algorithms for the models should be created
                Learner = (s) => new MulticlassSupportVectorLearning<IKernel, double[]>
                {
                    Learner = (a) => new SequentialMinimalOptimization<IKernel, double[]>()
                    {
                        UseComplexityHeuristic = true,
                        Kernel = _kernelParameter.GetKernel(s)
                    }
                },

                // Define how the performance of the models should be measured
                Loss = (actual, expected, m) => new ZeroOneLoss(expected).Loss(actual),
            };`

Kind regards,
Thorsten

**Comment by cesarsouza** [comment]
Hi @vonboettichert,

Thanks for opening the issue! I was just about to write an answer when you submitted your solution. From the code you've posted, I understand you have struggled quite a bit to get the generic parameters right! 

The easiest way to create a Grid Search for an arbitrary model and learning algorithm would have been by using the static [GridSearch class](http://accord-framework.net/docs/html/T_Accord_MachineLearning_Performance_GridSearch.htm). It offers a static Create method that can be used to create a grid search algorithm without having to specify all the generic arguments (such as in ``` new GridSearch<MulticlassSupportVectorMachine<IKernel, double[]>, double[], int>```).

Hope it helps,
Cesar

**Comment by vonboettichert** [comment]
Thanks a bunch! Again, great stuff! You guys are heros.
